### ISSUE TITLE
[cbuildgen] Improve error message when `update-rte` is needed

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1018]
Take for example the `Blinky` project from https://www.keil.arm.com/boards/nxp-lpcxpresso55s69-56e55af/projects/
After converting it with `uv2csolution` and trying to build with `cbuild`, the following error message is given:
```
*** ERROR M204:
  Path not found: 'D:/examples/blinky-f23141e6/RTE/_LPCXpresso55S69'!
```
The mentioned path contains the auto-generated `RTE_Components.h` that's typically **not** checked in within the project files.

For this sort of failure would be helpful to enhance the error message suggesting the use of the `--update-rte` option.

cc: @mcgordonite

**Comment by ReinhardKeil** [comment]
Would it be an option that uv2csolution flags this issue already with a information?  Not sure if this can be done at that level.

**Comment by brondani** [comment]
A proper implementation in `uv2solution` would require RTE Model awareness which it currently does not have.

In the PR #1019 a `cbuildgen` warning message was introduced, for example:
```
*** WARNING M634:
  File 'D:/examples/blinky-f23141e6/RTE/_LPCXpresso55S69/RTE_Components.h' was not found, use the option '--update-rte' to generate it
```
