### ISSUE TITLE
[csolution] Explicitly check all file references in *.csolution, *.cproject, *.clayer for case sensitive match

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1020]
**Describe The Problem To Be Solved**
The csolution  YAML input files are specified as host platform independent files. As a consequence file references need to match case sensitive also when running on case insensitive operating systems. 

**(Optional): Suggest A Solution**
The `csolution` tool should run this validation as part of reading the YAML files and output any mismatches with filename and line number information.

* Details of the technical implementation
TBD
* Tradeoffs made in design decisions
TBD
* Caveats and considerations for the future
TBD

**Comment by brondani** [comment]
In addition to the case check, I would suggest the following portability checks for all file/path references:
- avoid backslash
- avoid absolute paths
