### ISSUE TITLE
Clearify syntax of --context

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1026]
What is the exact syntax for defining a context set?

I believe that the syntax published ~2 weeks ago in the TRM slides using comma separator is incorrect.

Working is:
```yml
csolution convert SimpleTZ.csolution.yml -c cm33_s.Debug+AVH -c cm33_ns.Release+AVH
cbuild SimpleTZ.csolution.yml -c cm33_s.Debug+AVH -c cm33_ns.Release+AVH
```

Could someone confirm that?

Note: I have slightly changed #1024 because of that.

**Comment by jkrech** [comment]
I can successfully invoke:
```
csolution convert SimpleTZ.csolution.yml -c CM33_s.Debug+AVH,CM33_ns.Release+AVH
```

```
csolution convert SimpleTZ.csolution.yml -c CM33_s.Debug+AVH,CM33_ns.Release+AVH
```
NOTE: There must not be any spaces between the `,` and the next context description!

**Comment by ReinhardKeil** [comment]
Yep that was my problem. I had used a space after comma.
