### ISSUE TITLE
Missing default linker script file when `etc` and project are on different drives

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1029]
From the [documentation](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Linker-Script-Management.md#automatic-linker-script-generation):

> If a project context does not specify any linker script (...) a toolchain specific linker script template is used.
> (...) The files are located in the directory \<cmsis-toolbox-installation-dir\>/etc of the CMSIS-Toolbox.

When the project (input yml files) are located in a different filesystem drive in respect to `<cmsis-toolbox-installation-dir/etc`, the default linker script file does not appear in the generated `*.cprj`/`*.cbuild.yml` files.

**Comment by jkrech** [comment]
Fixed staring cmsis-toolbox 2.0.0
