### ISSUE TITLE
Configure default 3-way merge utility for 'unattended' merge

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#104]
The PLM of configuration file requires to run a three way merge of configuration files:
a) default configuration file @ version A
b) modified configuration file based on version A
c) default configuration file @ version B
=> all modifications shall be applied to default configuration file @ version B

a) In an IDE or CLI interactive development flow the merge operation should be executed manually by the User, who should be able to configure the preferred merge utility as part of the IDE/CLI specific environment configuration (not workspace/solution/project specific)
b) In an unattended CI workflow the 'csolution' tool may attempt to execute the 3-way merge automatically in case of a change in the configuration file version. In case of "errors" the original configuration file is restored. For this case we need to configure the 3-way merge utility via an installation specific config file or using an Environment Variable as we are using for specifying the default CMSIS_PACK_ROOT.

**Comment by ReinhardKeil** [comment]
Is it really the task of the projmgr to define a merge utility.

**Comment by jkrech** [comment]
We could store it as part of the tools configuration as suggested as replacement for environment variables: https://github.com/Open-CMSIS-Pack/devtools/issues/142

git uses the following parameters in their configuration system:
subset of options from git:
```
merge.tool =
mergetool.<tool>.path = 
mergetool.<tool>.cmd = (using: BASE, LOCAL, REMOTE, MERGED variables)
mergetool.keepBackup = true|false
```

**Comment by ReinhardKeil** [comment]
@jkrech what concrete actions do you propose?

**Comment by jkrech** [comment]
In this issue I had just captured the parameter info that git is storing for configuring the merge that git uses during a merge. git is storing configfile information e.g. in `C:\Users\<username>\.gitconfig` and defaults in `C:\Program Files\Git\etc\gitconfig`.

At this point csolution (Version 1.4.0) implements the PLM of configuration files in a non-destructive way. It copies the "updated" default config file version but does not modify the configuration file itself.
In order to keep the separation of concerns a separate utility could check the RTE folders for config files that require merging. This utility would require to know where to find a "suitable" three way merge utility which should be a setup step for this utility with the options being stored in a suitable location (e.g. relative to the utility `../etc`.)
I will close this for now. It should be looked at in the context of a dedicated utility that attempts to merge from the command line rather than from an IDE.
We may review whether we think `csolution` should list outdated config files, especially those with major version differences.
