### ISSUE TITLE
[csolution] Cannot generate archive library with ".a" extension for AC6 using YAML Input 2.0.0

### ISSUE THREAD

**Issue by ronyrad** [Open-CMSIS-Pack/devtools#1043]
In the project yml that was used with cmsis-tools 1.6.0 I had the following output definitions for library output:

 output:
   type: lib               
   file: libsomename.a 

When converting to cmsis-tools 2.0.0 I had to change "file:" to "base-name:" 

 output:
   type: lib               
   base-name: libsomename.a 

As a result, I get libsomename.a.lib instead of libsomename.a 

I cannot get rid of .lib extension

I'm using AC6.6.19.0 compiler

**Comment by brondani** [comment]
As the name `base-name` suggests, it regards only the file's base name, not the file's extension.
As decided in https://github.com/Open-CMSIS-Pack/devtools/issues/895#issuecomment-1539748611:
> All artifacts will use their toolchain specific default file extensions

@ronyrad Maybe you can help us with this unanswered question:
https://github.com/Open-CMSIS-Pack/devtools/issues/895#issuecomment-1539819261
> When is there a need to rename default file extensions?

**Comment by brondani** [comment]
> BTW is there a way now to modify toolchain-specific default file extensions?

No, as a result of https://github.com/Open-CMSIS-Pack/devtools/issues/895 the artifact's affixes are currently hardcoded [here](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.0.0/tools/projmgr/include/ProjMgrUtils.h#L162-L177).

Possible workarounds:
- edit the generated CPRJ before invoking the build process
```
<target ...>
  <output lib="libsomename.a"
```
- rename the artifact after build completion.

**Comment by jkrech** [comment]
This is not considered a bug, since the tools implement the specification correctly.
I am wondering whether the proposed "post-build" step should be used for file renaming when required:
https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#execute

**Comment by ReinhardKeil** [comment]
I believe that we should focus next on improving the CMake backend to support 'post-build', etc. As outlined this is the solution to such problems. 

I set this therefore to discussion done.

**Comment by ReinhardKeil** [comment]
Added example to documentation on how to copy an output file.
https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#executes
