### ISSUE TITLE
Add License Information to cbuild.yml files (BOM for projects)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1046]
For applications it would be good to provide license information about software components that come from packs.

This could be added to `cbuild.yml` files as outlined here https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md#licenses

The purpose of this information is a BOM license list.  We should therefore review the current problems to ensure:
- it contains complete information about an image
- for components that come from software packs without license information, this should be also highlighted (so that there is a manual check)

Before implementing a review of the current proposal should be done.

**Comment by edriouk** [comment]
@ReinhardKeil, first the information should be collected by RTE Model. Than it could be used in several ways: 

- output into cbuild.yml (csolution only)
- output into a separate file, e.g. LincesesBOM.txt  and put into RTE directory. That is useful for uVision and Keil Studio 
  this file can also be referenced from cbuild.yml 
- displayed in UI of uVision or Keil Studio

Questions: should the license BOM also include licenses for all files in the project, not only from CMSIS-Packs?
