### ISSUE TITLE
[packchk] missing component (Cvariant) not detected when specified in `<accept>` (M504:)

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#1052]
Hi

Pdsc content:
```
    <condition id="xxx">
      <description>xxx</description>
      <require condition="xxx"/>
      <require Cclass="Device" Cgroup="STM32 HAL" Csub="Core"/>
      <accept Cclass="Device" Cgroup="STM32 HAL" Csub="timebases" Cvariant="NONE"/>
      <accept Cclass="Device" Cgroup="STM32 HAL" Csub="timebases" Cvariant="RTC_ALARM"/>
      <accept Cclass="Device" Cgroup="STM32 HAL" Csub="timebases" Cvariant="RTC_WKUP"/>
      <accept Cclass="Device" Cgroup="STM32 HAL" Csub="timebases" Cvariant="TIM"/>
    </condition>

    <component Cclass="Device" Cgroup="STM32 HAL" Csub="timebases" Cvariant="NONE" Cversion="0.1.0" condition="Timebase NONE">
...
    </component>
```

If some Cvariant are missing, there are no warning detecting this issue ?

Regards,

**Comment by jkrech** [comment]
@thorstendb-ARM 
Does it make a difference whether `<accept>` or `<require>` is being used?

**Comment by jeromecoutant** [comment]
> Does it make a difference whether <accept> or <require> is being used?

Yes!
Got message like
`M504: RTE Model reports: MISSING:     --   require Device:STM32 HAL:timebases:RTC_WKUP`

**Comment by thorstendb-ARM** [comment]
M504 reports the internal RTE Model checks. We should extend PackChk:
Find all references and check if they are available (WARNING if not)

**Comment by jkrech** [comment]
@thorstendb-ARM can you please provide a version for @jeromecoutant to test the fix?
