### ISSUE TITLE
Proposal: Rebuild *.cbuild.yml and *.cbuild-idx.yml files when using cbuild -r option

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1094]
This is not necessarily a bug, but an improvement suggestion.

Using `cbuild hello.csolution.yml` does not overwrite *.cbuild.yml and *.cbuild-idx.yml files when they exist. This is a great feature!

But I would recommend that when using the option -r, these files are regenerated.

Note: There seems to be a small bug, as in the `generated-by` tag the version number is not compared, but that might be also a feature.

**Comment by jkrech** [comment]
Today cbuild's `-r` `--rebuild` option is probably only forwarded to the invocation of the `cmake` command. This means we may need to better understand whether `csolution` should have a command line option to control the cbuild.yml generation more precisely. If we leave cbuild.yml files from previous tool invocation untouched, this bears the risk that they are outdated when inspected or used by other tools.

**Comment by soumeh01** [comment]
The files (`*.cbuild.yml` and `*.cbuild-idx.yml`) are only overwritten when the content already present in the files differs from the new content being introduced. `csolution` always processes the information that needs to go into the files and then compares it with the existing content. If there is any difference, it overwrites it with the newly processed information.

After this fix [Clean all selected contexts before rebuilding](https://github.com/Open-CMSIS-Pack/cbuild/pull/82), The inconsistency is no more there. 

```
$ cbuild.exe ./SimpleTrustZone/SimpleTZ.csolution.yml -r
<PATH>/csolution-examples/SimpleTrustZone/CM33_s/CM33_s.Debug+AVH.cprj - info csolution: file generated successfully
<PATH>/csolution-examples/SimpleTrustZone/CM33_s/CM33_s.Release+AVH.cprj - info csolution: file generated successfully
<PATH>/csolution-examples/SimpleTrustZone/CM33_ns/CM33_ns.Debug+AVH.cprj - info csolution: file generated successfully
<PATH>/csolution-examples/SimpleTrustZone/CM33_ns/CM33_ns.Release+AVH.cprj - info csolution: file generated successfully
<PATH>/csolution-examples/SimpleTrustZone/CM33_s/CM33_s.Debug+AVH.cbuild.yml - info csolution: file is already up-to-date
<PATH>/csolution-examples/SimpleTrustZone/CM33_s/CM33_s.Release+AVH.cbuild.yml - info csolution: file is already up-to-date
<PATH>/csolution-examples/SimpleTrustZone/CM33_ns/CM33_ns.Debug+AVH.cbuild.yml - info csolution: file is already up-to-date
<PATH>/csolution-examples/SimpleTrustZone/CM33_ns/CM33_ns.Release+AVH.cbuild.yml - info csolution: file is already up-to-date
<PATH>/csolution-examples/SimpleTrustZone/SimpleTZ.cbuild-idx.yml - info csolution: file is already up-to-date
```

```
$ cbuild.exe ./Hello/Hello.csolution.yml -r
<PATH>/csolution-examples/Hello/Hello.Debug+AVH.cprj - info csolution: file generated successfully
<PATH>/csolution-examples/Hello/Hello.Release+AVH.cprj - info csolution: file generated successfully
<PATH>/csolution-examples/Hello/Hello.Debug+AVH.cbuild.yml - info csolution: file is already up-to-date
<PATH>/csolution-examples/Hello/Hello.Release+AVH.cbuild.yml - info csolution: file is already up-to-date
<PATH>/csolution-examples/Hello/Hello.cbuild-idx.yml - info csolution: file is already up-to-date
```

**Comment by jkrech** [comment]
https://github.com/Open-CMSIS-Pack/cbuild/pull/82
