### ISSUE TITLE
YAML input formats: a pack selection with `path:` specified, must not have a version 

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1097]
**Describe The Problem To Be Solved**
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#pack
`path:` specifies an explicit path name that stores the software pack 
In this case the pack version is directly taken from the `<packID_without_version>`.pdsc file in the specified directory. Therefore the pack version must not be specified in the `pack:` node.

**Suggest A Solution**
Clarify specification and have `csolution` raise an error message if a pack version is specified and a `path:` is specified at the same time.

**Comment by brondani** [comment]
Error messages and schema changes were addressed in https://github.com/Open-CMSIS-Pack/devtools/pull/1116.
@ReinhardKeil Would you clarify the specification accordingly? Thanks

**Comment by jkrech** [comment]
Documentation fixed: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#pack
