### ISSUE TITLE
packchk : wrong ERROR M310 ?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#110]
Hi

It seems that function that is checking file name doesn't work when path name includes "." ?

```
*** ERROR M310: C:/xxx/STMicroelectronics.STM32U5xx_Drivers.pdsc (Line 597) 
  Filename mismatch (case sensitive):
  PDSC name : 'config/ReferenceFiles/CRC/stm32_crc_template.h'
  Filename  : '.config/ReferenceFiles/CRC/stm32_crc_template.h'
```

Here is STMicroelectronics.STM32U5xx_Drivers.pdsc (Line 597):
```
        <file category="other" name=".config/ReferenceFiles/CRC/stm32_crc_template.h"/>
```

**Comment by jeromecoutant** [comment]
Seems that
'.config/ReferenceFiles/CRC/stm32_crc_template.h'.find_first_not_of("./") = 1
'.config/ReferenceFiles/CRC/stm32_crc_template.h'.find_first_not_of(".") = 1
'.config/ReferenceFiles/CRC/stm32_crc_template.h'.find_first_not_of("/") = 0

**Comment by thorstendb-ARM** [comment]
The function CheckCaseSense() (required for Windows only) compares the path/file found on the FS with what is exactly specified in the PDSC (file Exist() check is done before).
A relative path must be trimed before it is compared with the result. This is where the "." fell through.
To fix this, the "find_first_of()" must be changed to "find("./")".

**Comment by jkrech** [comment]
For the time being use this version of PackChk:
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/Linux64/PackChk
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/Win32/PackChk.exe
