### ISSUE TITLE
CMSIS-Toolbox 2.0: csolution-examples - SimpleTrustZone does not build when specifying `-r` (rebuild)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1100]
The SimpleTrustZone example does not build as the build process deletes `out\AVH` directory.

**To Reproduce**
Use 
 - Example: https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/SimpleTrustZon
 - Command: `cbuild SimpleTZ.csolution.yml -r -c .Debug`

**Expected behavior**
The issue is that each build cleans the `out\AVH` directory. However it should only delete the files `<cproject.name>.*` when the build target of `<cproject.name>.<build-type>+<target-type>.clog` is different.

See also #831

**Comment by jkrech** [comment]
A rebuild (-r) runs a clean followed by build. During the clean the whole content of the tmp and output folder is removed.
When building without rebuild the build and updates of individual contexts works as expected.

**Comment by ReinhardKeil** [comment]
OK, I see.  In this case I would change the order where this is processed to:
  - first clean all contexts
  - the start the build process

**Comment by brondani** [comment]
Fixed in https://github.com/Open-CMSIS-Pack/cbuild/pull/82
