### ISSUE TITLE
packchk : wrong ERROR M339 ?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#111]
Ex:
```
M056: Checking if File category 'include' has correct extension: 'Inc'
*** WARNING M339: C:/xxx/STMicroelectronics.STM32U5xx_Drivers.pdsc (Line 631) 
  Include Path 'Inc' must not be a file!
```

Maybe line
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/packchk/src/CheckFiles.cpp#L687
if(RteFsUtils::IsDirectory(name)) {
should be
if(!(RteFsUtils::IsDirectory(name))) {
?

**Comment by thorstendb-ARM** [comment]
Wrongly ported to RteFsUtils.

**Comment by jkrech** [comment]
For the time being use this version of PackChk:
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/Linux64/PackChk
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/Win32/PackChk.exe

**Comment by jeromecoutant** [comment]
Verified with #123
