### ISSUE TITLE
Check filename compatibility Linux/Windows

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1115]
The project https://github.com/RobertRostohar/AVH-MLOps/blob/main/Target/CM23/Target.clayer.yml#L15 refers

```
         - file: ./FVP_config.txt
```

However the filename on disk is just `fvp_config.txt`.  On Windows everything works fine, but porting this project to Linux fails as filenames are case sensitive.  Can the CMSIS-Toolbox check for compatibility between Linux and Windows?

**Comment by brondani** [comment]
CMSIS-Toolbox 2.1.0 already has portability check:
```
$ csolution.exe Project/TFLmicrospeech/MLOps.csolution.yml convert -c ML_Test.balanced+CM23
D:/examples/AVH-MLOps/Target/CM23/Target.clayer.yml:15:17 - warning csolution: './FVP_config.txt' has case inconsistency, use 'fvp_config.txt' instead
```
