### ISSUE TITLE
Add Memory Information to  build/debug information files.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1117]
It should be beneficial to get the information from the packs about memory into the [build information files](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md).

Proposal is to add the system wide memory information to `build-idx.yml` the context specific memory into `<context>.cbuild.yml`. 

Note: This needs more work at the specification side.

**Comment by ReinhardKeil** [comment]
Should we do this in the `cbuild-run.yml` file proposed under [#1831](https://github.com/Open-CMSIS-Pack/devtools/issues/1831)

**Comment by brondani** [comment]
`cbuild-run.yml` is covered in https://github.com/Open-CMSIS-Pack/devtools/issues/1867
