### ISSUE TITLE
packchk : multiple include pdsc seems not possible

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#112]
I tried to include 2 PDSC as specified in the usage:
  Check: packchk <InFile.pdsc> -i <RefFile1.pdsc> -i ... <RefFile2.pdsc> -v

But only 1 is taken into account:
M051: Adding PDSC File: xxx
M051: Adding PDSC File: xxx OK

**Comment by thorstendb-ARM** [comment]
Found, caused by a wrong early exit.

**Comment by jkrech** [comment]
For the time being use this version of PackChk:
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/Linux64/PackChk
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/Win32/PackChk.exe

**Comment by jeromecoutant** [comment]
Verified with #122
