### ISSUE TITLE
[csolution] Support multiple component instances

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1123]
The component subnode `instances` is described in the specification but it is not yet implemented:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#instances

There is also an open discussion in Open-CMSIS-Pack-Spec about this subject:
Handling of Multiple Component Instances [#76](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/76)

**Comment by edriouk** [comment]
RTE library already handles multiple component instances and their config files.
What is not yet implemented:
- describing number of instances in cproject.yml file and passing this information to RTE model when selecting components

**Comment by fred-r** [comment]
Do we agree that a component with "MaxInstance>1" and no "attr=config" files in its description is still accepted ?
In such a case, you cannot really link easily the instance and the files associated to it.

**Comment by edriouk** [comment]
@fred-r, sure you can use "MaxInstance>1" without config files as well. 
RTE_Components.h is populated with zero-based component indexes, e.g: 
```
/* Keil::File System&MDK-Plus:Drive:Memory Card@6.16.2 */
#define RTE_FileSystem_Drive_MC_0       /* File System Memory Card Drive 0 */
#define RTE_FileSystem_Drive_MC_1       /* File System Memory Card Drive 1 */
```

**Comment by jkrech** [comment]
Considering the fact that the subnode `instances` is specified but neither allowed by the Input YAML schema files nor supported by `csolution` processing this becomes a defect rather than an enhancement.
Note that in the `cprj` format and the `cbuildgen` tools already support the attribute [instances](https://open-cmsis-pack.github.io/devtools/buildmgr/latest/element_components.html#element_component)

**Comment by jkrech** [comment]
We have closed the discussion about changes to the specification and agreed that we would use the existing scope and features as already specified.
We need to ensure that we reflect the specification of instances in the schema of the CMSIS solution project YAML format once the format has been agreed:

current:
```
components:
  - component: USB:Device
    instances: 2
```

proposed 2024-02-14 (https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md#instance-number)
adding optional instance count [=N] (default 1)
```
[Cvendor::] Cclass [&Cbundle] :Cgroup [:Csub] [&Cvariant] [=N] [@[~ | >=]Cversion]
```
```
components:
  - component: USB:Device=2
```
