### ISSUE TITLE
[RTE] API version selection/resolution may be incorrect

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1124]
**Describe the bug**
A component implementing `Capiversion="0.1.0"` fails to build because the `<api version="1.0.0">` is selected when present. The interface versions are incompatible (major version differs).

**To Reproduce**
install both pack versions:
ARM::CMSIS@5.9.0
ARM::CMSIS@6.0.0-dev35 (https://github.com/ARM-software/CMSIS_6/releases/tag/dev%2Fv6.0.0-dev35)
and
Keil::B-U585I-IOT02A_BSP@1.0.0
Add component: Keil::CMSIS Driver:VIO:Board&B-U585I-IOT02A
to your project and inspect the selected include path for the CMSIS Driver:VIO api (VIO is taken from ARM::CMSIS@6.0.0... with version 1.0.0 instead of ARM::CMSIS@5.9.0 with version 0.1.0

**Expected behavior**
CMSIS Driver:VIO needs to be taken from ARM::CMSIS@5.9.0 with version 0.1.0

**Environment (please complete the following information):**

- RTE Model
- Version 2.1.0
- OS: all

**Comment by jkrech** [comment]
It is perfectly valid to load two versions of a pack and then pick and choose versions of components but also resolve suitable versions of an api for selected components. The only thing that is not supported is to have multiple components which implement incompatible versions of the same api.

**Comment by edriouk** [comment]
Fixed by PR  https://github.com/Open-CMSIS-Pack/devtools/pull/1130
