### ISSUE TITLE
[csolution] <solution>.cbuild-idx.yml always contains the list of all project contexts

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1125]
**Describe The Problem To Be Solved**
The index file shall represent the structure of the solution, listing all projects, build-types and target-types => contexts as well as the location of the `<context>.cbuild.yml` files, regardless whether a context has been processed or not.
This makes the file content independent from the csolution command line and allows tools to read the solution structure without processing the solution.

**Suggest A Solution**
For this purpose the `<solution>.cbuild-idx.yml` is generated for all contexts as if `csolution convert <solution>.csolution.yml` gets invoked and any specified contexts `-c <context>` options are ignored.

Note: It is proposed to have `csolution update-rte` update the cbuild-idx.yml file as well (covering the case a build-type, target-type or cproject, clayer got changed)

**Comment by brondani** [comment]
Implemented in https://github.com/Open-CMSIS-Pack/devtools/pull/1136
