### ISSUE TITLE
[csolution] *.cbuild-set.yml lists all selected contexts form last invocation

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1127]
**Describe The Problem To Be Solved**
Simplify the usage of the tools for a collection of contexts in a solution named `context set` 

**(Optional): Suggest A Solution**
a) when csolution is invoked specifying multiple contexts using `--context` and `--context-replacement` as well as partial contexts, the effective list of processed contexts is stored next to the `<solution>.csolution.yml` file named `<solution>.cbuild-set.yml`
b) when csolution is invoked without specifying one or more contexts and the file `<solution>.cbuild-set.yml` exists. The contexts specified in this file  are selected.
c) when csolution is invoked without specifying one or more contexts and the file `<solution>.cbuild-set.yml` does not exists the command is executed for all contexts 
Note: any command that requires a single context to be specified will not use the above scheme and will not update the `<solution>.cbuild-set.yml` file.

**Comment by jkrech** [comment]
Feedback from Technical Project Meeting (2023-09-18) suggested that we should also store the `--toolchain` specified via the command line in case the toolchain/compiler selection is driven via the command line parameter.
This sounds very useful to me.

**Comment by brondani** [comment]
> we should also store the `--toolchain` specified via the command line in case

@jkrech The effective toolchain selection for a given context is already stored in the `compiler` node in its *.cbuild.yml file, regardless of being specified via command line or in one of the yml input files.

**Comment by fred-r** [comment]
Ok, clarified by @jkrech : this is a way to store the list of contexts you want to build without passing them as an argument to the build command.

**Comment by brondani** [comment]
> Just curious: what if I remove a context from my yml files ? This file will contain a "ghost context" ==> warning ?

In my opinion this would be an error so the process would be aborted.

**Comment by brondani** [comment]
Implemented in https://github.com/Open-CMSIS-Pack/devtools/pull/1145
