### ISSUE TITLE
pack file path in cbulid.yml generate by cbuild in macOS

### ISSUE THREAD

**Issue by TheWrangler** [Open-CMSIS-Pack/devtools#1147]
I use Keil studio for vscode on macOS to build my project
the building ouput is:

info cbuild: Build Invocation 2.1.0 (C) 2023 Arm Ltd. and Contributors
/Users/Wrangler/Terms/CANScope/CANScope_Toolkit_Firmware/CANScope_Toolkit+GD32F103C8xx.cprj - info csolution: file generated successfully
/Users/Wrangler/Terms/CANScope/CANScope_Toolkit_Firmware/CANScope_Toolkit+GD32F103C8xx.cbuild.yml - info csolution: file is already up-to-date
/Users/Wrangler/Terms/CANScope/CANScope_Toolkit_Firmware/CANScope_Toolkit.cbuild-idx.yml - info csolution: file is already up-to-date
info cbuild: Processing 1 context(s)
info cbuild: Retrieve build information for context: "CANScope_Toolkit+GD32F103C8xx"

info cbuild: (1/1) Building context: "CANScope_Toolkit+GD32F103C8xx"

M650: Command completed successfully.

*** ERROR M204:
  Path not found: '/Users/Wrangler/.cache/arm/packs/GigaDevice/GD32F10x_DFP/2.0.3/Device\Include'!
error cbuild: error executing 'cbuildgen cmake'
error cbuild: error building '/Users/Wrangler/Terms/CANScope/CANScope_Toolkit_Firmware/CANScope_Toolkit+GD32F103C8xx.cprj'
error cbuild: exit status 
Process failed with exit code 255
Process failed with exit code 255

an error like " Path not found: '/Users/Wrangler/.cache/arm/packs/GigaDevice/GD32F10x_DFP/2.0.3/Device\Include'!" exists!!!

I opened the *.cbuild.yml created by cbuild,it like:
...
  add-path:
    - StdPeriphLib/Include
    - CMSIS
    - ${CMSIS_PACK_ROOT}/GigaDevice/GD32F10x_DFP/2.0.3/Device\Include
...

but in macos,"\\" is not valid for file path,the path '/Users/Wrangler/.cache/arm/packs/GigaDevice/GD32F10x_DFP/2.0.3/Device\Include'! is not valid! 
the correct path is "/Users/Wrangler/.cache/arm/packs/GigaDevice/GD32F10x_DFP/2.0.3/Device/Include"
so how can i fix it?

**Comment by brondani** [comment]
It seems there are several paths with backslashes in the pack `GigaDevice::GD32F10x_DFP@2.0.3`
By running `packchk` over `GigaDevice.GD32F10x_DFP.pdsc` it throws hundreds of such warnings:

```
*** WARNING M327: [...]/AppData/Local/arm/packs/GigaDevice/GD32F10x_DFP/2.0.3/GigaDevice.GD32F10x_DFP.pdsc (Line 492)
  Path is not conformant: 'Device\Include\gd32f10x.h':
  Backslashes are not recommended, use forward slashes.
```

Please report it to the pack vendor.

**Comment by TheWrangler** [comment]
i replace backslashes with forward slashes in GigaDevice.GD32F10x_DFP.pdsc and rebuild,it works!
thanks!
