### ISSUE TITLE
[cbuild] support IAR C/C++ Compiler for ARM

### ISSUE THREAD

**Issue by tarek-bochkati** [Open-CMSIS-Pack/devtools#115]
It would be nice to support more compilers out of the box like `IAR C/C++ Compiler for ARM`

**Comment by mario-pi** [comment]
This looks correct to us but we at IAR would need some guidance on how to test it.

**Comment by jkrech** [comment]
@mario-pi this should be discussed in more detail in the context of the respective pull requests e.g. #480 
There is tests being added specifically for GCC, however these tests could/should be replicated for other compilers as well.

**Comment by mario-pi** [comment]
@jkrech thanks for pointing to that. I will switch to the main branch as support for EWARM 8.50 has been merged, so that from there we can start learning how the test system works.

**Comment by tarek-bochkati** [comment]
As suggested by @ReinhardKeil I'm closing this issue

**Comment by tarek-bochkati** [comment]
BTW, @mario-pi I proposing a new PR series to support Translate Controls options (aka optimize, debug and warnings)
3  / 4 PRs are merged, and the last one #484 is modifying the IAR.cmake file
it would be helpful if you can check the IAR.cmake file changes
