### ISSUE TITLE
Provide a way to access the component and API version from the source code

### ISSUE THREAD

**Issue by MiloradCvjetkovic** [Open-CMSIS-Pack/devtools#1154]
It would be good if there was a way to determine the component version at compile-time as that way it would be easier to make the code compatible with multiple component versions (if there were any incompatible changes).

**Comment by ReinhardKeil** [comment]
A potential solution would be to extend `RTE_components.h` to also contain the version information.

**Comment by jkrech** [comment]
```
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.5.4 */
        #define RTE_CMSIS_RTOS2             /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
```
adding e.g.:
```
#define ARM__CMSIS_RTOS2_Keil_RTX5_Source_MAJOR 5
#define ARM__CMSIS_RTOS2_Keil_RTX5_Source_MINOR 5
#define ARM__CMSIS_RTOS2_Keil_RTX5_Source_PATCH 4
#define ARM__CMSIS_RTOS2_Keil_RTX5_Source_VERSION 0x05050400
```

**Comment by MiloradCvjetkovic** [comment]
`#define ARM__CMSIS_RTOS2_Keil_RTX5_Source_VERSION 0x05050400`

sounds good, maybe that patch uses last 4 digits and if possible that macro is all capital letters.

For reference, this is how version is encoded for :

**Arm Compiler 5** : 
__ARMCC_VERSION     PVVbbbb
P = major
VV = minor
bbbb = build

**Arm Compiler 6** :
__ARMCOMPILER_VERSION     Mmmuuxx
M = major
mm = minor
uu = update
xx = for Arm internal use

**Comment by edriouk** [comment]
@MiloradCvjetkovic We cannot use compiler version schema here. 
Some components use year as the major version, e.g. 2023

**Comment by ReinhardKeil** [comment]
I believe that this needs more discussion as we have API version and implementation version.
In CMSIS-Driver we have already [version information](https://arm-software.github.io/CMSIS_6/latest/Driver/html/group__common__drv__gr.html#structARM__DRIVER__VERSION) at runtime.

@MiloradCvjetkovic what was the actual problem that triggered this. Could you describe the scenario?
Could this be better handled at the level of the API header file itself? Hence no change to `RTE_components.h`?

**Comment by ReinhardKeil** [comment]
I suggest to close that issue.  If there is no further votes to keep it, we close it Oct 24.
