### ISSUE TITLE
[csolution] files with category `doc` are not in the generated *.cbuild.yml

### ISSUE THREAD

**Issue by tarek-bochkati** [Open-CMSIS-Pack/devtools#1155]
**Describe the bug**
this might not be a bug, could be a wanted behavior ...
I have a cproject file:
* containing a README.md file with `doc` as category 
* or referring to component with `doc` file

in the generated `*.cbuild.yml`, only source and header files are resolved.

**To Reproduce**
* add a README.md to `*.cproject.yml` file
* then convert to `*.cbuild.yml`
* check the generate `*.cbuild.yml`

**Expected behavior**
* the README.md should be in the generated `*.cbuild.yml`

**Environment (please complete the following information):**

- cmsis-toolbox
- Version: 2.1.0
- OS: windows

**Comment by brondani** [comment]
Indeed this is the intended behaviour. Documentation files are not relevant for the build which is the scope of *.cbuild.yml files.

**Comment by tarek-bochkati** [comment]
@brondani, do you think that is interesting to align both behaviors of user files and component files ?

IMHO: 
* if we consider that the *.cbuild.yml is a build artifact only, then no need for doc files
* if we consider that the *.cbuild.yml is a lock file and it contains the resolved project state, then docs should be part of it (incl. component docs)

**Comment by jkrech** [comment]
We have moved on from using *.cbuild.yml as a lock-file. 
In https://github.com/Open-CMSIS-Pack/devtools/issues/1122 -> introducing `<csolution-name>.cbuild-pack.yml` instead.

**Comment by brondani** [comment]
@tarek-bochkati Yes for consistency we should definitely align the behavior.
For completeness I would vote to print all files, leaving to consumers to filter the categories to their use cases, but this could inflate the *.cbuild.yml files with irrelevant data.

**Comment by LMESTM** [comment]
Hi @jkrech @brondani 
for my information, have you come to a conclusion and a proposed way forward on this topic ?

**Comment by brondani** [comment]
@LMESTM I believe we agree all files must be listed in the `*.cbuild.yml` alongside their categories. I am scheduling this GH issue to be addressed for the next release.

Hint for the implementer: make use of `RteTarget::GetFilteredFiles`.
