### ISSUE TITLE
[csolution] Extend `list boards` and `list devices` behaviour

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1158]
Parsing boards, devices and processor names is non-trivial because they can be placed in several different nodes in input yml files.
The `list boards` and `list devices` commands could be used to ease this process.
Suggestion: when calling these commands over a `*.csolution.yml` and each context has a board or device selected, restrict the response to the actually selected boards/devices.

**Comment by ReinhardKeil** [comment]
See #1177

**Comment by ReinhardKeil** [comment]
I don't think that this is required anymore. Reopen it if you feel different
