### ISSUE TITLE
[csolution] Add a flag/command to retrieve the `created-for` value from csolutions

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1161]
Csolution projects now have a `created-for` flag e.g. https://github.com/Arm-Examples/Hello_MIMXRT1064-EVK/blob/855f0389a1044bb27c70b139d335786cceec024e/hello.csolution.yml#L3 to describe the minimum version of tools to use so that they understand the project definition. This piece of data is really valuable to know which projects are supported by our tools and we would like to retrieve it in a sustainable way. Thus, we would like to request a flag or a command on the csolution binary so that this value can be returned

**Comment by brondani** [comment]
Conceptually a consumer should read the `created-for` node before choosing which tool version to use. It sounds odd having to run the tool to retrieve this info.
We should guarantee a reasonable immutability of this node during the whole tool's life-cycle.

**Comment by ReinhardKeil** [comment]
I suggest that tools tolerate missing information to some level. `created-for` is optional an just an indicator.

Attached is an example of how tools should react.
[Hello-Broken.zip](https://github.com/Open-CMSIS-Pack/devtools/files/13162276/Hello-Broken.zip)

When using `cbuild` there are clear error messages:

```
C:\Test\Hello-Broken>cbuild hello.csolution.yml
info cbuild: Build Invocation 2.1.0 (C) 2023 Arm Ltd. and Contributors
error csolution: compiler: value not set
error csolution: processing context 'Hello.Debug+AVH' failed
error csolution: compiler: value not set
error csolution: processing context 'Hello.Release+AVH' failed
error cbuild: exit status 1
```

**Comment by madchutney** [comment]
@brondani, that is what we are trying to achieve, but the consumer is indirect, via the website/services. In the development of the website we are trying to establish a fixed interface between the backend services and the CMSIS ecosystem to expose the information to the end consumer. 

This would enable us not only to provide an indication to the user of which version of the tools they might require, but it would also allow any validation CI to use the most suitable tools. @ReinhardKeil I agree that if the information is not there, then this shouldn't be breaking, but I hope that for our official examples we would make the effort to include this information and improve the UX.

For context, maintaining the services is an overhead so we try to automate as much as possible. Updating our services to automatically pull in updated tools that understand multiple schema versions and are maintained in line with schema updates, is much more sustainable than updating the service to support new schemas.

**Comment by ReinhardKeil** [comment]
See #1177
