### ISSUE TITLE
[csolution, cbuildgen] Explicit section of Automatic Linker Script Generator

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1175]
**The Problem To Be Solved**
When a linker script is part of a software component, there is no way to use [automatic linker script generation](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#automatic-linker-script-generation). This is useful for many reasons, for example it enables a way that allows to change compilers, as linker scripts provided in software packs are frequently limited to just a subset of the supported compilers.

**Suggested Solution**
Add key `auto:` to the [`linker:`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#linker) node. 

`linker:`                                                   |            | Content
:-----------------------------------------------------------|:-----------|:--------------------------------
`- auto:`                                                                           | Optional  | Use [automatic linker script generation](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#automatic-linker-script-generation).
&nbsp;&nbsp;&nbsp;`regions:`                                      |  Optional  | Path and file name of `<regions_file>.h`, used to generate a Linker Script.
&nbsp;&nbsp;&nbsp;`script:`                                 |  Optional  | Explicit file name of the Linker Script, overrules files provided with [`file:`](#files) or components.
&nbsp;&nbsp;&nbsp;[`define:`](#define)                      |  Optional  | Define symbol settings for the linker script file preprocessor.
&nbsp;&nbsp;&nbsp;[`for-compiler:`](#for-compiler)         |  Optional  |  Include Linker Script for the specified toolchain.
&nbsp;&nbsp;&nbsp;[`for-context:`](#for-context)           |  Optional  |  Include Linker Script for a list of *build* and *target* type names.
&nbsp;&nbsp;&nbsp;[`not-for-context:`](#not-for-context)   |  Optional  |  Exclude Linker Script for a list of *build* and *target* type names.

>Notes:
> 
> `auto:` cannot be combined with `script:`, `for-compiler:`, `regions:` as for automatic script generation this information would be conflicting. An warning should be issued that indicates this conflict and auto should overrule other settings.
> `auto:` can be combined with `define:` to supply additional information for the preprocessor.

**Comment by ReinhardKeil** [comment]
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/1134#issuecomment-1777028097

**Comment by jkrech** [comment]
I think the linker script is rather a "source module" than a "header file".
`ac6_linker_script.sct.c`
but to ensure that this is not considered a c module and if *.h accidentally included in the preprocessing of modules I would suggest an extension that is not currently used in the build context. 
`ac6_linker_script.sct.src`

**Comment by brondani** [comment]
Currently the build system already appends [`.pp`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/cbuild/include/CbuildUtils.h#L27) after the linker script preprocessing which then would be redundant and need a clean-up.
I see the value of differentiating files that must and must not be preprocessed, but for consistency all files requiring pre-processing should have the new (yet another) file extension, not only the "auto" ones.
Another suggestion could be inspired by GNU/clang assembly files preprocessing trigger: capitalized extensions would require preprocessing.

**Comment by ReinhardKeil** [comment]
Capitalized extension are perhaps problematic as after the preprocessor step we would have:
`ac6_linker_script.SCT`  // preprocessor input
`ac6_linker_script.sct`   // preprocessor output

I like therefore the idea of using `.src` as extension which we could do already in the `./etc` directory.
The extension `.pp` should be then removed.

**Comment by brondani** [comment]
Specifying `regions` (and optionally `for-compiler`) with the default linker script is among the [expected use cases](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#linker-script-management:~:text=A%20Linker%20Script%20file%20is%20preprocessed%20when%20a%20regions%3A%20header) so combining it with `auto` should be perfectly normal.
In my opinion the only real conflict is `auto` combined with `script`, in this case the tool must throw an warning.
Implemented in https://github.com/Open-CMSIS-Pack/devtools/pull/1214.
@ReinhardKeil Would you agree and update the documentation accordingly? Thanks

**Comment by ReinhardKeil** [comment]
Added clarification in upcoming documentation
