### ISSUE TITLE
Provide Feedback on "Create Applications"

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1189]
The section [Create Applications from Components](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/Apps-from-components.md) explains a potential workflow that would require a new tool for generating [pack datasheets](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/262)

- Could we get feedback on what is missing as comments to this issue?
- Can we work on tutorials and examples?  
    - What should be used, i.e. based on LwIP, FreeRTOS, AWS components?
- How should complex examples be published?
    - Via links to Github (https://github.com/Arm-Examples)?
    - Could we change the approach to examples by leveraging clayers for boards?
 - What changes to we need to the PDSC file, i.e. 
    - remove <taxonomy>
    - extend <component> header file with node attribute (to solve an issue with LwIP)
    - change the approach to examples, i.e. via weblinks to Github?

**Comment by fred-r** [comment]
Hi @ReinhardKeil,

the section describing the creation flow of an application looks good to me.
It has the merit of being clear and concise.

I wonder if we should give more explanations about the link between:
- the world of components in this "design stage"
- the world of files that you will need in the IDE I guess

Basically, if I had to add more information I would probably try to:

1. Make the parallel between the dependencies resolved by the tool through conditions and the purpose they serve: to me, they express build-time dependencies. Basically, resolving all dependencies make sure that your project will build. It does not ensure it will run.

2. Make a relation between each step and its consequences in the world of files.

For this, I would define 3 "areas":
(A) User Code area
	This is fully under the control of the end-user (folders, files names and contents).
        This is where the templates are used.

(B) Components code area
	This is where the components code is stored.
	This is $CMSIS_PACK_ROOT by default, but a user can use local packs (mostly if he is developing in one of the packs?).

(C) Components configuration area 
        This is where the configuration code goes, (and the instantiated files too as far as I remember ?)

**Comment by fred-r** [comment]
> How should complex examples be published?
> Via links to Github (https://github.com/Arm-Examples)?
> Could we change the approach to examples by leveraging clayers for boards?

Why not delivering the examples in the packs with the example tag ?
This would be consistent with the current approach.

**Comment by ReinhardKeil** [comment]
@fred-r it will be still an option to deliver examples as part of packs, but complex examples are sometimes dynamic.  When they are part of a pack hard to maintain.  We did discuss this in yesterdays TRM meeting (maybe worth watching).

Take a look to https://github.com/Arm-Examples/mlek-cmsis-pack-examples/blob/main/mlek.csolution.yml#L24
When new packs are release, you would need to update the pack list.  For such complicated examples having them part of a pack would create a maintenance nightmare.

**Comment by ReinhardKeil** [comment]
It would be good to get further review comments on the documentation, specifically on the part [Create Applications](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/CreateApplications.md).

**Comment by jkrech** [comment]
Documentation can be updated after the tools release.

**Comment by ReinhardKeil** [comment]
This is done (as far it can go today without pack datasheets).
