### ISSUE TITLE
Remove option `--context-replacement arg`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1195]
**Problem**
I don't think the option  `--context-replacement arg` is needed anymore.

The new way is: 
option `-S` specifies that `cbuild-set.yml` is used to specify a context set.
when combined with `-c` options, these specify the new context set (overwrite the content of `cbuild-set.yml`

**Suggest A Solution**
Remove option  `--context-replacement arg` as this is confusing.

**Comment by jkrech** [comment]
@ReinhardKeil, can  you please ensure that this is removed from the documentation everywhere:
It is already removed here:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-tools.md#csolution-invocation
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-tools.md#cbuild-invocation
