### ISSUE TITLE
Should we support multiple build types for a target type? How to handle access sequences...

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1198]
The attached project uses separate out directories for debug and release build.
[SimpleTrustZone.zip](https://github.com/Open-CMSIS-Pack/devtools/files/13336410/SimpleTrustZone.zip)

To duplicate use:
`csolution convert SimpleTZ.csolution.yml -S -c CM33_s.Release -c CM33_ns.Debug`

There is an issue when `CM33_s.release` and `CM33_ns.debug` is selected.  The file CM33_ns.Debug+AVH.cbuild.yml contains:
```
        - file: ../out/CM33_s/AVH/Debug/CM33_s_CMSE_Lib.o
```

My Environment: Windows, CMSIS-Toolbox 2.2.0 pre-release

Workaround: configure a common out directory (as in the public example).

**Comment by brondani** [comment]
@ReinhardKeil context-set just [lists all selected contexts from last invocation](https://github.com/Open-CMSIS-Pack/devtools/issues/1127). Why would you expect any impact in access sequences?
`../out/CM33_s/AVH/Debug/CM33_s_CMSE_Lib.o` seems the correct expansion for the access sequence `$cmse-lib(CM33_s)$` when processing the context `CM33_ns.Debug+AVH`.

**Comment by ReinhardKeil** [comment]
@brondani in above setup, the `CM33_s` is build in `Release`, whereas `CM33_ns` is build in `Debug`. The context-set should define  the context setup for the application where some parts are generated in Debug.  Debug has the effect that size/timing is different.  Therefore the user expectation is that you can mix the build types.

There is an acceptable workaround:  use the same `out` directory for both build types. But I believe, we should discuss how these build scenarios are.  I got confused yesterday with #1200 - I believe generating two different build types for the same target makes little sense.

**Comment by jkrech** [comment]
According to the [access sequence specification](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#access-sequences) the programmatic way of specifying the access of another context is:

```
   files:
      - file: $cmse_lib(CM33_s.Release)
```

I do appreciate that this cannot be steered from the command line.

**Comment by ReinhardKeil** [comment]
Replaced by #1587
