### ISSUE TITLE
Proposal: restrict --context-set to one identical target-type and only one build-type per context.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1203]
**The Problem To Be Solved**

When working with multiple projects it is required to know which `--context` selection should be used to debug and download to the target hardware. For that reason we have introduced the option `--context-set`. See also #896

Currently it is possible to use more than one build-type per context. This makes the tool very flexible, but is hard to understand from user's point of view. IMHO, we should also consider how a debugger or a download process would use the generated projects.

**Suggested Solution**
When using the option `--context-set`, the CMSIS-Toolbox only allows one `build-type` per `context`.  For example https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/SimpleTrustZone that would mean it is impossible to request context `CM33_s.Release+AVH` and `CM33_s.Debug+AVH` at the same time.

For [Access Sequences](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#access-sequences) I propose:

- Access sequences that have no `build-type` qualifier are handled as follows:
  - without context-set: are only permitted when they refer to the same `project-name`. Otherwise an error or warning is generated
  - with context-set: are resolved to the selected build-type for the `project-name`, which means with context-set it is possible to mix build types.

See also: #1198

**Comment by brondani** [comment]
My comment https://github.com/Open-CMSIS-Pack/devtools/issues/896#issuecomment-1651409667 is still valid.

**Comment by mcgordonite** [comment]
Should we go further and only allow one target type and build type per project?

**Comment by ReinhardKeil** [comment]
> Should we go further and only allow one target type and build type per project?

I guess that depends:
- IDE: Yes, perhaps in an IDE flow the right choice. Usually you have just one target connected. 
- DevOps/MLOps: CLI builds for CI/CD testing may need multiple targets

**Comment by VGRSTM** [comment]
> Should we go further and only allow one target type and build type per project?

IDE view:  for target-type possibly one is good enough, build-type my guess is no choice we have to support multiples (common Debug & Release profiles are a must)

**Comment by ReinhardKeil** [comment]
I believe this needs further review. We should make also a decision about `target-types` and maybe restrict them to just one when using `context-set`.

This is related to #1215

**Comment by jkrech** [comment]
How about being able to concurrently select one or more `project` . `build-type` for each `target-type`, assuming that all projects I want to program "concurrently" use the same `target-type`. Or is that adding too much complexity?

this could be all merged into a single `<csolution-name>.cbuild-set.yml` file grouped by `target-type` and an `active target-type` selected. This would allow to switch between target-types.

**Comment by ReinhardKeil** [comment]
I recommend that `context-set` is restricted to one identical `target-type` for the complete solution, and one `build-type` per project. The `build-type` for each project can be different. This matches "Active Context" selection in an IDE.

**Comment by soumeh01** [comment]
If I understand correctly, given the listed contexts within the project

```
$ cbuild list contexts test.csolution.yml
project1.debug+target1
project1.debug+target2
project1.debug+target3
project1.release+target1
project1.release+target2
project1.release+target3
project2.debug+target2
project2.release+target2
project3.debug+target1
project3.debug+target2
project3.debug+target3
project3.release+target1
project3.release+target2
project3.release+target3
project4.debug+target1
project4.debug+target2
project4.debug+target3
project4.release+target1
project4.release+target2
project4.release+target3
project5.debug+target2
project5.debug+target3
project5.release+target2
project5.release+target3
```

the proposed resultant contexts to be selected are those corresponding to

```
project1.debug+target1
project1.release+target1
project3.debug+target1
project3.release+target1
project4.debug+target1
project4.release+target1
```

Essentially, this selection aligns with querying contexts for `+target1`

**Comment by ReinhardKeil** [comment]
@soumeh01 the behavior of `cbuild list context` should not change.

What should change is the possibility to select different contexts when using the option `--context-set`.

It should be only possible to select:
  - the same target-type for all projects.
  - only one build-type for a project.
  - it is possible to exclude projects from a `context-set`
  
With your example, when using `--context-set` it is possible to use:
```
project1.debug+target1
project3.release+target1
project5.debug+target1
```

This should create an error:

```
project1.debug+target1
project1.release+target1     # error: project1 is selected already with build-type debug
project3.release+target2     # error: project1 is selected already with target-type target1
project5.debug+target1
```

**Comment by soumeh01** [comment]
@ReinhardKeil Thanks for the explanation. It appears there might have been a misunderstanding regarding the comment. I fully agree that the change is unnecessary for the `list contexts` command. When I mentioned `list contexts`, I simply intended to demonstrate that the project supports these specific contexts.

Nonetheless, I've taken note of the restrictions and have already implemented them [here](https://github.com/Open-CMSIS-Pack/devtools/pull/1509)

**Comment by soumeh01** [comment]
I would appreciate your feedback to enhance the effectiveness of user error messages. Please feel free to share your comments, feedback, or suggestions. Currently, error messages are reported as follows:

```
error csolution: error found in context(s):
  test1.Debug+CM3  <-- invalid selection, 'CM0' target-type is already chosen from 'test1.Debug+CM0'
```

```
error csolution: error found in context(s):
  test1.Release+CM0  <-- invalid selection, the combination of 'test1' and 'CM0' for build-type 'Debug' is already selected from 'test1.Debug+CM0'
```

**Comment by jkrech** [comment]
```
error csolution: invalid combination of contexts specified (<solution>.cbuild-set):
  target-type does not match for "test1.Debug+CM3" and "test1.Debug+CM0"
```

```
error csolution: invalid combination of contexts specified (<solution>.cbuild-set):
  build-type is not unique for project "test1" in "test1.Release+CM0" and "test1.Debug+CM0" 
```
