### ISSUE TITLE
[projmgr] Library project dependency is not well set

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#121]
Creating a csolution project describing two cproject ones:
>solution:
  projects:
    - project: ./Project_1/Project_1.cproject.yml
      depends:
        - Project_2
    - project: ./Project_2/Project_2.cproject.yml

If one is set to `output-type: lib` being dependency of second we end up at that time with some lacking directives if related .cprj file content.

>\<group name="Project Dependencies"\>
      \<file category="other" name=".a"/\>
 \</group\>

and nothing if `</ldflags>`

**Comment by brondani** [comment]
@VGRSTM Please note the temporary `depends` keyword has been removed in the PR https://github.com/Open-CMSIS-Pack/devtools/pull/118. Now you should use [Access Sequences](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#access-sequences).

**Comment by VGRSTM** [comment]
@brondani I'm aware access sequences [ok](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#access-sequences) principle but I've not played with yet (quite fresh introduction). Will do for sure asap. At that I'm not sure how they helps to define build order at a time ... I had feeling `depends` was quite good because explicit from root (csolution level).

**Comment by brondani** [comment]
@VGRSTM 
In your example I think you wanted to use `OutDir` instead of `Output`:
```
$Output(project[.build-type][+target-type])$ - Path to output file without extension.
$OutDir(project[.build-type][+target-type])$ - Path to output directory
$Source(project[.build-type][+target-type])$ - Path to source directory
```
We can safely discover all inter-project dependencies by analyzing the cross-references described with access sequences. Even if not explicit as it was previously with `depends`, it is still full descriptive (there is nothing hidden) and therefore it is sufficient to automate the build sequence.

**Comment by VGRSTM** [comment]
@brondani Thanks works for me now.
I agree (I've stated such myself) thru access sequence nothing hidden but sounds you agree less obvious than `depends` because we have to 
>discover all by analyzing
Based on former `depends` I was liking capability as end user from top most metadata (i.e. csolution.yml) to get direct understanding about my complex multi projects relationships

But works so closing issue !
