### ISSUE TITLE
[cbuild.yml] Missing `type` definition in schema

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1211]
the schema of [cbuild.yml](https://github.com/Open-CMSIS-Pack/devtools/blob/e12662a0a9e47b3d5126a88b501b39d28f8a8d2b/tools/projmgr/schemas/cbuild.schema.json) is missing the type definition: i.e.  `"type": "object"`  https://json-schema.org/draft/2020-12/json-schema-core#name-keywords-for-applying-subschemas

The schema should be, as follows. Otherwise any validation tool based on this schema may not work properly:
```json
{
  "$schema": "https://json-schema.org/draft/.../schema",
  "title": "...",
  "description": "...",
  "type": "object",
  "properties": {
  ....
```
The `type` field is indeed fundamental in the Json Schema https://json-schema.org/understanding-json-schema/reference/type#type-specific-keywords.

**Comment by soumeh01** [comment]
This issue has already been addressed in https://github.com/Open-CMSIS-Pack/devtools/pull/1208
