### ISSUE TITLE
csolution: ASM define management

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#1212]
Hi

From https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#define
We can see that `defines` only applies to C and C++ source files. For assembler source files use the misc: node.

In my project,  all ASM source files are built with all defines,
so if I add define with specific ASM options, define come in double

@tarek-bochkati

**Comment by jkrech** [comment]
This needs review. When we stopped forwarding the C/C++ defines to the Assembler we found that projects stopped building. We need to re-investigate this.

**Comment by brondani** [comment]
From my comment [here](https://github.com/Open-CMSIS-Pack/devtools/issues/607#issuecomment-1602681237):
> In particular the add-path scope limitation breaks the build of libraries where include paths are needed by assembly files

We could investigate whether it would be meaningful to limit the `define` scope keeping the `add-path` as it is.

**Comment by ReinhardKeil** [comment]
I think this could be the solution: https://github.com/Open-CMSIS-Pack/devtools/issues/607#issuecomment-1369774843

**Comment by ReinhardKeil** [comment]
implemented - hence closing this request
