### ISSUE TITLE
cbuild behavior when RTE directory is missing

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1213]
**Problem**

The https://github.com/Arm-Examples/mlek-cmsis-pack-examples does not contain the `.\RTE` directory.  Therefore a vanilla build using `cbuild` does not work.  

When using VS Code, there is an implicit `csolution convert` that does create this directory (with related content), 

**Reproduce**

This command fails as the RTE directory does not contain the files `Pre_Include_Global.h` and `RTE_Components.h`
```
cbuild mlek.csolution.yml -c kws.Release+AVH-SSE-310 -S
```

This works:
```
cbuild mlek.csolution.yml -c kws.Release+AVH-SSE-310 -S --update-rte
```

**Suggested steps:**
- document the exact behavior of `update-rte`.  `update-rte` seems to be default with `csolution convert` whereas `cbuild` does not use this.
- discuss if there should be another control that creates `pre-include` and `RTE_Components.h` file when they are missing.  I believe forcing a config file update by default in `.\RTE` is not the right approach.  However I would like to understand what `update-rte` really does.

**Comment by jkrech** [comment]
Once we have the `*.cbuild-pack.yml` file support, it becomes clear that the default `cbuild` invocation will not modify any project sources but instructs `csolution` to only generate files required by the `build-system`, followed by the build system invokations (cmake + ninja):
=> reproducible build
`csolution` is directly invoked during the `construction` and `configuration` of a project by the user or an IDE.

`convert` and `update-rte` commands run through the same processing steps, however `update-rte` will stop after the config file PLM and RTE file generation (global/local preinclude, RTE_Components.h) and e.g. not generate cprj files.

**Comment by ReinhardKeil** [comment]
Fixed in https://github.com/Open-CMSIS-Pack/cmsis-toolbox/commit/5ec3e56baed8e5e0b67c134d5deba1ad0b020289
