### ISSUE TITLE
[csolution] command line option `list toolchains` + `*.csolution.yml` only works for explicitly specified `compiler:`

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1217]
**Describe The Problem To Be Solved**
How does the user or IDE using a project find out, which toolchains are supported by a csolution project? Especially for a toolchain agnostic project without `compiler:` nodes, when using components/files which are not available/suitable for `all` toolchains.

**(Optional): Suggest A Solution**
`csolution list toolchains` today prints the currently registered toolchains.
When specifying a `*.csolution.yml` file, only those toolchains that are supported in the specified `*.csolution.yml` files should be printed. 
The default toolchain, being selected when no `--toolchain` is specified at the command line should be identified.

* Details of the technical implementation
The yml project format allows to specify the default compiler or to associate a compiler with `<target>` and `<build>` types.
There is no explicit way of specifying the `supported toolchains` within the .

**Comment by brondani** [comment]
For a cleaner toolchain selection, while keeping backwards compatibility, I would suggest the following conceptual change:
- Interpret the `compiler` node as `for-compiler` node allowing to list compatible toolchains, in other words to list the toolchains that CAN be used to compile the solution.
- In case of ambiguity, i.e. when a context is compatible with more than one registered toolchain, the command line `--toolchain` would be mandatory.

**Comment by mcgordonite** [comment]
@brondani how would your suggestion work with the `compiler` field in cdefault?

**Comment by ReinhardKeil** [comment]
Fixed with https://github.com/Open-CMSIS-Pack/cmsis-toolbox/commit/5ec3e56baed8e5e0b67c134d5deba1ad0b020289
