### ISSUE TITLE
[cbuildgen] `packlist` does not report missing packs when `local_repository.pidx` does not exist

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1232]
**Describe the bug**
The `cbuildgen packlist <*.cprj>` command does not report the missing packs when the `.\Local\local_repository.pidx` file is not present in the pack repository.
This seems to be a regression introduced in RteKernel in [#1221](https://github.com/Open-CMSIS-Pack/devtools/pull/1221/files#diff-20efca01123832d89af249203c0ac11a49309b269aa98789e67e2655deadcaa1R479-R480).

**To Reproduce**
Set `CMSIS_PACK_ROOT` to an empty folder and run  `cbuildgen packlist <Target.cprj>`, for example [Target.cprj](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/test/testinput/Examples/AC6/ArmAsm/Target.cprj) from test input data.

**Expected behavior**
The tool should report the missing packs in the stdout and in cpinstall files, for example:
```
M654: Package 'ARM::CMSIS' was added to the list of missing packages.
M654: Package 'Keil::ARM_Compiler' was added to the list of missing packages.
M650: Command completed successfully.
```

**Environment (please complete the following information):**
- cbuildgen
- Version 2.2.0
- OS: windows/linux

**Additional context**

**Comment by ReinhardKeil** [comment]
Please use the term 'pack' instead of 'packages'. The message should be therefore:
```
M654: `pack: ARM::CMSIS` was added to the list of missing packs.
M654: `pack: Keil::ARM_Compiler' was added to the list of missing packs.
M650: Command completed successfully.
```
