### ISSUE TITLE
[Future build] Add language and scope support in the build generator

### ISSUE THREAD

**Issue by KeilChris** [Open-CMSIS-Pack/devtools#1234]
Issue [#702](https://github.com/Open-CMSIS-Pack/devtools/issues/702) has asked to add language and scope to csolution which has been done. Unfortunately, cbuildgen does not support this. So the support in the CMSIS-Toolbox is only half-baked. With a partner, I am working on a CMSIS-Pack that requires the "language" attribute being supported throughout the whole tools flow.
As we are planning for the updated build generator tool based on cmake, I ask for adding this to the list of features to be present from the start.

**Comment by brondani** [comment]
Implemented in https://github.com/Open-CMSIS-Pack/cbuild2cmake/pull/91 and https://github.com/Open-CMSIS-Pack/devtools/pull/1433.
It will be available in the next release [CMSIS-Toolbox 2.4.0](https://github.com/orgs/Open-CMSIS-Pack/projects/10).
