### ISSUE TITLE
Layers Interfaces

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#124]
Can you please elaborate a bit more about this element:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#layer-interface-defintions

This is quite new for me, can you clarify ?
How is an interface specified ? Via components ? 
is there a link with the notion of API ?

**Comment by fred-r** [comment]
Thanks Joachim.
I am not very familiar with the concept of API already present in the spec:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_apis_pg.html#element_api

Can we specify that we provide and consume API with the current spec ?
I find only reference to Capiversion.

Maybe this is the first step I should take ?

Then Interfaces are "similar ideas" but at layer level ?
So interfaces are in fact features (I would call it services ?) that a layer can:
- either provide
- or consume

How to declare it ?

And I am not sure it is so close to API.
I mean an API is a service but also the way to provide it.
Is the interface also defining the way to provide it ?
I guess so, otherwise it becmes complicated to link compatible layers.

Thanks & Regards,
Fred

**Comment by fred-r** [comment]
I still have difficulties to understand how features rely to API.

 A feature is something defined at layer level ?
And it is associated to [1..N] APIs ?
An API can be explicitly and API but maybe for people not using the <api> it may be a Cclass/Cgroup/[Capiversion] combination ?

So

Layer ---> [1..N] provided interfaces  --> [1..N] APIs
         ---> [1..N] consumed interfaces

And the tool looks for layers providing the consumed interfaces ?
But as there is no central repository of interfaces then i guess the toll must go down to API level to make sure it is really matching ?

**Comment by jkrech** [comment]
Creating/maintaining a central repository of interfaces may be something we need to explore. Any ideas or existing examples  we could learn from? Or do you believe going down to the API level will be sufficient?

**Comment by fred-r** [comment]
Clarified by @ReinhardKeil : the interface concept is a HW notion, it does not imply the SW API.

**Comment by ReinhardKeil** [comment]
@fred-r the node `interface:` is no longer limited to `*.clayer.yml`.  I did also improve the description https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#interface. 

I suggest we open new issues to discuss it further.
