### ISSUE TITLE
CPackGet Local Filepath

### ISSUE THREAD

**Issue by Jonny-vb** [Open-CMSIS-Pack/devtools#1242]
I've just updated uVision Keil to the latest version (5.39), which it sounds like now uses cpackget for managing packs behind the scenes. However, this is now not working in the scenario we have - we have some internally developed packs which we store on a local network, with the pdsc url pointing to this as a "file://" url. This was previously supported and worked well, but now I can't install a pack by double clicking it, and the uvision package manager no longer finds updates in the given location.
The file path has some spaces in it which I suspect are causing the issue, but we can't change the location of the pack as that would break lots of old software of ours relying on the pack.

**To Reproduce**
Create a cmsis pack located in a local file location, specifying the pack url as "file://....". Try to install pack by double clicking it, or through the uvision package manager.

**Expected behavior**
The pack will install and/or be updatable.

**Environment (please complete the following information):**

uvision 5.39
Windows 10

**Additional context**

**Comment by jkrech** [comment]
Initial investigation shows that `cpackget` is not at fault.
```
cpackget add Local Pack_Distribution\MyVendor.Local.1.0.0.pack
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
I: Adding pack "Pack_Distribution\MyVendor.Local.1.0.0.pack"
E: File "Pack_Distribution\MyVendor.Local.1.0.0.pack" doesn't exist
E: file not found
```
It looks like the invocation by MDK PackInstaller is not putting the pack path into quotes which fails when there is a space in there.

Once quotes are added cpackget works.
```
cpackget add "Local Pack_Distribution\MyVendor.Local.1.0.0.pack"
I: Adding pack "Local Pack_Distribution\MyVendor.Local.1.0.0.pack"
I: Extracting files to C:\Users\jkrech\AppData\Local\Arm\Packs\MyVendor\Local\1.0.0...
I: 100% |█████████████████████████████████████████████████████████████████████████████████████| (1/1, 999 it/s)
```
This needs to be reported against Keil MDK uVision.

The suggested workaround for you is to continue to use the PackInstaller from MDK 5.38a until there is a fix available.
(alternatively download a slightly updated version (but not using cpackget): https://developer.arm.com/documentation/ka005531/latest)

**Comment by jkrech** [comment]
The bug in the MDK packinstaller is now tracked against the product. Therefore I am closing this issue here.
