### ISSUE TITLE
[csolution] `intdir`: solution level intermediate directory is needed for multi-context CMakelists 

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1243]
In the multi-context scenario a solution level intermediate directory is needed.
By default it could be the top level `tmp` directory already defined in the `intdir` [specification](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.2.0/docs/YML-Input-Format.md#output-dirs).
How `intdir` should be evaluated when it is customized, in particular concerning context specific access sequences?
Should we change or restrict the rules concerning its customization?

**Comment by ReinhardKeil** [comment]
It this really required?  I would suggest to clarify the behavior of access sequences. It could be:

`$cmse-lib(Myproject)$` is only permitted when `--context-set` is used. When applying the [**Rules for Context-Set**](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#working-with-context-set) this would give only one valid context that translates to a full specified context.

Without `--context-set` for such access sequences a fully qualified context must be specified.  Would this work?

**Comment by ReinhardKeil** [comment]
The direct CMake flow:
 - requires a top-level `intdir`
 - does not allow to specify `intdir` at cproject.yml level.

A potential solution is to only allow to specify `intdir` at the level of csolution.yml.

**Comment by ReinhardKeil** [comment]
# Current situation

[`output-dirs:`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#output-dirs) is only allowed at `*.csolution.yml` level. Only the option to use Access Sequences for `intdir:` needs to be removed from the documentation.

Is this correct?

**Comment by ReinhardKeil** [comment]
In case of Access sequences in `intdir:`, the proposal is to just issue an warning.

**Comment by brondani** [comment]
Solved by https://github.com/Open-CMSIS-Pack/devtools/issues/1607.
