### ISSUE TITLE
Very slow configuration stage when using AC6

### ISSUE THREAD

**Issue by ronyrad** [Open-CMSIS-Pack/devtools#1260]
**Describe the bug**
The configuration CMAKE stage takes a very long time when using AC6 on Windows 10
As you can see below

-- The ASM compiler identification is ARMClang
-- Found assembler: C:/Program Files/Arm/Development Studio 2022.2/sw/ARMCompiler6.19/bin/armclang.exe
-- The C compiler identification is ARMClang 6.19.0
-- The CXX compiler identification is ARMClang 6.19.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Arm/Development Studio 2022.2/sw/ARMCompiler6.19/bin/armclang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Arm/Development Studio 2022.2/sw/ARMCompiler6.19/bin/armclang.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (188.5s)
-- Generating done (0.6s)

The configuration stage takes 188.5 seconds.
On consecutive builds, it will take ~30sec

If GCC is used the configuration stage takes ~3sec

We are using AC6 with a floating license

Can the configuration time be reduced?

Setup
CMSIS TOOLS 2.1.0
Windows 10 Machine
AC6 6.19.0 compiler

**Comment by jkrech** [comment]
I don't think CMake is treating AC6 and GCC differently when it comes toolchain identification/configuration. Most likely it is the compiler/assembler itself adding this latency.
@brondani any thoughts/options to cache/skip this step?

**Comment by ReinhardKeil** [comment]
@ronyrad are you using a AC6 Floating License?  Could this explain the latency?

**Comment by brondani** [comment]
The compiler detection can be skipped as commented [here](https://github.com/Open-CMSIS-Pack/cbuild/issues/60#issuecomment-1519700208) but not the full configuration stage, anyway it's automatically cached by cmake and apparently consecutive builds are still slow.
Indeed license handling could be slowing it down.

**Comment by ReinhardKeil** [comment]
MDK v6 uses User Based Licensing.  This latency (caused most likely by slow Floating User Server) should not appear anymore. Hence I'm closing this issue.
