### ISSUE TITLE
Clarify `cbuild` schema check flag `--schema`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1261]
**Describe the bug**

When `cbuild` is called with  option `--schema`, on Windows the `xmllint` tool is required. Do we really need to check the XML input files?  I believe the `schema` check should be limited to the `YML` input files.

Could you clearify what schema check is really enabled by this command?  Is the csolution schema check disabled when this option is not used (csolution called with `--no-check-schema`)?

**Comment by jkrech** [comment]
Currently YML and XML  schema checks are unified, it's enabled or disabled for both (disabled by default).
When the build runs with yml as input, there is no need to check the XML (cprj) schema.
Only when the command is `buildcprj` and therefore the input file must be a *.cprj file (`cbuild buildcprj myproject.cprj`) the `--schema` flag should invoke the xmllint tool.
