### ISSUE TITLE
Explore usage of Build Information files to provide project information in IDEs

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1266]
**Describe The Problem To Be Solved**
There is a risk that the source files of components are not resolved in the same way as the build process is using source files. This could be caused by local pack installations or explicit pack path information.

**Suggest A Solution**
This could be solved by using the csolution build information files that are also used for the CMake process.  In this way we ensure that the IDE has knowledge about the exact source files.

This requires that build information files are also created in case of errors such as components that cannot be resolved or missing generator output files. 

Build Information files may also contain information about generator run commands and potentially other component related information (API, documentation, etc.)

Relates to #1265

**Comment by jkrech** [comment]
@ReinhardKeil  can we close this one in track the implementation (`cbuild setup`) here: https://github.com/Open-CMSIS-Pack/devtools/issues/1265
