### ISSUE TITLE
Better definition of --toolchain option

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1268]
**Describe The Problem To Be Solved**
The `compiler:` node in the YML input files is possible at the following levels:
- `default:`, `solution:`, or `project:` to specify the compiler used for a complete csolution project or just one `cproject.yml` part.
- for each `build-type:` or `target-type:` a compiler can be specified.

It is however unclear what the option `--toolchain` at the command line level does.

**Suggest A Solution**

IMHO it should overwrite all `compiler:` settings, which is useful for:
- testing a new compiler or new compiler version on the overall project
- for unit testing to allow usage of different compilers

Is this inline with the current implementation?

IMHO we can add over time a `lock compiler` option. But for now I don't see this as a priority.

**Comment by brondani** [comment]
> Is this inline with the current implementation?

Yes this sounds to be aligned with the current implementation.
For the records, this is my suggestion for a cleaner toolchain selection:
https://github.com/Open-CMSIS-Pack/devtools/issues/1217#issuecomment-1821072361

**Comment by ReinhardKeil** [comment]
Fixed with https://github.com/Open-CMSIS-Pack/cmsis-toolbox/commit/5ec3e56baed8e5e0b67c134d5deba1ad0b020289
