### ISSUE TITLE
[csolution] How to update a pack version in the *.cbuild-pack.yml file?

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1277]
**Describe the bug**
The documentation for [pack locking](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#pack-locking) does not describe how a pack version in the `*.cbuild-pack.yml` can be maintained:
- edit the file manually (discouraged)
- editing `pack: <packID>@<version>` node in csolution, cproject, clayer temporarily, removing the version after running e.g. a `csolution convert` command.

**To Reproduce**
see: [Steps to reproduce the behavior:](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#pack-locking)

Question: Do we need a "programmatic way" for IDEs?

**Comment by mcgordonite** [comment]
In the JavaScript world, npm has a user-editable package.json file (similar to our csolution input files) and a package-lock.json file (similar to our cbuild-pack.yml). `npm update <dependency>` updates the version of the dependency in the lock file to the latest version compatible with any version range in the package.json file.

We could introduce a similar command like `csolution update-pack My::Pack`. This would only modify the cbuild-pack.yml file.

**Comment by mcgordonite** [comment]
I think manually editing the cbuild-pack file should be discouraged. It should only be updated via running Toolbox commands. Users already have controls to select specific versions or version ranges in the YAML input files, so requiring the user to manually edit an extra file is unnecessary complexity.

However, there is a use case for updating the locked version of a pack to the latest version allowed by the version range in the input files. For example, if the user has `pack: ARM::CMSIS@~5` in a solution, and the lock file contains `5.8.0`, a user might want to update to `5.9.0` without editing the input files. In that case, a command like this would be useful:
> csolution update ARM::CMSIS

Alternatively:
> csolution update ARM::CMSIS@~5

Other pack version updates can be achieved by modifying the input files. For example, in the situation above with `ARM::CMSIS@~5` in the cproject file and `5.8.0` in the lock file, if the user wants to use `5.7.0` instead they should update the version in the input file to `ARM::CMSIS@5.7.0`.

**Comment by ReinhardKeil** [comment]
The solution to this is the option `--load latest`. It updates with the modification in #1291 the `*.cbuild-pack.yml` file.

**Comment by mcgordonite** [comment]
> The solution to this is the option --load latest.

This would update all packs in the solution rather than just one pack, but that could be enough for most users.

**Comment by jkrech** [comment]
@mcgordonite are you happy to close this issue based on the method that allows the user to update all used packs to the latest installed versions.

**Comment by mcgordonite** [comment]
Yes, happy to close.

**Comment by ReinhardKeil** [comment]
ToDo: Improve documentation

**Comment by ReinhardKeil** [comment]
Started with a documentation for this topic here https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/Apps-from-components.md#update-software-packs

Comments welcome
