### ISSUE TITLE
[csolution] misc->for-compiler: documentation vs schema misalignment

### ISSUE THREAD

**Issue by soumeh01** [Open-CMSIS-Pack/devtools#1279]
Reported by @JonatanAntoni 

**Describe the bug**
Currently `misc, for-compiler` not accepting a list of compilers
I.e., we have to duplicate options even if identical for multiple compilers

According to the documentation `for-compiler` should be accepting a list of compilers:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#misc
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#for-compiler

However, it is set to accept only one compiler type in the schema:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L285
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L91-L95

**Comment by brondani** [comment]
The `misc->for-compiler` accepts only one compiler at each item to safely keep compiler options separated.
For example:
```
  misc:
      - for-compiler: AC6
        C-CPP:
          - -O1
          - -g
      - for-compiler: GCC
        C-CPP:
          - -Og
```
In my opinion the clarity of having separated misc options overweighs the benefit of having a more concise yaml file when the options are eventually identical, for this reason I would suggest just to update the documentation to make it more clear - actually in [misc](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#misc) it is already written singular "Name of the toolchain" which implies one toolchain and not a list.

**Comment by ReinhardKeil** [comment]
Let's improve the documentation.  I would suggest not to change the tool.

**Comment by ReinhardKeil** [comment]
Fixed in https://github.com/Open-CMSIS-Pack/cmsis-toolbox/commit/5ec3e56baed8e5e0b67c134d5deba1ad0b020289
