### ISSUE TITLE
[projmgr] get version

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#128]
Very minor thing puzzling me a bit:

$ csolution --help
CMSIS Project Manager 0.9.0 (C) 2022 ARM 
...

but:

$ csolution --version
error csolution: Option 'version' does not exist

Maybe the --version can be helpful ?
Because to me the 0.9.0 is the version of the bundle, probably not the version of the csolution part ?

**Comment by brondani** [comment]
A command to get specifically the semantic version is certainly helpful, let's work on that.

**Comment by ReinhardKeil** [comment]
closing this issue as the relevant tools have now a way to list versions.
