### ISSUE TITLE
Document the scope of the `CMSIS_COMPILER_ROOT` environment variable 

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1292]
**Describe The Problem To Be Solved**
Users are unclear about what to expect from setting up a custom `$CMSIS_COMPILER_ROOT` directory.

**Suggest A Solution**
Enhance the documentation of the `$CMSIS_COMPILER_ROOT` environment variable
here: [Environment Variables](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#environment-variables) specifying the files that are referenced from the specified directory:
- Toolchain cmake files: `<ToolsID>.<major>.<minor>.<patch>.cmake`
- Default linker script files  (to be preprocessed): `<ToolID>_linker_script.<ext>.src`
- `cdefault.yml`

All other files located in the `./etc/` directory of the CMSIS-Toolbox are not "relocatable".

**Comment by ReinhardKeil** [comment]
Solved by https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#environment-variables
