### ISSUE TITLE
`cbuild-idx.yml` refinement; default directory locations of `cbuild.yml` and `compile_commands.json`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1305]
**Problem To Be Solved**
- `cbuild` need to be aware when a build is required; the timestamp the of `cbuild-idx.yml` file can be used to identify that. Any newer source file would require to run a build. But missing is the information about the usage of the file `cbuild-set.yml` (option `--context-set` is used).
- To solve #1301, the default location of the `cbuild.yml` files should be in the `out` directory of the related project. `cbuild-set.yml` should refer the files of the current `--context-set` (when used)).
- The `compile_commands.json` should be located in the same `out` directory as the `cbuild.yml` file of the related context. As `compile_commands.json` is created by CMake, the file is not referenced in the `cbuild-set.yml` - if the timestamp of `compile_commands.json` is older then `cbuild.yml` it is outdated and need to be recreated.

**Possible Solution**
- Add in `cbuild-idx.yml` the node `context-set: <path>/<name>.cbuild-set.yml` to indicate that `--context-set` is used. This node is not present if `--context-set` is not used.
- Change default location of default location of `cbuild.yml` to the `out` directory.

**Questions**

`compile_commands.json` should be generated by CMake using the `-target database`. As proposed in #1265 this would be created with the command `cbuild setup`.
- Do we need an option to enable generation of `compile_commands.json` during `cbuild setup`?
- Do we need to refer the file `compile_commands.json` in `cbuild-set.yml`. If yes, for which reason?
- I believe the content of `compile_commands.json` should include `-mcpu=cortex-m33` along with all processor specific settings such as `fpu`. 
  - Who is defining the content? 
  - What `*.cmake` file is used?

**Comment by jkrech** [comment]
Question: Do we plan to move the files:
- `<solution>.cbuild-set.yml` (input file should not be located in output folder)
- `<solution>.cbuild-idx.yml` 

as well? 
How does a tool find the output files without knowing where the `*.cbuild-idx.yml` is

**Comment by ReinhardKeil** [comment]
I would propose to leave this files co-located with the `csolution.yml` file.  

For `<solution>.cbuild-idx.yml` it would be unclear in which `out` directory this is located, as each `context` has potentially a separate directory.

**Comment by jkrech** [comment]
To be solved by #1322
