### ISSUE TITLE
[csolution] Add flag on list pack command (e.g. --json) to obtain data in a machine readable format 

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1307]
`csolution list packs` command provides information about installed packs or missing packs
this piece of information can then be used by other tools to perform actions such as installing packs. Nonetheless, the list of packs is not currently expressed in a machine readable format specified by a schema and is quite likely to change in the future to comply with any UX requirements. Therefore, in a similar fashion to `cbuildgen packlist`, it would be extremely useful for reliability and robustness to have an option to express the data in a machine readable format other tools can then consume

For example, this is how currently packs are installed for a particular test project in the [MCU's sandbox](https://github.com/Arm-Debug/build-service-pack-management/blob/63a0e131ce86793ab9bc7671907b99fa7b7e54d2/scripts/install_workspace_packages.sh#L59C30-L59C39).

This request may seem similar to https://github.com/Open-CMSIS-Pack/devtools/issues/1159 but is actually specific to listing packs as the usecases and the consumption tools are slightly different

**Comment by ReinhardKeil** [comment]
@acabarbaye thanks for pointing to this.  In which context do you need this type of information?  Is it during project setup?
What we want to avoid is that `csolution` is called multiple times during the setup of an IDE as this is slowing down the UX experience.  Therefore we are currently working on the `setup` flow, see here https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md

We could add information about missing packs in the YML build information files. Would this solve your issue?

**Comment by acabarbaye** [comment]
Although, I mentioned the MCU sandbox, this feature request is for a different context. I was mentioning the MCU sandbox to provide an example of the machine readable format in use there.

For extracting information from csolution projects about themselves, the recommendation detailed in https://github.com/Open-CMSIS-Pack/devtools/issues/1177 is followed and we use `csolution` to generate `*.cbuild.yml` files. However, if packs are missing (likely on git repositories), `csolution` output error messages listing the missing packs and fails. At this point, we are not doing a build but a `convert`. Since `csolution` already has a command to list the missing packs, my request was to add an option to express this list in a machine readable format, so that it is stable.

**Comment by jkrech** [comment]
The  link to #1177 is a useful detail. 
What if you would call `cbuild setup --packs`  and that command would install the missing packs before it runs the convert?

@ReinhardKeil I think this would be a use case where we probably do not need to generate the compile_commands.json files as part of the setup command.

**Comment by ReinhardKeil** [comment]
Solved it differently with the proposal to extend [*.cbuild-idx.yml files](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md#extend-cbuild-idxyml-files) with `packs-missing:` note.  

Let me know if this would work for you?

**Comment by acabarbaye** [comment]
Would `csolution convert` still fail if there are missing packs? if so, it won't help me because what I am trying to get is the *cbuild.yml files

**Comment by ReinhardKeil** [comment]
If packs are missing, at least the `*.cbuild-idx.yml` file will be still generated with the list of missing packs.

**Comment by ReinhardKeil** [comment]
@acabarbaye we should solve this issue with the release of CMSIS-Toolbox 2.3.0. Missing packs are now part of the `*.cbuild.yml` files. In these context specific files there is also an `error: true` indicator in case that it does not build.

Is this sufficient?
Could you also comment on #1385

**Comment by ReinhardKeil** [comment]
closing this as it is addressed with CMSIS-Toolbox 2.3.0 with *.cbuild*.yml files.
