### ISSUE TITLE
Implement `cbuild setup` command

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1322]
**The Problem To Be Solved**
To streamline IDE integration and provide other useful information missing information should be added to the `*.cbuild*.yml` information files. The overall problem is described in #1265. 

**Solution**
Add the features described in [setup.md](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md)

**Comment by Torbjorn-Svensson** [comment]
- Should the `cbuild-idx.yml` really contain the status information? Isn't this suppose to be a "stable" file?
- It also seems like this also introduces a new concept `instance-number` for component ids, but this is not compatible with existing parsers based on the current regex from the schema for 2.2.0. Is this a break that should require a 3.0.0?

**Comment by ReinhardKeil** [comment]
`cbuild-idx.yml` and `cbuild+<target-type>.<debug-type> are build information files that contain information about the current context-set the developer is using.

If a project cannot be build, the proposal is to provide an error status.  Today there are no files, which could be also due to incorrect installation. By providing the error status the user knows that there is a problem in the csolution project files itself.

**Comment by soumeh01** [comment]
I'm seeking clarification and need inputs regarding the `setup` command in cbuild. Should the `setup` command have limited command-line arguments, or should it inherit all arguments from the parent cbuild command? The current set of parent command-line flags includes options like `clean`, `jobs` etc . I'm uncertain about the potential use cases for additional options in conjunction with the 'setup' command.

The current cbuild options look like this
```
Options:
  -C, --clean              Remove intermediate and output directories
  -c, --context arg [...]  Input context names [<project-name>][.<build-type>][+<target-type>]
  -S, --context-set        Use context set
  -d, --debug              Enable debug messages
  -g, --generator arg      Select build system generator (default "Ninja")
  -h, --help               Print usage
  -j, --jobs int           Number of job slots for parallel execution
  -l, --load arg           Set policy for packs loading [latest | all | required]
      --log arg            Save output messages in a log file
  -O, --output arg         Set directory for all output files
  -p, --packs              Download missing software packs with cpackget
  -q, --quiet              Suppress output messages except build invocations
  -r, --rebuild            Remove intermediate and output directories and rebuild
  -s, --schema             Validate project input file(s) against schema
  -t, --target arg         Optional CMake target name
      --toolchain arg      Input toolchain to be used
      --update-rte         Update the RTE directory and files
  -v, --verbose            Enable verbose messages from toolchain builds
  -V, --version            Print version

Use "cbuild [command] --help" for more information about a command.
```

**Comment by ReinhardKeil** [comment]
It can inherit for now all options, even when you are correctly pointing out that `--clean` makes perhaps no sense.

**Comment by edriouk** [comment]
The **instance number** makes confusion here: 
 https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md#instance-number
 
the example refers to '0' , assuming that is an index. That is wrong, because we can only use of 1-based **number of instances** , or in other words **instance count**

**Comment by edriouk** [comment]
We need to think that different contexts can have different instance count.

**Comment by ReinhardKeil** [comment]
@edriouk the content of a `*.cbuild+<target-type>.<build-type>.yml` file is specific to a context.
