### ISSUE TITLE
Merged dependabot PRs have embedded html in the commit message

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [Open-CMSIS-Pack/devtools#1325]
This was raised in a call a few weeks/months back, but I raised this again in the meeting today.

An example of how the history in git looks like can be seen here: https://github.com/Open-CMSIS-Pack/devtools/commit/5f553849b394783d7be9939216636dbd76916654

Commit messages like this makes it hard to read up on changes when just doing `git log` in the console.

**Comment by Torbjorn-Svensson** [comment]
Yes, it would be better, but I don't understand why it's a problem for this repository.

As an example, dependabot is running for the npm/cli project and creates some PRs. One example PR is https://github.com/npm/cli/pull/6916 with the corresponding commit https://github.com/npm/cli/pull/6916/commits/5b21a3c63aae4a91848e221449eca15a36e3c657. If you look at the commit, you see that there is no HTML in the commit message.
I have, so far, not come across any other repository where there are these ugly HTML commit messages from dependabot.

**Comment by soumeh01** [comment]
The presence of this HTML message in the repository stems from our utilization of the GitHub merge strategy for dependabot pull requests. Previously, I employed the GitHub `squash and merge` option, consolidating all commits from the feature branch into a single squashed commit, which inadvertently included the dependabot PR HTML comment as the commit message.

To address this issue, I propose adopting a new merge strategy: `rebase and merge` This approach preserves the individual commit messages, ensuring a linear history. Consequently, users will no longer encounter the HTML message; instead, they will see commit messages similar to those found [here](https://github.com/Open-CMSIS-Pack/devtools/commit/b16cd87c8dd59b7887e79a9a0496d5e0012ab78d) (As pointed in your example)


If this solution aligns with your requirements and meets your expectations, would you like me to proceed with closing this issue?
