### ISSUE TITLE
`[*.cbuild.yml]` generated files using `csolution convert` fail validation against schema  `$.build.groups[3]: 'files' is a required property`

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1327]
**Describe the bug**
In order to extract information from *.cbuild.yml files about projects (e.g. project metadata or project output artefacts), we parse the files using their schema ( https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.2.1/tools/projmgr/schemas/cbuild.schema.json or https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/main/tools/projmgr/schemas/cbuild.schema.json) and hence, require compliance.

Parsing currently fails when using Toolbox 2.2 with the following error:
```
build.groups[3]: 'files' is a required property
``` 
This is the case for all the csolution projects present in packs.

**To Reproduce**
- Get a pack containing csolution projects : e.g. https://www.keil.arm.com/packs/frdm-ke16z_bsp-nxp/boards/
- run `csolution convert`  (csolution 2.2) on a project contained in the pack e.g. `<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.csolution.yml`

the following should happen
```
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.cbuild-idx.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+armgcc.cbuild.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+iar.cbuild.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+mdk.cbuild.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.release+armgcc.cbuild.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.release+iar.cbuild.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.release+mdk.cbuild.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.cbuild-pack.yml - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+armgcc.cprj - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+iar.cprj - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+mdk.cprj - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.release+armgcc.cprj - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.release+iar.cprj - info csolution: file generated successfully
<...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.release+mdk.cprj - info csolution: file generated successfully
```
- Validate the produced files against the schema
```
  check-jsonschema <...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+armgcc.cbuild.yml --schemafile https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.2.1/tools/projmgr/schemas/cbuild.schema.json
  
  or 
  
   check-jsonschema <...>/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+armgcc.cbuild.yml --schemafile https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/main/tools/projmgr/schemas/cbuild.schema.json
```
You should see errors as follows:
```
Schema validation errors were encountered.
  boards/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+armgcc.cbuild.yml::$.build.groups[2]: {'group': 'MKE16Z4/iar'} is not valid under any of the given schemas
  Underlying errors caused this.
  Best Match:
    $.build.groups[2]: 'files' is a required property
  boards/frdmke16z/driver_examples/tsi_v5/mutual_cap/tsi_v5_mutual_cap.debug+armgcc.cbuild.yml::$.build.groups[3]: {'group': 'MKE16Z4/arm'} is not valid under any of the given schemas
  Underlying errors caused this.
  Best Match:
    $.build.groups[3]: 'files' is a required property
```

**Expected behavior**
Produced `*.cbuild.yml` files should comply with the schema

**Environment (please complete the following information):**
Attaching one of the produced files
[tsi_v5_mutual_cap.debug+armgcc.cbuild.yml.txt](https://github.com/Open-CMSIS-Pack/devtools/files/14297113/tsi_v5_mutual_cap.debug%2Barmgcc.cbuild.yml.txt)

- cmsis TOOLBOX 2.2

**Comment by acabarbaye** [comment]
This is currently blocking us in trying to follow the process detailed in https://github.com/Open-CMSIS-Pack/devtools/issues/1177

**Comment by brondani** [comment]
The reported issue happens because the mentioned project has groups containing only context/compiler specific files, which are filtered out depending on the context but the empty groups are still stored in cbuild.yml, for example:
```
groups:
  - group: MKE16Z4/iar
  - group: MKE16Z4/arm
  - group: MKE16Z4/gcc
```
I see two solutions:
1. Make `files` an optional property in the schema
2. Do not emit empty groups in cbuild.yml

@jkrech @ReinhardKeil What is your take?

**Comment by acabarbaye** [comment]
By the way, for your information, we use a go parser in our process but it is easier to use https://github.com/python-jsonschema/check-jsonschema to check the compliance of a yaml file with a schema
