### ISSUE TITLE
How to patch a csolution project at component or file level ?

### ISSUE THREAD

**Issue by iomint** [Open-CMSIS-Pack/devtools#1331]
**The Problem To Be Solved**
A user can be reluctant to upgrade with a full pack when he wants  only to get a patch fixing a bug in his project for various reasons:  it can be the size of the full pack, a minimal change to ensure a full control , ... In other words, is Open-CMSIS-Pack toolbox having a way to patch a *.cproject.yml project at a component(s) or even file(s) granularity level ? 
Note: Doing so the consistency of the components package together in a pack is lost so it assumes the user is accepting the associated risk 

**Potential direction to address this request**
Let's consider the user want to pick up only one component upgraded with a patch fixing a bug.  
- A new pack with a new version number N+1 is created integrating the upgraded component (and possibly also additional modified components) 
- Packs version N and N+1 are installed 
- Mix components from pack N and N+1 to include the patched component from the pack N+1  using "from-pack" 
[https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#for-compiler](url)

Is it going to work ?

**Comment by jkrech** [comment]
Open-CMSIS-Pack does not have a concept for providing "partial updates" to packs. When a patch version of a pack is released (increment in the patch part of the version major.minor.patch) this pack must contain the full content of the pack and when installed will be extracted into a separate directory with no files being overwritten from a previous pack version installation.

"patching" on a component level is possible:
Multiple pack versions can be specified in csolution/cproject/clayer:
```
  packs:
    - pack: MyVendor.MyPack@1.2.0
    - pack: MyVendor.MyPack@1.2.1
```
It is required to specify components with versions, to ensure they are taken from the pack version 1.2.0 assuming that there is a newer component version in 1.2.1

"patching" on a file level is not supported through the tools but:
if a pack version is stored as part of the solution through specifying a relative path in the `path:` node, then it is up to the user to patch individual files in this directory. In this case it is strongly recommended to indicate a local modification in the pack version.

**Comment by ReinhardKeil** [comment]
Closing as this was discussed in the TRM on 27. Feb 24
