### ISSUE TITLE
cbuild.yml file is reporting a duplication error

### ISSUE THREAD

**Issue by kanthanp** [Open-CMSIS-Pack/devtools#1367]
**Describe the bug**

Using the updated official Hello FRDM-K32L3A6 example with the latest VS Code extensions it is noticed that the cbuild.yml file is reporting a duplication error. 

**To Reproduce**

1. Clone https://github.com/Arm-Examples/Hello_FRDM-K32L3A6
2. Open Hello example in VS Code
3. Do one of the following:
- select the `hello.Debug+FRDM-K32L3A6.cbuild.yml` file from Explorer view and check the open file in Editor
- add the connected K32 board in Device Manager, perform Run operation from CMSIS extension and go to Problems view

=> The cbuild.yml file reports a duplication error as there are 2 "cm4" lines

![(1) Error screenshot](https://github.com/Open-CMSIS-Pack/devtools/assets/28144660/e35db4fc-3bd9-425b-9bf2-437ac9d05399)

**Expected behavior**
No duplication error reported and run operation completes successfully

**Environment (please complete the following information):**

- Cmsis toolbox 2.2.1
- MacOS 14.3

**Comment by jkrech** [comment]
A simple `csolution convert hello.csolution.yaml` is enough to trigger the generation of the `cbuild.yml` files.

I consider this a bug in the example, as it does specify:
```
     define:
        - DEBUG
        - CPU_K32L3A60VPJ1A_cm4
```
in hello.csolution.yaml: line 87 unnecessarily as this define is set by the selected device in the package description file already.
I am not sure it would be the right thing to have `csolution` always remove duplicates.

**Comment by mcgordonite** [comment]
Should we relax the schema to allow duplicates in the cbuild.yml files?

**Comment by brondani** [comment]
It has been already addressed in https://github.com/Open-CMSIS-Pack/devtools/pull/1334 and will be present in the next release.

**Comment by jkrech** [comment]
closing as duplicate.
