### ISSUE TITLE
[cbuild] setup command is supposed to pick the first `target-type` and `build-type` in case `--context-set` is specified but `*.cbuild-set` is not present

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1381]
**Describe the bug**
According to specification: [setup.md](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md)

> When option `-S` is used and the file *.cbuild-set is missing, the setup command creates a *.cbuild-set file with selection of the first target-type and the first build-type.

Currently the ordering of `target-type` and `build-type` is alphabetically.
As a consequence e.g. a build-type `Debug`  is always chosen over `Release` regardless of the order in the *.csolution.yml file.

**To Reproduce**
Take any solution with two build-types, reorder them and compare the *.cbuild-set.yml files that are being generated by cbuild.

**Expected behavior**
*.cbuild-set.yml should list contexts based on the first `build-type` and the first `target-type` listed in the `<solution names>.csolution.yml` file.

**Environment (please complete the following information):**

- cbuild
- Version [2.3.0-devint0]
- OS: all

**Comment by soumeh01** [comment]
When considering alignment with the consistent behavior of other utilities, the proposed solution appears to deviate. Specifically, when executing `csolution convert ./test.csolution -S` without having a **cbuild-set.yml** file, **csolution** does not generate a 'cbuild-set' file but converts all projects nonetheless.

**Comment by ReinhardKeil** [comment]
@soumeh01 this is about `cbuild setup` not `csolution convert`. Why would we need consistency here?

However, I would suggest that we park this problem as less critical.
