### ISSUE TITLE
Add `description:` to `cbuild-idx.yml`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1383]
**The Problem To Be Solved**
For exposing examples on a web page, the `cbuild setup` command could be used to check if an example can be generated.  This command creates the `*.cbuild-idx.yml` file that is processed by the web infra-structure to display correct examples.  To avoid that the web infra-structure needs to also process the `*.csolution.yml` it is beneficial to output the `description:` in the *.cbuild-idx.yml` file.

**Suggest A Solution**
Output in `*.cbuild-idx.yml` the `description:` of the example that is provided in [`*.csolution.yml`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#solution)

**Comment by ReinhardKeil** [comment]
Reopen as it is missing in documentation

**Comment by soumeh01** [comment]
Documentation has been revised. The modifications will be accessible in CMSIS-Toolbox 2.3.0
