### ISSUE TITLE
[docs] Introduce `optimize: debug` for optimum debug illusion - was: Map `optimize: none` to -O1 for LLVM and AC6

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1384]
**The Problem To Be Solved**
For  LLVM and AC6 the option -O0 generates extremely in-efficient code that uses considerable more stack space. This creates even problems during debugging.

**Suggest A Solution**
For optimum debug illusion, the option -O1 is a better choice. 

I suggest therefore to map  [`optimize: none`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#optimize) to -O1 for LLVM and AC6. This should be then also reflected in the documentation that 'none' is intended for debug and may not literally translate to zero compiler optimization. 

An alternative might be to introduce `optimize: debug`, however this might be just overwhelming.

**Comment by ReinhardKeil** [comment]
Perhaps a better way is:

`debug: on` and no explicit `optimize:` selects the best optimize level for debug. In case of LLVM and AC6 it would be -O1, in case of GCC to `Og`.

**Comment by jkrech** [comment]
See current implementation in GCC: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/cbuildgen/config/GCC.10.3.1.cmake#L100
```
...
set(OPTIMIZE_VALUES       "debug" "none" "balanced" "size" "speed")
set(OPTIMIZE_CC_FLAGS     "-Og"   "-O0"  "-O2"      "-Os" "-O3")
...
# GCC provides a better optimization level for debug
  if ((debug STREQUAL "on") AND (optimize STREQUAL ""))
    set(optimize "debug")
  endif()
```

**Comment by jkrech** [comment]
a) Note, that the option "debug" only exists inside the cmake file! You cannot specify it in the input YAML files!
This local string currently only exists for GCC but the same functionality could be added to other compilers for consistent behavior.
b) @brondani please correct me if I am wrong, it is my understanding that if in the YML input files there is node optimize explicitly set for a context, then there will be no `-Ox` parameter specified at the compiler command line and the compiler chooses its default. 
AC6: https://developer.arm.com/documentation/101754/0621/armclang-Reference/armclang-Command-line-Options/-O--armclang-
```
Default
The default is -O0.
```

**Comment by brondani** [comment]
@jkrech Your understanding is correct.
As previously discussed for GCC when `debug:` is  `on` and `optimize:` is empty it's mapped to `-Og`.
In a similar way we can map this for AC6 and CLANG to `-O1` and for IAR `-On`.

Reference: [EWARM_DevelopmentGuide](https://wwwfiles.iar.com/arm/webic/doc/EWARM_DevelopmentGuide.ENU.pdf):
```
-O[n|l|m|h|hs|hz]
n None* (Best debug support)
l (default) Low*
...
*All optimizations performed at level Low will be performed also at None. The only
difference is that at level None, all non-static variables will live during their entire scope
```

**Comment by ReinhardKeil** [comment]
Maybe we should consider to add `optimize: debug` (which is default with `debug: on`).  I'm worried that we make otherwise an tool that is not transparent (different optimization when debug is on/off)

**Comment by brondani** [comment]
`optimize: debug` was added in https://github.com/Open-CMSIS-Pack/devtools/pull/1387
@ReinhardKeil Please update the documentation accordingly.

**Comment by ReinhardKeil** [comment]
Added to documentation. 

@brondani can you confirm that `optimize: balanced` is the default when notthing is specified and that this default is independent of `debug: on/off`?

**Comment by brondani** [comment]
> @brondani can you confirm that `optimize: balanced` is the default when notthing is specified and that this default is independent of `debug: on/off`?

@ReinhardKeil When nothing is specified in the yml files also nothing is added to the command line, in other words the default is the toolchain's default. Independently of `debug: on/off`

**Comment by jkrech** [comment]
fix in documentation.
