### ISSUE TITLE
INFO/WARNING log alignment

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#139]
Hi

This a minor point.

I got M377 warning, but it is logged as INFO:
```
*** INFO M377: xxx/STMicroelectronics.STM32L5xx_DFP.pdsc (Line 658) 
  File 'startup_stm32l562xx.c' source must have 'attr="config"'
```

In order to be aligned with 
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/packChk.html
Maybe we should change WARNING3 into WARNING ?
https://github.com/Open-CMSIS-Pack/devtools/blob/main/libs/errlog/src/ErrLog.cpp#L272

**Comment by thorstendb-ARM** [comment]
Issue fixed, please verify
