### ISSUE TITLE
`[cbuild schema]` Schema should be more lenient to allow future additional fields/properties

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1397]
**Describe the bug**

The current schemas of `cbuild-idx.yml` and `cbuild.yml` are really stringent in that they do not allow new fields to be added :
They indeed specify that there cannot be any additional properties:
- https://github.com/Open-CMSIS-Pack/devtools/blob/7e591ed426bf3f00baf358d48708dc5aae59d6f1/tools/projmgr/schemas/cbuild-idx.schema.json#L13
- https://github.com/Open-CMSIS-Pack/devtools/blob/7e591ed426bf3f00baf358d48708dc5aae59d6f1/tools/projmgr/schemas/cbuild.schema.json#L13

https://json-schema.org/understanding-json-schema/reference/object?highlight=additionalproperties#additionalproperties
> Setting the additionalProperties schema to false means no additional properties will be allowed.

This prevents any new properties to be appended to the files and so, it is not currently possible to allow non-breaking changes in future versions of the schema.

This is an example of the problem https://github.com/Arm-Examples/Hello_V2M-MPS3-SSE-300-FVP/actions/runs/8392335668/job/22984746692 where `cdefault` was introduced to the files but the schema in use is not aware of the `cdefault` definition which was introduced later:

> "msg"="Failed importing projects" "error"="unexpected: cannot retrieve project [hello.csolution.yml]'s metadata: unexpected: validation of the index file [/tmp/project-sandbox-hello-csolution-yml-891283134/project-files/hello.cbuild-idx.yml] failed: invalid: failed to validate yaml [map[build-idx:map[cbuilds:[map[cbuild:hello.Debug+V2M-MPS3-SSE-300-FVP.cbuild.yml configuration:.Debug+V2M-MPS3-SSE-300-FVP project:hello] map[cbuild:hello.Release+V2M-MPS3-SSE-300-FVP.cbuild.yml configuration:.Release+V2M-MPS3-SSE-300-FVP project:hello]] cdefault:${CMSIS_COMPILER_ROOT}/cdefault.yml cprojects:[map[cproject:hello.cproject.yml]] csolution:hello.csolution.yml generated-by:csolution version 2.2.1]]] against schema: jsonschema: '/build-idx' does not validate with https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.2.1/tools/projmgr/schemas/cbuild-idx.schema.json#/properties/build-idx/$ref/additionalProperties: additionalProperties 'cdefault' not allowed"

**Expected behavior**
Have a more lenient specification in the schema to allow future additions. To do so, the lines `"additionalProperties": false,` could be removed

**Comment by ReinhardKeil** [comment]
#1090 refers to the YML input files, whereas this case refers to the `*.cbuild*.yml` build information files. 

A solution would be to ensure that the schema matches the implementation, which I believe is the root cause of this problem.

**Comment by jkrech** [comment]
I agree that we could/should treat INPUT and OUTPUT files differently.
My expectation is also that the generated output files (e.g. *.cbuild*.yml) are checked against the corresponding schema files as part of the automated testing to catch any inconsistencies.

**Comment by brondani** [comment]
> My expectation is also that the generated output files (e.g. _.cbuild_.yml) are checked against the corresponding schema files as part of the automated testing to catch any inconsistencies.

@jkrech Please note the inconsistencies listed in https://github.com/Open-CMSIS-Pack/devtools/pull/1090#issuecomment-1683457144 will also NOT be caught by the schema check once `additionalProperties` is set to `true`.

**Comment by brondani** [comment]
In my understanding the fundamental problem that must be fixed is the missing `cdefault` node in the cbuild-idx.yml schema:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L838-L849

**Comment by brondani** [comment]
Agreed actions in [Open-CMSIS-Pack Meeting 2024-04-02](https://linaro.atlassian.net/wiki/spaces/CMSIS/pages/29228990467/Open-CMSIS-Pack+Technical+Meeting+2024-04-02):
- https://github.com/Open-CMSIS-Pack/devtools/pull/1416
- https://github.com/Open-CMSIS-Pack/devtools/pull/1419
