### ISSUE TITLE
[csolution] Print boards list

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Open-CMSIS-Pack/devtools#141]
I am suggesting to print list of available boards in similar way as devices.
It is good to have reference during editing of project/solution yml files.

```
Usage:
  csolution <command> [<args>] [OPTIONS...]

Commands:
  list packs          Print list of installed packs
       devices        Print list of available device names
       components     Print list of available components
       dependencies   Print list of unresolved project dependencies
       contexts       Print list of contexts in a csolution.yml
  convert             Convert cproject.yml or csolution.yml in cprj files
  help                Print usage

Options:
  -p, --project arg   Input cproject.yml file
  -s, --solution arg  Input csolution.yml file
  -f, --filter arg    Filter words
  -o, --output arg    Output directory
  -h, --help          Print usage
```

This could be probably extended also for other categories like examples, vendors, keywords, conditions...

**Comment by purdurnr** [comment]
I installed update to cmsis-toolbox_0.9.1.s.
My projects that were working now fail because board "was not found."
Per issue, it would be nice to list the boards that are available when checking cproject.yml

**Comment by brondani** [comment]
@DavidJurajdaNXP the `list boards` command was added to [CMSIS-Toolbox v0.9.3](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools/toolbox/0.9.3), can you please test it?

**Comment by purdurnr** [comment]
@brondani I verified the list boards worked.
Question on all of these "list" commands.
I am confused why the list includes ALL potential options.
I thought it would limit the devices or boards IF the .cproject.yml includes a SPECIFIC device / board?

I have a project that has
  board: LPCXpresso55s69
  device: LPC55S69JBD64:cm33_core0
However, if I issue command with -p name.cproject.yml list devices  OR  list boards
I get the full list available in packs folder?
I would expect that if I typed:  csolution list packs OR csolution list boards.  BUT NOT when I type -p project.
Am I understanding the command wrong?  I would like to know that my project is limiting scope appropriately.

**Comment by brondani** [comment]
Thanks @purdurnr
The `-s solution -c context` option will limit the `list devices` and `list boards` commands according to the pack selection. If nothing is specified under the `packs` keyword in `csolution.yml` or in `cdefault.yml` all the installed packs are considered.
Concerning the `-p project` there is a specification decision to be taken whether to extend the pack selection to `cproject.yml` as requested [here](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/85) or to limit the input and accept only `-s solution`.

**Comment by purdurnr** [comment]
@brondani I noticed an error with specifying the board in my example cproject.
I concluded it is case sensitive.  I guess that is ok, but wonder if that is intended. 
![image](https://user-images.githubusercontent.com/94857467/161334843-f382c3f4-f89f-40a1-bff8-a9f591585c73.png)

**Comment by jkrech** [comment]
As far as I am aware at this point Open-CMSIS-Pack is case sensitive in all areas without exceptions.
Nevertheless a fair question to raise, whether the csolution being able to process "sloppy" yaml input should also accept case insensitive input.
I would prefer not to open that door. When using the CLI people should copy the output into the file.

**Comment by ReinhardKeil** [comment]
Closing this as `list boards` has been implemented long time ago.
