### ISSUE TITLE
Improvement proposals for help text

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1415]
The documentation contains a slightly improved help text.

For cbuild: 
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-tools.md#cbuild-invocation

For csolution:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-tools.md#csolution-invocation

Could you please reflect that in the tool.

**Comment by soumeh01** [comment]
Help text has been revised. The modifications will be accessible in [CMSIS-Toolbox 2.3.0](https://github.com/orgs/Open-CMSIS-Pack/projects/8)
