### ISSUE TITLE
[CMSIS-Toolbox] Print config data

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Open-CMSIS-Pack/devtools#142]
Print internal state variables in similar way as git:

```
$ git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.usebuiltinfsmonitor=true
pull.rebase=false
credential.helper=manager-core
init.defaultbranch=main
core.autocrlf=true
```

"csolution config --list" could provide data like:
- currently used installation folder CMSIS_PACK_ROOT
- current project directory
- tools folder CMSIS_BUILD_ROOT
- CMSIS_COMPILER_ROOT
- registered compiler paths
 
I would prefer configuration yml file in CMSIS-Toolbox installation folder instead of environment variables.

cdefaults.yml  might allow custom redefinition of CMSIS_PACK_ROOT. I think it would be useful for destructive experiments, where is expected total re-installation of all packs afterwards.  Re-installation of one huge centralized pack installation folder might consume too much time.

**Comment by ReinhardKeil** [comment]
@DavidJurajdaNXP This is a very good proposal, that we have not addressed yet (sorry busy with too much other stuff).

I suggest to extend the `list` command with:
```
`csolution list setup`
```

**Comment by jkrech** [comment]
I like the idea of a command that lists the "implicit tool configurations".
The reason I would not use the term `setup` here is that we use setup as a keyword in the csolution.yml already. I am afraid this is confusing:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#setups

**Comment by ReinhardKeil** [comment]
Good point.  Let's rename it to "list config"

**Comment by ReinhardKeil** [comment]
We have this command now in CMSIS-Toolbox 1.7.0 with *list environment*
