### ISSUE TITLE
Incorrect order of processing optimization level

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1420]
**Describe the bug**
The order of processing optimization levels when specified on solution and project level seems to be incorrect. The optimization level specified in `.csolution.yml` seems to override the optimization level specified in `.cproject.yml`.

**To Reproduce**
`.csolution.yml` contains:
```yml
  build-types:
    - type: Debug
      optimize: none
```
`.cproject.yml` contains:
```yml
  optimize: balanced
```
cbuild reports:
`error csolution: redefinition from 'balanced' into 'none' is not allowed`

**Expected behavior**
The optimization level specified in `.csolution.yml` level should be overridden by the optimization level specified in `.cproject.yml`.

**Environment:**
- cbuild
- Version 2.3.0-dev0
- OS: windows

**Comment by brondani** [comment]
As the error message states the redefinition of translation controls such as `optimize` is not allowed, regardless of the order. This is NOT a new behaviour.
Generically the processing order is: `project > solution > target-type > build-type` so it looks correct even though in this case it does not matter.
The order plays a role when processing for example `add-path`/`del-path` and `define`/`undefine`.

**Comment by RobertRostohar** [comment]
Why is it not allowed to change `optimize`? There might be use cases that would benefit.

**Comment by brondani** [comment]
This has been decided as an implementation choice since the very beginning of `csolution` to avoid unexpected redefinitions.
Obviously the behaviour can be changed but it would an enhacement request rather than a bug fix.

**Comment by RobertRostohar** [comment]
Thanks. I will close this issue and open a feature request.
