### ISSUE TITLE
[docs] redefining optimization level

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1421]
**Describe The Problem To Be Solved**
Optimization level can be specified with `optimize:` in various places: `build-types:`, `target-types:`, `project:`, `layer:`, `group:` , `file:`, `setup:`, `component:`. However it is not allowed to redefine it. What is then the point of having it in multiple places? Anyway, there are many uses cases where you want to change a global solution/project optimization level for a certain group/file/component ...

**(Optional): Suggest A Solution**
Allow redefining optimization level and follow the hierarchy solution->project/layer->group ...

**Comment by ReinhardKeil** [comment]
The documentation covers this already: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#translation-control

**Comment by RobertRostohar** [comment]
But the implementation does not allow to change the optimization level.
See: https://github.com/Open-CMSIS-Pack/devtools/issues/1420#issuecomment-2034137287

**Comment by brondani** [comment]
Please note redefinitions are not allowed at context level, it does not apply to the lower levels (components, groups and files).
The processing order of context level translation controls is the following:
`project > solution > target-type > build-type > setup > layer`

**Comment by jkrech** [comment]
Fix in documentation
