### ISSUE TITLE
Accepted Chars in build-type/target-type names: (Run Generator issue  when target-type name contains space)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1449]
**Describe the bug**

CubeMX cannot start if the target-type name is "STM32U5 Board". Moreover a such a context cannot be entered using `--context "CubeMX.Debug+STM32U5 Board"`

**To Reproduce**

- Fork https://github.com/ReinhardKeil/csolution-examples 
- Change in ./CubeMX/CubeMX.csolution.yml: STM32U5Board to STM32U5 Board
- use:
```
csolution CubeMX.csolution.yml run --generator CubeMX --context .Debug
```
**Expected behavior**
Blanks in target-type names should be allow (or rejected by the tool with a clear error message).

**Minor other improvement proposals**

```
>csolution CubeMX.csolution.yml run --generator CubeMX --context .Debug
```
outputs
```
C:/w/csolution-examples/CubeMX/tmp/CubeMX/STM32U5Board/Debug/CubeMX.cbuild-gen-idx.yml - info csolution: file generated successfully
C:/w/csolution-examples/CubeMX/tmp/CubeMX/STM32U5Board/Debug/CubeMX.Debug+STM32U5Board.cbuild-gen.yml - info csolution: file generated successfully
info csolution: generator 'CubeMX' for context 'CubeMX.Debug+STM32U5Board' reported:
```

There is no further `reported:` output; suggest to change the line to 
```
info csolution: starts generator CubeMX for context 'CubeMX.Debug+STM32U5Board'
```

When CubeMX was not executed, there is an error message that I suggest to change to:
```
C:/w/csolution-examples/CubeMX/STM32CubeMX/STM32U5 Board/CubeMX.cgen.yml - error csolution: cgen file not found, use: run --generator CubeMX --context <context-name>
```

**Environment:**

- CMSIS-Toolbox 2.3.0
- OS: Windows

**Comment by jkrech** [comment]
> There is no further reported: output; suggest to change the line to
Please note that this is a regression in the cbridge fixed already for the next release (https://github.com/Open-CMSIS-Pack/generator-bridge/issues/43)

e.g.:
info csolution: generator 'CubeMX' for context 'HID.Debug+B-U585I-IOT02A' reported:
Launching STM32CubeMX with  C:/Layers/MW/STM32CubeMX/B-U585I-IOT02A/STM32CubeMX/STM32CubeMX.ioc

**Comment by ReinhardKeil** [comment]
After reviewing, I would recommend to restrict usage of "space" (and other characters such as '+') in `build-type` and `target-type` names. IMHO the accepted characters should be: `A-Z`, `a-z`, `0-9`, and `_` (underscore).  I suggest also to restrict the length to 16 characters max.

**Comment by mdortel-stm** [comment]
Hi Reinhard,
I try to share some feedback from ST people.
Correction about spaces is fine but we do not get the reason why the length topic comes into the picture. What kind of issue are we facing which requires to restrict user to 16 characters? (which looks -subjectively- quite strong)

**Comment by ReinhardKeil** [comment]
I agree that 16 might be a bit strong; but we should define a useful limit here.  Build and Target type names contribute to the filename; and filenames are still size restricted (256 chars on Windows).  Is 32 characters OK from your perspective.

**Comment by ReinhardKeil** [comment]
Replaced by #1497
