### ISSUE TITLE
[Pack, Build Manager] Multiple references to same source module are silently accepted

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1451]
Consider the [attached solution](https://github.com/Open-CMSIS-Pack/devtools/files/15042762/multiple-definitions.zip) using two components from a local pack where both components reference the same source module:
```
  <components>
    <component Cclass="TestClass" Cgroup="GroupA" Cversion="1.0.0" condition="Test_Condition">
      <description>TestGlobal</description>
      <files>
        <file category="source" name="Files/test.c"/>
      </files>
    </component>
    <component Cclass="TestClass" Cgroup="GroupB" Cversion="1.0.0" condition="Test_Condition">
      <description>TestLocal</description>
      <files>
        <file category="source" name="Files/test.c"/>
      </files>
    </component>
  </components>
```
The `cbuild2cmake` modular approach exposes the problem leading to a linker error:
```
Error: L6200E: Symbol func multiply defined (by test.o and test.o).
```

The problem is hidden in the `RteModel` because the duplicated source modules are silently overwritten when populating the 
[`m_projectGroups`](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/buildmgr/2.3.0/libs/rtemodel/include/RteTarget.h#L1068) map. Even if such components have different `Cclass` the modules are eventually overwritten in the `cbuildgen` [`m_ccFilesList`](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/buildmgr/2.3.0/tools/buildmgr/cbuildgen/include/BuildSystemGenerator.h#L121) map.

`packchk` does not report any error nor warning.
It could be expected that non mutually-exclusive components referencing the same source module should be reported.

The problem was first observed in the public pack [`ARM::ml-embedded-eval-kit-uc-api@22.8.0-Beta`](https://www.keil.arm.com/packs/ml-embedded-eval-kit-uc-api-arm/versions/) where the source module `source/math/PlatformMath.cc` is referenced by several different components.

**Comment by ReinhardKeil** [comment]
I believe that there are situations where 2 components include the same source module. Maybe this needs to be handled by the tool (duplicates are ignored).

**Comment by brondani** [comment]
> I believe that there are situations where 2 components include the same source module. Maybe this needs to be handled by the tool (duplicates are ignored).

Which situations? I can only think on bad design situations, as in the mentioned [pack ](https://www.keil.arm.com/packs/ml-embedded-eval-kit-uc-api-arm/versions/) where the module is repeated several times instead of adding the "Common" component in the other component dependencies/conditions.

Which references would be ignored? The first? The last? What if they have different compile options, defines, includes? Ignoring duplicates sounds just wrong.

**Comment by jkrech** [comment]
After further review there is agreement that the above scenarios contributing duplicated modules to the build from multiple selected components needs to be considered an "error" in the component design.
The `packchk` utility shall identify such cases: see https://github.com/Open-CMSIS-Pack/devtools/issues/1499
