### ISSUE TITLE
[Question] environment contribution to CFLAGS, LDFLAGS and friends

### ISSUE THREAD

**Issue by tarek-bochkati** [Open-CMSIS-Pack/devtools#1458]
**Describe The Problem To Be Solved**

* using GNU make, we can do do
```bash
$ CFLAGS='-g' make
```
this will allow to influence the flags used in the makefile.

* using CMake

as documented here, https://cmake.org/cmake/help/latest/envvar/CFLAGS.html
`CFLAGS` could be used to contribute to `CMAKE_C_FLAGS`

**Question**
how to benefit from this when using the toolbox ?

**Comment by jkrech** [comment]
@tarek-bochkati, can you please provide a use case example, where people would want to use environment variables instead of settings in the yml input files for setting compiler flags. 
Recreating a build environment becomes more complex when more environment variables come into play.

**Comment by jkrech** [comment]
@ReinhardKeil, please document that in the CMSIS-Toolbox build system the CMake step does **not** take compiler and linker flags specified by environment variables into account as documented for CMake here: https://cmake.org/cmake/help/latest/envvar/CFLAGS.html.

**Comment by ReinhardKeil** [comment]
Note added to https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/README.md#overall-workflow
