### ISSUE TITLE
Extend generator options: explicit `*.cgen.yml` name, map

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1459]
**Problem To Be Solved**

For using CubeMX with `*.clayer.yml` files, it is required to specify an explicit `*.cgen.yml` name as the default behavior (using the project name) does not allow to use the configuration across multiple projects.

For the STM32H7S device series, an runtime context is added to CubeMX. It is required to map this context to the *csolution project*.

**Suggest A Solution**
As described in [generator - options]((https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#generators---options) add:
* `name:` to set an explicit name for `*.cgen.yml`.
* `map:` to refer a CubeMX runtime context.

Implied changes to tools:
- csolution: explicit name of `*.cgen.yml` needs to considered when the generator import file is read.
- csolution: output of `cbuild-gen-idx.yml` needs extensions as described [here](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#file-structure-of-cbuild-gen-idxyml)
- cbridge needs to utilize above information.

This is a test project: [USBD2.zip](https://github.com/Open-CMSIS-Pack/devtools/files/15076170/USBD2.zip)

**Comment by ReinhardKeil** [comment]
Related is #1446

**Comment by brondani** [comment]
@ReinhardKeil Can you please elaborate on how the `map: <runtime>` interacts with the [Project Types](https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/Simplified%20Generator%20Proposal.md#project-types) and how it should be supported going forward?
Generating cbuild-gen-idx.yml and cbuild-gen.yml files currently also takes in consideration the `project-type` in addition to the generator-id and base-dir.
