### ISSUE TITLE
SVDConv v3.3.46 reports an Error if sauNumRegions is equal 0

### ISSUE THREAD

**Issue by chentang16** [Open-CMSIS-Pack/devtools#1460]
SVDConv version 3.3.46 which comes with MDK 5.39 reports an error M364 when the svd file contains a XML tag sauNumRegions = 0. The SVDConv version 3.3.44 that comes with MDK 5.38a does not report an error.  According to the SVD schema file, a sauNumRegions value of 0 is valid (see https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_cpu.html).
![image-2024-01-31-19-12-22-033](https://github.com/Open-CMSIS-Pack/devtools/assets/18185016/36d595b9-6de0-43c0-901f-d76fbcce2d87)

**Comment by thorstendb-ARM** [comment]
Fixed error message.

Setting num regions to zero makes not much sense (tag can be left out), but when regions are set this is an error, because in partition.h regions are created but the #define is set to 0.
see PR https://github.com/Open-CMSIS-Pack/devtools/pull/1582

**Comment by thorstendb-ARM** [comment]
Release v3.3.47 see https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fsvdconv%2F3.3.47
