### ISSUE TITLE
[csolution] `run` command does not support the `--context-set` command line option

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1463]
**Describe the bug**
csolution seems to not take into account the context specified in `.cbuild-set.yml`.

**To Reproduce**
A solution file `.csolution.yml` containing multiple `target-types` and/or `build-types` resulting in multiple contexts.
A single context is selected in `cbuild-set.yml`.
Executing `csolution .csolution.yml run -g <generator_id> --context-set` results in an error: "a single context must be specified".
Executing `csolution .csolution.yml convert` will only convert the specified context.

**Expected behavior**
`cbuild-set.yml` should be taken into account also for `csolution run`

**Environment (please complete the following information):**
- CMSIS-Toolbox 2.3.0
- OS: Windows

**Comment by ReinhardKeil** [comment]
Relates to #1203 - when only one target-type is selected it should be fine to call the generator.
