### ISSUE TITLE
Regions header file name and location

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1467]
**Describe the bug**
Regions header file name and location is not consistent:
 - `target-type` is `device`: RTE/Device/`device`/regions_`device`.h
Fine until there are `-` in the `device` which are then converted to `_`.
Example: `device: SSE-300-MPS3`: RTE/Device/`SSE_300_MPS3`/regions_`SSE_300_MPS3`.h
 - `target-type` is `board`: RTE/Device/`device`/regions_`board`.h
The file name reflects the `board` but the directory reflects the Device/`device` of the underlaying `device`.
The following would be more consistent: RTE/Board/`board`/regions_`board`.h

**To Reproduce**
Create a solution with `target-type` as specified above and check the regions header file name and location.

**Expected behavior**
Regions file name and location should be consistent with the `board` or `device` specified for `target-type`.

**Environment (please complete the following information):**
- CMSIS-Toolbox 2.3.0
- OS: Windows

**Comment by ReinhardKeil** [comment]
This is according to specification: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#automatic-linker-script-generation.

I would also raise the question: what should we do when both a board and a device (that overwrites the board device) is specified.

**Comment by RobertRostohar** [comment]
It makes sense to keep the RTE/Device/`device` directory even when `board` is specified. But why use the `board` for the name?

Also the conversion `-` into `_` should not occur. For example, startup/system uses the original device name and is in such case in a different directory.

**Comment by ReinhardKeil** [comment]
Issue #1185 seems to be identical.

**Comment by ReinhardKeil** [comment]
The rational to use <board> as part of the region name is that it should also cover the memory regions defined by the board.  Unfortunately it seems that there is currently a bug that prevents from it. See #1468

**Comment by jkrech** [comment]
For directories in RTE named after the device we must not convert `-` to `_` in case of linker scripts.
