### ISSUE TITLE
Regions header file not processing information from `<boards>`

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1468]
**Describe The Problem To Be Solved**
It seems that `<memory>` information from `<boards>` is not considered when creating the regions header file (only `<memory>` information from `<devices>` is considered).

**(Optional): Suggest A Solution**
`<memory>` information from `<boards>` should also be processed when `board` is specified as `target-type`.

**Comment by edriouk** [comment]
@RobertRostohar , I need a reproducer. We have a test that adds board memory to the file. That is validated at every PR, no fails have been seen so far..

**Comment by RobertRostohar** [comment]
I have seen this issue with B-U585I-IOT02A BSP. It should be easy reproducible.

You can use the following example [Hello_B-U585I-IOT02A](https://github.com/Arm-Examples/Hello_B-U585I-IOT02A):
- modify the BSP pack version to 1.1.0 (includes also memory definitions):
  [hello.csolution.yml](https://github.com/Arm-Examples/Hello_B-U585I-IOT02A/blob/main/hello.csolution.yml#L10): `- pack: Keil::B-U585I-IOT02A_BSP@1.1.0`
- enable automatic linker script generation by adding to [hello.cproject.yml](https://github.com/Arm-Examples/Hello_B-U585I-IOT02A/blob/main/hello.cproject.yml):
  ```
  linker:
    - auto:
  ```
  
After building, `RTE\Device\STM32U585AIIx\regions_B_U585I_IOT02A.h` contains only memory defines from the DFP. Memory `RAM-External` and `Flash-External` from BSP are not considered.

**Comment by edriouk** [comment]
@RobertRostohar , where do I get Keil::B-U585I-IOT02A_BSP@1.1.0?
I see 1.0.0 as the latest version

**Comment by jkrech** [comment]
The problem got fixed and will be released in CMSIS-Toolbox csolution 2.4.0.
(Tested with version 2.4.0-devint1)
