### ISSUE TITLE
cbuild reporting errors when the build of a context fails (context specific error status and messages in `*.cbuild-idx.yml`)

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1469]
**Describe The Problem To Be Solved**
Using cbuild in CI system on a solution with multiple contexts should indicate failure when a context fails. How can this be achieved?

**Comment by ReinhardKeil** [comment]
I believe there is currently no feature that allows that.

**Possible Solutions could be**

 - Exit code
 - Build summary in *.cbuild-idx.yml

**Comment by ReinhardKeil** [comment]
This is a proposal how messages could look like in `*.cbuild-idx.yml`

 cbuilds:
    - cbuild: BSD_Client/BSD_Client.Debug+MIMXRT1062DVL6A.cbuild.yml
      project: BSD_Client
      configuration: .Debug+MIMXRT1062DVL6A
      errors: true
      messages:
        errors:
          -  "No compatiple software layer found. Review required connections of the project."
          - "board 'NXP::EVK-MIMXRT1060x' was not found"
        warnings:
          - "My fake warning: xyz" 
        info:
          - "My fake info: component "Arm:CMSIS@6.0.0" obsolete
      configuration: .Release+MIMXRT1062DVL6A
      errors: true
      messages:
        errors:
          - "board 'NXP::EVK-MIMXRT1060x' was not found"

**Comment by ReinhardKeil** [comment]
MCUTO-347
