### ISSUE TITLE
Reduce messages from `cbuild`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1539]
**The Problem To Be Solved**

`cbuild` generates too much user output that are distracting.

Take #1537 as an example.

**Suggest A Solution**

Instead of:
```
>cbuild setup USB_Device.csolution.yml --packs
error csolution: undefined variables in USB_Device.csolution.yml:
  - $Board-Layer$

To resolve undefined variables, copy the settings from cbuild-idx.yml to csolution.yml
error cbuild: error generating build files
error cbuild: exit status 2
```

Generate:
```
>cbuild setup USB_Device.csolution.yml --packs
error csolution: undefined variables in USB_Device.csolution.yml:
  - $Board-Layer$

info cbuild: to resolve undefined variables, copy settings from cbuild-idx.yml to csolution.yml
```

`error cbuild: error generating build files` is misleading, as I would expect that the tool could not write the files because existing files are R/O and therefore write protected.

`error cbuild: exit status 2` is not really an error.  Instead, I would suggest to output this only with option `--verbose` as `info`

```
>cbuild setup USB_Device.csolution.yml --packs --verbose
error csolution: undefined variables in USB_Device.csolution.yml:
  - $Board-Layer$

info cbuild: to resolve undefined variables, copy settings from cbuild-idx.yml to csolution.yml
info cbuild: exit status 2
```

**Comment by soumeh01** [comment]
> `error cbuild: exit status 2` is not really an error. Instead, I would suggest to output this only with option `--verbose` as `info`

@ReinhardKeil This change is feasible and can be made.

However, changing the severity level of the message **To resolve undefined variables, copy settings from cbuild-idx.yml to csolution.yml** to `info `would suppress this message by default. I recommend keeping this message as a part of an error to ensure it's not overlooked, for example. for e.g.

```
>cbuild setup USB_Device.csolution.yml --packs
error csolution: undefined variables in USB_Device.csolution.yml:
  - $Board-Layer$
To resolve undefined variables, copy the settings from cbuild-idx.yml to csolution.yml
```
