### ISSUE TITLE
Question on cbuild / Cmake process

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1541]
**This question is related to #1540**

When using `cbuild` with option `--debug` my output shows two CMake calls:
```
cmake.exe -G Ninja -S C:\Test\USBD\tmp -B C:\Test\USBD\tmp -Wdev
cmake.exe --build C:\Test\USBD\tmp -j 8 --target all
```

Q1: Are these CMake calls exactly the same as without the option `--debug`?
Q2: Do we always need the call `cmake.exe -G Ninja -S C:\Test\USBD\tmp -B C:\Test\USBD\tmp -Wdev`? It seems to setup the environment.

**Comment by jkrech** [comment]
To my understanding cmake always works in these two steps. 
The question is, whether cmake recognizes, if any of the configuration input changed to decide whether or not to re-generate the files used by ninja to build. This way a rebuild with only one source module being changed should not need to do anything during the first step.

**Comment by brondani** [comment]
It is CMake itself that checks the presence and validity of a cached CMake setup and skip the steps that are not needed. `cbuild` does not make any assumption about the CMake cache presence or status. For this reason both calls are mandatory and have in practice no impact on performance.
