### ISSUE TITLE
csolution: 'attr=template' files and cbuild.yml use

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#1547]
Hi

When a file is part of a component with attr="template", it is defined in the generated cbuild.yml file:

Example:
```
        - file: xxx/CMSIS/Core/Template/ARMv8-M/main_s.c
          category: sourceC
          attr: template
          version: 1.1.1
          select: Secure mode 'main' module for ARMv8-M
```

Is it the expected behavior?
Is it up to IDE to filter this template attribute ?

Thx

**Comment by jkrech** [comment]
According to the documentation here: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#files-of-a-component
this information could be used by IDEs offering to copy a selected template to the user's project space.

**Comment by ReinhardKeil** [comment]
@jeromecoutant is the answer sufficient? Can we close this ticket?

**Comment by jeromecoutant** [comment]
yes, I understand this template attribute is used only optionally by IDE.

Note this should be taken into account when cbuild tool will use cbuild.yml instead of cprj :-)
