### ISSUE TITLE
[csolution] Save compiler version in *.cbuild.yml

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1559]
Since https://github.com/Open-CMSIS-Pack/devtools/issues/1276 the toolchain registration via environment variables is mandatory.
During the `convert` call the compiler version selected for each context should be stored in `*.cbuild.yml` alongside the selected compiler name in the `compiler` node following the pattern `compiler: <name>@<version>`, for example `AC6@6.16.0`

see: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#file-structure-of-cbuildyml

**Comment by ReinhardKeil** [comment]
This is the [proposed node `toolchains:`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md).

It allows to record the compiler used, but also supports compiler selection for projects that have an undefined compiler.

**Comment by jkrech** [comment]
The "used compiler" is already captured in the `compiler:` node today. However we can now capture the version of the compiler.
Capturing alternative compilers that could be selected should be handled separately.

**Comment by ReinhardKeil** [comment]
Sorry, I was wrong.  Just add to the `compiler;` node of the `cbuild.yml` for the project the version number as it could be done in the YML input files,

```yml
compiler: AC6@6.22
```
