### ISSUE TITLE
Improve "error csolution: compiler: value not set"

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1569]
**The Problem To Be Solved**

Toolchain can be specified using the option `--toolchain` or `compiler:` node.

**(Optional): Suggest A Solution**
Therefore 
Change: `error csolution: compiler: value not set`
To: `error csolution: compiler undefined, use --toolchain option or add compiler: value to yml input`

**Comment by jkrech** [comment]
using csolution nightly 2024-0624:
```
cbuild Hello.csolution.yml
error csolution: processing context 'Hello.Debug+AVH' failed
error csolution: processing context 'Hello.Release+AVH' failed
error csolution: compiler undefined, use '--toolchain' option or add 'compiler: <value>' to yml input, selectable values can be found in cbuild-idx.yml
error cbuild: exit status 1
```
