### ISSUE TITLE
Improve warning csolution: Multiple 'device_cfg.h.base' files ...

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1594]
Change this warning message:
`warning csolution: Multiple 'device_cfg.h.base' files ...`
To:
warning csolution: 'C:/w/csolution-examples/Hello/RTE/Device/SSE-300-MPS3' contains more than one 'device_cfg.h.base' file, PLM may fail.

Note: can be duplicated with `csolution-examples\Hello`

**Comment by jkrech** [comment]
Easy to reproduce with any example having config files. Just duplicate a base file with different `@version`.
Multiple base file versions:
device_cfg.h.base@1.1.2
device_cfg.h.base@1.1.3

PLM should always use the highest version present
Future command `cbuild release` shall check for a clean status of config files.
- no duplicate base files with different versions
- no update files indicating a pending update
