### ISSUE TITLE
Proposal: Add command-line option to redirect `tmp` directory

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1610]
**The Problem To Be Solved**

In CI test environments with parallel build (i.e. GitHub Actions Matrix), it is possible to build for example LLVM and GCC in parallel. However the out/tmp directory needs to be separated to avoid clashes.

For the Output directory this exists already at the command line, however the behavior needs to be specified better.

**Suggest A Solution**

- Add a command-line option (cbuild + csolution) to redirect `tmp` directory, i.e.  `-T  --tmp     Set directory for all interim temporary files`.
- Specify how `-O --output` works for project/build/target types as it is right now unclear what happens when multiple context are generated at the same time.

**Comment by jkrech** [comment]
`cbuild -O` / `cbuild -output`  and `csolution -o`  /  `csolution -output` allow to specify a toplevel  directory specification. Underneath this directory the `tmp` and `out` (or otherwise configured) directories remain unaffected.

Example: https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/SimpleTrustZone
```
cbuild SimpleTZ.csolution.yml -c .Debug -O test_ac6 --toolchain AC6  
cbuild SimpleTZ.csolution.yml -c .Debug -O test_gcc --toolchain GCC

The generated files (temporary and output) are located in fully separate subdirectories

test_ac6/
		out
		tmp
		CM33_ns.Debug+AVH.cbuild.yml
		CM33_s.Debug+AVH.cbuild.yml
		SimpleTZ.cbuild-idx.yml

test_gcc/
		out
		tmp
		CM33_ns.Debug+AVH.cbuild.yml
		CM33_s.Debug+AVH.cbuild.yml
		SimpleTZ.cbuild-idx.yml
```

**Comment by ReinhardKeil** [comment]
I would not combine the redirect of `out` and `tmp`.  In some DevOps systems you may want to store `out` in a permanent location (for post-processing with other services) while `tmp` can be scraped when the VM stops.

**Comment by jkrech** [comment]
Usually there is specific actions required to copy data into a space that is retained after the overall actions completes.
Therefore I think having a single redirect supports simplicity. By default you will have `tmp` and `out` sub-directories.

**Comment by ReinhardKeil** [comment]
--output does both, temp and output. Therefore this is not required
