### ISSUE TITLE
Improve documentation on `cdefault.yml`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1641]
**The Problem To Be Solved**

`cdefault.yml` is a good starting point, but there are a few issues that should be improved for **GCC**.

1. Link option `--specs=rdimon.specs` 
     Enables semihosting, but may actually create problems as it runs on a breakpoint. Should this be in the default?

2. Linker warning `warning: ...elf has a LOAD segment with RWX permissions` when using the default linker script management.
     What is causing this? Can it be solved or does this need to be in the documentation?

**Comment by jkrech** [comment]
The rational behind enabling semihosting for GCC was driven by running solutions on AVH-FVP models using semihosting for test output.

**Comment by ReinhardKeil** [comment]
Decision on 1. is to not enable semihosting (leave the existing toolchain default).
