### ISSUE TITLE
cbuild  reports "bad pack name"

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1649]
**Describe the bug**

Error unexpected with this project [Hello.zip](https://github.com/user-attachments/files/16262144/Hello.zip)

```txt
cbuild Hello.csolution.yml --context-set --update-rte --packs --context Hello.Debug+AVH-CM0plus
Hello.cbuild-set.yml - info csolution: file is already up-to-date
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
```

**To Reproduce**
All required packs are installed and up-to-date on local computer.

Error also appears when cpackget is called with:

```
cpackget add " "
```
Therefore it is likely that even when no packs are missing cpackget is called.

**Expected behavior**
Project builds correct.

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.5.0-devint5
- Windows

**Comment by jkrech** [comment]
Its seems a side effect of extending --context-set to all the commands
when cbuild calls list packs with -S it tries to generate cbuild-set. As a result of which we 
`cbuild list packs -c X.y+Z-S return
C:/Sandbox/opensource/Hello/Hello.cbuild-set.yml - info csolution: file is already up-to-date
Keil::V2M-MPS2_CMx_BSP@1.8.2
 
when parsing the output. The first entry is not a valid pack name.

**Comment by ReinhardKeil** [comment]
VS Code extension issues exactly this command. IMHO this needs to be addressed before release

**Comment by jkrech** [comment]
Agreed. Sourabh is on it already.
