### ISSUE TITLE
Component resolution unexpected when only partially specified (updated)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1650]
**Describe the bug**

This component is incorrectly resolved for this project: [Hello.zip](https://github.com/user-attachments/files/16263247/Hello.zip)

```yml
    - component: ARM::CMSIS Driver:USART
```

Use this command 
```
csolution covert Hello.csolution.yml --context .Debug+AVH-CM0plus
```

The component does not exist, as for the DFP for this device only contains `Keil::CMSIS Driver:USART`.

The `Hello.Debug.AVH+CM0plus.cbuild.yml` file shows that csolution picks:

```yml
  components:
    - component: ARM::CMSIS Driver:USART:Custom@1.0.0
      from-pack: ARM::CMSIS@6.1.0
```

However in `ARM::CMSIS@6.1.0` this component is not marked with [attribute `isDefaultVariant`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#element_component).  This behavior is only expected for components that have `isDefaultVariant` set.

**Expected behavior**
Error message that the component cannot be resolved.

**Environment (please complete the following information):**

- All packs installed from `hello.cbuild-pack.yml`
- CMSIS-Toolbox 2.5.0-devint5
- OS: Windows

**Comment by brondani** [comment]
This looks like intended behaviour rather than a bug:
1. The component identifier `ARM::CMSIS Driver:USART:Custom` corresponds to  [`Cvendor::Cclass:Cgroup:Csub`](https://github.com/ARM-software/CMSIS_6/blob/b258ac96a2a57ecfb17414baba70534161f3f3ce/ARM.CMSIS.pdsc#L703), there is no `Cvariant` so the attribute `isDefaultVariant` is irrelevant.
2. Partial component identifiers are accepted and resolved to the best match.

**Comment by ReinhardKeil** [comment]
This needs review.  I think resolving it in an IDE is great, but csolution should perhaps not auto-pick it.

**Comment by jkrech** [comment]
The feature of allowing partially specified packs and components was introduced in the CMSIS solution project format right from the start. In my opinion removing this capability should be considered for a major version update (e.g. 3.0.0) and not for 2.6.0.

**Comment by ReinhardKeil** [comment]
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#component-name-conventions
documents under **Partly defined components** the behaviour.  `:Csub` is not automatically selected for the user. 

Today default implementations of device interfaces are defined without `:Csub`. It is therefore dangerous to add `:Csub` when there is not default implementation.

**Comment by brondani** [comment]
As just seen in the last nightly build, this impacts partial component identifiers such as `CMSIS:OS Tick` in
 [Open-CMSIS-Pack/csolution-examples](https://github.com/Open-CMSIS-Pack/csolution-examples/blob/main/Hello/Hello.cproject.yml#L21), which now requires `CMSIS:OS Tick:SysTick` to be resolved.
 Potentially many other projects may have replicated it.

**Comment by RobertRostohar** [comment]
It appears also in some other files within the Open-CMSIS-Pack organization:
- https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/878cd68d0d046512ed87fb7532416c4c214ce954/docs/CubeMX.md?plain=1#L198
- https://github.com/Open-CMSIS-Pack/vscode-get-started/blob/a7225162af0572c5d2f935fe6a6cf722d4dd28c9/hello/hello.cproject.yml#L9
- https://github.com/Open-CMSIS-Pack/RefApp-Framework/blob/1fc13e1e8e57c850b973d40a79c7e81a60c3cfe2/layer/RTOS/RTX/RTOS.clayer.yml#L17
- https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/878cd68d0d046512ed87fb7532416c4c214ce954/docs/MCUXpressoConfig.md?plain=1#L200
- https://github.com/Open-CMSIS-Pack/cbuild2cmake/blob/8e45fa1f13deacf0ebca633ca1db16350d5eacdd/test/data/solutions/library-rtos/project/project.cproject.yml#L7

Should be also fixed.

**Comment by jkrech** [comment]
1. fixed
2. fixed
3. fixed
4. fixed
5. fixed
