### ISSUE TITLE
`select-compiler:` does not work

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1659]
**Describe the bug**

It should be possible to select the compiler based on information in cbuild-idx.yml. However it seems that this fails.

**To Reproduce**
Attached project USB_Device.zip uses `select-compiler:`. [USB_Device.zip](https://github.com/user-attachments/files/16335897/USB_Device.zip) However this seems not to work.

```
>cbuild setup USB_Device.csolution.yml -S --update-rte --packs -s
C:/Test/U5/USB_Device/USB_Device.csolution.yml:11:7 - error csolution: schema check failed, verify syntax
C:/Test/U5/USB_Device/USB_Device.csolution.yml:11:7 - error csolution: schema check failed, verify syntax
```
Issue: it does not load the project as the schema seems not to contain `select-compiler:`.

```
>csolution list toolchains USB_Device.csolution.yml -n
error csolution: compiler undefined, use '--toolchain' option or add 'compiler: <value>' to yml input, selectable values can be found in cbuild-idx.yml
```
Issue: There is not `cbuild-idx.yml` generated.

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.5.0
- Windows

**Comment by brondani** [comment]
In the attached example the node `compiler: LLVM` does not match the pattern `(GCC|CLANG|AC6|IAR)`, `CLANG` must be used instead of `LLVM`.
![image](https://github.com/user-attachments/assets/814a7bc6-454f-4df7-b398-4194f65655ae)

**Comment by ReinhardKeil** [comment]
I can confirm, this is a user error.
