### ISSUE TITLE
cbuildgen is more strict than csolution for packs name

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#166]
csolution accepts a pack whose name is not the same as the name of the file.pdsc.
cbuildgen does not.

I think the 2 tools should apply the same checks.

**Comment by brondani** [comment]
Such a pack fails packchk validation:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/packChk.html#packChkMessages

For example:
```
*** ERROR M207: C:\Packs\Keil\ARM_Compiler\1.6.3\Keil.ARM_CompilerX.pdsc
  PDSC file name mismatch!
  Expected: 'Keil.ARM_Compiler.pdsc'
  Actual  : 'Keil.ARM_CompilerX.pdsc'
```

This check should be added into common libs.

**Comment by ReinhardKeil** [comment]
Is this still relevant or solved by now?

**Comment by brondani** [comment]
This should already be solved.
@fred-r Could please test it with the [CMSIS-Toolbox 1.1.0](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.1.0)?
