### ISSUE TITLE
cbuild option -s does not make sense

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1660]
**Describe the bug**
The `cbuild` option `-s` enables schema check, but this is already enabled by default.  It makes therefore little sense.

`csolution` implements the option `-n` to disable schema check. I would therefore recommend to implement a similar option in `cbuild`.

**Environment:**

- CMSIS-Toolbox 2.5.0

**Comment by soumeh01** [comment]
By default, schema check is disabled in cbuild. To enable schema check, users must provide the `-s` flag. Conversely, the `cbuild setup` command has schema check enabled by default

```
$ cbuild -h
cbuild: Build Invocation 2.5.0 (C) 2024 Arm Ltd. and Contributors
...
  -s, --schema             Validate project input file(s) against schema
```

```
$ cbuild setup -h
Generate project data for IDE environment
...
  -s, --schema             Validate project input file(s) against schema (default true)
```

**Comment by ReinhardKeil** [comment]
OK, I believe this is acceptable.

**Comment by ReinhardKeil** [comment]
Add also information that `-update-rte` is default for `cbuild setup`
