### ISSUE TITLE
Create example CMake script to execute FCARM

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1661]
**The Problem To Be Solved**

We need an example script that shows how legacy tools such as FCARM could be used with CMSIS-Toolbox.
Details see https://github.com/ARM-software/MDK-Middleware/issues/33

**Comment by brondani** [comment]
An example is already attached to https://github.com/ARM-software/MDK-Middleware/issues/33, I assume it comes from my comment https://github.com/Open-CMSIS-Pack/devtools/issues/1545#issuecomment-2173873395.

In the mentioned example, which uses a standalone CMakeLists.txt, the `execute` node has as `input` only the CMakeLists directory and the Web root directory, and as `output` the `.c` file to be generated.
CMake retrieves all input files using file globbing, handles them as dependencies (i.e. any change in their content will retrigger fcarm), and format fcarm arguments using the ROOT() parameter (i.e. keeping short filenames), for example:

```
FCARM FILE CONVERTER V2.59 ad.cgi,ad.cgx,buttons.cgi,buttons.cgx,home.png,index.htm,keil.gif,language.cgi,lcd.cgi,leds.cgi,llblue.jpg,logo.gif,network.cgi,pabb.gif,pg_footer.inc,pg_header.inc,system.cgi,tcp.cgi,xml_http.js TO ../project/Web.c RTE NOPRINT ROOT ( Web )
```

What else needs to be improved or explained on this matter?

**Comment by ReinhardKeil** [comment]
- FCARM depends on the command-line limit of Windows (8192 characters).  The script should create a 'cmdfile' and should invoke with FCARM @cmdfile.
  - We should test also a more complex structure that has files in sub-directories.  Does the search work in this case?

**Comment by brondani** [comment]
> The script should create a 'cmdfile' and should invoke with FCARM @cmdfile.
> We should test also a more complex structure that has files in sub-directories. Does the search work in this case?

The changes to address both items are reported below and in the updated [http-server.zip](https://github.com/user-attachments/files/16412585/http-server.zip) example.

> FCARM will be part of the MDK Toolbox; could be the CMake Script also part of that toolbox? How would this work?

My biggest concern is handling compatibility when the "FCARM" CMakeLists.txt get updated.
Just taking whatever is in the MDK Toolbox installation does not handle versioning properly.

In my opinion a better approach is to ship it inside a pack. Its path could be referenced in csolution via a new access sequence
`$PackDir(<vendor>::<name>[@version])` as described here for other purposes: https://github.com/Open-CMSIS-Pack/devtools/issues/1413#issuecomment-2031298724.

Updated CMakeLists.txt:
``` cmake
# CMakeLists.txt for calling FCARM
# Find input files in the input base directory and in its subfolders using file globbing recursively
# Format arguments and generate a steering command file, overcoming any command line length limitation
# Call FCARM using the steering command file, generating the source file in the expected output  
#
# Configuration Step: ${CMAKE_COMMAND} -G <generator> -S <source directory> -B <build directory> -DINPUT_DIRECTORY=<input base directory> -DOUTPUT=<output source file>
# Build Step: ${CMAKE_COMMAND} --build <build directory>
#
# <generator>: underlying generator build system, e.g. Ninja
# <source directory>: directory where this CMakeLists.txt resides
# <build directory>: directory for temp files
# <input base directory>: directory where input data is located
# <output source file>: path and filename of source file to be generated

cmake_minimum_required(VERSION 3.22)
include(ExternalProject)
	
project("FCARM" NONE)

file(GLOB_RECURSE INPUT ${INPUT_DIRECTORY}/*)

foreach(ITEM ${INPUT})
  cmake_path(RELATIVE_PATH ITEM BASE_DIRECTORY ${INPUT_DIRECTORY} OUTPUT_VARIABLE FILE)
  list(APPEND FILES ${FILE})
endforeach()
string(REPLACE ";" ",\n" FILES "${FILES}")

cmake_path(RELATIVE_PATH OUTPUT BASE_DIRECTORY ${INPUT_DIRECTORY} OUTPUT_VARIABLE RELATIVE_OUTPUT)
cmake_path(GET INPUT_DIRECTORY FILENAME INPUT_DIRECTORY_NAME)
cmake_path(GET INPUT_DIRECTORY PARENT_PATH WORKING_DIRECTORY)

set(COMMAND_FILE "${CMAKE_CURRENT_BINARY_DIR}/Auto_FcArm_Cmd.inp")
file(WRITE ${COMMAND_FILE} "${FILES}\nTO ${RELATIVE_OUTPUT} RTE NOPRINT ROOT(${INPUT_DIRECTORY_NAME})\n")

add_custom_target(FCARM ALL DEPENDS ${OUTPUT})
add_custom_command(OUTPUT ${OUTPUT} DEPENDS ${INPUT}
  COMMAND fcarm @${COMMAND_FILE} 
  WORKING_DIRECTORY ${WORKING_DIRECTORY}
)

```

**Comment by furbanc** [comment]
My concerns about retrieving input files via file globbing:
- also adds backup files and copies if found in the web folder
- no error message if a file is accidentally deleted in the web folder

Therefore, I would prefer to add a list of files in the project file cproject.yml. I have updated the network web examples to use this concept and calls FCARM via @cmdfile.
