### ISSUE TITLE
`cbuild setup` should also identify the compiler

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1663]
**The Problem To Be Solved**

Reference Applications will not contain a compiler selection and are incomplete as layers are missing.

**Suggest A Solution**

To get the missing information, the IDE will issue the `cbuild setup` command.  This command should therefore deliver all missing information in one step.

This is an example project [USB_Device.zip](https://github.com/user-attachments/files/16348634/USB_Device.zip)

`cbuild setup USB_Device.csolution.yml --context-set --update-rte --packs`

should update in `*.cbuild-idx.yml`:
 -   `select-compiler:`  
 -   `configurations:`

`cbuild list toolchains USB_Device.csolution.yml` should output the same as `csolution list toolchains` (or this command should be removed).

**Comment by brondani** [comment]
Similarly to `device` or `board` selection, the `compiler` can be used for filtering candidate layers from packs.
Again for consistency, as already explained in https://github.com/Open-CMSIS-Pack/devtools/issues/1658#issuecomment-2243381108 for `Pname`, also the compiler should be selected before applying RTE Model conditions.

**Comment by ReinhardKeil** [comment]
Thanks for the constructive feedback. I just try to streamline the project setup in an IDE.

None of the layer definitions has so far a dependency on a compiler or a processor core. They are all board specific.

**Comment by ReinhardKeil** [comment]
verified, #1708 could improve user messaging
