### ISSUE TITLE
error csolution: found multiple mounted devices - cannot be solved by specifying a device

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1668]
**Describe the bug**

The attach project [Blinky.zip](https://github.com/user-attachments/files/16428753/Blinky.zip) results in:
```
cbuild c:\Test\Boards\Keil\MCB1700\Blinky\Blinky.csolution.yml --clean --context-set --update-rte --packs --context Blinky+Debug
error csolution: found multiple mounted devices
error csolution: one of the following devices must be specified:
LPC1758
LPC1768
error csolution: processing context 'Blinky+Debug' failed
error cbuild: exit status 1
Process failed with exit code 1
Process failed with exit code 1
```

**Expected behavior**

As there is a device specified the project should compile without error.
```
solution:
  created-by: uv2csolution@1.5.0
  created-for: CMSIS-Toolbox@2.4.0
  compiler: AC6
  target-types:
    - type: Debug
      board: Keil::MCB1700
      device: NXP::LPC1768
      optimize: debug
```

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.5.0
- Windows

**Comment by brondani** [comment]
According to the specification:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_mountedDevice
> Exactly one device must be specified per deviceIndex

For this reason the pack Keil::LPC1700_DFP@2.7.2 does not seem to be compliant:
``` xml
  <mountedDevice deviceIndex="0" Dvendor="NXP:11" Dname="LPC1758"/>
  <mountedDevice deviceIndex="0" Dvendor="NXP:11" Dname="LPC1768"/>
```

Nevertheless `csolution` does not cope even with multiple mounted devices with different indexes, therefore the handling must be updated.

**Comment by ReinhardKeil** [comment]
works
