### ISSUE TITLE
`boards:` with explicit vendor information fails

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1671]
**Describe the bug**
[`boards:`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#board-name-conventions) allows to specify a revision. However this feature seems to be not implemented.

**To Reproduce**
Use this project: [Blank4.zip](https://github.com/user-attachments/files/16441921/Blank4.zip)

```
> cbuild c:\Test\MyLPC1700\Blank4\Blank4.csolution.yml --context-set --update-rte --packs --context Project.Debug+A31G112
ABOV::A31G1xx_Series@2.5.0          # output artifact
I: Adding pack "ABOV::A31G1xx_Series@2.5.0"
I: Downloading ABOV.A31G1xx_Series.2.5.0.pack...

I: Extracting files to C:\Users\reikei01\AppData\Local\Arm\Packs\ABOV\A31G1xx_Series\2.5.0...
error csolution: board 'ABOV::StarterKit-A31G112CL:V1.1' was not found
error csolution: processing context 'Project.Debug+A31G112' failed
```

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.5.0
- Windows

**Comment by jkrech** [comment]
After installing the pack ABOV::A31G1xx_Series@2.5.0 using `cpackget`, I run `csolution  list boards -f A31G112.
The boardID that is returned is:

```
>csolution list boards -f A31G112
ABOV Semiconductor::StarterKit-A31G112CL:V1.1 (ABOV::A31G1xx_Series@2.5.0)
```

While the vendor uses `ABOV` as the pack vendor name, they use `ABOV Semiconductor` as Dvendor and Bvendor name.

I can see that CMSIS Solution Extension does add the wrong Bvendor for this board.

**Comment by ReinhardKeil** [comment]
not an bug in CMSIS-Toolbox

**Comment by JonatanAntoni** [comment]
The board is defined in ABOV.A31G1xx_series.pdsc 2.5.0 as follows:
```xml
    <board vendor="ABOV" name="StarterKit-A31G112CL" revision="V1.1">
      <description>ABOV StarterKit-A31G112CL_V1.1</description>
      <mountedDevice deviceIndex="0" Dvendor="ABOV Semiconductor:126" Dname="A31G112" />
    </board>
```

But `csolution list boards -f A31G112` reports:
```
ABOV Semiconductor::StarterKit-A31G112CL:V1.1 (ABOV::A31G1xx_Series@2.5.0)
```

This seems to be a confusion between the `Dvendor` (enum) and the pack vendor name (string).

**Comment by ReinhardKeil** [comment]
This is a problem in the VS Code csolution extension.

**Comment by jkrech** [comment]
There is no problem in the VSCode CMSIS Solution extension.
Csolution > 2.5.0 (nightly) now correctly computes the boardID and finds the matching board:

```
>csolution list boards -f A31G112
ABOV::StarterKit-A31G112CL:V1.1 (ABOV::A31G1xx_Series@2.5.0)
```
