### ISSUE TITLE
How is HEAP_SIZE adjusted in generated linker region files?

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1675]
**The Problem To Be Solved**

The generated `region*.h` files contain `#define __HEAP_SIZE     0x00000C00`

Is this number randomly picked?  The issue is that on very small devices (where auto-generated region files make most sense), the HEAP eats-up memory that is most likely never used (as small embedded applications don't call malloc).  For devices with just 4K RAM, this generates typically a linker error even with the smallest possible stub application.

If there is no reason behind this setting, I suggest to pick HEAP_SIZE 0 as initial value.

See #1670

**Comment by ReinhardKeil** [comment]
Note: HEAP_SIZE is generated with value 0 in csolution version 2.5.0+p16-g5f15bb17

**Comment by ReinhardKeil** [comment]
AC6 requires HEAP for several operations. See here 
https://developer.arm.com/documentation/100073/0622/The-Arm-C-and-C---Libraries/Stack-and-heap-memory-allocation-and-the-Arm-C-and-C---libraries/Library-heap-usage-requirements-of-the-Arm-C-and-C---libraries

Suggested solution is for auto region.h generation is therefore:
```
  - set HEAP_SIZE 0xC00     // for devices with >=6KB RAM
  - set HEAP_SIZE 0             // for devices with < 6KB RAM
```

This is a compromise that we need to revise later.

**Comment by brondani** [comment]
@ReinhardKeil
> - set HEAP_SIZE 0xC00     // for devices with >=6KB RAM
> - set HEAP_SIZE 0             // for devices with < 6KB RAM

Should only the device RAM be considered (i.e. ignore the board RAM)?
By 6KB do you mean decimal 6000 or 6144?

**Comment by ReinhardKeil** [comment]
It should consider also external RAM as there might be devices that rely on external memory.

6KB = (2 * 0xC00), so 6144.

The change ensures that on very small devices (i.e. Cortex-M0), with just 4KB of RAM the HEAP+STACK does not exceed the available memory.

**Comment by ReinhardKeil** [comment]
works
