### ISSUE TITLE
Need cpackget command flags option to check for pack updates

### ISSUE THREAD

**Issue by KeilChris** [Open-CMSIS-Pack/devtools#1684]
Currently, there is no way to check if the packs you have installed on your computer are the latest. You can update single packs with `cpackget add Vendor.PackName@latest` to the latest version, but if you have a large number of packs in a project, this is tedious.
I suggest to create a flag for the `update-index` command, for example `--check_for_updates` or short `-c` to get a list of updated packs for the project in the current project directory (containing the csolution) that have an update available.

**Comment by jkrech** [comment]
@KeilChris please use the cpackget repository issues for enhancement requests.
I think the above is already captured here https://github.com/Open-CMSIS-Pack/cpackget/issues/236.

**Comment by KeilChris** [comment]
Yes, looks good! Sorry for using the wrong repo!
