### ISSUE TITLE
When generating a library, cbuild output is misleading

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1686]
**The Problem To Be Solved**

When generating a library, there is no link step.

**Suggest A Solution**

Therefore change cbuild output:
`Linking C static library C:\w\MDK-Middleware\.ci\out\Network\CM4\Debug\Network.lib`
To:
`Generate static library C:\w\MDK-Middleware\.ci\out\Network\CM4\Debug\Network.lib`

Reproducer:
```
https://github.com/ARM-software/MDK-Middleware/tree/main/.ci
cbuild library.csolution.yml --toolchain AC6
```

**Tool**
CMSIS-Toolbox 2.5.0 on Windows

**Comment by brondani** [comment]
The message originates from CMake that historically uses this terminology even for archiver calls, as it can be seen in its source code for Ninja and Unix Makefiles generators:
https://gitlab.kitware.com/cmake/cmake/-/blob/v3.30.2/Source/cmNinjaNormalTargetGenerator.cxx?ref_type=tags#L592
https://gitlab.kitware.com/cmake/cmake/-/blob/v3.30.2/Source/cmMakefileLibraryTargetGenerator.cxx?ref_type=tags#L556

I wouldn't recommend any action in cbuild.

**Comment by jkrech** [comment]
Reject, as this is standard CMake terminology.
