### ISSUE TITLE
[solution] Allow definition of minimal *compatible* pack version `@^` and `@~` 

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1687]
**Describe The Problem To Be Solved**
Once a solution makes use of a feature that was introduced with a certain pack version, this version becomes the minimum required pack version in order to successfully build this application. According to Semantic Versioning, the compatibility of a pack is only guaranteed in case the `<major>` version stays unchanged. Once the `<major>` version increments the relying solution may start to fail.

**Solution**
In order to prevent a solution to be built using a potentially incompatible pack version, a minimal compatible pack version can be specified

```
  packs:
    - pack: ARM::CMSIS@^6.0.1
```

This means the version of the `ARM::CMSIS` pack must be: `6.0.1 <= version < 7.0.0`

Note that this notation is already supported by cpackget today:

```
  cpackget add "ARM::CMSIS^6.0.1"
```

A more restrictive version range qualifier is `~`:

```
  packs:
    - pack: ARM::CMSIS@~6.0.1
```
This means the version of the `ARM::CMSIS` pack must be: `6.0.1 <= version < 6.1.0` - both `major` and `minor` version remain unchanged - which semantically means only newer patch versions = "bug fixes" are allowed.

**Comment by ReinhardKeil** [comment]
Please use the same syntax in the *.yml files as on cpackget command line 

```
  packs:
    - pack: ARM::CMSIS~6.0.1
```

**Comment by jkrech** [comment]
Sorry for the confusion. The correct syntax for `cpackget add` is `@^6.0.1` for consistency the version delimiter `@` should be used and `^`  or `>=` as qualifier. The syntax `cpackget add ARM::CMSIS~6.0.1` does not work for me (version 2.1.3)
