### ISSUE TITLE
Handling of RTE files; --update-rte no longer default for `cbuild setup`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1694]
**The Problem To Be Solved**

cbuild has two modes:
 - IDE:  `cbuild setup *.csolution.yml`
 - CI/Build: `cbuild *.csolution.yml`

In both modes, it is possible that:
 - Files in the RTE folder are missing (as the repo does not contain it).
 - Files in the RTE folder are outdated, as there are newer packs installed.
 
The user should be notified about these situations.

-----

**Suggestions**

**Add messages:**

```
//----- missing files
// when config files are missing
C:/w/csolution-examples/Hello/Hello.cproject.yml:14:17 - error csolution: file './RTE/CMSIS/RTX_Config.h.' not found; use --update-rte

// when .base files are missing
C:/w/csolution-examples/Hello/Hello.cproject.yml:14:17 - warning csolution: file './RTE/CMSIS/RTX_Config.h.base.' not found; base version unknown

//----- new files in packs
// when only patch version differs
C:/w/csolution-examples/Hello/Hello.cproject.yml:14:17 - warning csolution: file './RTE/CMSIS/RTX_Config.h.' update suggested as newer packs are installed; use --update-rte 

// when minor version differs
C:/w/csolution-examples/Hello/Hello.cproject.yml:14:17 - warning csolution: file './RTE/CMSIS/RTX_Config.h.' update recommended as newer packs are installed; use --update-rte 

// when major version differs
C:/w/csolution-examples/Hello/Hello.cproject.yml:14:17 - error csolution: file './RTE/CMSIS/RTX_Config.h.' update required as newer packs are installed; use --update-rte 
```
If possible, the line reference should locate the component that these RTE files belong to.

**Add information to `cbuild.yml` file**

To show status of RTE files in a IDE project outline window, the Build Information Files should be extended with:
  - status under [`file:` of a component](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#files-of-a-component)
  - potentially warning or error status in `cbuild-idx.yml`.

**`--update-rte` no longer default for `cbuild setup`**

In CMSIS-Toolbox 2.5, `cbuild setup` has `--update-rte` set by default. This should be removed.

`cbuild setup` with option `--update-rte` should be called by the IDE when:
- component selection is changed by the user
- an explicit update for the RTE files is requested by the user

**Comment by jkrech** [comment]
Daniel was referring to the `use --update-rte` at the end of your proposed messages:
```
C:/w/csolution-examples/Hello/Hello.cproject.yml:14:17 - warning csolution: file './RTE/CMSIS/RTX_Config.h.' update suggested as newer packs are installed; use --update-rte 
```

**Comment by brondani** [comment]
> Unless I am specifying --update-rte the RTE folder content remains unchanged

I can confirm this.
Even if it was agreed differently in https://github.com/Open-CMSIS-Pack/devtools/issues/1265 this is the current default behaviour which is also aligned with the documentation:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.5.0/docs/build-operation.md#details-of-the-setup-mode

**Comment by ReinhardKeil** [comment]
works as expected
