### ISSUE TITLE
`--frozen-packs` should result in error when file `*.cbuild-pack.yml` is missing

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1696]
**Describe the bug**
The option `--frozen-packs` should result in an error (very early in the build process) when the file `*.cbuild-pack.yml` is missing.

**To Reproduce**
Use `csolution-examples` Hello project, delete `*.cbuild-pack.yml` and execute:

```
cbuild hello.csolution.yml --frozen-packs
```

**Expected behavior**
Should result in:

error cbuild: file `<solution-name>.cbuild-pack.yml` is missing; required when using `--frozen-packs`

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.5.0
- OS: Windows

**Comment by soumeh01** [comment]
The issue is not reproducible using **CMSIS-Toolbox version 2.5.0**. It throws the expected error message.

```
$ cbuild --version
cbuild version 2.5.0 (C) 2024 Arm Ltd. and Contributors

```
```
$ cbuild Hello.csolution.yml --frozen-packs
C:/Sandbox/test/examples/Hello/Hello.cbuild-pack.yml - error csolution: file is missing and required due to use of --frozen-packs option
error cbuild: exit status 1
```

**Comment by ReinhardKeil** [comment]
Sorry cannot duplicate the issue anylonger. Might be my mistake.
