### ISSUE TITLE
Can't use newer C language standards than C11 with AC6/ARMCLANG compilers

### ISSUE THREAD

**Issue by EaselinkBachmann** [Open-CMSIS-Pack/devtools#1703]
**Describe the bug**

The CMake build system generated by `cmsis-toolbox` rejects newer C standards than C11 for ARMCLANG compilers despite newer versions of ARMCLANG being based on versions of Clang supporting up to `-std=c23` (e.g. AC6.21.0 based on Clang 18.0.0). ARM itself only claims "community" support for C11 and doesn't even mention newer C language standards, but artificially rejecting these language standards unnecessarily cripples the capabilities of the compiler.

**To Reproduce**

Specify `language-C: c17` or `language-C: c23` in a `.cproject.yml` file and attempt to build the project. The build fails with `unknown 'language' value 'c17' !`.

**Expected behavior**

When using a compiler that accepts `-std=c17` or `-std=c23` without error the CMake build system generated by `cmsis-toolbox` should not reject these language standards.

**Environment (please complete the following information):**

- `cmsis-toolbox` version 2.5.0 
- `armclang` version 6.21.0
- OS: Linux

**Additional context**

Newer C standards (especially C23) provide new language features and syntax options that allow writing cleaner code or reject error-prone code without needing standard library support, so might be useful even when not officially supported by ARM (removal of prototype-less declarations, new attribute syntax, allow placement of labels before declarations, enums with explicit underlying types, constexpr variables, etc...).

**Comment by ReinhardKeil** [comment]
Documentation is here: https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#language-c

**Comment by EaselinkBachmann** [comment]
great!

**Comment by EaselinkBachmann** [comment]
I noticed that the list of supported language values still isn't perfect:

- C standards `gnu17` and `gnu23` are missing
- C++ standards `c++20` and `gnu++20` incorrectly map to `-std=c++17` and `-std=gnu++17` instead of `-std=c++20` and `-std=gnu++20`
- C++ standards `c++23` and `gnu++23` are missing

Should I open a new issue for this?

**Comment by ReinhardKeil** [comment]
Yes please open a new issue for that.
