### ISSUE TITLE
GCC does not generate Secure project that has no cmse entries

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1711]
**Describe the bug**

The GCC linker produces this error which prevents the tool from generating an ELF file.

```
CM33_s_CMSE_Lib.o: no symbol found for import library
CM33_s_CMSE_Lib.o: failed to generate import library
ld.exe: final link failed: no symbols
```

This prevents from using it for generating a Secure-Only project.

AC6 only generates a warning.

**Comment by ReinhardKeil** [comment]
Documentation is here: https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#processor

**Comment by brondani** [comment]
How can I reproduce the linker errors above?
The only way I see is by compiling the modules without the `-mcmse` option which I assume is wrong because it would be equivalent to non-secure compiling.
What am I missing?

**Comment by jkrech** [comment]
Using nightly build: cmsis-toolbox-windows-amd64-2024-09-03_00-03-21 and SimpleTrustZone I could validate the introduction of secure-only fixing the GCC linker failure.
