### ISSUE TITLE
Notify users about incorrect installation

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1728]
**The Problem To Be Solved**
Can this be reviewed/added https://github.com/Open-CMSIS-Pack/devtools/pull/1600

**Suggest A Solution**
Change messages to:

"error: no compiler registered. Add path to compiler with environment variable CMSIS_COMPILER_ROOT=\<name\>\_TOOLCHAIN\_\<major\>\_\<minor\>\_\<patch\>. \<name\> is one of AC6, GCC, IAR, CLANG."

If the cmake files in `./etc` directory are missing, output:
"error: no toolchain cmake files found. Check ./etc directory and verify CMSIS-Toolbox installation."

**Comment by jkrech** [comment]
`CMSIS_COMPILER_ROOT ` cannot be used to specify a compiler registration environment variable. This variable is used to point to an alternative directory to the `./etc` directory of the CMSIS-Toolbox installation, containing e.g. the *.cmake files for the supported toolchains (see: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#environment-variables)

**Comment by ReinhardKeil** [comment]
@jkrech you are correct.  

Suggest to make the message a bit shorter
"error: no compiler registered. Add path to compiler ./bin directory with environment variable \<name\>\_TOOLCHAIN\_\<major\>\_\<minor\>\_\<patch\>. \<name\> is one of AC6, GCC, IAR, CLANG."
