### ISSUE TITLE
execute commands on windows may fail due to paths specified with '/' instead of '\'

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1735]
**Describe the bug**

Trying this execute command on windows fails:
```
  executes:
    - execute: dir 
      run: copy $input$ $output$
      input:  
        - $elf(Project)$
      output: 
        - $OutDir(Project)$/Project.out
```

with this output:
```
FAILED: C:/Test/Blank4/out/Project/ADuCM320-Board/Debug/Project2.out
C:\WINDOWS\system32\cmd.exe /C "cd /D C:\Test\Blank4\tmp && copy C:/Test/Blank4/out/Project/ADuCM320-Board/Debug/Project.axf C:/Test/Blank4/out/Project/ADuCM320-Board/Debug/Project2.out"
The syntax of the command is incorrect.
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Add the command to Hello.csolution.yml.

**Expected behavior**

The reason is that the Windows copy requires `\` characters in path names.

It also triggers the question: do we need a `for-host-os:` key/value as the syntax of copy commands is different across operating systems. 

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.5.0 
- OS: Windows 11

**Additional context**

I was trying to solve #1043 with in a pragmatic way.

**Comment by brondani** [comment]
I would recommend to use CMake commands (as well as CMake scripts) to overcome platform specific limitations.
For example instead of `copy $input$ $output$`, the crossplatform command `${CMAKE_COMMAND} -E copy $input$ $output$` could be used.

**Comment by ReinhardKeil** [comment]
Great that seems to solve it.  I will add this to documentation

**Comment by ReinhardKeil** [comment]
https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#executes
