### ISSUE TITLE
Execute `run` do not expand access sequences

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1738]
Requested by @RobertRostohar:

The execute `run` string expands only `$input()$` and `$ouput()$` entries:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#executes

Expanding access sequences such as `$BuildType$` may be handful to differentiate commands at context level - for example for correctly placing several CMake binary directories related to different instances in the same solution (advanced use case of https://github.com/Open-CMSIS-Pack/devtools/issues/1661).

**Comment by ReinhardKeil** [comment]
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/168 is a similar issue.  I believe that enabling access sequences in `run:` node is helpful.

**Comment by brondani** [comment]
> [Open-CMSIS-Pack/cmsis-toolbox#168](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/168) is a similar issue. I believe that enabling access sequences in `run:` node is helpful.

This is a different matter.

**Comment by brondani** [comment]
Addressed in [Expand non-path access sequences in execute `run` node](https://github.com/Open-CMSIS-Pack/devtools/issues/1738)
Please note: access sequences that lead to path expansion/replacement must be located under `înput`/ `output` nodes.

**Comment by ReinhardKeil** [comment]
@brondani could you provide a list of the access sequences that are expanded.
Is it possible to use $SolutionDir()$ to specify the location of a tool?  This would allow this instead of $input(1)$:

```
      run: $SolutionDir()$/KeyGen.bat $input(0)$ -o $output$
      always:                                 # always generate the keyfile.c as it has a timestamp
      input:
        - $ProjectDir()$/keyfile.txt          # contains the key in text format
        - $SolutionDir()$/KeyGen.bat
```

See the examples on:
https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#executes

**Comment by brondani** [comment]
> @brondani could you provide a list of the access sequences that are expanded
```
$Bname$
$Dname$
$Pname$
$BuildType$
$TargetType$
$Compiler$
$Solution$
$Project$
```

> Is it possible to use `$SolutionDir()$` to specify the location of a tool?

Currently the access sequences that lead to path replacement also relativize the expanded paths for keeping the generated `cbuild.yml` portable. This would need to be reworked if `$SolutionDir()$` is required.

However I believe in most cases, certainly in this example, it would be highly recommend to add the script as an `input` and not directly in the `run` string, so any change in the script itself will retrigger the execute.

**Comment by RobertRostohar** [comment]
Having `$Pack()$` available in the `run:` node might also be useful. For example, a tool/script might be distributed in a pack.
