### ISSUE TITLE
warning with generator run potentially incorrect

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1739]
**Describe the bug**
The USB Device MDK Middleware example configured for the STM32U5 board shows this warning:

```
csolution run c:\Test\USB_D\USB_Device.csolution.yml -g CubeMX -c HID.Debug+STM32U585AIIx
warning csolution: variable 'Board-Layer' redefined from 'C:/Test/USB_D/Board/B-U585I-IOT02A/Board.clayer.yml' to '$SolutionDir()$/Board/B-U585I-IOT02A/Board.clayer.yml'
```

The message is potentially incorrect.

**Environment:**

- CMSIS-Toolbox 2.5.0

**Comment by jkrech** [comment]
It looks like the string compare has not considered the expansion of the Access Sequence or maybe the canonical conversion?
'C:/Test/USB_D/Board/B-U585I-IOT02A/Board.clayer.yml'
'$SolutionDir()$/Board/B-U585I-IOT02A/Board.clayer.yml'

Assuming that `$SolutionDir()$` correctly converts to a case insensitive `c:/test/usb_d/` on windows this should match.
