### ISSUE TITLE
An option to set the output directory when running `cbuild setup`

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1747]
**Describe The Problem To Be Solved**
On `cbuild` usual commands it is possible to use the `--output` directory so that any produced/generated files are put there. This is an important feature because our source file directory is read only and so cannot accept any files to be generated there. 
After cbuild>2.5 the only way to generate compile_commands.json files for intellisense is to call `cbuild setup`. This command however does not have the `--output` flag meaning files such as cbuild-idx.yml or *cbuild.yml are put in the directory where the csolution is. This will unfortunately not work for us due the reason aforementioned.

**(Optional): Suggest A Solution**
add a `--output` option to the `cbuild setup` command like other commands

**Comment by ReinhardKeil** [comment]
The option `--output` will be not used in IDEs.  It is only for CI systems.

**Comment by jkrech** [comment]
@acabarbaye please fetch the latest nightly build from here tomorrow Wednesday 2024-09-11
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/actions/workflows/nightly.yml
