### ISSUE TITLE
`execute:` behaves different when using `--context-set` or `--context`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1752]
**Describe the bug**

This project  [Blank4.zip](https://github.com/user-attachments/files/16961154/Blank4.zip) shows several issues:

- At `csolution.yml` level an `execute:` node is only run when `cbuild` without `--context` is used.  It works with `--context-set` even when this file specifies just the same `--context`.
   - Both calls should execute the the node in `csolution.yml`.  Alternatively issue a "warning:  `execute:` node in `solution:` file is ignored".

- It is unclear which CMake targets are executed when. 
    - Would it be possible for example to output "Execute <target-name: <run-command", for example "Execute touch_main:  ${CMAKE_COMMAND} -E touch C:/Test/Blank4/Project/main.c"  (could be also 2 lines).

- For `--context-set`: It appears that ${CMAKE_COMMAND} -E touch C:/Test/Blank4/Project/main.c" is executed twice, or at least it triggers 2 times the project build.

- My attempt to specify a path to a batch file using access sequences failed. In `cproject.yml`, the input $SolutionDir()$KeyGen.bat is expanded to C:/Test/Blank4/.KeyGen.bat. This is not accepted.
   - Allow some access sequences in run, i.e. "run: $SolutionDir()$KeyGen.bat ..."
   - Note: this was my mistake `$SolutionDir()$/KeyGen.bat` works, but `$SolutionDir()$\KeyGen.bat` fails.  I will add a note that `\` is not accepted in paths. Maybe something for the schema.

    
**To Reproduce**

```
C:\Test\Blank4>cbuild Blank4.csolution.yml --context-set
C:/Test/Blank4/Project/Project.cproject.yml:22:11 - warning csolution: path 'keyfile.txt' was not found
+-----------------------------------------------------
(1/1) Building context: "Project.Debug+ADuCM320-Board"
Building CMake target 'Project.Debug+ADuCM320-Board'
[1/2] Building C object CMakeFiles/Group_Source_Files.dir/C_/Test/Blank4/Project/main.o
[2/2] Linking C executable C:\Test\Blank4\out\Project\ADuCM320-Board\Debug\Project.axf
Program Size: Code=476 RO-data=316 RW-data=4 ZI-data=2060  

C:\Test\Blank4\tmp>ECHO C:\Test\Blank4\KeyGen.bat C:/Test/Blank4/.KeyGen.bat KeyGen 
C:\Test\Blank4\KeyGen.bat C:/Test/Blank4/.KeyGen.bat KeyGen
+----------------------
Check all CMake targets
Building CMake target 'Project.Debug+ADuCM320-Board'
[1/2] Building C object CMakeFiles/Group_Source_Files.dir/C_/Test/Blank4/Project/main.o
[2/2] Linking C executable C:\Test\Blank4\out\Project\ADuCM320-Board\Debug\Project.axf
Program Size: Code=476 RO-data=316 RW-data=4 ZI-data=2060  

C:\Test\Blank4\tmp>ECHO C:\Test\Blank4\KeyGen.bat C:/Test/Blank4/.KeyGen.bat KeyGen 
C:\Test\Blank4\KeyGen.bat C:/Test/Blank4/.KeyGen.bat KeyGen
+------------------------------------------------------------
Build summary: 1 succeeded, 0 failed - Time Elapsed: 00:00:00
+============================================================

C:\Test\Blank4>cbuild Blank4.csolution.yml --context Project.Debug+ADuCM320-Board
C:/Test/Blank4/Project/Project.cproject.yml:22:11 - warning csolution: path 'keyfile.txt' was not found
C:/Test/Blank4/Project/Project.cproject.yml:22:11 - warning csolution: path 'keyfile.txt' was not found
+-----------------------------------------------------
(1/1) Building context: "Project.Debug+ADuCM320-Board"
Building CMake target 'Project.Debug+ADuCM320-Board'
[1/2] Building C object CMakeFiles/Group_Source_Files.dir/C_/Test/Blank4/Project/main.o
[2/2] Linking C executable C:\Test\Blank4\out\Project\ADuCM320-Board\Debug\Project.axf
Program Size: Code=476 RO-data=316 RW-data=4 ZI-data=2060

C:\Test\Blank4\tmp>ECHO C:\Test\Blank4\KeyGen.bat C:/Test/Blank4/.KeyGen.bat KeyGen
C:\Test\Blank4\KeyGen.bat C:/Test/Blank4/.KeyGen.bat KeyGen
+------------------------------------------------------------
Build summary: 1 succeeded, 0 failed - Time Elapsed: 00:00:00
+============================================================
```

**Environment (please complete the following information):**

- build: Build Invocation v2.5.0-17-g40fe18b
- OS: Windows

**Comment by brondani** [comment]
> At csolution.yml level an execute: node is only run when cbuild without --context is used. It works with --context-set even when this file specifies just the same --context.

This has been already discussed and it is intended behavior.
When `--context` is specified, only steps that are needed to **build** that context are triggered.
`executes` that go beyond the **build** of a context are triggered only when building the **solution** without a specific `--context` option (context-set can be used in this case).
To check such `post-build` steps the CMake target `all` is currently called.

> It is unclear which CMake targets are executed when.

In verbose mode the `execute` description is printed by CMake along side the progress indication when it's triggered.
Note that `executes` in *.cproject.yml are context-iterated, for this reason they have the context name prepended to it.
For example for the `execute: GenKeys`:
```
[1/6] Project.Debug+AVH-GenKeys
FAILED: CMakeFiles/Project.Debug+AVH-GenKeys D:/tmp/Blank4/Blank4/tmp/CMakeFiles/Project.Debug+AVH-GenKeys 
```

> For --context-set: It appears that ${CMAKE_COMMAND} -E touch C:/Test/Blank4/Project/main.c" is executed twice, or at least it triggers 2 times the project build.

This is a known side effect of steps with `always` attribute and additionally calling `CMake --target all` for triggering post-build steps.
A possible fix, at least for context-level post-builds, is proposed and now tracked in https://github.com/Open-CMSIS-Pack/cbuild2cmake/issues/185

**Comment by ReinhardKeil** [comment]
Behavior is no covered in documentation.  Hence I remove the "bug" and qualify it as enhancement.

**Comment by ReinhardKeil** [comment]
closing this as it is as it is cover https://github.com/Open-CMSIS-Pack/cbuild2cmake/issues/185
