### ISSUE TITLE
Don't issue an error when same `component:` is defined in *.clayer.yml and *.cproject.yml

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1766]
**The Problem To Be Solved**

Defining the same component in *.clayer.yml and *.cproject.yml creates in the moment this error:

```
error csolution: conflict: component 'CMSIS:CORE' is declared multiple times
```

**Suggest A Solution**

I suggest that this should be tolerated. Layers should be reusable across projects and it is not really an error when the same component is required by the layer and the project.

> **Note:** this is more complex. Components with configuration files cannot work that way, as otherwise the tool does not know which config files to use.

**Comment by jkrech** [comment]
Is it possible to express this through `consumes` and `provides` and make it either located in the clayer or the cproject?

**Comment by ReinhardKeil** [comment]
This issue is about flexibility for reusing layers across various projects. We should discuss this.
