### ISSUE TITLE
csolution convert adds `*.base` configuration files to RTE folder

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1768]
**Describe the bug**

When a `*.base` file is missing in the RTE folder the `csolution convert` without further options adds the `*.base` file of the current software pack. As the project might have been used an older version of the pack (with an older version of the `*.base` file, this might create incorrect information.

**To Reproduce**

Delete the `*.base` file of a RTE configuration file and run `csolution convert`.

**Expected behavior**

The missing `*.base` file should be reported as error as proposed under #1694 

This relates to #1484 

**Environment:**

- csolution: 2.5.0+p43-gca002acf
- OS: Windows

**Comment by brondani** [comment]
Please note, contrary to `cbuild`, `csolution` uses `--update-rte` by default.
After removing the base file you should call csolution with `--no-update-rte` to get the warning precisely as proposed in https://github.com/Open-CMSIS-Pack/devtools/issues/1694
```
$ csolution convert USB_Device.csolution.yml --no-update-rte
warning csolution: file 'D:/examples/USBD/HID/RTE/USB/USB_Debug.h.base' not found; base version unknown
```

The copy of the base file when using `--update-rte` was already discussed in the past, please see https://github.com/Open-CMSIS-Pack/devtools/issues/773

**Comment by jkrech** [comment]
The question for me remains, whether or not the `--udpate-rte` should have created the `*.base` file.
Would it be okay to copy the `*.base` configuration file if it is not present and the configuration file that is present is identical with the default config file located in the selected pack?

**Comment by ReinhardKeil** [comment]
I believe the current behavior is OK. We should just enable that cbuild setup outputs warning messages (#1767).
