### ISSUE TITLE
Add in `*.cbuild-idx.yml` under `cbuilds:` a new list `packs-unused:`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1771]
**The Problem To Be Solved**

Over time a solution may add packs that are no longer required (previously used components are removed).
Identifying such packs is not trivial.

**Suggest A Solution**
Add in the `*.cbuild-idx.yml` file under `cbuilds:` a new list `packs-unused:`. This is similar to `packs-missing:` that is currently already available.

**Comment by soumeh01** [comment]
@ReinhardKeil 
I need some clarification on this. From my understanding, the goal is to identify and remove redundant packs that aren't used across the entire solution. The key point to note is that, currently, only the selected contexts are being processed. A pack flagged as unused in one context may actually be in use by another context that isn't selected.

To get a comprehensive list of packs unused throughout the solution, we would need to process (may be new command/mechanism) all contexts to determine which packs are not used anywhere. This raises a couple of considerations:

1. Processing all contexts could be time-consuming, especially for solutions with a large number of contexts.
2. When exactly should this mechanism/command be triggered?

**Comment by ReinhardKeil** [comment]
Let's discuss in the next meeting.  We have also other scenarios that need work: upgrade of packs.
