### ISSUE TITLE
cbuild disables schema check by default

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1777]
**The Problem To Be Solved**

cbuild has schema check disabled by default.  User errors (such as blanks in built-type names) are therefore not flagged.

**Suggest A Solution**

Consider to change the default to "schema check enabled".

See also #1767

**Comment by jkrech** [comment]
Review the purpose of the tools.
Initially we were separating `solution configuration` = csolution from `solution build` = cbuild.
With the introduction of `cbuild setup` an alternative to csolution was introduced.
Maybe `cbuild setup` should do a schema check but not `cbuild`?

**Comment by ReinhardKeil** [comment]
My proposal is schema check is enabled by default.

**Comment by jkrech** [comment]
Add schema check to all invocations by default.
