### ISSUE TITLE
csolution tool will fail to expand a generator list of variables ($P/#P/$G...) if a project absolute path containing a space is used

### ISSUE THREAD

**Issue by BadreddineBJAST** [Open-CMSIS-Pack/devtools#1783]
**Describe the bug**
If a csolution software project is created under a path with a space (eg: c:\My Folder Name With Space\my_app_project), then the current expanded project absolute path containing a space will cause unhandled exceptions `regarding generators variables expansion`

`pdsc generators section`   
```
 <generator id="genId">
            <description>generator description</description>
            <exe>
                <command host="win">gen.bat</command>
                <command host="linux">gen.sh</command>
                <argument>$S</argument> ==> will cause an issue if the CMSIS Pack Root path contains a space
                <argument>$D</argument> ==>issue if a device name contains a space
                <argument>$P</argument> ==> issue if the project path contains a space (path segmented)
                <argument>#P</argument> ==> issue if the project path contains a space (path segmented)
                <argument>$G</argument> ==> issue if the project path contains a space (path segmented)
                <argument mode="dry-run">--dry-run</argument>
            </exe>
            <gpdsc name="$P/vendor.name.gpdsc"/>
        </generator>
```
`generators variables` that should be correctly handled event if the current project path contains a space   
```
$P | PATH to current project
#P | PATH and name of the current project
$G | Absolute PATH to the generator input file describing the project and component context.
```

**How To Reproduce**

1. create an open cmsis project under a path with a space` (e.g: c:\My Folder Name With Space\my_app_project.csolution.yml)`
2. `a testpack with a componentA` that uses the following `generator `description

```
  <generator id="genId">
            <description>generator description</description>
            <exe>
                <command host="win">gen.bat</command>
                <command host="linux">gen.sh</command>
                <argument>$S</argument> 
                <argument>$D</argument> 
                <argument>$P</argument> 
                <argument>#P</argument>
                <argument>$G</argument> 
                <argument mode="dry-run">--dry-run</argument>
            </exe>
            <gpdsc name="$P/vendor.name.gpdsc"/>
   </generator>
```
3. the `<exe>gen.sh</exe>` could be a simple shell script to log the list of expanded generator variables
```
#!/bin/bash
echo "Device Description" $1
echo "Device Name" $2
echo "Project Path" $3
echo "Project CPRJ Path and Name" $4
echo "Generator Input File Absolute Path" $5
```

4. execute the `csolution run command: csolution run -g "genid" -s *.csolution.yml -c "context"`
``
Observed output example:

```
$ csolution run -g "GEN-1" -s app_3.csolution.yml -c "app_3_SW.debug_GCC+B-U585I-IOT02A"
C:/CS/MX-Projects/My App Project/app_3/app_3_SW/app_3_SW.cproject.yml:8:3 - warning csolution: key 'output-dirs' was not recognized
C:/CS/MX-Projects/My App Project/app_3/app_3_SW/build/debug_GCC/app_3_SW.debug_GCC+B-U585I-IOT02A.cbuild-gen.yml - info csolution: file is already up-to-date
info csolution: generator 'GEN-1' for context 'app_3_SW.debug_GCC+B-U585I-IOT02A' reported:

Device Description C:/Users/benjemab/AppData/Local/Cube/packs/STMicroelectronics/stm32u5xx_dfp/2.0.0-alpha.11.0/
Device Name STM32U585AII6Q
Project Path C:/CS/MX-Projects/My
Project CPRJ Path and Name
Generator Input File Absolute Path
```

**Expected behavior**
`**csolution tool should correctly expand all generators variables even if the current project absolute path contains a space**`
 
Today, the only workaround to bypass this issue is to  `double quote` all variables in the generators PDSC tag like this

```
<generators>
        <generator id="genId">
            <description>genId generator</description>
            <exe>
                <command host="win">gen.bat</command>
                <command host="linux">gen.sh</command>
                <argument>\"$S\"</argument>
                <argument>\"$D\"</argument>
                <argument>\"$P\"</argument>
                <argument>\"#P\"</argument>
                <argument>\"$G\"</argument>
            </exe>
            <gpdsc name="$P/vendor.name.gpdsc"/>
        </generator>
    </generators>
```

**Environment (please complete the following information):**

- [tool or library]: csolution v2.4.0)
- Version: [v2.4.0]
- OS: [windows]

**Additional context**

**Comment by jkrech** [comment]
Critical bug raised by ST - consider for 2.6.1 ?

**Comment by BadreddineBJAST** [comment]
Hi @jkrech @brondani, after further analysis and investigation applied with @Torbjorn-Svensson using internal generators, it seems that arguments expansion is well handled in the csolution tool under windows (using a .bat script). the issue comes from handling arguments using the generic operator %*, this will be expanded after when redirecting it to a bash script (errors in path segmentation.
This will be considered as an ST bug and will be corrected in our tools leveraging the generator concept, so we could cancel this false Positive.
thanks and regards
