### ISSUE TITLE
[projmgr] [buildmgr]  Opportunity to introduce toolchain-independent configuration using the most common generic configurations

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#179]
Discussion initiated if https://github.com/Open-CMSIS-Pack/devtools/issues/120

https://github.com/Open-CMSIS-Pack/devtools/issues/120#issuecomment-1050612457
https://github.com/Open-CMSIS-Pack/devtools/issues/120#issuecomment-1050634268
https://github.com/Open-CMSIS-Pack/devtools/issues/120#issuecomment-1055457730

Sounds good to me to get dedicated issue to comment / amend on.

Discussion is about following yml schema contributions: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json
>    "OptimizeType": {
      "enum": [ "max", "size", "speed", "debug" ],
      "description": "Generic optimize levels (max, size, speed, debug) for code generation."
    },
    "DebugType": {
      "enum": [ "on", "off" ],
      "description": "Generic control for the generation of debug information (on, off)."
    },
    "WarningsType": {
      "enum": [ "no", "all", "Misra", "AC5-like" ],
      "description": "Control warnings (no, all, Misra, AC5-like)."
    },

**Comment by ReinhardKeil** [comment]
The is inline with proposal #315

**Comment by tarek-bochkati** [comment]
after the translation controls options addition (ie. optimize, debug, warnings),
I have started supporting them into `projmgr` and `buildmgr`
while doing that I had some notes which I need to share with you:
* `WarningsType` enum `AC5-like` is only valid for AC6 compiler,
   thus I suggest either to remove it from the standart or add a mention in the documentation saying it's for AC6 only
* `OptimizeType`
  * I can agree that `debug` means the lowed optimization possible + plus adding more debug info into the generate ELF file. 
    thus I'm wondering if it is worth replacing it by `none` and we can use the debug options to add debug information
    ```
    if optimize=none
        if debug=on
            use -Og
        else
            use -O0
        endif
    endif
    ```
  * `max` is not clear for me:
    * for AC6 it should be linked to LTO: but is it `-Omin` (minimal size) or `-Omax` (best performance)
    * what about AC5 does it implies using `Cross-Module Optimization` ?
      and the same question as for AC6, is it using `-Ospace -O3` or `-Otime -O3`
    * IAR does not have equivalent for `-Omax` optimization,
      but it does have max performance aka `-Ohs --no_size_constraints`
    * so I can retain the question does this `max` optimization targets size or performance ?
  * current enumeration values are `debug`, `size`, `speed` and `max`
  Comparing these values against to possible compilers optimization options,
  I'm wondering if it is worth adding `low`, `medium` and `high` values mirroring respectively `-O1`, `-O2` and `-O3`
* **options precedence**: options could come from csolution/cproject and also from build-type/target-type
  * while implementing #328 I avoided to do silent override of options, but the options merger should be discussed and implemented.

**Comment by VGRSTM** [comment]
Despite mixed feeling about myself because pro & cons I would promote possibly another way to progress here. Feel free to consider or not ... just a proposal trying to unlock this issue.

First let's come back to pro & cons to my point of view per my understanding:
- Pro: would be nice to get if basic / common projects some compiler agnostic project (*.yml) files. Such helps portability from one vendor to another
- Cons: end user is not exposed explicitly to toolchain setups ... stuff is working Thanks some kind of back magic (i.e. toolchain .cmake config files) he cannot act on

Such said my thinking would be rather to fight finding some commonalities across various toolchains, let's push black magic concept then.  Instead promoting `OptimizeType`, `DebugType`, `WarningType`, `LanguageType`, ....  let's promote only `ProfileType`. 
>"ProfileType": {
"enum": [ "debug", "release", "debug_verbose", "release_targetSpeed", "release_targetSize" ],
"description": "Generic target profiles abstracting various toolchain common setups"
},

**Comment by ReinhardKeil** [comment]
no further feedback - hence I'm closing it as it is covered in the tools.  Raise specific issues on perhaps missing features.
