### ISSUE TITLE
Document structure of CMSIS_PACK_ROOT folder and the file usage

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1806]
**The Problem To Be Solved**

The files and the overall structure of the CMSIS_PACK_ROOT folder needs better documentation.

It is also unclear when and how the files are used.  Specifically, there is a need to specify how cpackget and off-line installers (like MDK PackInstaller) are using these files. Documentation should cover therefore:
- how are the different tools using the files in CMSIS_PACK_ROOT.

Going forward, the proposal is to use web services.  This should remove the need to keep local copies of each `*.pdcs` file in the `.web` folder. I'm not suggesting to drop this now, but over time.

This issue relates to https://github.com/Open-CMSIS-Pack/cpackget/issues/357 + https://github.com/Open-CMSIS-Pack/cpackget/issues/355

**Comment by jkrech** [comment]
There is this wiki page:
https://github.com/Open-CMSIS-Pack/devtools/wiki/The-CMSIS-PACK-Root-Directory
