### ISSUE TITLE
Clean does not work for multitarget projects

### ISSUE THREAD

**Issue by KimmoVaisanen-AlifSemi** [Open-CMSIS-Pack/devtools#1809]
**Describe the bug**
cmsis-toolbox 2.6.0/2.6.1 fails to clean multitarget/compiler project.

**To Reproduce**

1. Clone https://github.com/alifsemi/alif_vscode-template
2. install submodules (git submodule update --init)
3. Open project with VSCode
4. Update cmsis-toolbox to version 2.6.1 in vcpkg-configuration.json
5. Run Task First time pack installation
6. Build the project from CMSIS menu
7. Clean project

**Expected behavior**
Project is cleaned

**Observed behavior**
- if you have only built for one target (in our example case, e.g. to HE), you get a bunch of errors complaining about missing RTE files for the target you didn't build.
- `out` and `tmp` directories are not cleaned.

**Environment (please complete the following information):**
- CSolution extension v1.40.0, cmsis-toolbox 2.6.0 or 2.6.1
- OS: Ubuntu 22.04

**Additional context**
This works ok with cmsis-toolbox v2.4.0

**Comment by ReinhardKeil** [comment]
Thanks for this example.  

I have not installed the pack yet, and get 
```
cbuild setup c:\Test\alif_vscode-template\alif.csolution.yaml --context-set --context blinky.debug+HE --context hello.debug+HE --context hello_rtt.debug+HE --packs --update-rte
error cbuild: invalid file argument
```

**Comment by KimmoVaisanen-AlifSemi** [comment]
Yes, sorry, forgot to mention that toolbox has to be updated manually. We haven't pushed 2.6.1 yet until we get these other issues resolved.

**Comment by ReinhardKeil** [comment]
NOTE: "Run Task First time pack installation" does not work on Windows.

This should do the job on all OS systems (provided that the pack is public).  And the new vscode extension executes this anyway with the default configuration.

```cbuild setup alif.csolution.yaml --packs
```

I agree with you that `--clean` should not be so sensitive to missing files.  Hence we leave this ticket open.

However, the RTE files should be part of the repo, see here https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#reproducible-builds

You might be interested in our device specific templates:
https://github.com/Open-CMSIS-Pack/STM32F4xx_DFP/blob/main/Keil.STM32F4xx_DFP.pdsc#L3789

It allows you to start new projects with a defined setup.  Use the New Project feature in VSCode.

**Comment by ReinhardKeil** [comment]
Yes, before it called `cbuild setup --update-rte`, but the consequence is that just opening a project modifies files. We have removed therefore this feature.  

RTE files contain configuration settings.  When you are only using defaults then `--update-rte` does the job, but we would like to avoid that users loose config settings.

**Comment by ReinhardKeil** [comment]
I suggest to implement clean with the following behaviour:

  - delete all files in the current configured [`tmpdir:`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#output-dirs)
  - delete all files in the current configured [`outdir:`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#output-dirs) for the context-set. This means selectively only removing the files of the current selected context list.
  
Discussion point: should this be more aggressive and delete all files in `outdir:`?

**Comment by brondani** [comment]
The fix was provided in https://github.com/Open-CMSIS-Pack/cbuild/pull/343.
@KimmoVaisanen-AlifSemi Can you please confirm it by testing a CMSIS-Toolbox [nightly build](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/actions/workflows/nightly.yml)? (e.g. [artifacts 05.12.2024](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/actions/runs/12172109235#artifacts)).

**Comment by jkrech** [comment]
I have been using the nightly build from 2024-12-05 prior to clean I have removed a config file from RTE directory of a project not in the context-set. On clean the this project no longer gets checked but instead the clean succeeds.
