### ISSUE TITLE
cbuild setup with `--packs` option should install required packs

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1819]
**Describe the bug**

When a BSP is loaded that requests a DFP with a certain version, the command `cbuild setup` with `--packs` option should install the required pack.

**To Reproduce**

Install these packs: 
 - `NXP::MCXN947_DFP@17.0.0`
 - https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/releases/tag/v19.1.0-dev

Use this project: [Simple_Device_project.zip](https://github.com/user-attachments/files/17460091/Simple_Device_project.zip)

Execute cbuild setup, it should show the following errors:
```
cbuild setup Simple.csolution.yml --packs --context-set
error csolution: no component was found with identifier 'Device:Config Tools:Init'
error csolution: processing context 'Simple.Debug+MCXN947VDF' failed
```

**Expected behavior**

cbuild downloads the required DFP pack 19.0.0, see:
https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/blob/main/NXP.FRDM-MCXN947_BSP.pdsc#L20

Note: cpackget add installs required packs, but I have used the uVision PackInstaller with a click on the pack file.

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.6.1
- OS: Windows

**Comment by jkrech** [comment]
Note that `cbuild` is intentionally calling `cpackget --no-dependencies`, fully relying on `csolution` to evaluate dependencies, in order to avoid that unnecessary pack versions get installed. Some packs require other packs only under certain circumstances, however all used pack versions required by a CMSIS solution project are known by csolution.

**Comment by ReinhardKeil** [comment]
The call with `--no-dependencies` was implemented as some packs had a long requirement list and forced in this way the installation of many unrelated packs.

**This is what we got:**

MCXN947_BSP requires [DFP 19.0.0 or higher](https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/blob/main/NXP.FRDM-MCXN947_BSP.pdsc#L20) to work.
[Template project contains no pack versions](https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/blob/main/boards/frdmmcxn947/cmsis/templates/Board/Simple/Simple.csolution.yml) which avoids that it needs to be constantly updated. But it lists the right packs (so this requirement list is correct, just versions are missing).

**Potential solution:**

Once the requested packs by the project are loaded, use the requirement list in the PDSC to check if pack versions are matching.
