### ISSUE TITLE
`$Bname$` expansion also contains vendor when specifying the header file in linker `regions:` node

### ISSUE THREAD

**Issue by VladimirUmek** [Open-CMSIS-Pack/devtools#1846]
**Describe the bug**
If vendor name is also specified together with board in target-type (in form vendor::board_name) then the whole specification is used when searching for region header file.

Assume there is a following target-type in a csolution.yml:
```
  target-types:
    - type: MCXN947_core0
      board: NXP::FRDM-MCXN947
      device: NXP::MCXN947VDF:cm33_core0
```
and that the corresponding cproject.yml file contains linker specification:
```
  linker:
    - regions: RTE/Device/$Dname$_$Pname$/regions_$Bname$.h
```
When cbuild is executed the following output can be observed:
```
{...}/RTE/Device/MCXN947VDF_cm33_core0/regions_NXP::FRDM-MCXN947.h - warning csolution: specified regions header was not found
```

**To Reproduce**
Use [DualCore project](https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/DualCore) and add vendor specification to [the board name in HelloWorld.csolution.yml](https://github.com/Open-CMSIS-Pack/csolution-examples/blob/983aabd1dabab63fec1e58853d6a621c28c31926/DualCore/HelloWorld.csolution.yml#L18)

**Environment (please complete the following information):**
- cmsis-toolbox 2.6.1

**Additional context**
The generated regions header file is correctly named as `regions_$Bname$.h` and copied into `RTE/Device/$Dname$_$Pname$/`

**Comment by jkrech** [comment]
Work-around: specifying the `board:` omitting the `vendor::` is expected to work as expected.

**Comment by ReinhardKeil** [comment]
@VladimirUmek thanks for raising this issue.  However, I believe that there should be a central regions header file for this type of projects.

**Comment by brondani** [comment]
@VladimirUmek Can you please confirm the reported issue was fixed? CMSIS-Toolbox nightly builds can be found among the [nightly](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/actions/workflows/nightly.yml) artifacts

**Comment by VladimirUmek** [comment]
The issue is fixed, verified with the example referenced above.
