### ISSUE TITLE
Discuss Consistency of Version Range Specification (PDSC/CPRJ vs. cproject.YML)

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#188]
For consistency reasons and reuse of existing implementation we should consider aligning version range specification in PDSC/CPRJ and cproject.yml

PDSC/CPRJ:
```
@1.2.3         larger or equal
@1.2.3:1.2.3   strictly equal (fixed version)
@1.2.3:1.3.0   any version in the rage from 1.2.3 till 1.2.99
```

cproject.yml:
```
- component: ARM::CMSIS:CORE           # CMSIS Core component from vendor ARM (any version)
- component: ARM::CMSIS:CORE@5.5.0     # CMSIS Core component from vendor ARM (with version 5.5.0)
- component: ARM::CMSIS:CORE@>=5.5.0   # CMSIS Core component from vendor ARM (with version 5.5.0 or higher)
- component: ARM::CMSIS:CORE@~=5.5.0  # CMSIS Core component from vendor ARM (version compatible with 5.5.0)
```

use '~=' to indicate compatible version based on semantic versioning (= major version unchanged).

**Comment by jkrech** [comment]
In python's installer the update to latest compatible version is specified here:
https://peps.python.org/pep-0440/#compatible-release using the syntax "~="
I am extending above's proposal to include this syntax to specify the upper limit based on semantic versioning.

**Comment by ReinhardKeil** [comment]
@jkrech is this still open.  See here https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md

Yes it deserves more examples, but fundamentally it is covered.  Not sure if we should align with the syntax of the *.CPRJ file as I find it harder to use.  Semantic versioning rules are somewhat inherent and perhaps we need to improve documentation further.

`@~1.2.3` should indicate that version 1.2.3 ... <1.3.0 are working.
`@=1.2.3` should indicate that exactly 1.2.3 is used.

**Comment by jkrech** [comment]
see version specification here: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#pack-name-conventions
