### ISSUE TITLE
Question on installer script

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#192]
Hi

Maybe this part:
https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/buildmgr/cbuildgen/installer
is deprecated, replaced by
https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/toolbox/installer
?

About default_path setting, maybe it could help user if script can detect  local settings:
ex:     compiler6_default_path=$(dirname "$(which armclang)")

**Comment by ReinhardKeil** [comment]
I reviewed the current install script and found it a bit overwhelming. As background: we should work towards installers that are domain specific, for example https://github.com/microsoft/vcpkg

As we don't know today, how exactly this foundation tools will get integrated into third-party offerings, I would suggest a more pragmatic way for the setup:

 - provide ZIP files for Windows, Linux, Mac   (maybe there is a more clever way)
 - explain for each foundation tool document:
     - requirements (assumptions to the operating system).  Most tools are stand-alone, but some may require others i.e. Python 
     - environment variables used (or other means of communication with the Host OS, i.e. registry)
     - usage: command-line parameters

I believe that the compiler path for example is only relevant for `CMake`, but not for `cbuildgen` or any other tool.

**Comment by jkrech** [comment]
I just want to point out, that you can already today simply extract the content into a folder by running:

```
$ cmsis-toolbox.sh -x ./dumpdir
```
Note help: `./cmsis-toolbox.sh -h`

But I do agree that we need to document the setup in all detail.

You are correct that the compiler path is only relevant when running CMake -> etc/AC6.6.16.0.cmake

**Comment by ReinhardKeil** [comment]
cool - exactly what I wanted.
