### ISSUE TITLE
[csolution] how to specify debug interface ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#195]
Hi,

I do not think it has been specified yet but is it possible to specify the debug interface to be used with the csolution ?

My use-case:
csolution-->cprj-->uvision : here I need to select ST-Link

I would like that the ST-Link choice is made when defining application project.
I agree this is not build.

**Comment by jkrech** [comment]
Hi Fred,

as much as I see the value in making the above flow completely "automatic", at this point we focus on build and pretty much ignore flash programming and debug, however the Specification of CMSIS-Pack has provisions to specify the mounted debug adapter on a board, which seems like a useful and obvious default selection. During import of a project this information shall be used by an IDE to configure the right debug adapter.

**Comment by ReinhardKeil** [comment]
@fred-r
