### ISSUE TITLE
Build error: No such file or directory - <filesystem>

### ISSUE THREAD

**Issue by mingyangSunshine** [Open-CMSIS-Pack/devtools#21]
When I am trying to build the tool, an error is reported:
```
In file included from /home/minsun01/git/devtools/libs/rtefsutils/src/RteFsUtils.cpp:15:0:
/home/minsun01/git/devtools/libs/rtefsutils/include/RteFsUtils.h:23:12: fatal error: filesystem: No such file or directory
   #include <filesystem>
            ^~~~~~~~~~~~
compilation terminated.
```
The cmake configuration process is finished with no error, but the build process broke down.
These are the information:
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building for: Linux
-- Found PythonInterp: /usr/bin/python (found version "3.6.9")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/minsun01/git/devtools/build
```

Could you give me some guide?

**Comment by mingyangSunshine** [comment]
Hi, I tried it on another machine whose GNU Compiler version is 8.3.0, it succeeded.
So I guess it is maybe related to the Compiler version.

> GNU Compiler (minimum recommended version 5.4)

It might need an update.

**Comment by JonatanAntoni** [comment]
Hi @mingyangSunshine,

Thanks for reporting this. You may have recognized we are using `std::filesystem` from `<filesystem>`. Support for this has been added in GCC 8. In your case GCC 7.5 is being used which doesn't have the required support.

Please try to update your build environment.

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
We are going to fix that in the documentation.

**Comment by JonatanAntoni** [comment]
@mingyangSunshine,

May I kindly ask you to give #27 a review, please?
This change to the README should clarify your issue.

Thanks,
Jonatan

**Comment by JacobBarthelmeh** [comment]
Ran into this also with default GCC (7.5.0) on Ubuntu 18. Was trying the approach of just building it, hitting cmake and diving in before reading the docs. Quickly moved on to trying a newer version of GCC but it would be nice to have a warning on GCC version printed out during compile. Something like a check on __GNUC__ macro in the code or a check in the CMakeLists.txt.
