### ISSUE TITLE
[csolution] project.optimize ad .debug seems to have no impact on cprj ?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#214]
Our cproject.yml files started with:

```
project:
  optimize: size                   # Code optimization: emphasis code size
  debug: on                        # Enable debug symbols
```

I would expect some -O3 and -g options in cflags of generated cprj files, but I couldn't see them...

Thx

@fred-r

**Comment by brondani** [comment]
@jeromecoutant Compiler abstraction options were not yet implemented.
There is currently an open issue to fine tune these options, if you have suggestions feel free to comment there: https://github.com/Open-CMSIS-Pack/devtools/issues/179

**Comment by jeromecoutant** [comment]
Agree
Thx @VGRSTM :-)

**Comment by tarek-bochkati** [comment]
@jeromecoutant i'm currently working on this
Please check #328
