### ISSUE TITLE
[csolution] enhance debug logs

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#215]
When converting a yml to cprj, it would be great to have additional logs:

- The cprj indicates packs versions => the logs may show where the packs are taken from (physically on the disk, useful when we have several CMSIS_PACK_ROOT and switching between them

- gpdsc => when the gpdsc add files in a component which is not present (wrong name or version) in the project we should be warned

**Comment by ReinhardKeil** [comment]
I consider this as duplicate and suggest to close that issue.

Most items should be covered by https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md

See also https://github.com/Open-CMSIS-Pack/devtools/issues/142 (proposed command "csolution list setup") which provides information about the configuration.

**Comment by jkrech** [comment]
@fred-r could you please check whether this issue can be closed in light of https://github.com/Open-CMSIS-Pack/devtools/issues/142 ?

**Comment by ReinhardKeil** [comment]
Closing this issue as considered as duplicate
