### ISSUE TITLE
Not clear about how to set `packchk`

### ISSUE THREAD

**Issue by mingyangSunshine** [Open-CMSIS-Pack/devtools#22]
Hi, 

> For validating and compressing pack files, the packchk and 7z utilities shall be in the PATH:
> packchk: https://github.com/ARM-software/CMSIS_5/tree/master/CMSIS/Utilities/

The instruction of adding packchk is not quite clear.
I copied the file `PackChk` to my current directory from "https://github.com/ARM-software/CMSIS_5/tree/master/CMSIS/Utilities/Linux64", and ran `./packgen manifest.yml -o output`, the output is:
```
sh: 1: packchk: not found
packgen error: packchk failed
```

files under current directory:
```
├── ARM.TestPack.pdsc
├── CMakeLists.txt
├── lib1
│   ├── api
│   │   └── interface.h
│   ├── CMakeLists.txt
│   ├── config
│   │   └── config.h
│   ├── inc
│   │   └── lib1.h
│   └── src
│       └── lib1.cpp
├── lib2
│   ├── CMakeLists.txt
│   ├── inc
│   │   └── lib2.h
│   └── src
│       └── lib2.cpp
├── lib3
│   ├── CMakeLists.txt
│   ├── inc
│   │   └── lib3.h
│   └── src
│       └── lib3.cpp
├── lib4
│   ├── CMakeLists.txt
│   ├── inc
│   │   └── lib4.h
│   └── src
│       └── lib4.cpp
├── lib5
│   ├── CMakeLists.txt
│   ├── inc
│   │   └── lib5.h
│   └── src
│       └── lib5.cpp
├── LICENSE
├── manifest.yml
├── PackChk
└── packgen
```

**Comment by brondani** [comment]
Hi Mingyang,

`PATH` mentioned in the documentation means the [PATH system variable](https://en.wikipedia.org/wiki/PATH_(variable)). You don't need to copy the utility to the project folder, just add its folder to the `PATH` variable.
If you are building `packgen` from the source code, be careful with the `PackChk` capitalization. Recently we were doing changes that may impact it, see PR #26.
In alternative you can run `packgen` with the option `--nocheck` to skip the pack check step.

Best regards
Daniel

**Comment by mingyangSunshine** [comment]
Hi, @brondani,

Thanks for your reply.

> PATH mentioned in the documentation means the PATH system variable. You don't need to copy the utility to the project folder, just add its folder to the PATH variable.

Do you mean the `CMSIS_5/CMSIS/Utilities` or the `CMSIS_5/CMSIS/Utilities/Linux64`, or both of them added to system PATH?

**Comment by mingyangSunshine** [comment]
Thank you all.
