### ISSUE TITLE
[cbuildgen] Add C and C++ linker flags support

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#224]
As part of [CPRJ.xsd](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/cbuildgen/config/CPRJ.xsd) we have 
>  <xs:complexType name="TargetType">
    <xs:choice maxOccurs="unbounded">
      <\!-- Build options -->
      <xs:element name="output"    type="OutputType" />
      <\!-- Linker command-line -->
      <xs:element name="ldflags"   type="LinkerFlagsType" />
      <\!-- C-Compiler command-line -->
      <xs:element name="cflags"    type="ToolOptionType" />
      <\!-- C++ Compiler command-line -->
      <xs:element name="cxxflags"  type="ToolOptionType" />
      <\!-- Archiver command-line -->
      <xs:element name="arflags"  type="ToolOptionType" />
      <\!-- Assembler command-line -->
      <xs:element name="asflags"   type="AsmOptionType" />
      <\!-- Include paths -->
      <xs:element name="includes"  type="xs:string" minOccurs="0" />
      <\!-- Preprocessing definitions -->
      <xs:element name="defines"   type="xs:string" minOccurs="0" />
    </xs:choice>
    
C compiler flags are addressed Thanks `cflags` element.
C++ compiler flags are addressed Thanks `cxxflags` element.
Sounds weird to get only `ldflags` supporting both C **and** C++ ..

Would push to introduce `ldxxflags` element as addon to `ldflags`

**Comment by brondani** [comment]
@VGRSTM Please note `ldflags` are not specific for one or another language.
Regardless of having mixed code, a single target will likely require a single linker.
Why would you use multiple sets of `ldflags` in a single `CPRJ`?

**Comment by VGRSTM** [comment]
Linker flags may vary if C or C++ project at least if GCC, let's think about built-in libraries.
- C++ :  -Wl,--start-group -lc -lm -lstdc++ -lsupc++ -Wl,--end-group
- C:  -Wl,--start-group -lc -lm -Wl,--end-group

**Comment by jkrech** [comment]
@VGRSTM I do agree that the linker flags will definitely depend on whether the objects you try to link are C++ or C. 
However in the scope of a CPRJ file there is only a single invocation of the linker and it can be either be linking with one or the other set of flags depending on the objects that get linked.
So it is not yet clear to me what should happen if a cprj files specifies both ldflags and ldxxflags.
When you write "addon to ldflags", does this mean in the above example:
```
ldflags = -Wl,--start-group -lc -lm $ldxxflags -Wl,--endgroup
with $ldxxflags = -lstdc++ -lsupc++ ?
```

**Comment by VGRSTM** [comment]
@jkrech 
Like we have already:
> \<cflags\> .... \</cflags\>
> \<cxxflags\> .... \</cxxflags\>

I was thinking to:
> \<ldflags\> .... \</ldflags\>
> \<ldxxflags\> .... \</ldxxflags\>

Up to build system to take into account `ldflags` or `ldxxflags` at link time.

**Comment by jkrech** [comment]
The argument provided by Vincent is that people shall always define/maintain both ldflags and ldxxflags so in case a C++ file or component with C++ file(s) is added, the linker invocation would be switched to using ldxxflags seamlessly.

**Comment by ReinhardKeil** [comment]
This has been added to the documentation under [`misc:`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#misc) with `Link-C` and `Link-CPP`.  

Who owns the implementation?

**Comment by soumeh01** [comment]
Yves Wang <yves.wang@linaro.org> owns the implementation for this.

**Comment by soumeh01** [comment]
As per my understanding, Below are the two proposals I propose

### Proposal 1

- **New project**: Implements both `LINK-C` and `LINK-CPP` flags (_No existing LINK flags_). 
- **Old Projects**: Implements only `LINK` flags. (for backward compatibility)

Pros: Less complex, clear distinction of flags
cons: Common flags need to be repeated in both `LINK-C` & `LINK-CPP`

### Proposal 2:
@yvesll comments: _we should keep LINK option if the user does not want to distinguish linker flags for the C or CPP project_

- **New Projects**: Implements all 3 flags `LINK`, `LINK-C`, and `LINK-CPP` flags. Where `LINK` flag should contain all the common flags shared between C and CPP flags. As a result of which we do not need to duplicate the flags and the final outcome will be additive flags `LINK + LINK-C `or `LINK + LINK-CPP`
- **Old Projects**: Still maintains `LINK` flags.

Pros: The concept will be consistent with existing Compiler flags. Where we have C, CPP and C-CPP flags.
Cons: Flags will be separated in 3 categories.

**Comment by jkrech** [comment]
For backward compatibility we will need to support `LINK`, therefore we always maintain 3 categories.
Since the linker flags are composed from `LINK + LINK-C` or `LINK + LINK-CPP` nothing prevents a user/tool to choose to only actively use:
a) `LINK`
b) `LINK-C` and `LINK-CPP`
or
c) `LINK`, `LINK-C` and `LINK-CPP`

That's why I prefer proposal 2. What are the pitfalls?
