### ISSUE TITLE
[cbuild] helper doesn't work

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#228]
Hi

```
$ cbuild.sh --help
(cbuild.sh): Build Invocation 0.10.5 (C) 2021 ARM
/c/xxx/cmsis-toolbox/bin/cbuild.sh: line 44: pushd: /c/xxx/cmsis-toolbox/bin/../doc/html: No such file or directory
error: pushd /c/xxx/cmsis-toolbox/bin/../doc/html failed
```

Proposition:
In
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/cbuildgen/scripts/cbuild.sh#L76
There is no html in cmsis-toolbox/doc

Then there is no `cbuild.html` but `index.html`

**Comment by brondani** [comment]
@jeromecoutant Thanks for pointing this out. The `cbuild.sh --help` option has been reworked to just print the usage.
Can you please test it with the [CMSIS-Toolbox v0.9.3](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools/toolbox/0.9.3)?

**Comment by jeromecoutant** [comment]
OK for `cbuild.sh --help`

Now doc directory could be removed from cmsis-toolbox ?

**Comment by jkrech** [comment]
The doc folder still contains an index html file linking to the online documentation of the various tools. I would like to keep that even if the cbuild.sh does not open it in the browser.
