### ISSUE TITLE
Please integrate PackChk in CMSIS-Toolbox

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#231]
Request coming from this discussion: #75

**Comment by jeromecoutant** [comment]
@brondani is it planned for next week delivery ?
Thx

**Comment by brondani** [comment]
@jeromecoutant due to the open issue https://github.com/Open-CMSIS-Pack/devtools/issues/110 it is not feasible for the next week delivery, but my colleagues are aware of it and we should unblock it ASAP.
@jkrech @JonatanAntoni

**Comment by brondani** [comment]
@fred-r @jeromecoutant
Please find it in the latest CMSIS-Toolbox and let me know if it works as expected, thanks!
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools/toolbox/0.10.0
