### ISSUE TITLE
[solution] Boards and devices cannot be reliably located

### ISSUE THREAD

**Issue by mark-edgeworth** [Open-CMSIS-Pack/devtools#254]
Background
* Boards and devices are identified by their name which is unique only within the context of a given vendor. 

Problem 
In the csolution and cproject schemas `vendor` is optional. If `vendor` is not defined then it is not possible to retrieve device/board information:
* https://github.com/Open-CMSIS-Pack/devtools/blob/fcb00fa01dce9f88883100ced73699a7ce619a50/tools/projmgr/schemas/common.schema.json#L35
* https://github.com/Open-CMSIS-Pack/devtools/blob/fcb00fa01dce9f88883100ced73699a7ce619a50/tools/projmgr/schemas/common.schema.json#L40

Solution
* Make vendor mandatory when specifying boards or devices

Related
* Stop using compound fields (https://github.com/Open-CMSIS-Pack/devtools/issues/165)

**Comment by jkrech** [comment]
We intentionally specified the YML schema to support "sloppy" information. Which is especially helpful when editing these files manually. At the same time this bears the risk of different results for different environments. Currently we would rely on the generated cprj files as "lock" files to determine the resolution.
Alternatively we could also consider the csolution tool to check a csolution/cproject/clayer for a "fully specified" file content.
I would like to enable both.

**Comment by ReinhardKeil** [comment]
Combined with nailing down the pack versions, the device/board/etc. information should be precise. However I get the concerns from @mark-edgeworth - maybe we need to recommend a clear publish *.yml files process for manually created projects.

**Comment by fred-r** [comment]
I think the lock file can handle this.

Also, we have the possibility in YML format to specify the packs and their paths.

**Comment by ReinhardKeil** [comment]
Closing this issue as it will by address with the `*.cbuild.yml` file.
