### ISSUE TITLE
[solution] specify an include directory together with source files ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#258]
I did not see in the spec a way to specify an include directory when using "files:".
I need to give the list of .c and .h

Can we specify and include directory directly ?

**Comment by jkrech** [comment]
Interesting questions. When looking at PACK.xsd include paths are managed as part of the files section. As far as I can see in the YML format this is a compiler option.
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#add-paths

**Comment by brondani** [comment]
`add-paths` are accepted in several levels, also for files:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#files

**Comment by fred-r** [comment]
great, thanks
