### ISSUE TITLE
Packs required to pass tests are not documented

### ISSUE THREAD

**Issue by Patater** [Open-CMSIS-Pack/devtools#275]
In trying to follow the `README` to build the project and then run tests to verify my build was valid, I ran into a few undocumented requirements. It'd help others get started quicker if we could document the following steps, assuming they are indeed necessary to get tests to pass.

I did the following things not mentioned in the `README.md`:
- I added `CMSIS_PACK_ROOT` to my environment, pointing to `$HOME/.cache/arm/packs`, as this seems to be a default location
- I installed `cpackget` and ran to set up an initial pack root: `cpackget init https://www.keil.com/pack/index.pidx`
- I installed packs that the tests showed an error about being missing.
  - `cpackget -v pack add ARM.CMSIS`
  - `cpackget -v pack add Keil.ARM_Compiler`

Could we add information about these requirements and how to fulfill them to the `Prerequisites` section of `README.md`?

**Comment by brondani** [comment]
Actually the test environment variables to set are in the [README.md - Run Tests section](https://github.com/Open-CMSIS-Pack/devtools#run-tests)
When properly set there should be no need to install packs manually.
We should review the mechanism and make the documentation more evident for new users.

**Comment by Patater** [comment]
> Actually the test environment variables to set are in the [README.md - Run Tests section](https://github.com/Open-CMSIS-Pack/devtools#run-tests) When properly set there should be no need to install packs manually. We should review the mechanism and make the documentation more evident for new users.

Maybe something is wrong with my environment where the automatic installation doesn't work. Is it required to set `CI_PACK_ROOT` if I have `CMSIS_PACK_ROOT` already set? The sentence "Required only when the pack repository/installed toolchains reside in places different from the default values" made me think I did not need to additionally set `CI_PACK_ROOT`.

There is also no mention of packs being automatically installed nor what the prerequisites are to get automatically installed packs to work.

**Comment by ReinhardKeil** [comment]
Is this still open?

**Comment by soumeh01** [comment]
> > Actually the test environment variables to set are in the [README.md - Run Tests section](https://github.com/Open-CMSIS-Pack/devtools#run-tests) When properly set there should be no need to install packs manually. We should review the mechanism and make the documentation more evident for new users.
> 
> Maybe something is wrong with my environment where the automatic installation doesn't work. Is it required to set `CI_PACK_ROOT` if I have `CMSIS_PACK_ROOT` already set? The sentence "Required only when the pack repository/installed toolchains reside in places different from the default values" made me think I did not need to additionally set `CI_PACK_ROOT`.
> 
> There is also no mention of packs being automatically installed nor what the prerequisites are to get automatically installed packs to work.

Yes, for running the tests you need to set the `CI_PACK_ROOT` otherwise the default pack root path ( which in your case is  `${HOME}/.cache/arm/packs`) will be used.
In the scenario, if you have already set `CMSIS_PACK_ROOT`. On running the tests, 'CMSIS_PACK_ROOT' will be overwritten with the `CI_PACK_ROOT` value.

Thanks for pointing out the **automatic installation of packs**. The documentation is updated and the statement can be found [here](https://github.com/Open-CMSIS-Pack/devtools#note)

**Comment by jkrech** [comment]
@Patater can you confirm that this is now properly documented and this issue can be closed?

**Comment by Patater** [comment]
Thanks for adding a line about automatic installation of packs. I'm still not clear if when I make a new pack root for running these tests, if I need to run `cpackget init` beforehand or if that'll get run for me as part of automatically installing the packs.

I still think the documentation around required environment variables could be improved. As someone new to the tool, I don't know what "places different from the default values" means. If we could spell out how the tool would use `CMSIS_PACK_ROOT`, and link to documentation on what `CMSIS_PACK_ROOT` is, that'd be helpful. @soumeh01 your comment above about how fallback works would be a good start: just add a link to documentation for `CMSIS_PACK_ROOT`,  too. Also, if it isn't recommended to use the same location for testing as your ordinary pack root, this should also be mentioned (maybe there are concerns about potentially polluting or breaking your working pack root when running these tests).

**Comment by soumeh01** [comment]
@Patater We have made an effort to simplify the [test documentation](https://github.com/Open-CMSIS-Pack/devtools/pull/563) and provide more details on the environment variables and their default values. Also, we agree that there was some confusion between `CMSIS_PACK_ROOT` & `CI_PACK_ROOT` environment variables. Now only `CMSIS_PACK_ROOT` exists. For your reference, related changes can be found in [PR 563](https://github.com/Open-CMSIS-Pack/devtools/pull/563). Hope this update will be helpful and make things more clear.

**Comment by ReinhardKeil** [comment]
@Patater is there anything open on this https://github.com/Open-CMSIS-Pack/devtools#run-tests
