### ISSUE TITLE
[projmgr] Add support for source type/language specific include paths specification

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#276]
Related to [#28](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/28).

For project definition, include paths can be source type/language specific:
add-paths-asm
add-paths-c
add-paths-cpp

**Comment by jkrech** [comment]
I agree that this level of differentiation is currently not considered.
I guess it would not end there but 
'defines' 
'undefines' 
'del-paths'

would need to be extended as well.
Would the use of 'misc' be acceptable as a workaround for the time being?

**Comment by tcsunhao** [comment]
"misc" is ok for the time being.
Thanks.

**Comment by ReinhardKeil** [comment]
I believe `misc` is an acceptable work-around.  I would suggest to reject for the moment until we understand how widely such extensions are used.

**Comment by jkrech** [comment]
Will be addressed by #607
