### ISSUE TITLE
Paths from local file URIs in pidx files broken on Linux

### ISSUE THREAD

**Issue by ErikLundinSTM** [Open-CMSIS-Pack/devtools#299]
File URIs in pidx files on the format `file://localhost/path/to/pack` incorrectly get converted to `path/to/pack` instead of `/path/to/pack`, i.e. with one forward slash too much removed.

These places seem to be where it happens:
- https://github.com/Open-CMSIS-Pack/devtools/blob/4109314e483328bd6f1b9a9b251b99e6ee67a28e/libs/rtemodel/src/RteKernel.cpp#L329-L332
- https://github.com/Open-CMSIS-Pack/devtools/blob/4109314e483328bd6f1b9a9b251b99e6ee67a28e/libs/rtemodel/src/RteKernel.cpp#L423-L427
- https://github.com/Open-CMSIS-Pack/devtools/blob/4109314e483328bd6f1b9a9b251b99e6ee67a28e/tools/buildmgr/cbuild/src/CbuildProject.cpp#L277-L291

A way to make it work on Linux is to subtract 1 from the length when erasing in order to leave the trailing slash, but unfortunately that breaks it for Windows, where the URIs typically look like `file://localhost/c:/path/to/pack` and the slash has to be removed for it to work.

**Comment by brondani** [comment]
@ErikLundinSTM Please check if the CMSIS-Toolbox 0.10.1 works as you expect:
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools/toolbox/0.10.1
Thanks

**Comment by ErikLundinSTM** [comment]
Taking the URLs from [the Wikipedia article](https://en.wikipedia.org/wiki/File_URI_scheme) as examples, the Unix ones work, but Windows paths don't (e.g. `file://localhost/c:/WINDOWS/clock.avi` --> `/c:/WINDOWS/clock.avi`). I'm not sure if that's in the scope to fix here, but I think that ideally, an algorithm like this should be truly platform independent in the sense that the same input always yields the same output, even if it happens to be run on a machine where the path doesn't match the native style.

**Comment by brondani** [comment]
@ErikLundinSTM
In Unix there is no "drive letter", for example `x:` means a directory called literally `x:`
`/c:/WINDOWS/clock.avi` is a perfectly valid Unix path, being `c:` a valid directory and not a drive letter. How would you undoubtedly say that `file://localhost/c:/WINDOWS/clock.avi` is Windows or Unix? :-)
If the behaviour of a feature is platform dependent the results are also platform dependent.
