### ISSUE TITLE
Using locally referenced packs in build

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#30]
While trying to use a pack that is locally referenced in $CMSIS_PACK_ROOT/.Local/local_repository.pidx there is this error:
```
*** ERROR M800:
  RTE Model reports: Error R821: Required pack not installed
```

Support for locally referenced packs is missing?

**Comment by brondani** [comment]
Hi @slhultgren,
Thanks for reporting this!
Currently local packs are not supported, it will be fixed soon. I let you know as soon as the PR will come in.
Cheers
Daniel

**Comment by brondani** [comment]
Hi @slhultgren,
The support for handling local packs was added in the [PR #33](https://github.com/Open-CMSIS-Pack/devtools/pull/33) and it's already in the main branch.
Please let me know if you can verify it and if it works as expected.
Cheers
Daniel

**Comment by slhultgren** [comment]
Hi @brondani, thanks for the update, I've tested it on my side and seems to be working well, thanks!
