### ISSUE TITLE
*.cprj to *.yaml conversion from existing *.uvprojx project

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#307]
I love the open CMSIS initiative, this is a great development, thank you!

To start migration I'd like to convert an existing and rather complex µVision .uvprojx solution to yaml files that can be parsed by `csolution`. MDK 5.36 can export to *.cprj, but is there any way back to yaml from that?

Thank you very much!

**Comment by ReinhardKeil** [comment]
@jankap not yet, but this will come and is expected in Q3.  We should stabilize the *.yml formats first

**Comment by jankap** [comment]
> @jankap not yet, but this will come and is expected in Q3. We should stabilize the *.yml formats first

Great news, thank you. Fully understand your point :)
