### ISSUE TITLE
[cbuild] build cprj files in subfolder

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#308]
I want to build cprj files that are in a subfolder relative to my sources, i.e.

```
uvision-template
├───inc
├───open-cmsis-pack based
│   └───generated-uv-projects
│       ├───uvision-template.csolution.yml
│       └───uvision-template.Debug+Production-HW
│                └───uvision-template.Debug+Production-HW.cprj
├───src
├───test
```

These commands fail because the main file can't be found:
```
E:\GIT\gitlab\embedded\templates\uvision-template > cbuild '.\open-cmsis-pack based\generated-uv-projects\uvision-template.Debug+Production-HW\uvision-template.Debug+Production-HW.cprj'   
info cbuild: cbuild: Build Invocation 0.9.0 (C) 2022 ARM
(cbuildgen): Build Process Manager 0.11.0 (C) 2022 ARM
M650: Command completed successfully.
(cbuildgen): Build Process Manager 0.11.0 (C) 2022 ARM

*** ERROR M204:
  Path not found: 'E:/GIT/gitlab/embedded/templates/uvision-template/open-cmsis-pack based/generated-uv-projects/uvision-template.Debug+Production-HW/..\..\src\te_main.c'!
error cbuild: error executing 'cbuildgen cmake'
```

There is one `../` missing. Can I use any output flag to fix that?

Thanks!

**Comment by ReinhardKeil** [comment]
I suggest we go iterative here and create usage examples. We have first examples here (however I would like to clean them a bit before dicussion): https://github.com/RobertRostohar/ctools_lab

These examples use for each project a sub-directory.  When the project is created using csolution, then the *.cprj files are already in sub-directories. 

Is therefore this requirement already fulfilled?  What would be different?

**Comment by jankap** [comment]
Thank you very much for your quick response :)

> Is therefore this requirement already fulfilled? What would be different?

I'll have a look. I guess it's already sufficient.

> @jankap we may need access to your project to replicate the issue you are describing. Did you manually copy the *.cprj file?

I did not manually copy anything. Will try to provide a minimal (non-) working example :)

**Comment by ReinhardKeil** [comment]
Should be discussed with #314

**Comment by ReinhardKeil** [comment]
closing as this is now in #314 and somewhat a duplicate
