### ISSUE TITLE
Add --version option to CMSIS-Toolbox utilities

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#310]
It would be good to have `--version` options for the various tools in the CMSIS-Toolbox.

I would prefer if this option lists just the version information in a consistent way, not additional information such as license text (currently cpackget does that).

Suggested output:

```
>csolution --version``
csolution v0.9.4 (C) 2022 Arm
```

**Comment by jkrech** [comment]
**cpackget:**
```
>cpackget --version
cpackget version 0.3.2
Copyright 2022 Linaro

Licensed under the Apache License, Version 2.0 (the "License");
...
```
**csolution:**
ToDo - Add command line option `--version`

**cbuild:**
```
>cbuild --version
cbuild version 0.9.0
```

**cbuildgen:**
ToDo - Add commandline option: `--version`

**packchk:**
```
packchk --version
1.3.95
```

**Can we all agree on a version output format?**
```
<name> version <semantic version> <copyright>
```

**Comment by brondani** [comment]
Related to: https://github.com/Open-CMSIS-Pack/devtools/issues/128

**Comment by ReinhardKeil** [comment]
closing as all relevant tools have now a way to print version information
