### ISSUE TITLE
Version control of RTE folder

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#313]
It would be great to understand which files shall go into version control and which not :) I have to add at least some configuration files e.g. under /RTE/Device/STM32F103/... which include Clock Configs etc. What about the "manually" versioned files  <file>@<version>? And what about the hidden ones .<file>@<version>?

I've read https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#plm-of-configuration-files but probably I didn't understand everything to decide which files should be versioned by GIT and which not.

Thank you very much!

**Comment by jkrech** [comment]
a) You need to put the actual configuration files under revision control
```
./RTE/component_class/ConfigFile.h
```
b) In addition you need keep the hidden versioned config file under revision control
```
./RTE/component_class/.ConfigFile.h@1.2.0
```
- this file is a copy of the original configuration file that was copied from the pack. This file must not be edited by the user. When running a file diff between a) and b) the user's modifications will show

c) In case the project is using a new version of the component with a new version of the configuration file, the tools will place a copy of the new configuration file version in the folder  (no "." -> not hidden):
```
./RTE/component_class/ConfigFile.h@1.3.0
```
Only after you updated the content of config file a) with c) and merge your changes from b) to retain the project's configuration
you need to delete config file b) and commit config file c) instead.

The hidden configuration file serves two purposes:
1) it indicates which version of the configuration file is in use
2) the original content of the config file from the pack is preserved without the need to locate this file in the previously used pack version.

Does that answer your question?

**Comment by jankap** [comment]
Awesome, thank you.

**Comment by ReinhardKeil** [comment]
I will add this to the documentation.

**Comment by Jonny-vb** [comment]
Regarding "This file must not be edited by the user." - if this is the case could they not be marked as read only? Currently I seem to be free to edit these versions

**Comment by jkrech** [comment]
Point taken, the "versioned" files must be read-only. @edriouk, @brondani would you agree?

**Comment by ReinhardKeil** [comment]
The only remaining point of this issue is the R/O of version info files.

@edriouk are the files that indicate the versions (extended with @<version>) already R/O?

**Comment by edriouk** [comment]
@ReinhardKeil, yes the files are read only

**Comment by jkrech** [comment]
As far as I can see on windows trunk, these versioned files have the read-only flag set. Note that csolution V 1.2.0 does not include the latest updates of the RTE Model yet.
