### ISSUE TITLE
Proposal: Usage of `cdefault.yml` to select Compiler toolchain

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#315]
My suggestion is to use the file `cdefault.yml` to select the Compiler toolchain.

By default, this file could be searched in the `.\etc` directory.  Overwriting the file/location with an command line option (-d / --default filename) should be added.

Background: we should allow different tool integrations, for example: VS Code with GCC, IAR with EW-Arm, Keil Studio with AC6. Each of this tool environments uses a different default compiler.  With `csolution` yml files and the right CI test process it should be possible to write example applications that are portable across this different toolchains.  The `cdefault.yml` file might simply provide the pre-configuration for the compiler.

See also https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/105

**Comment by ilg-ul** [comment]
Does this allow to define multi-platform projects, i.e. projects with build configurations that need different toolchains, for example arm-none-eabi and aarch64-none-elf?

**Comment by ReinhardKeil** [comment]
Suggestion is to provide an overwrite for the `.\etc\cdefault.yml` file: so yes is the answer.

**Comment by fred-r** [comment]
.cdefault.yml is not defined here:  https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md
it appears in the doc, but it is nowhere in the diagram

**Comment by ReinhardKeil** [comment]
The picture in the documentation is fixed.
