### ISSUE TITLE
RTE Configuration file PLM - reconsider filenaming convention

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#324]
While answering and discussing this issue https://github.com/Open-CMSIS-Pack/devtools/issues/313 the concerns got raised, that on UNIX operating systems files and directories starting with a "." are hidden by default but not on windows.

In order not to confuse users with multiple "similar" filenames, one suggestion was to store the "versioned" files in a different directory location. Which may make it harder for users to identify and localize the files required for a three-way merge.

a) project specific configuration file used by the build process

b) copy of the configuration file version used as the basis of the project specific file as provided by the component version at the time when the component was added or an updated version merged
- unmodified
- read-only
- provides version information

c) copy of the configuration file as provided by the current component version / pack version when processed
- unmodified
- read-only
- provides version information

Alternative using current and update
```
<configfile>.<ext>
<configfile>.<ext>.current@version
<configfile>.<ext>.update@version
```

Note: 
a) we need to be able to identify which versioned file is the basis of the actual configuration file.
b) the tools shall remove any "update" configuration file that was not merged. 
c) there is a maximum of one "update" file present or none in case the version of "update" would match "original".

**Comment by ReinhardKeil** [comment]
Reflected in the next version of the documentation https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#plm-of-configuration-files (will be live tomorrow)

**Comment by ReinhardKeil** [comment]
Is this completed?

**Comment by jkrech** [comment]
This has not been implemented in `csolution`  (RTE-Model) yet.
During discussion @edriouk  and @brondani suggested to use `base` instead of `current` as this term is also used by git merge.
```
<configfile>.<ext>
<configfile>.<ext>.base@version
<configfile>.<ext>.update@version
```

**Comment by ReinhardKeil** [comment]
implemented
