### ISSUE TITLE
PackChk Warning M339 wrongly issued

### ISSUE THREAD

**Issue by MatthiasHertel80** [Open-CMSIS-Pack/devtools#327]
When a directory specified as an include path in a component does not exist, PackChk will report:
`"*** WARNING M339: **.pdsc (Line **) Include Path '**' must not be a file!"`

This is because the std::filesystem::is_directory will return false also if the path does not exist. I recommend to add a std::filesystem::exists check before. This should trigger a different warning/error.

**Comment by jkrech** [comment]
I agree that this warning message is simply wrong in case the directory does not exist.

**Comment by thorstendb-ARM** [comment]
This has been fixed in PackChk 1.3.95: https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.3.95
