### ISSUE TITLE
problem to list dependencies ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#330]
```
> csolution.exe -s gpio-toggle.csolution.yml -c gpio-toggle.cproject.yml list dependencies
error csolution: context 'gpio-toggle.cproject.yml' was not found

frq09468@LMECWL0888 MINGW64 /c/Cube/stm32cube_fw_all/examples/hal/gpio/toggle/projects (main)
$ ls
gpio-toggle.cproject.yml
gpio-toggle.csolution.yml
```

With:
```
> csolution.exe --help
CMSIS Project Manager 0.9.5 (C) 2022 ARM
```

But:
```
> csolution.exe -s gpio-toggle.csolution.yml convert
/gpio-toggle.AC6+B-U585I-IOT02A.cprj - info csolution: file generated successfully
/gpio-toggle.GCC+B-U585I-IOT02A.cprj - info csolution: file generated successfully
/gpio-toggle.IAR+B-U585I-IOT02A.cprj - info csolution: file generated successfully
```

And:
```
> csolution.exe -s gpio-toggle.csolution.yml -c gpio-toggle.GCC list dependencies
error csolution: context 'gpio-toggle.GCC' was not found

> csolution.exe -s gpio-toggle.csolution.yml -c gpio-toggle.GCC+B-U585I-IOT02A list dependencies

```

I assume this is normal but the doc is not so clear about it:
```
 -c, --context arg     Input context name <cproject>[.<build-type>][+<target-type>]
```

I can understand that in my case the build-type is mandatory as I have 3 of them, but why target-type ? 
I have only one.

Also, what if I want to check all my dependencies at once ?

**Comment by brondani** [comment]
@fred-r In the current implementation you have to provide the full project context name for the `-c` or `--context` option. The option can be fully omitted if the solution has only one project context, but it cannot be partially omitted due to a type. You can see the available contexts with the `csolution list contexts` command.
Please feel free to propose other use cases that you would require, possibly with a description of expected inputs/outputs.

**Comment by fred-r** [comment]
In fact, I have no preferred use-cases.

It is just that the help message:
```
 -c, --context arg     Input context name <cproject>[.<build-type>][+<target-type>]
```

indicates some parts are optional so I thought that when not needed to discriminate the projects it could be omitted.
If this is not possible, we just need to update the help message.

**Comment by jkrech** [comment]
How about 

```
    -c, --context arg        Input context identifier
```
or should we mention the command to list the context identifiers? 

```
    -c, --context arg        Input context identifier (see: csolution -s <csolution> list contexts)
```

**Comment by fred-r** [comment]
I think the second solution is more user-friendly.
I see what I can copy paste :-)

**Comment by jkrech** [comment]
@brondani please note: 
```
convert               Convert cproject.yml or csolution.yml to cprj files
```
should read:
```
convert               Convert csolution.yml to cprj files
```
as we are deprecating the immediate specification of a cproject.yml file and mandate csolution.yml files as input.

**Comment by ReinhardKeil** [comment]
@brondani - to avoid confusion, I did suggest to change the [help text under](https://github.com/Open-CMSIS-Pack/devtools/issues/330#issuecomment-1251015059)

**Change**
```
 Options:
   -s, --solution arg    Input csolution.yml file
   -c, --context arg     Input context name <cproject>[.<build-type>][+<target-type>]
```

**To**
```
 Options:
   -s, --solution arg    Input csolution.yml file
   -c, --context arg     Input context name <cproject>.<build-type>+<target-type>
```

Rational: <build-type> and <target-type> are not optional.  They must be specified when they exist.
