### ISSUE TITLE
cproject spec unclear about packs repositories precedence

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#331]
I expect that the precedence rule would be:
1. if a pack is available in the local packs list : use it
2. otherwise revert to CMSIS_PACK_ROOT

But in my case I have:
- pack A version 0.0.1 as a local pack
- pack A version 0.0.3 in CMSIS_PACK_ROOT

csolution selects version 0.0.3 though I have configured a local pack.

**Comment by ReinhardKeil** [comment]
@fred-r I agree: a local pack path should always overwrite - hence this pack should be not searched in CMSIS_PACK_ROOT

**Comment by jkrech** [comment]
@fred-r, I just want to make sure we are talking about the same scenario.
When you write "local pack" in the context of 'csolution' you refer to a pack being specified in the .csolution.yml file with a path.

```
- pack: NXP::K32L3A60_DFP             # add pack for NXP device 
    path: ./local/NXP/K32L3A60_DFP      # with path to the pack (local copy, repo, etc.)
```

In this case my expectation is that csolution would never look in `$CMSIS_PACK_ROOT/` . If the pack (more specifically the pdsc file) is not found in the specified path, then in my view this must be reported as an error.
`./local/NXP/K32L3A60_DFP/NXP.K32L3A60_DFP.pdsc`

Any silent fall-back is not intended by the csolution.yml file.

**Comment by fred-r** [comment]
Ok, I see, so using local repositories does not takes precedence over CMSIS_PACK_ROOT if the higher version of a pack is in CMSIS_PACK_ROOT.
