### ISSUE TITLE
csolution: generator exe command issue?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#338]
Hi

ex:
```
    <generator id="CodeGen">
      <exe>
        <command>script_to_execute.sh</command>
```

sh script is not executed, it is "opened" like a double click.
So execution is depending on default action from windows

@fred-r

**Comment by jkrech** [comment]
Sorry for the lack of response on this.
I think we must not expect shell scripts to be executable on windows hosts. This was one of the reasons we got rid of cbuild.sh and any dependency on bash on windows.
You should specify a batch or powershell script using the attribute "host" to specify different commands for windows and other hosts.
see: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_generators_pg.html#element_gen_exe
