### ISSUE TITLE
Build flag order needs to be kept

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#35]
Currently there is no guarantee that e.g. "-I incpath2 -I incpath1" will be passed in that order when building since a set<> is used internally.

The build system first needs to be reliable, predictable and deterministic.

**Comment by brondani** [comment]
Hi @slhultgren,

Thanks for the PR.
Do you have a concrete use case to describe the problem you want to tackle?

I believe we should separate the discussion in two items:

_1. The user having control over include path order_
Please note the order of components process in RTE Model is given by their IDs, the PR is not really considering it. `std::set` is also used to filter out duplicated elements, it's not rare different components providing the same include paths. Changes in this field could imply in other specification/architectural changes. In any case it is reproducible and deterministic.

_2. The generation of CMakelists.txt from cprj being deterministic_
I would agree the final sorting of fully specified include paths may not be deterministic if the underlying filesystem/pack repository change location. But to correctly address it the PR shall be amended.

Thanks
Daniel

**Comment by slhultgren** [comment]
Hi @brondani 

For GCC, the last flag is the one that wins, for example if -O3 and -O0 are both specified.

For GCC, the order in which the include paths are searched is determined by the order of the include path flags on the command line.
Therefore the user needs to be able to specify the exact order of the include paths to be able to build their code.

I'll add some comments to the PR as well.

KR, Samuel

**Comment by brondani** [comment]
Hi @slhultgren,

The PDSC specification already provides means to avoid header files collision by setting the `path` file attribute which can act as header namespace:
https://www.keil.com/pack/doc/CMSIS/Pack/html/pdsc_components_pg.html#element_file
Are there other use cases in which the user may need to specify the exact order of the include paths?

Cheers
Daniel

**Comment by slhultgren** [comment]
Hi @brondani 

Yes, consider the case of user code in the .cprj. The user must be able to say in the cprj in which order the include paths should be used for the user code.

Regarding components I believe a change in the order of the components in the CPRJ should also be reflected in the order of include paths on the command line.
(assuming the components used specifies/exposes include paths to the user code)

KR, Samuel

**Comment by slhultgren** [comment]
Hi @brondani thanks :)

Makes sense, I think I agree regarding the ordering of component "resolving". It could be tricky indeed.

The thing remaining that I'm still thinking about is the include path order "within" components. Ideally I think this should be kept, but unfortunately it means we can no longer rely on a sorted set of all include paths, but instead we could move to a sorted "set<ComponentIncludePaths>" where ComponentIncludePaths is a vector<string> of unique detection-ordered include paths.

But it is a bit of an edge case I agree. What do you think?

**Comment by slhultgren** [comment]
@brondani Indeed, I agree that it is probably bad design, but I'm also a bit worried since an "opinionated" build system like this leads to some possibly unsupported use-cases, even though we both may agree those are from bad design. I'll close this for now, it can always be raised again if it becomes an issue for someone in the future.

KR, Samuel
