### ISSUE TITLE
[rtemodel] Target defines are not split

### ISSUE THREAD

**Issue by Quaker762** [Open-CMSIS-Pack/devtools#351]
In a regular ARM DFP PDSC, the `device` section's `compile` XML object has the attribute `define` (https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_devices_pg.html). UV5 allows _multiple_ definitions in this, separated by a comma. These are then put separately on the compiler's command like via the `-D` flag. 

Currently, this does not occur on invocation of `cbuild`, and a define of this type is put directly onto the command line, causing build failures for packs of this nature.  The offending section seems to be here:

https://github.com/Open-CMSIS-Pack/devtools/blob/4524cb6e6f2be0318e6e714e57fa38ce8aadc09a/libs/rtemodel/src/RteTarget.cpp#L613-L620

**Comment by jkrech** [comment]
Note, the specification you point to does not specify that the attribute allows multiple defines. The fact that the implementation of MDK/uVision supports a comma separated list of defines, is an implementation feature which is outside of the specification.

**Comment by Quaker762** [comment]
> Note, the specification you point to does not specify that the attribute allows multiple defines. The fact that the implementation of MDK/uVision supports a comma separated list of defines, is an implementation feature which is outside of the specification.
> I suggest to reject this change request.
> We should consider updating the Pack Schema to just allow a single ANSI C compliant MACRO symbol.

Fair point, perhaps this is undocumented behaviour in uvision 5. I've updated our DFP to use a semicolon to delimit instead, which seems to work instead.

Would you like to me to close this issue?

**Comment by jkrech** [comment]
It sounds like you depend on the feature to specify more than one macro and apparently you got this to work with ';' which is also outside of the specification. 
We need to conclude whether we want to make this an official feature and add it to the specification accordingly before we close this issue.

**Comment by jkrech** [comment]
@edriouk could you please comment what exactly has been implemented in the different RTE model implementations.

**Comment by Quaker762** [comment]
@jkrech 
> It sounds like you depend on the feature to specify more than one macro and apparently you got this to work with ';' which is also outside of the specification.
Yeah, I think it's ninja that's specifically resolving this. I double checked today at the office and it looks like the macro is still getting shoved into the `CMakeLists.txt` file with the semicolons included (e.g `add_definitions(macro1;macro2;macro3), so somewhere else down the chain is rectifying it when it's split via a `;`. I find it curious that uvision handles both of these, as you've mentioned it's outside of the spec.

> We need to conclude whether we want to make this an official feature and add it to the specification accordingly before we close this issue.
Sounds good!

**Comment by edriouk** [comment]
RTE Model itself does not process the define string, just supplies collection of strings to clients.
Multiple defines in the string works in MDK only by chance, because the collected RTE defines are processed in the same way as user ones => split.
Other client implementations, like one for Eclipse do not split the define string.
Making this an official feature would require updating such clients as well.

RTE Model however provides other ways to specify multiple defines via component's elements:
1. RTE_Components_h 
2. Pre_Include_Global_h 
3. Pre_Include_Local_Component_h 

Would those methods be sufficient?

**Comment by ReinhardKeil** [comment]
I think the conclusion is that the define attribute should allow multiple define settings separated by ';'.  Otherwise it is restricted to just one define per device which might be not enough.
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_compile

**Comment by Quaker762** [comment]
> RTE Model itself does not process the define string, just supplies collection of strings to clients. Multiple defines in the string works in MDK only by chance, because the collected RTE defines are processed in the same way as user ones => split. Other client implementations, like one for Eclipse do not split the define string. Making this an official feature would require updating such clients as well.
> 
> RTE Model however provides other ways to specify multiple defines via component's elements:
> 
> 1. RTE_Components_h
> 2. Pre_Include_Global_h
> 3. Pre_Include_Local_Component_h
> 
> Would those methods be sufficient?

Not quite. The essence of the problem is that we have 2+ separate parts that are similar in nature to each-other, however different enough (via software) that they require both a part macro and a common macro to be included by default with the Pack's system header file. E.g both `__PARTXXX__` _and_`__PART1234__` (and even  `__PART_FPGA__` for DFPs in use with an FPGA to test silicon). 

These macros are not so much application specific as they are DFP specific (related to the part), meaning there's no real way around this except by having two or more of them attached to the system header file itself which is obviously done via the PDSC.

I suppose we could get around this by defining some of these based on the part number via an `#ifndef` and the part number to define them during compilation.

> I think the conclusion is that the define attribute should allow multiple define settings separated by ';'. Otherwise it is restricted to just one define per device which might be not enough.

I think at the end of the day, yes, it would be nice if the define attribute supported more than a single macro to be defined per system header in the RTE.

**Comment by ReinhardKeil** [comment]
My view: the [<compile>](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_compile) element must support multiple `define` arguments in the attributes `define` and `Pdefine`.  This are separated by `;`.

**Example:**
```
  <compile  header="Device/Include/stm32f4xx.h" define="STM32F40XX; MAX_CLOCK=18000000"/>
```

The change should be reflected in documentation and tools, starting wiht Open-CMSIS-Pack specification first.

**Comment by jkrech** [comment]
We designed the `<compile>` tag as part of the `<devices>` tag with the following intention in mind:
a) As part of [CMSIS-Core](https://arm-software.github.io/CMSIS_5/latest/Core/html/index.html) we specify the scope and content of a [device header file](https://arm-software.github.io/CMSIS_5/latest/Core/html/device_h_pg.html)
b) The define is used within the software to identify which device is targeted during a build

The latter is true also for the `<device>.h` header file, which may cover a single device variant or up to a whole family of devices.
The header files are required to be designed in such a way that every specialization as well as generalization is derived/originates from this device specific define.

Note that there maybe cases where multiple devices share that exact same software configuration/features/etc. and therefore a set of devices could share a common define.

My question is, what problem are we trying to resolve by adding additional defines, that could not be addressed by including such a define in the `<device>.h` or any header file include from there?

**Comment by jkrech** [comment]
Since you identified a way to resolve the description using only a single define and this is only "nice to have", we decided to reject the request to extend the support for multiple defines.
In the specification we shall change the description of the `define` attribute to:

```
A single device specific preprocessor define (macro) which is used to uniquely identify
a device or device series in the software (e.g. STM32F407). 
This macro is automatically set in the pre-processor command line (-D<macro>)
of the build tools and allows to enable/disable device specific code during preprocessing
of the application code, e.g. enabling/disabling device specific definitions in device
header files that are shared across multiple devices. 
```
