### ISSUE TITLE
csolution: add json file as list result ?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#352]
Hi

Context is automatic script:
what do think to add a json file as list command option ?

```
csolution.exe list generators -s xxx.csolution.yml -c xxx.AC6+xxx --json
```

It would be easier for tool to parse json file to get results ?

Thx

**Comment by ReinhardKeil** [comment]
My take, this feature is now covered by the cbuild.yml file.  We just may need to add the generators to it.
See https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md

**Comment by jeromecoutant** [comment]
I don't understand your point...

Maybe my question was not clear.
In my environment, command gives me 2 answers:
```
csolution.exe list generators -s xxx.csolution.yml -c xxx
STM32Cube_AAA_CodeGen (ST Microelectronics: STM32 Cube Code Generator)
STM32Cube_BBB_CodeGen (ST Microelectronics: STM32 Cube Code Generator)
```
I then use some grep and cut command to get the generator, but it is not "friendly".
My request is maybe we can get a json file instead of console with a specic parameter ?

Thx

**Comment by ReinhardKeil** [comment]
I think this is part of the generators concept and it needs indeed further discussion.

But, what would be the next step after you get the *.json file.  How does this improve usiblity?

**Comment by jkrech** [comment]
I think the use case here is, that you run e.g. an IDE where for the active context the user is displayed a list of one or more generators that need to be run and based on the user response will run the user selected generator. The json file format provides a structured description to easily construct the command line. For a human typing at the command line, copying the generator ID from the output is straight forward.

**Comment by jeromecoutant** [comment]
OK, our tool will parse pdsc files directly.
No need for extra json or whatever generated list.
Thx

@slhultgren
