### ISSUE TITLE
Support device feature 'SON' in PackChk

### ISSUE THREAD

**Issue by GuentherMartin** [Open-CMSIS-Pack/devtools#353]
The current PACK.xsd (Revision 1.7.7, SchemaVersion=1.7.7) contains SON as device feature. But PackChek V1.3.95 does not yet support this feature. SON (Small Outline No Lead) package is a device package type similar to SOP.

`*** ERROR M371: C:/Users/margun01/Downloads/cmsis-toolbox-windows64/bin/Keil.Test_DFP.pdsc (Line 35)
  Device Feature for 'TestDevice': 'SON' unknown. `

To reproduce add the following device feature to a PDSC and run packchk:
` <feature type="SON" n="8"/>`

**Comment by thorstendb-ARM** [comment]
Added feature "SON".

**Comment by ReinhardKeil** [comment]
This is fixed
