### ISSUE TITLE
Any API / doc if toolchain cmake description file ?

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#367]
Considering https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/buildmgr/cbuildgen/config is there any description of requirements ?
What about expecting to contribute to a new toolchain ?

We have couple of issues running if toolchain setup (#120 #68 #179 #315) but in the meantime have we any clear definition of current requirements aiming to contribute to such cmake config files ?

**Comment by jkrech** [comment]
We don't have a specification/documentation for it. Instead people would take an existing cmake file to find out about the input and output variables that need to be mapped.
Do you have any immediate question blocking  you from adding a new toolchain?

**Comment by jkrech** [comment]
@tarek-bochkati, you have created the cmakefile file for IAR, would you be able to contribute a description how you did this so we can add it to the documentation?

**Comment by ReinhardKeil** [comment]
Now documented here https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Build-Operation.md

Closing this issue as it seems to be somewhat a duplicate
