### ISSUE TITLE
Optional RTE creation

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#371]
To make the tools easier to use for testing and validation and to help the user control when and why the RTE structure is created/updated, it would be desirable to have a flag to disable/enable RTE file creation for both cbuildgen.exe and csolution.exe.

This would allow to generate CPRJ and/or CMakeLists.txt without creating the RTE structure.

Related to https://github.com/Open-CMSIS-Pack/devtools/issues/85

**Comment by jkrech** [comment]
@slhultgren, sorry for the lack of response to this issue. 
Let's ask for feedback on this "feature request". 
My take is that the `cbuildgen` needs to have the manipulation of the content of the 'RTE' folder removed
Except maybe for: the generation of the RTE_Components.h  and Pre_Include files (to be further discussed)
The PLM of config files needs to be managed exclusively by `csolution` (or similar tools).
However I don't like the idea to provide a command line option to `csolution` where the resulting project will fail to build.
Please note that csolution does not(!) update the config file and only copies the default config file in case that file is not present. It does however maintain an additional versioned copy of the configuration file as provided by the current component version. The file is only used for 3-way merge based update but does not affect the actual build until the user chooses to edit the config file.
If you need to remove these versioned files for your test you can easily identify and remove them from  your test script.

**Comment by thegecko** [comment]
This would be a very useful way of enabling builds on ephemeral file systems which are read-only.

Ideally, the source shouldn't be modified during a build so I would go as far as saying the default should be not to generate extra files unless a flag is present.

**Comment by thegecko** [comment]
cc @acabarbaye

**Comment by mcgordonite** [comment]
I can see decoupling cprj/cmake generation from config file PLM being useful for both users and IDEs.

For example:
- `csolution rte update` could write out config files for the user to edit without having to generate the build files.
- `csolution convert --no-update-rte` could generate cprj/cmake without updating RTE, perhaps printing warnings if the project won't be buildable.
- `csolution convert --immutable-rte` could fail if the RTE needs updating, useful for CI flows.

**Comment by jkrech** [comment]
I do see the use cases for updating configuration files, however what is the use case for not creating a folder containing the config files for the selected components. To me this is a dead end. `csolution` is responsible for adding config files for components that have been added. Without the config files I cannot see how the project will build. We already said that this is different for `cbuild`. There it would be acceptable to throw an error if a config file is not present.
