### ISSUE TITLE
[packchk] Add a check for using forward slashes in <license> element

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#373]
The packchk (Version 1.3.95) utility fails to detect the use of a backward slash when specifying the location of the license file in the element `<license>`

The following shall be reported as Warning M327 - Path is not conformant ...
```
   <license>licenses\license.dat</license>
```

**Comment by thorstendb-ARM** [comment]
Fixed - do you need a new version now?
