### ISSUE TITLE
cbuildgen should read version from the pdsc file

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#374]
Hi

cbuildgen relies on the version information in local_repository.pidx,
but it should rather take the version information from the PDSC file.

Scenario with an issue:

I got a local pack already configured some time ago:
```
$ grep Example_xxx $CMSIS_PACK_ROOT/.Local/local_repository.pidx
  <pdsc vendor="STMicroelectronics" url="[file://localhost/C:\path\](file:///C:/path/)" name="Example_xxx" version="0.1.0"></pdsc>
```
I updated my local pack:
```
$ grep version STMicroelectronics.Example_xxx.pdsc
    <release version="0.1.1-alpha" date="2022-06-07">
```

```
$ csolution.exe list dependencies -s xxx.csolution.yml -c xxx.AC6+B-U585I-IOT02A
```
=> OK

```
$ csolution.exe convert -s ./xxx.csolution.yml
C:/path/xxx.AC6+B-U585I-IOT02A.cprj - info csolution: file generated successfully
```
=> OK

```
$ cbuild.exe ./xxx.AC6+B-U585I-IOT02A.cprj
info cbuild: cbuild: Build Invocation 0.9.1 (C) 2022 ARM
(cbuildgen): Build Process Manager 0.11.2 (C) 2022 ARM
M650: Command completed successfully.
error cbuild: cpackget was not found, missing packs cannot be downloaded
```
=> Message is normal in my side, cpackget is really not available. 

**But the issue is why cbuild needs to use cpackget ?**

```
$ echo $?
0
```
=> 2nd issue but minor, cbuild should exit with non 0 value in my case

If I update manually local_repository.pidx file with the correct version,
cbuild command is now well calling cbuildgen as expected;

**Comment by jeromecoutant** [comment]
Hi Daniel

````
$ cbuild.exe  gpio-exti.AC6+B-U585I-IOT02A.cprj
info cbuild: Build Invocation 1.0.0 (C) 2022 ARM
(cbuildgen): Build Process Manager 1.0.0 (C) 2022 ARM
M654: Package 'STMicroelectronics::Example_HAL_GPIO_EXTI@0.3.0' was added to the list of missing packages.
M650: Command completed successfully.
info cbuild: missing packs must be installed, rerun cbuild with the --packs option

$ echo $?
0
````
Is it what is expected ?
=> I agree that error message is clearer, but
=> version from local_repository.pidx is still taken into account
=> exit code is still OK

**Comment by brondani** [comment]
@jeromecoutant Thanks for the feedback!
The new local repository handling implemented for `csolution` and `cbuildgen cmake` was indeed not applied to `cbuildgen packlist`, this is being fixed in the PR [#442](https://github.com/Open-CMSIS-Pack/devtools/pull/442).
Concerning the exit code, this is actually different from the one that you reported previously when the `cpackget` was not available. This time it is being fixed in the PR [#9](https://github.com/Open-CMSIS-Pack/cbuild/pull/9).

**Comment by brondani** [comment]
@jeromecoutant Can you please test it with the latest CMSIS-Toolbox 1.1.0? Many thanks!
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.1.0

**Comment by jkrech** [comment]
@jeromecoutant I would like to remind you to validate the fix and comment accordingly/close the issue.

**Comment by jeromecoutant** [comment]
Hi
To be honest, we don't use any more local_repository.pidx file :-)
But I will try to make a test!
