### ISSUE TITLE
Renaming 'misc'

### ISSUE THREAD

**Issue by sophewilliams** [Open-CMSIS-Pack/devtools#378]
We're finding that users don't understand the 'misc' label in the build-type object unless we pre-populate the field with examples. 

We'd like to generate the settings UI rather than having to hard-code anything, so is it possible to rename this property to something more meaningful? Happy to gather some user feedback on what this might be in our next round of testing.

**Comment by jkrech** [comment]
"misc" stands for miscellaneous
The schema help reads:
"List of miscellaneous literal tool-specific controls that are passed directly to the tools depending on the file type"

uVision uses "Misc Controls"
ArmDS uses "Miscellaneous"
today already.

In order for "miscellaneous" to make sense it is also important to see this in the context of the options we have for [translation control](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#translation-control)
'misc' covers whatever cannot be described in a compiler agnostic way using the above list of options.

**Comment by sophewilliams** [comment]
@jkrech thanks for checking. We included the description during testing and unfortunately users still struggled with it, but we're happy to work with users to modify it in the next testing round if necessary. However, we will try providing fields for the properties listed in the translation control in the next design and testing iteration, I think that will fix the issue. Thanks for your help, and I'm happy to close this out.

**Comment by jkrech** [comment]
Agreed to close.
