### ISSUE TITLE
csolution does not use default variant indicator ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#380]
I have a component with several variants.
The default vairant has a generator associated to it:
```
<component Cclass="Utility" Cgroup="Debug" Csub="basic trace" Cvariant="Configurable" Cversion="0.0.2" condition="STM32 HAL Configurable Low Level" isDefaultVariant="true" generator="STM32Cube_BasicTrace_CodeGen">
```

When running the generator:
```
> csolution.exe run -g STM32Cube_BasicTrace_CodeGen -c HAL_CRC_UserDefinedPolynomial.AC6+B-U585I-IOT02A -p HAL_CRC_UserDefinedPolynomial.cproject.yml -s HAL_CRC_UserDefinedPolynomial.csolution.yml
error csolution: multiple components were found for identifier 'STMicroelectronics::Utility:Debug:basic trace'
STMicroelectronics::Utility:Debug:basic trace&Configurable@0.0.2 in pack C:/stm32cube_fw_all/utilities/basic_trace/STMicroelectronics.basic_trace.pdsc
STMicroelectronics::Utility:Debug:basic trace&Custom@0.0.1 in pack C:/stm32cube_fw_all/utilities/basic_trace/STMicroelectronics.basic_trace.pdsc
STMicroelectronics::Utility:Debug:basic trace&ITM@0.0.1 in pack C:/stm32cube_fw_all/utilities/basic_trace/STMicroelectronics.basic_trace.pdsc
STMicroelectronics::Utility:Debug:basic trace&UART@0.0.1 in pack C:/stm32cube_fw_all/utilities/basic_trace/STMicroelectronics.basic_trace.pdsc
```

==> is it normal that the default variant does not prevail ?

**Comment by jkrech** [comment]
@fred-r, this is an excellent question. In my opinion the functionality you are expecting would be implemented in a "dependency resolver" where "default variant" is a hint to the resolver. Csolution does not implement this functionality, therefore in my view it is expected that the user needs to resolve this ambiguity explicitly as otherwise the alternative components would go silently unnoticed.

**Comment by fred-r** [comment]
@jkrech : I would tend to agree with you.

I guess we just need to clarify this definition: 
"Identifies this component variant to be the preferred variant for tool driven selection"

==> here the tool we are referring to is not csolution, it is another tool, not provided in OpenCMSIS.

To me it makes sense that csolution reports only that a dependency must be solved or a choice must be made.

**Comment by jkrech** [comment]
Will resolve with clarification in the specification.
