### ISSUE TITLE
Add debugger & flash settings to csolution or cproject files?

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#389]
My goal is to have identical settings in both, the commandline and Keil MDK. I could almost make all flags and settings identical to the default settings in Keil MDK, but the flash and debugger settings are reset every time, MDK imports the `.cprj` file and creates/overwrites a `.uvprojx/.uvoptx` file.
That happens quite a lot, because we try out things in the `.csolution.yml` and `.cproject.yml` files and to get these changes into Keil MDK, we have to re-import the `.cprj`. That overwrites debug settings which need to be set by hand every time. This also causes a lot of noise in GIT.

Is there any way to specify debugger settings in `csolution` or `cproject` files? If no, is this planned? Any other workaround ideas? Like an automated patching script of the resulting MDK files?

Thanks!

**Comment by tcsunhao** [comment]
Associate with https://github.com/Open-CMSIS-Pack/devtools/issues/335.  Debug configuration is necessary for project out box run.
