### ISSUE TITLE
Specify `intdir` and `outdir` in `.cprj` files?

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#390]
Is there any way to define the `intdir` or `outdir` keys in a `cprj` file?

I create my files via `csolution convert -s ./prj/<prj>.csolution.yml -o ./prj/generated-uv-projects` but there seems to be no option to define the intdir. 
I have to use `cbuild ./prj/generated-uv-projects/<prj>/<prj>.cprj -i ./build-src/tmp -o .build-src/`. Why does cbuild not look at the intdir in the cprj file?

Application: I'd like to use th esame int/out directories for cbuild and for Keil MDK.

Thanks!

**Comment by brondani** [comment]
The `csolution` YAML options for customization of `intdir` and `outdir` have been just recently added as discussed in the issue
https://github.com/Open-CMSIS-Pack/devtools/issues/314. It will appear in the next release.

Concerning `cbuild` the command line options `-i, --intdir` and `-o, --outdir` have precedence over the equivalent values in the cprj.

**Comment by VGRSTM** [comment]
According to me in sync. with @brondani comment I'm thinking we can close such issue
