### ISSUE TITLE
Specify features and defects to be fixed for csolution/cbuildgen Version 1.0.0

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#395]
Please add references to issues containing "features" and "bugs" that you think are required to be resolved before releasing the csolution and cbuildgen as Version 1.0.0. in comments below.

**Comment by jankap** [comment]
Imo, this one is essential: #314

**Comment by VGRSTM** [comment]
I would be pleased to get #82 as required (will be part of lock file processing #119 as addon to components)  & #224 as nice to have in.

**Comment by VGRSTM** [comment]
Possibly [Pre/Post build steps](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#prepost-build-steps) would be nice to have in

**Comment by tcsunhao** [comment]
[Support project customized config file replacement of specific SW pack component](https://github.com/Open-CMSIS-Pack/devtools/issues/296) is critical for many middleware cases. The default provided "config" file for certain middleware components cannot meet specific example, developers frequently need to provide customized "config" file for certain component.

**Comment by brondani** [comment]
Thanks for all suggestions.
#314 and access sequences are included :heavy_check_mark:
#82 and #224 I believe would need to go through the decision committee :heavy_multiplication_x:
Pre/Post build steps need significant effort :heavy_multiplication_x:
#296 in the discussion I don’t see an agreement about concrete actions :heavy_multiplication_x:

The [CMSIS-Toolbox](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Ftoolbox%2F1.0.0) has been released today, please check it out and let's continue the discussions after the summer break.

**Comment by VGRSTM** [comment]
@brondani Thanks for all such. Enjoy well deserved summer break !

**Comment by jkrech** [comment]
I am closing this issue, since cmsis-toolbox 1.0.0 got released.
