### ISSUE TITLE
Windows download blocked due to found virus by ZScaler

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#399]
Hey guys,

I can't download the [most recent Windows release](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Ftoolbox%2F0.10.2) due to ZScaler. This likely affects lots of commercial customers since ZScaler is very common. Is there anything you can do about it?

Thanks!

![image](https://user-images.githubusercontent.com/12893844/179492996-c59fda08-e1bc-4f73-ad1a-661f4b870df2.png)

**Comment by jankap** [comment]
I'm very sorry, but I don't know hot to fix that. There's no more information available, just tried to download it from my corporate network. I know that this has worked for a former version and I know that it's a false alarm.

Maybe, there's a way to get into contact with ZScaler directly? https://www.zscaler.com/company/contact

**Comment by purdurnr** [comment]
@jankap 
We have ZScaler at NXP.  I clicked on the Download Win64.
It immediately popped up the .zip "downloading" in the upper right window.  ZScalar did not block.
Can you confirm that you cannot download the .zip file from the link?  OR can you not launch some of the executables within the .zip once you download?
I am in our corporate network, not remote.  I can try the same process from remote network without Firewall to see if it operates differently.
![image](https://user-images.githubusercontent.com/94857467/179785725-df16b9a6-8bd8-452e-a4f0-024c8573f076.png)

**Comment by jankap** [comment]
Dear @purdurnr 
thanks for testing. It is indeed clicking on the Win64 link, i.e. on <https://github.com/Open-CMSIS-Pack/devtools/releases/download/tools%2Ftoolbox%2F0.10.2/cmsis-toolbox-windows64.zip> 

The download itself was blocked directly. No file was downloaded.

I raised a ticket in our IT to ask for more information, but in the meantime the issue has gone from on-site and from remote location. Maybe it was a glitch in ZScaler's or our IT's configuration.

Sorry for making you nervous, but I thought this was an important topic. I will raise a new ticket when this happens again with hopefully more information which you could probably add to a "Proxy issues" section in the README or so.

Thanks!
