### ISSUE TITLE
Common (RTE) settings for build and/or target types

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#410]
We try to handle a project with multiple build and target options, which causes a big mess whenever settings in `RTE_Device.h`, located under the RTE folders shall be adapted.

Example:
project name = `my-cool-project`
target types = `system config 1 on hardware a`; `system config 1 on hardware b`; `system config 2 on hw a`;  `system config 2 on hw b` 
build types = `debug`; `release`

You see, we currently have to mix system configs, e.g. different hard-coded feature sets and target hardwares, and then there are multiple build types. 

There will be 8 project folders with individual RTE folders. 

Now, in this example, both build types, and the same hardware options share the same RTE folder/config. Currently, by changing some settings in e.g. `RTE/RTE_Device.h` of one project folder would need to manually adjust all other related RTE folders. This makes things really complicated and error prone. We've spend multiple hours in git to find out which is the correct version ;) The possibility to make errors is much higher when adding redundant information to 8 files instead to one only.

We will want to use a simulator soon, too. This would further double the files :/ Not very scalable.

Do you have suggestions how to solve that issue? Are shared folders across projects the solution, or the layer approach help somehow?

Thanks :)

**Comment by brondani** [comment]
@jankap I assume you are calling the `convert` command with the `-o` option to specify the output, so the RTE folders are generated separately for each solution context. If you can avoid the `-o` option, the RTE folder will remain next to your `cproject.yml`.
In alternative you can use the new output directories structure - it will appear in the next CMSIS-Toolbox release - where the RTE folder remains next to the `cproject.yml` by default and can be customized by setting the [`output-dirs`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#output-dirs) node in the `csolution.yml` file.

**Comment by ReinhardKeil** [comment]
I think this would be covered by `RTE-paths:` that have been proposed two weeks ago.
An example is here: https://github.com/RobertRostohar/Demo_EW/blob/test_rte/AWS_MQTT_MutualAuth_Demo/Board/AVH_MPS3_Corstone-300/Board.clayer.yml#L27

Could you confirm?

**Comment by jankap** [comment]
> I think this would be covered by `RTE-paths:` that have been proposed two weeks ago. An example is here: https://github.com/RobertRostohar/Demo_EW/blob/test_rte/AWS_MQTT_MutualAuth_Demo/Board/AVH_MPS3_Corstone-300/Board.clayer.yml#L27
> 
> Could you confirm?

That looks amazing! Is this already in v1.1.0?

Thanks!

**Comment by ReinhardKeil** [comment]
> Is this already in v1.1.0?
Not yet, but we work on a prototype - should get available within the next few weeks.

**Comment by jkrech** [comment]
csolution v1.2.0 is targeted for Oct. 11th 2022

**Comment by jankap** [comment]
Just to confirm, is this included in the most recent release? Thanks :)

**Comment by brondani** [comment]
@jankalp We don't have progress on the proposed `RTE-paths` node because it is in conflict with the `output-dirs` node and the behaviour of the customization at the several levels must be first clarified, currently being discussed in https://github.com/Open-CMSIS-Pack/devtools/issues/557

**Comment by jankap** [comment]
Hi all,

what's the current state of this? I'm now at CMSIS-Toolbox v1.7.0 and the `rtedir` option in `output-dirs` exists, but I can't align the settings with µVision/Keil MDK. Is there any recommendation how to structure the RTE folders to be compliant to MDK and CMSIS-Toolbox v2?

Thanks!

**Comment by ReinhardKeil** [comment]
The default RTE directory structure (without rtedir: specification) should be compatible with MDK.
See here https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#project-structure

Note that MDK does not support layers.

**Comment by jankap** [comment]
Thank you @ReinhardKeil 
Putting every cproject into a sub directory and creating the RTE folder there makes much more sense and seems to be compatible with MDK. 

That'll work for now, thank you!
