### ISSUE TITLE
csolution(1.0.0) 'output-dirs' issue

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#427]
1.  If output-dirs with sub outdir is maintained in cproject.yml, then cmd will output warning message "warning csolution: key 'output-dirs' was not recognized", correspondingly "outdir" doesn't work.
For multiple project csolution, each project may has its own output, thus cproject.yml instead of csolution.yml should be place for it.

2. For trust zone projects solution, if outdir is set in csolution.yml like 
```
  output-dirs:
    outdir: ./$Project$/$Compiler$/$BuildType$
```
There will be issue message:  "Path not found: /trustzone_examples/hello_world/cm33_core0/hello_world_ns/..\hello_world_s\$Project$\$Compiler$\$BuildType$hello_world_s.debug+Board_CMSE_Lib.o"

**Comment by brondani** [comment]
@tcsunhao thanks for the feedback!
There was indeed an issue when evaluating access sequences from interdependencies. I have already provided the fix [#437](https://github.com/Open-CMSIS-Pack/devtools/pull/437), it will appear in the next release.

**Comment by brondani** [comment]
@tcsunhao Can you please test it with the latest CMSIS-Toolbox 1.1.0? Many thanks!
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.1.0
Please note the `output-dirs` are currently supported only at csolution.yml level.

**Comment by jkrech** [comment]
@tcsunhao we have not heard back from you on the above topic. Can you please help to validate the reported defect?

**Comment by tcsunhao** [comment]
Hi @brondani , I confirm that this issue has been fixed. (Sorry for this late reply, just found it during check).
