### ISSUE TITLE
Finding currently used packs programmatically

### ISSUE THREAD

**Issue by mumble-myopia** [Open-CMSIS-Pack/devtools#43]
When we release a binary, we need to record the version numbers of the various packs that went into it (so we can reliably reproduce it later).
Can anyone suggest a reliable way of achieving this please?

We use Keil uVision 5, Sourcetree/git under Windoze and don't (yet!) build our own packs.

**Comment by mumble-myopia** [comment]
ok ta - oddly it was Keil support that sent me here :-) Maybe they just thought I'd go away.
I use the Pack selector quite often but that is all manual and for selecting the pack used, for reliability I have to come up with a way of determining what was _actually_ use in a build.
As it happens I've done a bit more snooping and found a file generated as a part of the build process ($TARGET$.build_log.htm) which seems to contain the info I'm after - just need to store it somewhere

**Comment by jkrech** [comment]
@mumble-myopia could you please let me know the support ticket ID that pointed you here. I want to make sure this does not happen again (Joachim.Krech@arm.com)
