### ISSUE TITLE
Add generatordir to output-dirs

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#433]
The user/project should be able to control where generators are placing/creating files.

Proposal is to add a `generatordir` to the [output-dirs](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#output-dirs) field.
The `generatordir` would then update the `destination` for the [generator input file](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#workflow)

In the PDSC we can also introduce a `$G` parameter that would expand to the generator input file path so that generators easily can find it.

The Generator could still potentially create files anywhere it wants, but assuming the generator is a good citizen it can at least use the `destination` to try follow user wishes.

**Comment by ReinhardKeil** [comment]
Is the proposed $G the path to the [cbuild.yml](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md) file?

**Comment by slhultgren** [comment]
> Is the proposed $G the path to the [cbuild.yml](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md) file?

Yes, it probably should be. For now the https://github.com/Open-CMSIS-Pack/devtools/pull/462 implements $G expansion to the currently implemented `...generate.yml` file, to connect the $G to something.

Once we have the .cbuild.yml implemented, I think we can start to change $G to point to this and remove/replace the current ".generate.yml"-code.

Then we can see if we need to create a temporary more explicit copy of .cbuild.yml or not (basically just with all paths resolved absolutely everywhere instead of relying on relative/variables) but this can be discussed later, since the format would not require change, only the values.

**Comment by slhultgren** [comment]
Closing this issue since it has now been implemented and merged.
