### ISSUE TITLE
Force MSVC using UTF-8 encoding

### ISSUE THREAD

**Issue by yvesll** [Open-CMSIS-Pack/devtools#446]
**Description**
When I build the unit test locally, it may fail in target XmlReaderUnitTests:
```
devtools\libs\xmlreader\test\XmlReaderTest.cpp(1,1): warning C4819: The file contains a character that cannot
be represented in the current code page (936). Save the file in Unicode format to prevent data loss [devtools\
build\libs\xmlreader\test\XmlReaderUnitTests.vcxproj]
devtools\libs\xmlreader\test\XmlReaderTest.cpp(12,25): error C2001: newline in constant [devtools\bui
ld\libs\xmlreader\test\XmlReaderUnitTests.vcxproj]
devtools\libs\xmlreader\test\XmlReaderTest.cpp(13,1): error C2144: syntax error: 'std::string' should be prece
ded by ';' [devtools\build\libs\xmlreader\test\XmlReaderUnitTests.vcxproj]
```
It seems XmlReaderTest.cpp contains a char that Windows cannot map to the default code page (936 Simplified Chinese). For some users like me, it is not convenient to change the system locale, so hope we can tell the compiler use utf-8 in Cmakefile:
```
if(MSVC)
# disable C4819: for some users with a non-UTF8 encoding
  add_compile_options(/utf-8)
endif(MSVC)
```
**Environment**:
Windows Version: Windows 10 Enterprise
OS build: 19042.1889
MSVC Version: 14.31
System Locale: Chinese (Simplified China)

**Comment by brondani** [comment]
@yvesll Could you please check whether adding the `u8` string literal prefix before the special characters would solve the issue in your environment?
For example replace the [line 12 in XmlReaderTest.cpp](https://github.com/Open-CMSIS-Pack/devtools/blob/main/libs/xmlreader/test/XmlReaderTest.cpp#L12) by `static string utfInfo = u8"한€ह";`
Thanks!

**Comment by yvesll** [comment]
Hi, @brondani, the u8 prefix cannot work as this warning/error occurs at a very early stage. Another solution is using Unicode escape sequence `static string utfInfo = "\xED\x95\x9C\xE2\x82\xAC\xE0\xA4\xB9";`.
But it would be feasible to prohibit this by setting compiler options for MSVC.
Thank you!

**Comment by yvesll** [comment]
Thanks, @brondani, it works well!
