### ISSUE TITLE
Remove explicit time-stamps from generated files

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#449]
Currently there are generated files (like *.CPRJ) contain explicit **timestamp** information. Example:
```
<cprj schemaVersion="1.0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CPRJ.xsd">
  <created timestamp="2022-08-22T10:38:17" tool="csolution 1.0.0"/>
```

This creates a file with different content, even when there is no functional change in the file itself.  Since this file would be committed to version control systems, each time when it is recreated a new version would be pushed.  

I suggest therefore to remove this explicit **timestamp** fields from every generated file, as it is implicit already capture by the file system (Win, Linux, ect) as timestamp of the file.

**Comment by brondani** [comment]
Just in case tracking the modification date is important for anyone: git does not store file creation or modification dates. Apart from the commit date there will be no other timestamp information in a generated cprj stored in a git repository. Updating a file's modification date in the local filesystem won't be reflected in the repository's checked-in file.

**Comment by ReinhardKeil** [comment]
less important as *.CPRJ file will be replaced by *.cbuild.yml for the build process
