### ISSUE TITLE
PACKCHK: wrong M371 error?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#469]
Hi

```
*** ERROR M371: C:/xxx.pdsc (Line 761)
  Device Feature for 'STM32U599/5A9': 'MIPI' unknown.
```
We think it should be correct as MIPI is present in pack.xsd:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd#L896

Regards,

@tarek-bochkati

**Comment by jkrech** [comment]
This is a `packchk` defect. The features listed in the Pack Schema is most up-to-date and `packchk` needs to catch up. 
We should review whether packchk should avoid duplicating checks which are covered by the schema check.

**Comment by jeromecoutant** [comment]
packchk could include schema check ?

**Comment by jeromecoutant** [comment]
Correction is linked to #506? Is this correct ?

**Comment by thorstendb-ARM** [comment]
MIPI is part of PackChk since 26ad5ecce580c2e39c9e0b1548cba3e28386e83d :
`  m_featureTableDevice["MIPI"] = FeatureEntry("MIPI", "<feature type=\"MIPI\"/>", "MIPI");`

**Comment by jeromecoutant** [comment]
> MIPI is part of PackChk since https://github.com/Open-CMSIS-Pack/devtools/commit/26ad5ecce580c2e39c9e0b1548cba3e28386e83d

Which pachchk version ?

**Comment by thorstendb-ARM** [comment]
> > MIPI is part of PackChk since [26ad5ec](https://github.com/Open-CMSIS-Pack/devtools/commit/26ad5ecce580c2e39c9e0b1548cba3e28386e83d)
> 
> Which pachchk version ?

Not yet released, will do after https://github.com/Open-CMSIS-Pack/devtools/issues/657
https://github.com/Open-CMSIS-Pack/devtools/releases

**Comment by thorstendb-ARM** [comment]
see PackChk 1.3.98
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.3.98

**Comment by jeromecoutant** [comment]
Verified
