### ISSUE TITLE
[packchk] embed XML validation as an initial validation step

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#506]
This is a request to integrate an XML schema validation step in the `packchk` utility to avoid requiring the installation/presence of additional tools for the automated as well as manual pack creation and validation flows.
From experience we find that people miss to validate the schema compliance but fully rely on `packchk` instead. That tool however is limited to semantical validation and does not cover schema validation.

The schema validation should be run as a first step when invoking `packchk`. If the validation fails the program shall print out all available messages and bail out without running any semantic checks.

Consider command line options:
a) disable schema validation (default is "enabled")
b) option to specify the path to the PACK.xsd schema file

**Comment by fred-r** [comment]
@jeromecoutant : would you like to volunteer for implementing this ?

**Comment by jeromecoutant** [comment]
@fred-r I support the idea of this issue, but I can't implement :-)

**Comment by fred-r** [comment]
> @fred-r I support the idea of this issue, but I can't implement :-)

@jkrech : is it really mandatory to merge the tools with new CLI options ?
May we keep the tools separated but provide a wrapper ?

This wrapper would be the new entry point to have both checks systematically made ?

**Comment by jkrech** [comment]
I am not saying it is mandatory, however from my experience, asking people to install xmllint (in particular on Windows) as another prerequisite is a hurdle if not a barrier and I am not in favor re-distributing tools and utilities but in this case prefer to integrate some existing XML-Library to run the schema check from within `packchck` without creating an additional dependency. In csolution we do the same for checking the yml files while in cbuild we rely on a the command line option `-s` to include a schema check. In case xmllint is not found in the path you see this output.
```
cbuild -s "EventStatistic.Debug+AVH.cprj"
info cbuild: Build Invocation 1.1.0 (C) 2022 ARM
warning cbuild: xmllint was not found, proceed without xml validation
```

**Comment by jkrech** [comment]
@yvesll , @tcsunhao you kindly agreed to contribute this feature to packchk. Please let me know if you have any questions.

**Comment by yvesll** [comment]
@jkrech, in order to add a copy of the PACK.xsd in the repo, I have a discussion with @soumeh01. Sourabh suggests I track the tags of the file to make it flexible to manage the version of the file. So marking the open cmsis pack spec repo as an external submodule seems convenient as we can directly get any version of PACK.xsd. Or a more lightweight proposal is downloading the file from GitHub in runtime. 
Does anyone have different ideas or concerns?

**Comment by JonatanAntoni** [comment]
I think we could deliver the latest PACK.xsd with CMSIS-Toolbox. Fetching the XSD file for the referenced schema version from GitHub at runtime might be an option but requires internet access. I think we need to specify whether we want to use the XSD for the used schema version or always the latest schema (from either release point in time or fetched at runtime).

**Comment by jeromecoutant** [comment]
> I think we could deliver the latest PACK.xsd with CMSIS-Toolbox.

+1

Then user can overwrite schema file with a new one, or a patched one for test manually.

**Comment by jkrech** [comment]
packchk now runs a schema check is specified
```
packchk --xsd <PACK.xsd> <PDSC file>
```
using xerces schema library (statically linked)

**Comment by thorstendb-ARM** [comment]
Just had a look at the code, did I miss M217 ?
`  { "M216", { MsgLevel::LEVEL_ERROR,    CRLF_B, "Unable to get executable path %MSG%!"} },
  { "M217", { MsgLevel::LEVEL_ERROR,    CRLF_B, "Unable to get executable path %MSG%!"} },
`

**Comment by yvesll** [comment]
@thorstendb-ARM, sorry it seems a mistake for the duplicated log message. I reserved M217 but forgot to use it.

**Comment by jkrech** [comment]
I suggest to close this issue and open a separate one for removing the duplicated unused message.
