### ISSUE TITLE
[packchk] Add validation rule that detects a dependency rule satisfied by the component itself

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#510]
packchk requires an additional validation rule that helps the pack developer to detect a dependency that is implicitly 'resolved'.

Example:
```
component ARM::CMSIS:DSP:Synchronous Dataflow
   condition: <require Cclass="CMSIS" Cgroup="DSP" />
component ARM::CMSIS:DSP
```
When selecting the first component without selecting the second, there will be no unresolved dependency reported because the first component already satisfies the condition, despite the fact that it specifies a Csub. 
In order to require a component with an unspecified Csub the condition needs to read:
```
condition <require Cclass="CMSIS" Cgroup="DSP" Csub="" />
```

**Comment by thorstendb-ARM** [comment]
Proposal for error message:
`*** WARNING M389: ARM.GitHub#510.pdsc (Line 17) 
  The component 'ARM::C.G(cond1)[]' (Line 17) has dependency 'SW' : 'require C:G' that is resolved by the component itself.
`
