### ISSUE TITLE
[csolution] Add flag to convert command for a "non-lockfile" mode

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#511]
The command `csolution convert` generates a *.cprj file for each context. Within cprj all versions of packs and components are fully specified, regardless whether fixed versions are specified by the csolution/cproject/clayer.yml files. This is allowing reproducible builds based on the *.cprj files, even if `csolution` and `cbuild` are executed independently in different environments.

This request is for extending the `csolution` command line with a flag, which generates *.cprj files which reflect only the pack and component versions which are explicitly set in the csoltuion/cproject/clayer.yml files, thus retaining the "flexibility of selected versions" as intended by the author of the *.yml files. Such files are more suitable for use in tools only supporting the *.cprj format.

**Comment by jkrech** [comment]
csolution 1.3.0:
-e, --export arg      Set suffix for exporting <context><suffix>.cprj retaining only specified versions

**Comment by brondani** [comment]
Added `--export` flag into csolution 1.3.0 published in [CMSIS-Toolbox 1.3.0](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.3.0)
