### ISSUE TITLE
[projmgr] Schemas v1.2 for projects and schemas is not backward compatible with v1.1

### ISSUE THREAD

**Issue by madchutney** [Open-CMSIS-Pack/devtools#528]
With the change in `OptimizeType` and `WarningsType`, solutions/projects created to work with version 1.1 will fail schema validation checks for the new version 1.2 schema.

* The valid range of values for `OptimizeType` has changed from  `["max", "size", "speed", "debug"]`, to `["size", "speed", "balanced", "none"]`. The removal of `max` and the renaming of `debug` breaks backwards compatibility.
* The valid range of values for `WarningsType ` has changed from `["no", "all", "Misra", "AC5-like"]` to `["on", "off"]`. The removal of `all`, `Misra` and `AC5-like` breaks backwards compatibility.

Do the new versions of the tools (v1.2) accept or upgrade earlier (v1.0 and v1.1) solution/project files or will builds etc fail?

**Comment by brondani** [comment]
The old values were accepted only in the schema but their handling was never implemented.
What backward compatibility would mean here? Accept old values in the schema but ignore them (which is the old behaviour) doesn't sound clever. For this reason I believe the cleanest solution is to accept it as compatibility break an update projects that may have used it occasionally. 
@tarek-bochkati What is your take?

**Comment by VGRSTM** [comment]
I'm supporting @brondani answer. 
1.1.0 schema on this area has never been implemented if core processing. Was more kind of proposal (merged at a point unfortunately if we consider a strict process).

**Comment by brondani** [comment]
@madchutney Thanks for the feedback. As documented in the [progress table](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/progress.md), unfortunately we still have many features to implement that will occasionally cause disruption.
For future releases let's try to be more clear about such changes and follow your suggestions. In this sense I invite all contributors working on specification changes to strongly take compatibility in consideration.
Closing the issue.

**Comment by ReinhardKeil** [comment]
@madchutney yes we should do better. I made the term backward compatibility clearer in the documentation (https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md)
