### ISSUE TITLE
cproject should not specify more specific info than a core ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#541]
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#project

We understand:
- output-type = library
- processor = Cortex-M4

But not board and device ==> this is csolution's scope.

@slhultgren @iomint @VGRSTM @LMESTM @emmanuelgrandin

**Comment by jkrech** [comment]
@fred-r, the cproject format specifies the instance name of the processor in a multi-core device while on the csolution level the device is specified. 
See https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#device-name-conventions
`[Dvendor:: [device_name] ] [:Pname]`
The Pname is part of the device definition in the DFP and is a string identifying the processor instance (e.g. cpu0, cpu1 but more intuitive: CM0, CM4)
This way a target-type joins the projects for multiple processor instances.
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#processor

**Comment by jkrech** [comment]
@fred-r  I am not sure we answered your question above.
