### ISSUE TITLE
Problem by using gcc compiler

### ISSUE THREAD

**Issue by UniverGao** [Open-CMSIS-Pack/devtools#566]
When I used AC6 in *.csolution.yml, running `csolution convert -s *.csolution.ym`, the `*.cproj` could be generated
But when I changed it into GCC, some error happend:
`error csolution: no component was found with identifier 'ARM::Device:Definition'`
`error csolution: processing context 'Blinky.Debug+AVH_MPS3_Corstone-300' failed`
`error csolution: no component was found with identifier 'Keil::Compiler&ARM Compiler:I/O:STDERR&User'`
`error csolution: processing context 'Blinky.Debug+B-U585I-IOT02A' failed`
`error csolution: no component was found with identifier 'ARM::Device:Definition'`
`error csolution: processing context 'Blinky.Release+AVH_MPS3_Corstone-300' failed`
`error csolution: no component was found with identifier 'Keil::Compiler&ARM Compiler:I/O:STDERR&User'`
`error csolution: processing context 'Blinky.Release+B-U585I-IOT02A' failed`
I wonder if the toolbox support gcc compiler or I did someting wrong

**Comment by jkrech** [comment]
@UniverGao looking at the error output above, the problem does not seem to be the general support for the gcc compiler toolchain of the tools but rather the availability of components, since some of the software modules like e.g. assembler files are specific for a certain tool-chain.
