### ISSUE TITLE
Definition mismatch between Cvariant in pdsc and component in cproject yml file

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#600]
From https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd#L329
Seems that variant name could be a string "with no condition"

In https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L340
component and variant name are not "full" string and doesn't accept "(" for example

**Comment by jkrech** [comment]
@jeromecoutant this is something to discuss for all parts of the componentID.
Probably this should become a change request for the PACK.xsd schema to restrict the allowed characters and then align them with cproject/clayer schema file.

What exact requirements do you have/see?

**Comment by jeromecoutant** [comment]
Maybe space ?

ex:
`/ARM.CMSIS.pdsc:    <component Cclass="Device" Cgroup="Startup" Cvariant="C Startup"`

**Comment by jkrech** [comment]
Analyzing current package descriptions listed in https://www.keil.com/pack/index.pidx we find in:
`Cbundle`, `Cclass`, `Cgroup`, `Csub`, `Cvariant`

`A-Za-z0-9`
`space`
`_ - + . ' ( ) / `
` : ` found in Csub is the most troublesome

In conditions we additionally find `* ?`

No leading: `space - + . ' / ( )` found

**Comment by ReinhardKeil** [comment]
@jkrech can we come to a conclusion here?  Are there changes suggested? What exactly should change?

**Comment by jkrech** [comment]
Both the Pack Schema File (https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/tree/main/schema) as well as the csolution, cproject, clayer json schema files (https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/projmgr/schemas) shall be refined to restrict the allowed characters in componentIDs and to align on the exact same restrictions.

`
<xs:pattern value="[A-Za-z0-9_-+ . :' \(\)/ ]*"
`

**Comment by jkrech** [comment]
@soumeh01, could you please check the restrictions now present in PACK.xsd and match them with the componentID schema for the yml files so we are consistent.

**Comment by jkrech** [comment]
Will be part of cmsis-toolbox 1.5.0

**Comment by jkrech** [comment]
fixed in CMSIS-Toolbox 1.5.0
