### ISSUE TITLE
Problem of including file in C file

### ISSUE THREAD

**Issue by Osika91** [Open-CMSIS-Pack/devtools#610]
When I create a C file in VS Code and including a library.h for my board, VS Code says that the 'stm32f10x.h' file not found clang (pp_file_not_found). But I verify and this fils is include in this path : C:\Users\"name"\AppData\Local\Arm\Packs\Keil\STM32F1xx_DFP\2.4.0\Device\Include.
Does I need to include it manually or i forgot something else ?

Here is a sreenshot of my project and my C file :
<img width="964" alt="Sans titre2" src="https://user-images.githubusercontent.com/99325911/205682535-dbd19858-4b79-4973-bb70-ebec5dfd3209.png">

**Comment by jkrech** [comment]
@Osika91, it looks like you were able to solve your problem. Is there any learning or improvement required for people not to stumble over your problem?
Thanks.

**Comment by Osika91** [comment]
I solve a problem, the code in my main which was highlighted was nots recognize by the compiler I configure. When I use a compiler from MVSC (Microsoft visual studio) the code highlighted disapear. But after this I have another problem because the line 1 : `#include "STM32f10x"` is now highlighted.
First I don't think I'm using the good compiler for CMSIS project in vscode. And second I need to include some parameters for the projet like the board I use or other.

**Comment by ReinhardKeil** [comment]
@Osika91 did you complete the setup of the clandg extension as explained here https://github.com/ARM-software/vscode-cmsis-csolution/blob/main/README.md#install-and-set-up-the-clangd-extension ?

**Comment by Osika91** [comment]
Yes I think I've complete the setup of the clandg extension.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/99325911/205895430-bf3f1983-0cbc-4a48-b113-237eafb3df4a.png">
The path of cbuild and csolution are well set in the extension.

**Comment by ReinhardKeil** [comment]
The right forum for raising issues regarding VS Code extensions is here:  https://github.com/ARM-software/vscode-cmsis-csolution/issues

Could you check the file "RTE_Components.h".  It defines the CMSIS_device_header.  Is this identical with your header file?

Also there should be a `compile_components.json` file in the related `out` directory of the selected target/build type.  Could you check the content of that file.  It should include the compile commands used.

**Comment by Osika91** [comment]
Thanks you for your help.
In the "RTE_Components.h" i have this define : 
`#define CMSIS_device_header "stm32f10x.h"`

If I include `"stm32f10x.h"` in my C file I've another error which says me : 
`In included file: "Compiler generates FPU instructions for a device without an FPU (check __FPU_PRESENT)"clang(pp_hash_error)
core_cm3.h(90, 6): Error occurred here`

In the `compile_components.json` I have this content :

> [
{
  "directory": "C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/tmp/Open/Board/Debug",
  "command": "C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\armclang.exe -Ic:/Users/Romano/Documents/Nucleo/NewTest05/Premier/RTE/Device/STM32F103RB -Ic:/Users/Romano/Documents/Nucleo/NewTest05/Premier/RTE/_Open.Debug_Board -IC:/Users/Romano/AppData/Local/Arm/Packs/ARM/CMSIS/5.9.0/CMSIS/Core/Include -IC:/Users/Romano/AppData/Local/Arm/Packs/Keil/STM32F1xx_DFP/2.4.0/Device/Include -mcpu=Cortex-M3 -mfpu=none  -Wa,-defsym,\"STM32F10X_MD=1\" -Wa,-defsym,\"_RTE_=1\"  -g   --target=arm-arm-none-eabi -c -o CMakeFiles\\Open.Debug+Board.dir\\C_\\Users\\Romano\\Documents\\Nucleo\\NewTest05\\Premier\\RTE\\Device\\STM32F103RB\\startup_stm32f10x_md.o C:\\Users\\Romano\\Documents\\Nucleo\\NewTest05\\Premier\\RTE\\Device\\STM32F103RB\\startup_stm32f10x_md.s",
  "file": "C:\\Users\\Romano\\Documents\\Nucleo\\NewTest05\\Premier\\RTE\\Device\\STM32F103RB\\startup_stm32f10x_md.s"
},
{
  "directory": "C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/tmp/Open/Board/Debug",
  "command": "C:\\Keil_v5\\ARM\\ARMCLANG\\bin\\armclang.exe --target=arm-arm-none-eabi -Ic:/Users/Romano/Documents/Nucleo/NewTest05/Premier/RTE/Device/STM32F103RB -Ic:/Users/Romano/Documents/Nucleo/NewTest05/Premier/RTE/_Open.Debug_Board -IC:/Users/Romano/AppData/Local/Arm/Packs/ARM/CMSIS/5.9.0/CMSIS/Core/Include -IC:/Users/Romano/AppData/Local/Arm/Packs/Keil/STM32F1xx_DFP/2.4.0/Device/Include -mcpu=Cortex-M3 -mfpu=none -mlittle-endian -DSTM32F10X_MD -D_RTE_   -g   --target=arm-arm-none-eabi -c -isystem \"C:/Keil_v5/ARM/ARMCLANG/bin/../include\"  -o CMakeFiles\\Open.Debug+Board.dir\\C_\\Users\\Romano\\Documents\\Nucleo\\NewTest05\\Premier\\RTE\\Device\\STM32F103RB\\system_stm32f10x.o -c C:\\Users\\Romano\\Documents\\Nucleo\\NewTest05\\Premier\\RTE\\Device\\STM32F103RB\\system_stm32f10x.c",
  "file": "C:\\Users\\Romano\\Documents\\Nucleo\\NewTest05\\Premier\\RTE\\Device\\STM32F103RB\\system_stm32f10x.c"
}
]

**Comment by mcgordonite** [comment]
You can check if this is a problem with your intellisense set up in VS Code or a problem with your solution by running the build (e.g. the CMSIS: Build command from the command palette): if you see the same error when running the build, it is a problem with the solution, if not, then it is an intellisense problem.

Some things to check if it is an intellisense problem:
- Check that a .clangd file has been generated alongside the cproject file. That should point to a valid compile_commands.json that is also generated by the csolution extension.
- Check the CMSIS Build Manager output channel for errors.
- Ensure you have the clangd extension enabled and not the microsoft C++ extension.

**Comment by ReinhardKeil** [comment]
@mcgordonite for me the Microsoft C++ extension works fine.  Is this not compatible?

**Comment by mcgordonite** [comment]
It is possible to use the Microsoft extension, but you need to manually update the c_cpp_properties.json to point at a different compile_commands.json file when you change target or build type - otherwise you can get incorrect autocomplete or go-to-definition behaviour.

The csolution file automatically maintains a clangd file as the user changes target/build type, that's why we recommend clangd for now. In the near future we plan to add similar functionality to support the MS extension.

However, if your solution doesn't have multiple build & target types, or they are similar enough, you can get good intellisense with the MS extension.

**Comment by Osika91** [comment]
> @mcgordonite for me the Microsoft C++ extension works fine. Is this not compatible?

No of course here attached my project.
[NewTest05.zip](https://github.com/Open-CMSIS-Pack/devtools/files/10166719/NewTest05.zip)

**Comment by mcgordonite** [comment]
The startup file `startup_stm32f10x_md.s` provided by your `Device:Startup` component is legacy armasm. That's why armclang is failing to build it. You can pass `-masm=auto` to get around this. For example, extend your build types with a misc entry:
```
    - type: Debug
       misc:
         - ASM:
            - "-masm=auto"
```

**Comment by ReinhardKeil** [comment]
@Osika91 the following modifications to the *.yaml files will solve your issues:

**csolution.yaml:**
```
solution:

  compiler: AC6
  misc:
    - ASM:
      - -masm=auto   # to assemble old legacy source files

  build-types:
    - debug: "on"
      type: Debug

    - debug: "off"
      type: Release
```

**cproject.yaml**
```
  groups:
    - group: MyFiles
      files:
        - file: Premier.c   # add the source file to consider it for intellisense
```

**Comment by Osika91** [comment]
Thanks for you answer. I add a misc entry in my `name.csolution.yaml` but I still have an error :

> *  Exécution de la tâche : cbuild c:\Users\Romano\Documents\Nucleo\NewTest05\Premier\Open.Debug+Board.cprj 
> 
> info cbuild: Build Invocation 1.3.0 (C) 2022 Arm Ltd. and Contributors
> 
> M650: Command completed successfully.
> 
> M652: Generated file for project build: 'C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/tmp/Open/Board/Debug/CMakeLists.txt'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/tmp/Open/Board/Debug
> [1/1] Linking C executable C:\Users\Romano\Documents\Nucleo\NewTest05\Premier\out\Open\Board\Debug\Open.Debug+Board.axf
> FAILED: C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/out/Open/Board/Debug/Open.Debug+Board.axf
> cmd.exe /C "cd . && C:\Keil_v5\ARM\ARMCLANG\bin\armlink.exe --cpu=Cortex-M3  --debug       CMakeFiles/Open.Debug+Board.dir/C_/Users/Romano/Documents/Nucleo/NewTest05/Premier/RTE/Device/STM32F103RB/startup_stm32f10x_md.o CMakeFiles/Open.Debug+Board.dir/C_/Users/Romano/Documents/Nucleo/NewTest05/Premier/RTE/Device/STM32F103RB/system_stm32f10x.o -o C:\Users\Romano\Documents\Nucleo\NewTest05\Premier\out\Open\Board\Debug\Open.Debug+Board.axf  --list=C:\Users\Romano\Documents\Nucleo\NewTest05\Premier\out\Open\Board\Debug\Open.Debug+Board.axf.map && cmd.exe /C "cd /D C:\Users\Romano\Documents\Nucleo\NewTest05\Premier\tmp\Open\Board\Debug && C:\Keil_v5\ARM\ARMCLANG\bin\fromelf.exe --i32combined --output C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/out/Open/Board/Debug/Open.Debug+Board.hex C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/out/Open/Board/Debug/Open.Debug+Board.axf && cd /D C:\Users\Romano\Documents\Nucleo\NewTest05\Premier\tmp\Open\Board\Debug && C:\Keil_v5\ARM\ARMCLANG\bin\fromelf.exe --bin --output C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/out/Open/Board/Debug/Open.Debug+Board.bin C:/Users/Romano/Documents/Nucleo/NewTest05/Premier/out/Open/Board/Debug/Open.Debug+Board.axf""
> Error: L6218E: Undefined symbol main (referred from __rtentry2.o).
> Finished: 0 information, 0 warning and 1 error messages.
> ninja: build stopped: subcommand failed.
> error cbuild: error executing 'cmake' build
> 
>  *  Arrêt du processus de terminal "C:\Program Files\PowerShell\7\pwsh.exe -Command cbuild c:\Users\Romano\Documents\Nucleo\NewTest05\Premier\Open.Debug+Board.cprj". Code de sortie : 1. 
>  *  Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.

**Comment by Osika91** [comment]
Thanks you a lot, now the project can build. 
Thanks you very much for your help !

**Comment by Osika91** [comment]
Sorry but I have also a problem at the moment to flash the Device. It seems that the code is doesn't send to the device.
Here the output of the flash command : 

> *  Exécution de la tâche : embedded-debug.flash: Flash Device 
> 
> Device Selected: 066BFF545589564867122754
> Parse debug description...
> Create system description...
> Connect to debug unit (ST-Link)...
> Configure debug unit (SWD @ 10000000 Hz)...
> Create device map...
> Add Flash Algorithm...
>         'STM32F10x Med-density Flash' (0x08000000 - 0x0801ffff)
> Add Flash Algorithm...
>         'STM32F10x Flash Options' (0x1ffff800 - 0x1ffff80f)
> Connect ('haltOnConnect') to device STM32F103RB...
> Device connected
> Halt...
> Device halted after connect
> Reset ('auto')...
> Reset completed
> Load application...
> Erase sectors...
> Warning: No flash sectors erased!
> Sectors erased in 0.001 seconds
> Program flash...
> Warning: No flash pages programmed!
> Flash programmed in 0.001 seconds
> Verify flash download...
> Warning: No programmed flash content verified!
> Flash download verified in 0 seconds
> Reset & run target...
> Disconnect from device...
> Disconnect from debug unit...
> success
>  *  Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.

And we could see that therie is three warning like if the build is not send on the device.

**Comment by ReinhardKeil** [comment]
I think this is because the Device Family Pack (*.DFP) of this series is missing a linker scatter file with useful defaults.

You may add this locally to the project with this content:

**STM32F1xx.sct:**
```
LR_IROM1 0x08000000 0x00020000  {    ; load region size_region
  ER_IROM1 0x08000000 0x00020000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000000 0x00005000  {  ; RW data
   .ANY (+RW +ZI)
  }
}
```

And then add it to your `*.project.yaml` with:
```
 groups:
    - group: MyFiles
      files:
        - file: Premier.c
        - file: STM32F1xx.sct
```

**Comment by Osika91** [comment]
Thnaks you very much now it's working with the `*.sct` file !

**Comment by Osika91** [comment]
Hello I have again a question about the debug.

> Device Selected: 066BFF545589564867122754
> Parse debug description...
> Create system description...
> Connect to debug unit (ST-Link)...
> Configure debug unit (SWD @ 10000000 Hz)...
> Create device map...
> Parse dbgconf file...
> Connect ('haltOnConnect') to device STM32F103RB...
> Device connected
> Halt...
> Device halted after connect
> Reset ('auto')...
> Reset completed
> Load application...
> Warning: Compilation unit with unsupported DWARF v3 info: 'C:/Users/Romano/Documents/Nucleo/NucleoOpenclassrooms/Premier/RTE/Device/STM32F103RB/startup_stm32f10x_md.s'
> Verify loaded image...
> 	Code section: 0x08000000 - 0x08000457
> ERROR: Contents mismatch at: 0x8000000  (Target=0x60  Required=0x68) !
> ERROR: Contents mismatch at: 0x8000120  (Target=0xd0  Required=0x28) !
> ERROR: Contents mismatch at: 0x8000121  (Target=0x2  Required=0x3) !
> ERROR: Contents mismatch at: 0x8000124  (Target=0xe0  Required=0x38) !
> ERROR: Contents mismatch at: 0x8000125  (Target=0x2  Required=0x3) !
> ERROR: Contents mismatch at: 0x8000158  (Target=0x31  Required=0x6d) !
> ERROR: Contents mismatch at: 0x800019c  (Target=0x60  Required=0x68) !
> ERROR: Contents mismatch at: 0x80001a0  (Target=0x60  Required=0x68) !
> ERROR: Contents mismatch at: 0x80001a4  (Target=0x60  Required=0x68) !
> ERROR: Contents mismatch at: 0x80001a8  (Target=0x60  Required=0x68) !
> ERROR: Contents mismatch at: 0x80003be  (Target=0x0  Required=0xa) !
> ERROR: Too many errors to display !
> Verify done
> Go to 'main'...

When i want to debug my code I've this error on the debug console. Have you an idea of the problem ?

**Comment by jkrech** [comment]
@Osika91 
a) note that this issue is set to "Closed". It would be better to open a new issue and link to the previous one, if you think they are related.
b) You are using the Arm Embedded Debugger which is independent from this open-source Open-CMSIS-Pack project and you need to raise an issue here: https://github.com/Arm-Software/vscode-embedded-debug/issues/new/choose (as documented in the Extension)
If the content from the ELF file to be programmed is not the data that is being read from the target after flashing in the verify step, then probably something during the programming failed.
