### ISSUE TITLE
Files with `.update@<version>` are generated even when no `.base@version` file is present

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#613]
Environment: csolution 1.3.0
Project: https://github.com/Open-CMSIS-Pack/AWS_MQTT_MutualAuth_SW_Framework

With command `csolution convert -s Demo.csolution.yml` two files in the directory `Board\B-U585I-IOT02A\RTE\Device\STM32U585AIIx` have an extension `.update@1.0.0` which seems to be wrong.  Expected is the extension `.base@1.0.0`.

![image](https://user-images.githubusercontent.com/8268058/205932694-c2dad504-814e-493b-bcf4-79c7a1ffcf57.png)

**Comment by edriouk** [comment]
That is intended behavior. Update file always gets created if:
- file version visible in the pack differs from base one
- the is no base file available  
Base files gets created only if current file version corresponds to the version visible in the pack:
- component just added
- component just updated 
- file version is available from another source (cprj, uvprojx) and it equals to the current version in the pack

It is impossible to create a base file if its version not known.

**Comment by ReinhardKeil** [comment]
@edriouk thanks for the explanation, however in the case that I show above use a single component `- component: Keil::Device:Startup`.  It creates a mix of `.base` and `.update` files.  Based on your explanation, I would just expect `.update` files.

I would also propose that we slightly change behavior to:
  - `.base` file is created when the `config` file is the first time copied to the project RTE space
  - `.update` file is only created when there is a `.base` file in the project RTE space

Effectively this means, if the user does not preserve the `.base` file in the version control system, `csolution` cannot tell if there is an update required or not.  We should make it an requirement to preserve `.base` files.

**Comment by ReinhardKeil** [comment]
Fixed in CMSIS-Toolbox 1.4.0
