### ISSUE TITLE
Incorrect Assembler used for AC6 on STM32F1 targets

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#614]
Environment: csolution 1.3.0

The attached project does not compile correctly using the following commands:

```
csolution convert -s Premier.csolution.yaml
cbuild Open.Debug+Board.cprj
```

Test Project: [Asm-Fail.zip](https://github.com/Open-CMSIS-Pack/devtools/files/10167390/Asm-Fail.zip)

**Comment by ReinhardKeil** [comment]
Would it be a problem to have `-masm=auto` as default?

**Comment by brondani** [comment]
> Would it be a problem to have `-masm=auto` as default? This seems to be the default in uVision right now.

Today I think it would not be a problem, but the `-masm` option [will be removed from the Arm Compiler](https://developer.arm.com/documentation/101754/0619/armclang-Reference/armclang-Command-line-Options/-masm?lang=en):

> Arm Compiler for Embedded 6 provides the -masm option as a short term solution to enable the assembly of legacy armasm syntax assembly source files. The -masm option will be removed in a future release of Arm Compiler for Embedded 6.

**Comment by ReinhardKeil** [comment]
OK, thanks for pointing it out.  We will just recommend to use - masm=auto for the time being.
