### ISSUE TITLE
Proposal: Investigate on how to "Minimize Toolchain Specific files in DFPs"

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#616]
Currently there are several toolchain specific files in DFPs (i.e. startup code in assembly language, linker scatter file, etc.).

I suggest that we investigate into options on how to minimize this, for example with:
  - startup code that is a pure C implementation (and ideally works for any compiler)
  - linker configuration that works via a header file (i.e. `memory-layout.h`) that is input to a C pre-processor

>Relates to #615

**Comment by ReinhardKeil** [comment]
C startup code exists already here https://github.com/ARM-software/CMSIS_5/tree/develop/Device/ARM/ARMCM3/Source

Could we make it device agnostic by generating the interrupt vector table using CMSIS-SVD and include this vector table file instead?

**Comment by ReinhardKeil** [comment]
@JonatanAntoni I think changing the startup component to `C` files and working on a linker script with `regions_<device_or_board>.h` (as in https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Linker%20Script%20File%20(Proposal).md) is all we need.

Could you create an example

**Comment by jkrech** [comment]
The linker topic is further discussed in #655

**Comment by ReinhardKeil** [comment]
Investigation has been completed.  Result: Linker Script generation, C startup code. 

Still open is the Flash algorithm, but there might be a solution that works.  This is currently in investigation.
