### ISSUE TITLE
headerC and includeC paths not added to the #include search paths

### ISSUE THREAD

**Issue by massonal** [Open-CMSIS-Pack/devtools#620]
Hi,

In a component I work on, I have a header file that is strictly meant for C code (i.e., no C++ guards, ...).
I have put it in its own subfolder, and described it in the pdsc as a "headerC" file.
The build then fails with the following message: 
> .../utilities/my_util/a_file.c:24:10: fatal error: 'c_specific_header.h' file not found
> #include "c_specific_header.h"

However, this error disappears when I describe the file as a staight "header".
I have also made experiments with "include" vs "includeC", and I observe the same outcomes.

Build with `open-cmsis-build`:
> cbuild version 1.3.0 (C) 2022 Arm Ltd. and Contributors

From looking at the actual compiler calls, I have found that the subfolder I put that header in did end up as a `-I` flag (illustrating with GCC) _only_ when I used "header"/"include", and not when I became specific with "headerC"/"includeC".

I conclude the build tool deviates from the specs as described [here](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#FileCategoryEnum).

Regards.

**Comment by jkrech** [comment]
Sorry for the lack of clarity when it comes to "supported features" of the specification. At this point the tools only support the features specified up to Version 1.7.7 - please see the revision history here: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pack_revisionHistory.html 
This is the reason why includeC is currently ignored.

**Comment by massonal** [comment]
Thanks for the feedback!

For my information, do you know when the tool will catch up on the spec ?

**Comment by ReinhardKeil** [comment]
I believe we could do better with this type of extensions, but adding a `language` and `scope` attribute.  In this way we would not create so many issues with backward compatibility.

This applies also to https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/176

In practice:
```
     <file category="header" name="Device/Include/system_stm32f2xx.h"/>    # applies to all languages
     <file category="header" name="Device/Include/system_stm32f2xx.h" language="C"/>    # applies only to C
     <file category="include" name="Device/Include" scope="private"/>    # applies only to components of that cClass
     <file category="include" name="Device/Include" language="C" scope="private"/>    # applies only to components of that cClass source type C
```

As new attributes are ignored by old tools, there would be some sort of acceptable backward compatibility.  Over time tools can pick up the new features.

**Comment by ReinhardKeil** [comment]
Are we in alignment to implement the **File category mapping [#175](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/discussions/175)/[#176](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/176)** as proposed in:
https://linaro.atlassian.net/wiki/spaces/CMSIS/pages/28807004186/Open-CMSIS-Pack+Technical+Meeting+2022-12-13

**Comment by jkrech** [comment]
a) we need to revert https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/28 
b) get the new proposal reviewed and accepted for the specification.
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/186

**Comment by jkrech** [comment]
Note, the specification has changed as indicated already above:
The support for the language and scope attributes has been added to `cbuild2cmake` which is the default CMakeLists generator starting CMSIS-Toolbox 2.5.0
The test cases can be found here: https://github.com/Open-CMSIS-Pack/cbuild2cmake/tree/main/test/data/solutions/language-scope - e.g.:
```
<file category="include" language="c-cpp" scope="private" name="LanguageAndScope/Private/"/>
```

Please let us know whether this satisfies your expectations.

**Comment by massonal** [comment]
Hi,

As I said in [issue #186](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/186), that proposal fulfills my needs. I think this issue can be closed now.
