### ISSUE TITLE
Open: Define Workflow with CubeMX Generator

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#626]
The current CubeMX workflow relies on the STM32CubeMX Launcher (which is a Windows only software).
It is also required to use a run command as shown below:

csolution run -s Premier.csolution.yaml -g STM32CubeMX

**Current Problem:** CubeMX is called multiple times, for each context. Specifying a context a the csolution command would solve the problem, but still creates some user confusion.  With the proposal below it should be possible to use `csolution list generators` to get a list of all existing scripts.

**Proposal:**
a) We should define a workflow that works on any supported operating system (Linux, Win, MacOS).  The STM32CubeMX Launcher might be replaced by a PATH environment variable setting that is created with CubeMX installation.

b) Perhaps the run command could be replaced by scripts (or batch files) that start the relevant generator.  This scripts could be generated using `csolution convert`.  Then only the script needs to be executed.

**Open:**
Open is still a workflow that would work for cloud based IDEs.  A potential solution is to display a README.md with manual instructions on how to run CubeMX.

**Bug:**
Note that the current workflow has also a problem with the directory for the generated files.
It uses `.\generated\STM32L476RGTx`
Instead of `.\RTE\Device\STM32L476RGTx`    <- this works in MDK

I guess there is some further testing with layers required as the location of the .\RTE directory may differ.  

This is an project that shows this issue
[Premier.zip](https://github.com/Open-CMSIS-Pack/devtools/files/10196199/Premier.zip)

**Comment by fred-r** [comment]
Regarding point (a) ==> this request has been shared with the CubeMX team.

**Comment by ReinhardKeil** [comment]
Is the issue listed under "bug" already solved?

**Comment by jkrech** [comment]
No, this bug is still present due to the <workingDir> specified in the PDSC being overruled by the default "gendir" assumed by csolution.

I think https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/207 needs to be extended in such a way that for backward compatibility we need to honor the <workingDir> from the pack if it is explicitly specified.

**Comment by ReinhardKeil** [comment]
closing this issue as it is covered somewhat by https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/207 and #832.  The bugs itself have been addressed.
