### ISSUE TITLE
Diagram for loading project files is low resolution

### ISSUE THREAD

**Issue by benmcmorran** [Open-CMSIS-Pack/devtools#63]
[This diagram](https://github.com/Open-CMSIS-Pack/devtools/blob/main/libs/rtemodel/docs/ProjectLoad.png) is very low resolution and impossible to read.

**Comment by jkrech** [comment]
Thanks for raising this. Let me just check whether this is better before getting the repo updated:

![ProjectLoad](https://user-images.githubusercontent.com/8290187/143445547-be11ea64-65cd-4aba-8cd2-e5d820a3b4d3.png)

**Comment by benmcmorran** [comment]
That looks much better. Thanks a lot!
