### ISSUE TITLE
Include path search order

### ISSUE THREAD

**Issue by JonTBeckett** [Open-CMSIS-Pack/devtools#644]
Hi, 
I'm working on migrating from Keil uVision to the CMSIS solution toolchain and one thing I'm bumping into an issue with include path order. The project I'm working on has some header files duplicated in multiple places so we have specifically ordered our include paths to get the ones we want. When building with cbuild and csolution, the Component header files are always being placed before all of the individually added paths. 

Is there currently any way to place the Component include paths last in the compile commands?

Obviously this isn't a long-term need. I'm hoping to push the team towards componentization so that our reusable chunks are components in packs that are organized such that we don't have duplicate header files anyway. But I need to be able to show that csolution and cbuild will serve us well right now if we want to switch to it before getting too far along. 

Thanks for any info you might be able to give!

**Comment by ReinhardKeil** [comment]
@JonTBeckett thanks for rising this issue. 

The current implementation of the include paths in csolution is:
  - all user defined include paths are added first
  - include paths that are defined in packs are then added.

The file `*.cbuild.yml` that is generated by the csolution tool lists all include paths in order (see `add-path:`.  This would give you a good starting point to validate the order of include paths.

In the Open-CMSIS-Pack Technical Workgroup we are currently discussing ways to reduce scope of header files.  It would be good to understand your expectations. Could you explain your problem a bit further?

**Comment by ReinhardKeil** [comment]
@JonTBeckett you are correct, the CBUILD tool is wrong.  It has the wrong order of include paths and does not yet use the information of the `*.cbuld.yml` file.  It is on the roadmap to change that tool. 

Still it would be useful to understand your expectations.

**Comment by JonTBeckett** [comment]
@ReinhardKeil thanks for the reply! Yes, the include order in compile_commands.json doesn't match the order that they are listed in the *.cbuild.yml. The exact issue I'm bumping into is that we are using some customized device files (startup and system startup files etc.). We are still including the DFP pack from Keil to get the debug and flash support though. Since the DFP has the original version of the device headers and the DFP headers are being included ahead of the user headers, we aren't able to include our customized versions of the files. 

The intended function you described in the first comment where the user headers are included before the packs would work for our needs!

**Comment by ReinhardKeil** [comment]
Decision: fix the order of include in cbuild

**Comment by JonatanAntoni** [comment]
@JonTBeckett, may I ask you which files from DFPs you duplicate? And why?

**Comment by JonTBeckett** [comment]
I'll have to go back and try to reproduce it when I get a chance. I have some time dedicated to it coming up next week so I may have a better answer for you then.

I can't remember off of the top of my head which file it was. I'm not sure if it was the device header or one of the HAL/LL files. 

The reasoning for a modified version though predates my time with the company and I haven't had time allocated to it to really dig in. I've just been doing this on the side while I'm waiting for a build or some tests to run. But I know that STM32 Cube was used to generate all of the HAL/BSP/Drivers. The output of the Cube was then placed in a private repo and the files manually added to Keil uVision as needed. It just hasn't been an issue in Keil since the user includes are placed before the pack includes.

I am working towards breaking our project down into multiple CMSIS Packs and would like to have our own DFP anyway. So if I can get that together this won't be a big issue. But that is a ways off.

**Comment by JonatanAntoni** [comment]
@JonTBeckett, thanks for confirming. So, I guess there is no underlying lack of feature to support your use case, i.e., create your own DFP would be the clean solution. I agree that we need to check the include path order, anyway.

**Comment by JonTBeckett** [comment]
I agree. It would be nice to have the user includes first though. Even if it is only to make migrating from Keil a little bit easier. 

Another aspect I have to consider for migrating is the final binary. So being able to match the compile commands as closely as possible between the two would be ideal. Hopefully converting our reusable components to Packs increases the compile command consistency.

**Comment by jkrech** [comment]
This include path search order got corrected in CMSIS-Toolbox 1.5.0

**Comment by JonTBeckett** [comment]
Just wanted to come back and say thanks for getting this small issue pushed through and release so quickly! I've updated to 1.5.0 and am now able to get a build with near binary equivalence to Keil! I'm hoping I can send this up the food chain now and convince the rest of my team and some other teams to switch from Keil to CMSIS build in VS Code.
