### ISSUE TITLE
Access to schema files for *.yml input files

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#645]
Currently the schema files are accessible via 
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/1.4.0/tools/projmgr/schemas/cproject.schema.json
```
Is there a way to make this path:
  - version agnostic
  - shorter

Is it possible to put the schema under the CMSIS-Toolbox github project?

**Comment by jkrech** [comment]
What is the benefit of being version agnostic?
Any "writer" human or machine should identify the schema version it is set to comply with. The editor Schema checking plug-in will download and use that version. Any "consumer" reading it has clear information which version the file is based on.
Where exactly a schema file is stored is secondary but we should make sure there is a single source/location of truth.

**Comment by ReinhardKeil** [comment]
It is important for guidelines on how to distribute `csolution` based project examples that are perhaps used with a newer version of csolution.  This version is upward compatible, but has perhaps new features that would be flagged as error when user enters it.

However the VS Code extensions seem to automatically add the relevant schema.  It is not required to add the line:
```
# yaml-language-server: ...
```

**Therefore the guideline should be to remove this line.**

The initial request is no longer relevant.
