### ISSUE TITLE
Align RTE Directory Structure

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#646]
**CBuild** no longer re-creates the content of `<project>/RTE/<context-dir>` .  For CI processes that just use **CBuild** to build the executable, it is therefore required to preserve the complete content of the `./RTE` directory.

See: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#rte-directory-structure

IMHO we should therefore harmonize the behavior of various tools. 
 - When a CPRJ file is imported into uVision, the context directory has just the name  `_<build-type>_<target-type>`. 
 - With csolution the directory has the name `_<project-name>.<build-type>_<target-type>`.

@JonatanAntoni is there any reason to keep the csolution directory naming for CI build processes?  Obviously this would mean that it limits a build process that uses only CBuild to just one `cproject.yml` per `<project>` directory.  However, if the `csolution` tool is used to recreate the `*.CPRJ` files this limitation does not apply.

**Comment by jkrech** [comment]
If each `<project>`  has its own directory I cannot see why to include the project name in the `<context-dir>` unless the RTE directory is renamed.

**Comment by ReinhardKeil** [comment]
Decision: csolution uses `_<build-type>_<target-type>`

**Comment by jkrech** [comment]
see CMSIS-Toolbox 1.5.0
