### ISSUE TITLE
CMSIS-Toolbox files .\etc\CMakeASM

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#647]
Are the files in the directory ` .\etc\CMakeASM` still relevant?  If not, can they be removed for the next version?

**Comment by brondani** [comment]
The files in this directory are relevant for handling projects with multiple different assembly variants, which is not supported in the CMake upstream.
CMake uses the compiler information files from this directory to find the correct assembler associated to each assembly source file.
We can investigate about removing it if we agree to not support legacy assemblers anymore (`armasm` for AC6 and `gas` for GCC).

**Comment by jkrech** [comment]
For the time being these files are still relevant and are "included" by AC6.6.18.0.cmake line 590:
`set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/CMakeASM")`
