### ISSUE TITLE
[csolution/packchk] 'name' attribute specifying folder in pack with file element causes segmentation fault.

### ISSUE THREAD

**Issue by smartinou** [Open-CMSIS-Pack/devtools#657]
Packs that have a file element + name attribute of the form:
<file category="source" name="source_path/" ... </file>

... cause a segmentation fault when attempting to convert the solution:
$ csolution convert -s <project>.csolution.yml
Segmentation fault (core dumped)

This was discovered while editing a custom CMSIS pack.

Looking at the doc for the 'name' attribute, it is clearly mentioned "in the format path/name.extension", so I was likely wrong to specify it as "path/". Yet, a segmentation fault seems a bit harsh.

packchk did not reject this construct, so maybe a bug should be raised against it too.

Found in v1.3.0

**Comment by jkrech** [comment]
Fixed in packchk 1.3.98 - 
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.3.98
included in CMSIS-Toolbox 1.5.0 
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.5.0
