### ISSUE TITLE
Are we able to "link" multiple cprojects thinking build process ?

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#662]
Possibly I've missed some steps so please comment and feel free to close if not relevant.

Where are we if we have at `csolution` project build time to manage dependencies between `cproject`s ?

Based on `.cprj` we had got capability to add as primary entry of one project the build artifact outputs from another.
Still related to `.cprj` era we have got some idea introducing a so called [MCPRJ](https://github.com/Open-CMSIS-Pack/devtools/issues/171).
Today we are embracing `*.yml`, we are getting some [`cbuild-idx.ynml`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md#file-structure-of-cbuild-idxyml), etc.

**Comment by ReinhardKeil** [comment]
Yes, this is on our ToDo list. But thanks for raising it again. I leave this open for now.

**Comment by jkrech** [comment]
In the context of reviewing CMSIS-Toolbox 2 we should agree on a phased approach.
a) for CMSIS-Toolbox 2 projects are built in the order they are listed in csolution and Code Sequences are used to reference outputs from other projects
b) once we deprecate cprj and revise the CMakeLists file generation to cover the solution the project inter-dependencies expressed through Code Sequences should be evaluated by build system used by CMake.

**Comment by VGRSTM** [comment]
I agree 2 steps proposal. Sounds like pragmatic way to go. Thanks !

**Comment by ReinhardKeil** [comment]
We take a two-step approach:
  - CMSIS-Toolbox 2: document the deployment process as current `csolution` supports a multi-project approach and `context-map:` does allow how the individual
  -  later enhancements: add features to CMSIS-Toolbox >2 to check dependencies, create an overarching CMakeLists, etc.

**Comment by jkrech** [comment]
In scope for CMSIS-Toolbox 2.0.0:
https://github.com/Open-CMSIS-Pack/cbuild/issues/25 => build contexts of a common `configuration` in the order they are listed in the csolution.yml
https://github.com/Open-CMSIS-Pack/devtools/issues/450 => add support for `context-map` in csolution.yml

**Comment by jkrech** [comment]
Released CMSIS-Toolbox 1.5.0 implements support for building 'configurations' but does not support `context-map`.

**Comment by ReinhardKeil** [comment]
Somewhat covered in #823 and #450 - hence consider this as duplicate and closing
