### ISSUE TITLE
component search issue in open CMSIS pack

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#668]
I’ve got an issue with Open-CMSIS-Pack toolbox running NXP RT1064 hello world project
I use the rt1064 board and MIMXRT1064xxxxA, but the csolution convert output gets clock from MK64F12 pack. 
![image](https://user-images.githubusercontent.com/3381677/212916197-0748b5d0-0ac2-4088-a784-8e9acafe4c2f.png)

If I add 'pack' in csolution to specify the pack like:
![image](https://user-images.githubusercontent.com/3381677/212916423-b172c973-5347-44cb-a4a3-6fb7bf675e76.png)
then open CMSIS pack tool can get correct clock from rt1064 pack. So We think the dependency for csub clock is ok in RT1064 pack.

It is not correct to use component from another device pack for irrelevant device project

**Comment by ReinhardKeil** [comment]
What is the condition on the component `NXP::Device:SDK Drivers:clock` in the MK64F12 pack?

Can we get the test project (please configure it for failure)?

**Comment by tcsunhao** [comment]
Sorry @ReinhardKeil , it could be our dependency issue. We are checking.
