### ISSUE TITLE
Custom RTE directory computation replaces whitespaces

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#676]
Take the project [reproducer.zip](https://github.com/Open-CMSIS-Pack/devtools/files/10467391/reproducer.zip) with the following customization: `rtedir="../white space/RTE"`

When running `cbuildgen` the whitespace in the path is replaced by an underline so the files inside RTE are not found:

```
$ cbuildgen cmake whitespace.Debug+ARMCM3.cprj

*** ERROR M204:
  Path not found: 'C:/Temp/csolution_test/reproducer/white_space/RTE/Device/ARMCM3/ARMCM3_ac6.sct'!
```

**Comment by edriouk** [comment]
That is intended. It was introduced to ensure MDK operation.

**Comment by edriouk** [comment]
The idea behind replacing white spaces is to simplify file operations for components that have a white space  in Cclass attributes, e.g. "CMSIS Driver". We have to keep that behavior to keep old projects working. 

However, only spaces after RTE folder should be converted, keeping spaces above or in the RTE folder itself.

**Comment by edriouk** [comment]
Fixed
