### ISSUE TITLE
[cbuildgen] Project with assembly source file (.S) for IAR fails with CMake 3.21.3

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/devtools#684]
A [project](https://github.com/Open-CMSIS-Pack/devtools/files/10491561/cbuild_iar.zip) containing an assembly source file (extension `.S`) fails to compile with IAR Compiler when using CMake 3.21.3. With later CMake 3.25.2 this issue got fixed.

Shall we increase the minimum CMake version (at least for IAR Compiler) to a version where this issue is fixed?

cc: @tarek-bochkati

**Comment by jlonnberg** [comment]
@JonatanAntoni  @brondani 
Some questions on this. I'm seeing problems with the latest versions of cmake as well, linked to file-specific defines.
Is the design made so that a file should be given the superset of defines or should file-specific defines replace general defines?
Moreover, could you please elaborate a bit on the problem that you encountered with version 3.21.3?

**Comment by JonatanAntoni** [comment]
Hi @jlonnberg,

Files with `.S` extension are not considered for compilation. See the attached [reproducer example](https://github.com/Open-CMSIS-Pack/devtools/files/10491561/cbuild_iar.zip). The `reproducer.cprj` contains a (commented out) `Reset_Handler.S` file entry. Once you uncomment this line and run it with cmake 3.21.3 it is not compiled. With a later version it is compiled.

The discussion about defines should probably go into a separate thread for better visibility. I'd rely on @brondani to give the details. If I am not mistaken defines are additive, i.e. defines from global (solution and project) scope, file group scope and per file. I do not know from the top of my head if one can undefine a define given in a wider scope.

Cheers,
Jonatan

**Comment by brondani** [comment]
@jlonnberg file-specific [defines](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#define) and [undefines](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#undefine) are applied to values inherited from parent groups that in turn inherit them from (in the order) build type, target type, csolution, project setup, cproject.
If you are observing unexpected behaviour please feel free to open a dedicated GH issue, possibly with a reproducer so we can investigate together.

**Comment by jlonnberg** [comment]
@JonatanAntoni So what's the rationale behind using capital letters for assembler files? Is it not some sort of standard, at least for linux, to use lower case.

Moreover, I've seen additional problem with that version of cmake so to me, it sound like a good idea to force the usage of a later version of cmake. Should that be done in the generic cmake or just for the IAR Toolchain, as perhaps it might be a good idea to keep up with the changes in cmake on a global level?

**Comment by JonatanAntoni** [comment]
@jlonnberg, if I am not mistaken, we use lower letter `.s` for plain assembly files and capital letter `.S` for assembly files that need to go through the preprocessor. GCC automatically recognizes the capital letter, see https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html. How does IAR compiler handle this?

And well, yes. I asked above if we should update the minimum CMake version at least in the IAR Compiler cmake file. I didn't try all intermediate version but just 3.25.2 which worked for me.

**Comment by jlonnberg** [comment]
So, the IAR Assembler always runs the preprocessor regardless. This was the first time I heard of conditional preprocessing for assemblers. However, the example that you provided will not build with an IAR toolchain but I will try to fix it and add it as a test to the IAR test suite

I think that it's resonable to bump the cmake version required to 3.25 for IAR's toolchain.

**Comment by JonatanAntoni** [comment]
@jlonnberg, with IAR 9.30.1 I didn't recognize any issues once fixing the CMake issue. If IAR compiler runs assembly through the preprocessing anyway, we can even change the IAR assembly files to lower `.s`. Anyway, the major goal in `csolution` is to reduce compiler dependencies as much as possible.

In inline assembly IAR compiler supports GNU assembly syntax (GAS). What about freestanding assembly modules. Is there a "compatibility" mode so that GAS files could be used with IAR compiler as well?

**Comment by jlonnberg** [comment]
@JonatanAntoni  Yes, there is inline support, but for explicit assemblerfiles the syntax is really different. So the project you sent can be translated to a cmake-file with all included source-files but it should not build (at least for me it does not...)

I guess that the supplier of the cprj file will need to provide assembler files that is compatible with the selected toolchain.

**Comment by JonatanAntoni** [comment]
@jlonnberg, oh, indeed. I changed the syntax on my machine to match IAR to make it work. Sorry, my fault.

[cbuild_iar.zip](https://github.com/Open-CMSIS-Pack/devtools/files/10722508/cbuild_iar.zip)

**Comment by ReinhardKeil** [comment]
@JonatanAntoni is this problem fixed by now?

**Comment by JonatanAntoni** [comment]
@ReinhardKeil, as indicated in the report above the problem is in CMake and requires the user to use a recent version of CMake to be on the safe side. We specify `cmake_minimum_required(VERSION 3.22)` in the generated `CMakeLists.txt` files. If I am not mistaken the discussed issues are solved in 3.22
