### ISSUE TITLE
Check on GCC version used (nice to have enhancement)

### ISSUE THREAD

**Issue by JacobBarthelmeh** [Open-CMSIS-Pack/devtools#696]
Ran into this also (https://github.com/Open-CMSIS-Pack/devtools/issues/21) with the default GCC (7.5.0) on Ubuntu 18. Was trying the approach of just building it, hitting cmake and diving in before reading the docs. Quickly moved on to trying a newer version of GCC but it would be nice to have a warning on GCC version printed out during compile. Something like a check on `__GNUC__` macro in the code or a check in the CMakeLists.txt.

**Comment by JonatanAntoni** [comment]
@JacobBarthelmeh, Could you please check if the addition in #698 does the job for you?

**Comment by JacobBarthelmeh** [comment]
It printed out a helpful warning with the default gcc 7.5.0 on the older Ubuntu. Seems good.
