### ISSUE TITLE
[csolution/cbuildgen] Improve the toolchain registration

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#699]
Today the user of the tools is required to register a toolchain by creating a copy of a toolchain version specific cmake file located in the $CMSIS_COMPILER_ROOT (default `../etc`).
`AC6.<version>.cmake`
`GCC.<version>.cmake`
`IAR.<version.cmake`

Inside the cmake two variables can be edited:
`TOOLCHAIN_ROOT` -> pointing to the bin directory of the toolchain
`TOOLCHAIN_VERSION` -> specifying the major,minor and patch version of the toolchain

Instead of specifying the TOOLCHAIN_ROOT an environment variable e.g. `GCC_TOOLCHAIN_<version>` can be specified.

This system requires to maintain one cmake file per registered toolchain.

Assuming that many toolchain versions are widely compatible the proposal is to use a single cmake file for multiple toolchain versions. The version in the cmake filename no longer specifies a fixed version but the minimum toolchain version that is 'sufficiently' compatible. Once a breaking change is introduced by a toolchain version an additional cmake version will get added to the 'etc' directory and any toolchain version greater or equal to this version will use the newly added cmake file.

If no environment variable is set for a toolchain, then the heuristic search of CMake will be used to try and find a suitable toolchain in the system.

Note:
One anticipated use case is for toolchain versions being managed as `vcpkg artifacts`. As part of the activation the corresponding environment variable will be exported by vcpkg. This way csolution does not rely on the order in the PATH and does not need to inquire the version from the toolchain.

**Comment by ReinhardKeil** [comment]
I like that approach as it is simple and easier to understand.

Would it be possible to write the *.cmake files in a way that they issue a warning if an unknown option is passed.

**Comment by VGRSTM** [comment]
Sounds good to me in the way it improves running proposal limiting toolchains description updates.

**Comment by jkrech** [comment]
CMSIS-Toolbox 1.5.0
