### ISSUE TITLE
[RTE Model] Add support for new file attributes `language` and `scope` 

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#701]
The CMSIS-Pack specification of the `<file>` element was extended with the attributes
`language`
`scope`
(see request https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/186)
Specification: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#element_file

**Comment by edriouk** [comment]
The requested functionality is implemented in RTE model
