### ISSUE TITLE
[csolution] Add support for new component file attributes `language` and `scope`

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#702]
Specification: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#element_file

The new attributes allow to use header files and include paths exclusively depending on the specified language for c-compiler, c++ compiler, assembler or linker.
The scope attribute specifies whether or not a header file is advertised for explicit include by other modules outside the component (hidden vs. visible)
The scope attribute specifies whether or not an include path is limited to the build of the modules of a component or set globablly (public vs. private)

**Comment by brondani** [comment]
Also see https://github.com/Open-CMSIS-Pack/devtools/issues/701

**Comment by brondani** [comment]
Pending issue: include paths with "private" scope can be retrieved with the `RteTarget::GetPrivateIncludePaths` function, but not header paths with "hidden" scope.
Note that all include paths with none or "public" scope and header paths with none or "visible" scope are returned by `RteTarget::GetIncludePaths`.

**Comment by brondani** [comment]
https://github.com/Open-CMSIS-Pack/devtools/pull/1011 brings the implementation and tests in `csolution`.
No change in Build Manager for the time being.

**Comment by jkrech** [comment]
see CMSIS-Toolbox 2.0.0-dev3
