### ISSUE TITLE
[RTE Model/csolution] Add condition evaluation for `Bvendor` `Bname` `Brevision`

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#703]
see: [#131](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/131)
specification: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_condition

If the condition of a component "requires a board", the component is only available for selection if the matching board is selected by the project target-type.

**Comment by edriouk** [comment]
The featureis  implemented
