### ISSUE TITLE
[RTE Model] Add support for collecting `<memory>` and `<algorithm>` data from the `<board>` description

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#704]
Change in specification: Open-CMSIS-Pack-Spec [#124](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/124)
See specification here: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_memory

**Comment by edriouk** [comment]
The support is implemented, call RteBoard::GetMemories()
