### ISSUE TITLE
the axf should be generated with debug information regardless of the target

### ISSUE THREAD

**Issue by fredo514** [Open-CMSIS-Pack/devtools#709]
Type: Feature Request

This maybe be already possible through a way I'm not aware, but it would be nice that since the build command generates a .axf file automatically anyway, it contained the debug information by default without needing to specifically compile in for debug.

**Comment by jkrech** [comment]
@ReinhardKeil as far as I can see in csolution 1.4.0 there is no implementation of a default behavior for the abstraction of compiler options like `debug`, `optimize`, `warnings` if they are not even present in the yml files. I think the assumption is made that in this case the user wants to use `misc` options to control these settings explicitly or simply does not want to enable capabilities in the compiler.
As consequence of making `debug: on` the default the only option to disable the command line option is to explicitly set `debug: off`. This feels counter intuitive. I would expect an IDE to configure clever default options but not the project description format.

**Comment by ReinhardKeil** [comment]
@jkrech thanks for highlighting. Looks like we need to come up with `cdefault.yml` files for each of the toolchains with useful settings and then adjust the documentation.

**Comment by fredo514** [comment]
My need is to be able to run any target in debug using the Arm Embedded Debugger extension without the need to have a dedicated debug target. I opened a ticket on the VSCode extension repo (https://github.com/ARM-software/vscode-cmsis-csolution/issues/13), but they sent me here.

I'm not sure where I'm supposed to add the "debug" field in the yaml, but I tried to put "debug: on" under both "target-types" and "misc" and it didn't change anything.

The default behavior currently gives me an "Unable to find symbols" error when I try to debug, unless I add the "-g" flag to the target compiler options in csolution.yaml.

Now with the -g gcc flag I don't get the error, but I'm unable to watch variables and see the current line cursor when I stop on a breakpoint... I'm not sure what I'm missing.

**Comment by jkrech** [comment]
Sorry for the delay. Let me investigate a bit further. This does not sound quite  right to me.

**Comment by jkrech** [comment]
@fredo514 I am glad to see that your problem is now investigated by the debug experts.

**Comment by fredo514** [comment]
For posterity, my debugging issues turned up to be improper retarget when using printf. 

Adding `debug: "on"` to the solution also now allows me to debug with symbols without having to setup a target that explicitely has the `-g` compiler option.
