### ISSUE TITLE
[csolution] Add check to generator launch if execute file permission + message

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#731]
Moving https://github.com/Open-CMSIS-Pack/cpackget/issues/117 from `cpackget` to `csolution`.

Proposal:
- if `csolution run -g <code generator>` is launched, csolution shall check whether execute permissions are set for the generator command prior to launching. If permissions are missing the output message will provide an absolute path to the file and ask the user to update the file permissions.

This is the most controlled/restricted way to handle this. It is up to the user to automate this further.

**Comment by ReinhardKeil** [comment]
In #626 the proposal is to replace the csolution run command with an option to generate scripts as this would be less confusing.

**Comment by edriouk** [comment]
Implemented
