### ISSUE TITLE
[csolution] Generate regions_*.h file from selected `device` and/or `board` `<memory>` tags

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#739]
Specified here: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Linker-Script-Management.md

**Comment by edriouk** [comment]
The initial implementation is submitted. Regions header gets generated when RTE folder is updated, but existing file is not overwritten.
