### ISSUE TITLE
[buildmgr] As a Software Component Maintainer, I want to select the compiler on command line.

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/devtools#748]
# User Story

As a Software Component Maintainer, I want to select the compiler on command line.

The user's environment has multiple compilers available, e.g., Arm Compiler 6, GCC and IAR. The validation projects for a software component shall be built using all three in a row.

In addition, there might be multiple version of the same toolchain, e.g. Arm Compiler 6.20, 6.16.1 and 6.6.5. The validation projects for a software component shall be built using all three version in a row.

## Acceptance Criteria

On a command prompt in a folder with a valid project:
- [ ] generate build context for Arm Compiler 6.20 using `csolution` 
- [ ] generate build context for Arm Compiler 6.16.1 using `csolution` 
- [ ] generate build context for Arm Compiler 6.6.5 using `csolution` 
- [ ] generate build context for GCC using `csolution`
- [ ] generate build context for IAR Compiler using `csolution`

**Comment by JonatanAntoni** [comment]
Possible solution could be another command line flag for csolution tool:
`-t/--toolchain <id>[@<version>]`

**Comment by ReinhardKeil** [comment]
I'm supportive of this idea! I guess it would indirectly select a `cdefault.yml` file also?

**Comment by JonatanAntoni** [comment]
@ReinhardKeil, I think how we cope with `cdefault.yml` needs some discussion. Do we have only one? Or do we have multiple ones, similar to the `<compiler>.<version>.cmake`?

**Comment by ReinhardKeil** [comment]
Yes, agreed this needs work!

**Comment by brondani** [comment]
I believe the current `cdefault` handling doesn't need changes. All supported compilers options can be in one single cdefault file in separated `for-compiler` nodes and the compiler selection would be then in the command line (or in the csolution/cproject) but not in the cdefault file.

**Comment by JonatanAntoni** [comment]
@brondani, yes, sounds like a valid option. A user could still set ones default compiler in the global cdefault file. I guess we don't want to set a default per project in our examples.

How do we cope with the version in `for-compiler`? Shall this be handled similar to the selection of the `<compiler>.<version>.cmake` file? I.e., the given version is the minimum version and we use the "best match" approach?

Once we look into the "toolchain configurator" we could think about setting the "default toolchain" in the global `.cdefault.yml`.

**Comment by brondani** [comment]
@JonatanAntoni Concerning compiler version currently only the `@` symbol is handled as mentioned in the [specification](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#for-compiler).
For consistency with pack and component name conventions, in my opinion we should at least accept `@` and `@>=` symbols for specifying respectively fixed and minimum versions.

**Comment by jkrech** [comment]
CMSIS-Toolbox 1.5.0
