### ISSUE TITLE
PackChk problem with "doc" attribute in the <example> element

### ISSUE THREAD

**Issue by KeilChris** [Open-CMSIS-Pack/devtools#75]
I have encountered an issue with PackChk where is does not check the documentation path of an example correctly. Consider the following <example> in a PDSC file:
```
<example name="MyExample" folder="Boards/v1/MyExample" doc="../../../Documentation/html/myexamples.html" version="1.0">
  <description>This is an example</description>
  <board vendor="Anyone" name="MyEVK" Dvendor="ARM:82"/>
  <project>
    <environment name="uv"  folder="./" load="MyExample.uvprojx"/>
  </project>
  <attributes>
    <component Cclass="CMSIS" Cgroup="Core"/>
    <component Cclass="Device" Cgroup="Startup"/>
  </attributes>
</example>
```
According to the PACK.xsd, the "doc" attribute is relative to the "folder" attribute. And it is not forbidden to specify folders in a couple of levels above (../../../). But PackChk throws an error on this, like:
```
*** ERROR M310: C:\03_work\Packs\Anyone\build\Anyone.MyPack.pdsc (Line 465)
  Filename mismatch (case sensitive):
  PDSC name : 'Boards\v1\MyExample\..\..\..\Documentation\html\myexamples.html'
  Filename  : 'Boards\v1\MyExample\v1\Boards\build\Documentation\html\myexamples.html'
```
PackChk needs to traverse the folder structure correctly to identify the correctness of the PDSC file.

**Comment by jeromecoutant** [comment]
> According to the PACK.xsd, the "doc" attribute is relative to the "folder" attribute.

Hi @KeilChris 

About this PACK.xsd file, do you use this one:
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/PACK.xsd

Maybe we should add explicitly this file inside Open-CMSIS-Pack repo ?

**Comment by KeilChris** [comment]
Hello @jeromecoutant,

trouble is that there is a PACK.xsd in Open-CMSIS-Pack repo as well. I think we need to conclude on having only one. What do you think. @JonatanAntoni ?

**Comment by jeromecoutant** [comment]
Oh, I see your PR in the other repo :-)

> trouble is that there is a PACK.xsd in Open-CMSIS-Pack repo as well

I didn't see this one in the Spec repo:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd

Thx

**Comment by JonatanAntoni** [comment]
Gents, the one in the Open-CMSIS-Pack-Spec is the master one. The one in CMSIS_5 repo is still kept for backward compatibility and should be removed somewhen in the future. Unfortunately, some tools fetch the PACK.xsd directly from CMSIS_5 GitHub repo and remove the schema file would break these tools.

**Comment by JonatanAntoni** [comment]
Gents, the one in the Open-CMSIS-Pack-Spec is the master one. The one in CMSIS_5 repo is still kept for backward compatibility and should be removed somewhen in the future. Unfortunately, some tools fetch the PACK.xsd directly from CMSIS_5 GitHub repo and remove the schema file would break these tools.

**Comment by jeromecoutant** [comment]
Back on the initial issue, if we want PackChk tool to apply the correct schema, it needs to be available in devtools, not in Spec ?

**Comment by jkrech** [comment]
@jeromecoutant just to set expectations here, PackChk itself does **NOT** run a schema check itself. 
How about the idea to include PackChk as well as the matching PACK.xsd (= most recent PACK.xsd schema file at the point of PackChk release) into the CMSIS-Toolbox?

**Comment by jeromecoutant** [comment]
> How about the idea to include PackChk as well as the matching PACK.xsd

I think it is a good idea

@fred-r

**Comment by ReinhardKeil** [comment]
With `doc="../../../Documentation/html/myexamples.html"` it is possible to escape the directory structure of a pack. Why should this be allowed?

**Comment by KeilChris** [comment]
Because this is the way how some examples work. Especially SiPs create one example that has a shared documentation, but the actual example is deeper in the folder hierarchy. So we need ../ to traverse the the hierarchy up until the right point. This happens more often that you would guess. Regarding escaping the structure of the pack: PackChk could be used to check that and throw an error in that case. We might need additional means for packunzip to abort the installation if it encounters such a situation. What do you think?

**Comment by thorstendb-ARM** [comment]
Shouldn't a pack be self contained except conditions? Not sure if a "Documentation pack" (and e.g. a "Driver Pack", ...) used by several packs is useful.

**Comment by KeilChris** [comment]
I'm not sure if I understand your comment. This has nothing to do with the pack purpose. We just cannot assume that the documentation for anything in the pack is below a certain folder. It can also be "above".

**Comment by thorstendb-ARM** [comment]
My question is: Do we want to allow to go outside the pack? (see Reinhards comment)

**Comment by jkrech** [comment]
In other words, please check that the reference is within the scope of a pack. The pdsc file defines the base directory of a pack. The referenced document must be in this base directory or any arbitrary level of sub-directories.

**Comment by thorstendb-ARM** [comment]
PackChk: issue on relative paths during case-sense check
excluding files from case sense check that have relative path elements "./" or "../"
added test if files are above pack root directory

**Comment by ReinhardKeil** [comment]
@KeilChris can you please verify it?

**Comment by KeilChris** [comment]
Retested with packchk version 1.3.98 and the issue is gone. Closing.
