### ISSUE TITLE
[prjmgr] Base files for configuration files are unconditionally created in case the file version matches the component version (bug)

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#773]
Generation of the PLM .base files seems inconsistent. Sometimes they are generated and sometimes not.

Using CMSIS-Toolbox V1.5.0.

This behavior can be seen in the following repo:
https://github.com/Open-CMSIS-Pack/AWS_MQTT_MutualAuth_SW_Framework

‘main’ branch (fdbe861)

All configuration files in RTE directories are present and initially without any .base files.

After running (converting target IP-Stack without schema check):
`csolution convert -s Demo.csolution.yml -c Demo.Debug+IP-Stack -n`

_Board\IMXRT1050-EVKB\RTE\Board_Support\MIMXRT1052DVL6B_: .base file generated for each file
_Board\IMXRT1050-EVKB\RTE\Device\MIMXRT1052DVL6B_: .base file generated for each file 
_Board\IMXRT1050-EVKB\RTE\Compiler_: .base file not generated
_Board\IMXRT1050-EVKB\RTE\CMSIS_Driver_: .base file generated – expected since the component is not used

_RTE\Security_: .base file generated
_RTE\RTOS_: .base file not generated

After running (converting target AVH without schema check):
`csolution convert -s Demo.csolution.yml -c Demo.Debug+AVH -n`

_Board\AVH_MPS3_Corstone-300\RTE\Device\SSE-300-MPS3_: .base file generated only for 2 files
_Board\AVH_MPS3_Corstone-300\RTE\Compiler_: .base file not generated

Why is there a difference in handling .base files and what is expected?

**Comment by ReinhardKeil** [comment]
The csolution tool does not generate the .base file when there is already a config file in the directory (as it does not overwrite this file and does not know which version it was).

Only when the file is the first time added, it is generated.

**Comment by RobertRostohar** [comment]
The .base files are generated even if a config file already exists - see details above.

**Comment by edriouk** [comment]
The .base files also created for the files with specified version if it the actual one. 
I need to look what happens.  I think that generated *.cprj file contains components with "fixed version" == current version => the .base files get created.

**Comment by jkrech** [comment]
@edriouk there seems to be a glitch here somewhere. 
I am using a very basic example from here: https://github.com/Open-CMSIS-Pack/vscode-get-started/
I am just looking at the device startup config files for `ARMCM3`. 
I have no pack versions nor component versions specified.

for `startup_ARMCM3.c` always the file `startup_ARMCM3.c.base@2.0.3` gets created.
for `system_ARMCM3.c` no base file is created.

Looking at the ARM.CMSIS.pdsc the only special thing I find is that the file version of `startup_ARMCM3.c` matches the component version. If I edit the ARM.CMSIS.pdsc and change the file version of the `system_ARMCM3.c` also to match the component version, then the base file gets unconditionally created also for this file.

@edriouk could you please fix this bug?
