### ISSUE TITLE
[csolution, cbuildgen] On macOS the default location of the PACK ROOT folder is incorrect

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#782]
According to the documentation the default location of the PACK Root folder on maxOS/darwin is:

`$USER/.cache/arm/packs`

csolution 1.5.0 searches in `$USER/arm/packs`

Setting of XDG_CACHE_HOME is not considered.

Work around: use `CMSIS_PACK_ROOT` environment variable

**Comment by soumeh01** [comment]
Fixed with the above changes
