### ISSUE TITLE
[cbuild, csolution, cbuildgen] Add commandline option to display "environment"

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#783]
All tools shall provide a common command line option for displaying information about the "environment they are detecting"

e.g.:
- `CMSIS_PACK_ROOT`: regardless whether default location, driven by environment variable or via command line option
- `CMSIS_COMPILER_ROOT`: default (..\etc\) or set via environment variable or via command line option
- `cmake`: location and version
- `ninja`: location and version
-  other ?

**Comment by ReinhardKeil** [comment]
There is already a proposal "list config" under #142

For windows host, I suggest to display also status of long filename support with `Long pathname support:  <disabled | enabled >`. This is the related windows key:

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```

**Comment by soumeh01** [comment]
see cmsis-toolbox 2.0.0-dev0
