### ISSUE TITLE
[packchk] no error message if `../etc/PACK.xsd` not found

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#786]
**Describe the bug**
if packchk does not find the pack schema in the default location (`../etc/PACK.xsd`) to validate against no output is provided.

**To Reproduce**
run packchk without `../etc/PACK.xsd` present

**Expected behavior**
A clear and concise error message should be provided that the PACK.xsd could not be found in `<absolute path>`.

```
*** ERROR M218:
  Unable to find schema file '<absolute path>/PACK.xsd' for validation
```
To be discussed: 
- consider to continue the validation skipping the schema validation ?
- the tool header output is currently appearing after any schema check and there is not message indicating that in case the schema check was successful
- in case of schema errors this is the output:
```
packchk.exe ARM.CMSIS.pdsc --xsd c:\Keil_538a\UV4\PACK.xsd
Error at file C:/CMSIS-PACKS/ARM/CMSIS/5.9.0/ARM.CMSIS.pdsc, line 408, column 54: value 'ARM:81' not in enumeration

CMSIS Pack Checker 0.0.0+g9b4a2e2 (C) 2012-2023 Arm Ltd. and Contributors
```

**Environment (please complete the following information):**

- [packchk]
- Version [development branch]
- OS: [any]

**Additional context**

**Comment by thorstendb-ARM** [comment]
Message M218 has been changed to: "Unable to find schema file for validation: '%PATH%'"
In case of default location of PACK.xsd, %PATH% iss expanded to "./, ../etc/, ../../etc/" (which is where packchk searches).

**Comment by thorstendb-ARM** [comment]
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.4.0

**Comment by jkrech** [comment]
Validating  version 1.4.0:
```
packchk.exe ARM.CMSIS-NN.pdsc


*** ERROR M218:
  Unable to find schema file for validation: './, ../etc/, ../../etc/'

*** ERROR M105:
  Error while parsing command arguments
```

**Comment by thorstendb-ARM** [comment]
Reviewed messages:
```
CMSIS Pack Checker 0.0.0+g9471c31 (C) 2012-2023 Arm Ltd. and Contributors

*** ERROR M218:
  Unable to find PACK.xsd schema file. Searched in './, ../etc/, ../../etc/' relative to 'D:\GIT\devtools-external\build\tools\packchk\windows-amd64\Debug\'.
  Alternatively use --xsd to specify the location of the schema file. 

Log created on Fri Jun  2 10:26:01 2023
```

```
CMSIS Pack Checker 0.0.0+g9471c31 (C) 2012-2023 Arm Ltd. and Contributors

*** ERROR M219:
  Unable to find specified schema file in 'D:/GIT/devtools-external/build/tools/packchk/foo.xsd'

Log created on Fri Jun  2 10:31:18 2023
```
