### ISSUE TITLE
Linking libcurl.so as as static library

### ISSUE THREAD

**Issue by jlonnberg** [Open-CMSIS-Pack/devtools#791]
Building packchk main fails with

"attempted static link of dynamic object libcurl.so"

for linux with the recent update to add xerces-c library.

**Comment by jkrech** [comment]
That is strange, I am not seeing this failing in the github actions build for linux.
Also I thought we had agreed that we would not configure the option for xcerces library to accessing a url.
Could this be a problem of command line options during build?

**Comment by jlonnberg** [comment]
There is a line in the CMakeFIle for packchk that forces the -static option when linking using gcc which triggers the problem. Is the  binary expected to link with libcurl.a or libcurl.so?

**Comment by JonatanAntoni** [comment]
Hi @jlonnberg,

May I ask you to check the output of your `cmake` configuration command, please?
In the GitHub action as well as on my local system I can see the following diagnosis message:
```
 :
-- Performing Test XERCES_HAVE_STD_THREAD
-- Performing Test XERCES_HAVE_STD_THREAD - Success
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Looking for C++ include nl_types.h
-- Looking for C++ include nl_types.h - found
 :
```

I.e., it is missing `libcurl`. Hence, I assume it disables curl functionality which in turn hides the issue you are having. Once I install `libcurlpp-dev` on my Ubuntu 22.04 the diagnosis output changes to
```
 :
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.81.0")
 :
```

But this still links successfully and results in a statically linked executable. So, I guess there is something else different in your build env.

Cheers,
Jonatan

**Comment by jlonnberg** [comment]
It lists 
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0") 

and the build fails with
[605/664] Linking CXX executable tools/packchk/linux64/Debug/packchk
FAILED: tools/packchk/linux64/Debug/packchk 
: && /usr/bin/g++-9 -g -O0 -MD -Wall -static tools/packchk/CMakeFiles/packchklib.dir/src/PackChk.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/PackOptions.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/ParseOptions.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/RteModelReader.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/Validate.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/ValidateSemantic.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/ValidateSyntax.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/CheckComponents.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/CheckConditions.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/CheckFiles.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/CreateModel.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/PackChk_Msgs.cpp.o tools/packchk/CMakeFiles/packchklib.dir/src/GatherCompilers.cpp.o tools/packchk/CMakeFiles/packchk.dir/src/PackChkMain.cpp.o -o tools/packchk/linux64/Debug/packchk  libs/rtemodel/libRteModel.a  libs/rtefsutils/libRteFsUtils.a  libs/crossplatform/libCrossPlatform.a  libs/xmltreeslim/libXmlTreeSlim.a  libs/xmltree/libXmlTree.a  libs/rteutils/libRteUtils.a  libs/xmlreader/libXmlReader.a  libs/xmlschemachecker/libXmlValidator.a  libs/errlog/libErrLog.a  external/xerces-c/src/libxerces-c.a  /usr/lib/x86_64-linux-gnu/libcurl.so  -lpthread && :
/usr/bin/ld: attempted static link of dynamic object `/usr/lib/x86_64-linux-gnu/libcurl.so'
collect2: error: ld returned 1 exit status

How does you command line for the linking look like?

**Comment by JonatanAntoni** [comment]
Okay, I cleaned my workspace and started from scratch and now I can reproduce the issue. This seems to be an issue with the Xerces build system.

**Comment by JonatanAntoni** [comment]
Do we want PackChk to use Xerces with network access support? If yes, we need to investigate how to get this statically linked. If not, there seems to be an option `option(network "Network support" ON)` which could be set to `OFF`.

**Comment by jkrech** [comment]
@JonatanAntoni I had agreed with Yves already that we wanted to exclude network support so I agree that the above option must be set to `OFF`. Does that problem solve your local build?

**Comment by jkrech** [comment]
@jlonnberg, please feel free to reopen the issue if the build of packchk is still failing locally for you.
