### ISSUE TITLE
Incorrect $Output$ when using access sequences

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#796]
**Describe the bug**
`$Output(context)$` seems to be incorrect when using access sequences. The naming convection for output files has changed recently, but the access sequence still uses the old naming convention.

Access sequence still uses the old format:
`<project-name>.<build-type>+<target-type>`

Output files in output directory use the new naming convection:
`<build-type>+<target-type>`

Except generated `.clog` file which still uses the old format which is another inconsistency.

It seems that when using the default output directory there is still a lot of repetition in the path:
 - `out/<project-name>/<target-type>/<build-type>/<project-name>.<build-type>+<target-type>` - old format
 - `out/<project-name>/<target-type>/<build-type>/<build-type>+<target-type>` - new format

The recent change to drop the `<project-name>` does not help a lot to shorten the path and it looks inconsistent.

**To Reproduce**

Should not be difficult to create a test example.

The following example can also be used to demonstrate this.
Repo: https://github.com/RobertRostohar/STM32U5_ctools

The non-secure project requires the CMSE library from the secure project which is described in the non-secure project:
`TZ\NonSecure\NonSecure.cproject.yml`:
 - `file: $Output(Secure)$_CMSE_Lib.o`

Use the following command to create the .cprj files:
`TZ> csolution convert -s TZ.csolution.yml`

Use the following command to build the secure project:
`TZ\Secure> cbuild Secure.Debug+HW.cprj`

The name with path of the built CMSE library is:
`TZ\out\Secure\HW\Debug\Debug+HW_CMSE_Lib.o`

However the CMSE libary in the generated .cprj has the wrong name:
`TZ\NonSecure\NonSecure.Debug+HW.cprj`:
 - `<file category="object" name="../out/Secure/HW/Debug/Secure.Debug+HW_CMSE_Lib.o"/>`

The name with path should be `"../out/Secure/HW/Debug/Debug+HW_CMSE_Lib.o"` (without the `Secure.` in the name).

**Expected behavior**
Access sequence `$Output$` should match the generated output files.

**Environment (please complete the following information):**
- CMSIS-Toolbox V1.5.0
- OS: Windows 10

**Comment by ReinhardKeil** [comment]
I created a simple TrustZone example and this shows some of the problems.  The example is currently located here: https://github.com/ReinhardKeil/csolution-examples/tree/main/SimpleTrustZone

Issues:

1. Files in the directory \out\ should use the basename of the project.  I would expect for example:
    ```
    out\CM33_s\AVH\debug\CM33_s.axf
    out\CM33_s\AVH\debug\CM33_s.map
    out\CM33_s\AVH\debug\CM33_s.bin
    out\CM33_s\AVH\debug\CM33_s.hex
    out\CM33_s\AVH\debug\CM33_s_CMSE_Lib.o
    ```

2. We should define clearly what `context` means in $Output ...$ sequences.

**Comment by ReinhardKeil** [comment]
@RobertRostohar could you review #826 and #821.  I believe together with your issue this should solve the problem.

**Comment by RobertRostohar** [comment]
The proposals #826 and #821 should solve also the problem reported in this ticket.
