### ISSUE TITLE
Phantom "Target_1" expected in RTE

### ISSUE THREAD

**Issue by JonTBeckett** [Open-CMSIS-Pack/devtools#799]
Hi,

This is a long shot because I don't really have much information to go on but I'm hoping the right people will see this question and have an idea of what's going on.

So I've converted a Keil project into a CSolution project which is in turn converted to a cprj file of course. When I try to build the cprj, it gives "ERROR M204: Path not found: c:\projectpath\RTE\_Target_1". The name of the cprj is TFM_SecureBoot+Release.cprj and there was no Target 1 target in the Keil project at the time of conversion. The RTE/_Release directory is created with the appropriate RTE header in it. I've searched my entire project repo for any reference to Target 1, TARGET_1, Target_1, and any other combination I can come up with but there are none.

Does anyone have any idea why cbuild would expect that based on any of the information I've provided? Or have any suggestions on where to look in my repo or the build system for additional information?

I'll also note that if I just create the RTE/_Target_1 directory, everything builds just fine. So it doesn't actually need anything in that directory, it just thinks that directory needs to exist.

Thanks for any help anyone can send my way!

**Comment by jkrech** [comment]
@JonTBeckett, thanks a lot for reporting your problem.
Could you please detail which version of the tools you are using
- are you making use of VSCode extensions?
- converter from uvprojx to csolution
- CMSIS-Toolbox: csolution, cbuild, etc. 

a) A recent change in the `cbuild` orchestration is that by default it does not make any modifications to the project, in particular it does not update the RTE directory which contains all configuration files of components.
This also includes e.g. the context specific file `RTE_Components.h` which is stored in `RTE/_build-type_target-type`
=> you can enforce the update of the `RTE` folder by adding the command line option `--update-rte`.

b) What is the filename of your cprj file? 
Note that the cprj represents a single project context but it does not have dedicated context information inside the format like csolution (.build-type+target-type).
For that reason the `cbuildgen` will derive build-type and target-type from the filename of the cprj file.
If a cprj filename does not contain a target-type (and not build-type) the default that is chosen to store the header files generated by the RTE system is `_Target_1`.
```
<project>.<build-type>+<target-type>.cprj
will expect the directory:
RTE/_<build-type>_<target-type>

<project>+<target-type>.cprj
will expect the directory:
RTE/_<target-type>

<project>
will expect the directory:
RTE/_Target1_
```

**Comment by JonTBeckett** [comment]
Thanks for taking the time to help with my problem! I’m using version 1.5.0 of the CMSIS toolbox. I’m also using the VS Code extension, including the uvprojx converter. 
So my workflow to get to this point has been the following:
* Open my project’s directory in VS Code.
* Run the uvprojx to csolution converter.
* Modify the .csolution.yaml and the .cproject.yaml as needed to get the build to work (this has just been small changes like removing duplicate defines, duplicate include paths, and other YAML format issues mainly).
* Let the VS Code extension handle the conversion from csolution/cproject to cprj files. 
* Build from the VS Code extension unless an error occurs and I need to pass additional arguments to cbuild to get more debug info.

I’m not sure what version of the extension I’ve been using but it should be the latest. I’m traveling today (it’s early morning for me in Minnesota, USA), but I can provide more detailed version information tomorrow. 

a) That’s a good detail to know. So do the RTE_components.h files (one for each target/build type combo) get created in the conversion step from csolution -> cprj? 
b) I have two targets and no build types at this point as the uvprojx -> csolution doesn’t generate any build type information. The two targets (coming directly from the uvprojx) are Release and Debug. The VS Code extension is successfully generating two cprj projects, TFM_SecureBoot+Release.cprj and TFM_SecureBoot+Debug.cprj. Inspecting the RTE directory after that, I have see. The RTE/_Release/ and RTE/_Debug are both successfully created with the expected RTE_components.h files. 

So your response has confirmed for me that the expected RTE/* directory is derived from the cprj file name. I also gather that those file names are generated in the conversion from csolution -> cprj. Is that the csolution tool? Does the csolution tool (or whatever does that conversion) generate the names purely from the target and build types listed in the .csolution.yaml file? I can’t find any reference to a Target 1 in the csolution.yaml at all.

I’ll also mention that I’ve followed this conversion process for a couple similar uvprojx files using the same versions of all of the tools without any problems.

**Comment by jkrech** [comment]
Thanks for that additional information.
a) correct: `csolution convert` creates the context specific RTE subdirectories containing e.g. `RTE_Components.h`
b) this all sounds consistent. Having a single cproject file, two `target-types` but no `build-type` `csolution` generates two cprj files.

I have now been able to reproduce your problem and a workaround for you until we can provide a fix is to add a `build-type` in your csolution.yml file.

```
  build-types:
    - type: any
```

Summary: it looks like cbuildgen Version 1.5.0 does expect `RTE/_Target_1` in case:
a) neither `build-type` nor `target-type` is specified in the cprj filename
b) no `build-type` and a `target-type` is specified in the cprj filename
However a project without a `target-type` must not exist, as no device/board would be specified.

**Comment by mcgordonite** [comment]
> However a project without a target-type must not exist, as no device/board would be specified.

The schema currently setting the device on the project itself. In that case, is the target type required?
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L649

**Comment by ReinhardKeil** [comment]
@mcgordonite this is correct, and I believe currently an error in the uVision exporter. From your perspective don't worry about it as we need to fix the underlying issue.

**Comment by JonTBeckett** [comment]
Thanks for the work around and looking into this so quickly!I've had minimal time to dig into these tools but have loved what I've seen so far. I've also loved the quick response and turn around on any questions or bugs I've raised!

That quick response is already turning heads on my team and could be one of the key things that gets them to convert to csolution/cprojects in the near future. Thanks for all the hard work and great tools! I look forward to using them more in the future.

**Comment by jkrech** [comment]
a) I have raised a bug report against `cbuildgen` here: https://github.com/Open-CMSIS-Pack/devtools/issues/882
b) Update documentation to make <target-type> mandatory https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#context and recommend specifying the device/board as part of <target-type>
c) Update schema to make <target-type> a required node.

**Comment by jkrech** [comment]
@ReinhardKeil in my view <build-type> is conceptually not mandatory.

**Comment by jkrech** [comment]
Now that target-type is mandatory this phantom "Target_1" case cannot occur anymore.
