### ISSUE TITLE
[csolution] Allow to specify the output artifact `cmse library` for secure projects

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#801]
**Describe The Problem To Be Solved**
When a secure project specifies non-secure callable entry points it must generated a `cmse library` for the non-secure projects along side a header file with the corresponding function prototypes.

**Proposal**
Extension of the node:
[output](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#output)
adding a type `cmse-lib`

**Comment by ReinhardKeil** [comment]
OK, I suggest to work on #826 and for now keep the name: `<project-name>_CMSE_Lib.o`.  OK for everyone?

**Comment by ReinhardKeil** [comment]
In #826 the suggestion to access a CMSE Library is with a dedicated access sequence:
```
- group: CMSE Library
      files:
       - file: $cmse-lib(CM33s)$
```

IMHO this removes the need to rename the output name.

I personally believe we should rework [output](https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#output) and provide the following:

```
output:
  - base-name: <base-file-name> # for all output artifacts
  - type: hex   # generate a HEX file 
  - type: bin   # generate a BIN file 
     offset:      # potential options for BIN file generation
```

**Comment by ReinhardKeil** [comment]
Replaced by #894 and #895
