### ISSUE TITLE
[csolution] Regex pattern error if the hyphen is a part of component name

### ISSUE THREAD

**Issue by ronyrad** [Open-CMSIS-Pack/devtools#805]
csolution.exe returns the following error

_C:/projects/s_firmware/sfw/sfw.cproject.yml:20:17 - error csolution: instance does not match regex pattern: (^[A-Za-z\d][\w+()'\/\- \.]+$)|(^([A-Za-z\d][A-Za-z\d ]+::)?([A-Za-z\d][\w+()'\/\- \.]+)(&[A-Za-z\d][\w+()'\/\- \.]+)?(:[A-Za-z\d][\w+()'\/\- \.]+)(:[A-Za-z\d][\w+():\/\- \.]*)?(&[A-Za-z\d][\w+()'\/\- \.]+)?(@(>=)?((0|[1-9]\d*)\.([\d]+)(\.([\d]+))?(\-((0|[1-9]\d*|\d*[a-zA-Z-][\da-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][\da-zA-Z-]*))*))?))?$)_

when following component is defined:
**- component: Arm-Packs::Test:Unity&Classic**

The reason is the hyphen in "Arm-Packs" name. If the hyphen is removed the problem dissapears

**Environment (please complete the following information):**

- [tool or library]
- Version [e.g. v1.5.0]
- OS: [windows]

**Comment by jkrech** [comment]
This got fixed in this PR
https://github.com/Open-CMSIS-Pack/devtools/pull/777
and will be fixed in the next release.

As a workaround you can specify the component without the vendor or disable the schema check
`csolution --no-check-schema`
