### ISSUE TITLE
Processor FPU option doesn't cover all possible variants

### ISSUE THREAD

**Issue by ronyrad** [Open-CMSIS-Pack/devtools#806]
Currently, the FPU enum consists of two options only on/off

        _"fpu": {
          "enum": [ "on", "off" ],
          "description": "Controls usage of FPU registers (S-Registers that are used for Helium and FPU hardware): on | off"
        },_

  if (!context.controls.processed.processor.fpu.empty()) {=
    if (context.controls.processed.processor.fpu == "on") {
      context.targetAttributes["Dfpu"] = "FPU";
    } else if (context.controls.processed.processor.fpu == "off") {
      context.targetAttributes["Dfpu"] = "NO_FPU";
    }
  }

However,  Dfpu enumeration type in cprj has also Single (SP_FPU) and Double Precision (DP_FPU) options
  
  <xs:simpleType name="DfpuEnum">
    <xs:restriction base="xs:token">
      
      <xs:enumeration value="FPU" />
      <xs:enumeration value="1" />
      
      <xs:enumeration value="NO_FPU" />
      <xs:enumeration value="0" />
      
      <xs:enumeration value="SP_FPU" />
      
      <xs:enumeration value="DP_FPU" />
    </xs:restriction>
  </xs:simpleType>

Thus in my opinion the FPU enum in project manager should be extended to all types listed in CPRJ.

**Comment by ReinhardKeil** [comment]
We believe that we should present simple, easy to understand options to the user. 

While the device itself may have single or double precision floating point unit, we believe it is sufficient to expose just the option to turn on/off the floating point unit.  The effect for the user is that S-registers are used or not-used (which might be important for interrupt code).  For code generation the tools are using the optimum which is either single or double precision.  The details for the FPU are specified in the Device Family Pack.

**Comment by ReinhardKeil** [comment]
@ronyrad  any further input here?

**Comment by ReinhardKeil** [comment]
Similar issue under #359

**Comment by JonatanAntoni** [comment]
On high level scope having just "off" and "on" (which uses full capabilities of a certain device) seems to be sufficient. When it comes to compiling shared libraries or for testing purposes, one might need more fine grained control. 

I'd like to propose keeping "off" and "on" as shortcuts for "no fpu" and "fpu" but add expert options like "hp" (half), "sp" (single), "dp" (double) to allow advanced users to steere the details. 

Folding in setting for `-mfloat-abi` (see #359) we could extend as the following:

| `fpu:`    | `-mfpu=`   | `-mfloat-abi=` |
|:---------:|:----------:|:--------------:|
| `off`     | `none`     | `soft`         |
| `softhp`  | `<half>`   | `softfp`       |
| `softsp`  | `<single>` | `softfp`       |
| `softdp`  | `<double>` | `softfp`       |
| `soft`    | `<best>`   | `softfp`       |
| `hp`      | `<half>`   | `hard`         |
| `sp`      | `<single>` | `hard`         |
| `dp`      | `<double>` | `hard`         |
| `on`      | `<best>`   | `hard`         |

**Comment by ReinhardKeil** [comment]
The [`fpu:`](https://github.com/open-cmsis-pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#processor) option enables/disables usage of S-Registers. It therefore also enables the usage of Helium vector instructions. Not sure if we can find a better name for `fpu`.

I believe features like the above are for expert user cases, and these type of controls are available using `misc:`.

**Comment by JonatanAntoni** [comment]
@ReinhardKeil, `misc:` might be an option even if we lose compiler abstraction in this way. Are we sure one can overrule default options (that comes from e.g. `fpu`) by setting the same flags via `misc:`?

**Comment by ReinhardKeil** [comment]
No we are not sure. @brondani we would need to get your view on that.

**Comment by ReinhardKeil** [comment]
Replaced by #879 - do not use this for further discussion.  We may refer to it later.
