### ISSUE TITLE
csolution convert does not warn about outdated config files

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#807]
The attached example uses the assembly startup method. 

As it was previously configured for GCC compiler, it does not compile using AC6 (due to the conflict in the startup_ARMCM33.s file).
[SimpleTrustZone.zip](https://github.com/Open-CMSIS-Pack/devtools/files/11077879/SimpleTrustZone.zip)

```
PS C:\Test\SimpleTrustZone> cbuild .\cm33_s\CM33_s.debug+avh.cprj
[1/1] Linking C executable C:\Test\SimpleTrustZone\out\CM33_s\AVH\debug\debug+AVH.axf
FAILED: C:/Test/SimpleTrustZone/out/CM33_s/AVH/debug/debug+AVH.axf
Finished: 1 information, 0 warning and 1 error messages.
```

However, the csolution tool could issue an warning about the potentially outdated  startup_ARMCM33.s file as the file startup_ARMCM33.s.base indicates a different version.

I know that this is not a perfect solution, but may have helped to spot the issue.

**Comment by jkrech** [comment]
I am wondering whether we should precisely specify a **Validation Step** which not only checks config file versions but also up-to-date generator files, up-to-date/present RTE_Components.h files, resolved dependencies, presence of referenced files, etc.
In a second step we need to define which csolution commands shall execute which steps.

**Comment by ReinhardKeil** [comment]
Agreed: we will define the validation steps clearly and implement for CMSIS-Toolbox 2.1 - no rush in the moment

**Comment by ReinhardKeil** [comment]
this is implemented now.  Just with --quite the warnings are not issued - but this is recorded in #1767
