### ISSUE TITLE
[csolution] add support for toolchain agnostic `pre-include` files in YAML Input files

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#808]
There are many cases that a project has a pre-include file. All IDEs and compilers supports pre include file.
Without pre include supported, many projects cannot be supported directly in Open-CMSIS-Pack.

**Comment by jkrech** [comment]
@tcsunhao, I guess you could use `misc` to specify a pre-include file, however the exact syntax would depend on the selected toolchain.
Do you have any suggestion for specifying files as `pre-include` files. Do we need to specify the pre-include files only globally or for a certain scope, e.g. a file group.
For components we have dedicated [FileCategoryTypes](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#FileCategoryEnum)

**Comment by tcsunhao** [comment]
Thank you @jkrech , for the time being, I will use 'misc' to hold toolchain specific preinclude file.

In NXP existing cases, preinclude file is for project level, but I think if we support it, in data model, we shall support all while in implementation, we can do with priority.

**Comment by ReinhardKeil** [comment]
@tcsunhao I will review this and try to come up with a tool agnostic way to specify pre-include files.

**Comment by ReinhardKeil** [comment]
Sorry my answer is late.  I have looked into options and would suggest to add a note `pre-include:` as shown below.
It is similar to `add-path:` and the control should be allowed at the same positions as `add-path:`. 

@tcsunhao would this fulfil the request?
@brondani @jkrech could we add this feature for CMSIS-Toolbox 2.2?

*`pre-include:`*

Add pre-include files to the command line of the development tools for C and C++ source files.

`pre-include:`                                                | Content
:----------------------------------------------------------|:------------------------------------
&nbsp;&nbsp;&nbsp; `- <file-name>`                         | Filename of the pre-include file to be added

>**Note:**
>
> This control only applies to C and C++ source files.  For assembler source files use the `misc:` node.

**Comment by JonatanAntoni** [comment]
Another use case for such a feature could be ARM-software/CMSIS_6#122

**Comment by jkrech** [comment]
Toolbox 2.3.0 will have an "experimental" version of cbuild2cmake and we need to see whether this version will have support for new features like `-preinclude`

**Comment by jkrech** [comment]
this feature did not make it into CMSIS-Toolbox 2.4.0.

**Comment by ReinhardKeil** [comment]
@brondani Pre-include is now specified here https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#pre-include
It is possible on all places where `language-c` can be specified (means at group, file, component, project, etc. level).

**Comment by brondani** [comment]
@ReinhardKeil User pre-include files are already supported in `cbuild2cmake` via file categories `preIncludeGlobal` and `preIncludeLocal` similarly as it is for component files, for example:
``` yml
  groups:
    - group: Source
      files:
        - file: ./pre-inc.h
          category: preIncludeGlobal
```
Could you please check whether this solves the issue so additional nodes are not needed?
