### ISSUE TITLE
Enable usage of environment variables for yml nodes that refer to a path or file.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#820]
Environment variables could be used to construct parts of path names or file names.

**Potential Solution**
I would suggest that we consider the syntax already and ensure that there is no conflict with [access sequences](https://github.com/open-cmsis-pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#access-sequences)

A possible (Unix-like) way to refer to environment variables might be:
```
${environment-variable-name}
```

**Comment by jkrech** [comment]
I am not very much in favor of adding environment variables as I see them as a source for failing projects unless we include some mechanism for managing environment variables.
E.g. we could extend [variables](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#variables) and only allow assigning environment variables here.

**Comment by ReinhardKeil** [comment]
@jkrech I agree with you.  We should perhaps limit scope. I just captured an idea here.

**Comment by ReinhardKeil** [comment]
Rejected
