### ISSUE TITLE
consistent command line options (cbuild, csolution)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#822]
I general all tools of the CMSIS-Toolbox should have consistent messages and options.

For `cbuild` I suggest the following changes:

```
Usage:
  cbuild [<command>] <project.cprj | csolution.yml> [<options>]

Commands:
  list contexts       Print list of contexts in a csolution.yml
  list toolchains     Print list of installed toolchains
  build                   Generate output (default when no command specified)

Options:
  -C, --clean                  Remove intermediate and output directories
  -c,  --context string        Input context name [<cproject>][.<build-type>][+<target-type>]
  -d, --debug                  Enable debug messages
  -g, --generator string       Select build system generator (default "Ninja")
  -h, --help                   Print usage
  -i, --intdir string          Set directory for intermediate files
  -j, --jobs int               Number of job slots for parallel execution
  -l, --load string            Set policy for packs loading [latest|all|required]
  -L, --log string             Save output messages in a log file
  -o, --outdir string          Set directory for output binary files
  -O, --output string          Set directory for all output files
  -p, --packs                  Download missing software packs with cpackget
  -q, --quiet                  Suppress output messages except build invocations
  -R, --rebuild                Remove intermediate and output directories and rebuild
  -S, --schema                 Validate project input file(s) against schema
  -t, --target string          Optional CMake target name
  -u, --update string          Generate *.cprj file for reproducing current build
  -U, --update-rte             Update the RTE directory and files
  -v, --verbose                Enable verbose messages from toolchain builds
  -V, --version                Print version
```

> Note: Some option letters are capitalize to harmonize it with csolution.

I suggest also to review the number of options that are currently available.  Maybe several options should be not exposed to the user, i.e. -intdir (which really refers to the ./tmp directory).

**Comment by jkrech** [comment]
Should we consider discontinuing the support for `*.cprj` files in cbuild 2.0 considering that this format will be replaced by `*.cbuild.yml` in the future?

**Comment by ReinhardKeil** [comment]
Yes, we should discontinue *.cprj and replace it with cbuild*.yml

**Comment by jkrech** [comment]
We cannot remove .cprj as input for cbuild until we support the building from *.cbuild.yml files since cprj is currently the only option to rebuild from fixed versions (reproducible build use case).

**Comment by jkrech** [comment]
I suggest to consider 
```
-u, --update string          Generate *.cprj file for reproducing current build
```
for cprj input files, because `csolution convert` will always generate a cprj with fixed pack and component versions.
Therefore move under cprj: specific flags

Also we need to make sure people understand the --context / -c can occur multiple times to construct a context set.
We still need to decide on the exact command line option for replacing a context rather than adding a context.
`--context-replacement`

**Comment by jkrech** [comment]
see: cmsis-toolbox 2.0.0-dev2
