### ISSUE TITLE
Relax order of build-type and target-type in the --context option of the various tools

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#825]
I suggest to relax the order of build-type and target-type in the --context option of the various tools (csolution, cbuild), meaning that these two command behave identical:
```
cbuild ... --context Myproject.Debug+AVH
cbuild ... --context Myproject+AVH.Debug
```

**Comment by jkrech** [comment]
starting: cmsis-toolbox 2.0.0-dev2
- adding validation tests now.
