### ISSUE TITLE
Handling of `CMSE_Lib.o` with TrustZone projects

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#826]
A secure project generates in the output directory a file with the format: <project-name>_CMSE_Lib.o.  This issue describes how this file could be handled in the non-secure part of the project.  

Assumption: suggested ./out directory structure of #821 is implemented; the example `./solution-examples/SimpleTrustZone` would then generate the following files:
```
./out/AVH/CM33_s.axf
./out/AVH/CM33_s.axf.map
./out/AVH/CM33_s.hex
./out/AVH/CM33_s.bin/ER_CMSE_VENEER     // FromElf splits large bin files into regions
./out/AVH/CM33_s.bin/ER_ROM
./out/AVH/CM33_s_CMSE_Lib.o                      // question: does GCC and IAR generate the same file?
./out/AVH/CM33_ns.axf
./out/AVH/CM33_ns.axf.map
./out/AVH/CM33_ns.hex
./out/AVH/CM33_ns.bin
```

To include the `CMSE_Lib.o` into the CM33_ns.cproject.yml could include the following file:
```
   - group: CMSE Library
      files:
       - file: $OutDir(CM33s)$\CM33_s_CMSE_Lib.o
```

**Assumptions:**
  - By default, the `$OutDir(CM33s)$` syntax uses the same target-type and the build-type of the current build.  It could be however explicitly specified.
  - `$OutDir(<project-name>)$` creates a dependency on <project-name>, the tools can verify build order to ensure that <project-name> is created before.
  - The build order or projects could be simply the order specified in the `projects:` nodes the csolution.yml file.

To make it even more intuitive for the user, `$OutDir()$` could be renamed to just $out()$

The tool and the manual would need clarifications in the section [access sequences](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#access-sequences) as the `<project-name>` is not optional in the context.  Resolving a empty `<project-name>` with the current project might bypass dependency checking.

I suggest to deprecate `$Output$` as it is unclear what exactly is referenced.

**Comment by brondani** [comment]
Instead of deprecating the `$Output$` access sequence I would suggest to add `cmse-lib` into the known output types as proposed in https://github.com/Open-CMSIS-Pack/devtools/issues/801 and extend it with the `type` argument like this `$Output(context, type)$`, for example:
```
- group: CMSE Library
      files:
       - file: $Output(CM33s, cmse-lib)$
```

**Comment by slhultgren** [comment]
> Instead of deprecating the `$Output$` access sequence I would suggest to add `cmse-lib` into the known output types as proposed in #801 and extend it with the `type` argument like this `$Output(context, type)$`, for example:
> 
> ```
> - group: CMSE Library
>       files:
>        - file: $Output(CM33s, cmse-lib)$
> ```

I agree with @brondani , I posted something similar in https://github.com/Open-CMSIS-Pack/devtools/issues/821#issuecomment-1508527317

**Comment by ReinhardKeil** [comment]
I believe the next version of the tool will give us enough flexibility to experiment.  The output directory can be configured in the way described above by using:

```yml
  output-dirs:
    outdir: ./out/$TargetType$/ 
```

I suggest to consider the following scenarios with https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/SimpleTrustZone:

- Build 'ns' part with .debug, 's' part with .release and load it to target
- Build both with the same build-type
- Add a new build-type .test that has an additional global define `test=1`, then build 'ns' part with .test, 's' part with .debug
- Then build 'ns' part with .test, 's' part with .release

How would you access the cmse-lib in these scenarios with the current default out directory?

**Comment by ReinhardKeil** [comment]
> > Instead of deprecating the `$Output$` access sequence I would suggest to add `cmse-lib` into the known output types as proposed in #801 and extend it with the `type` argument like this `$Output(context, type)$`, for example:
> > ```
> > - group: CMSE Library
> >       files:
> >        - file: $Output(CM33s, cmse-lib)$
> > ```
> 
I like 


> Instead of deprecating the `$Output$` access sequence I would suggest to add `cmse-lib` into the known output types as proposed in #801 and extend it with the `type` argument like this `$Output(context, type)$`, for example:
> 
> ```
> - group: CMSE Library
>       files:
>        - file: $Output(CM33s, cmse-lib)$
> ```

I like that idea, let me work on it.

**Comment by brondani** [comment]
> How would you access the cmse-lib in these scenarios with the current default out directory?

In this scenario the goal would be to produce 5 different `ns` artifacts, so in `SimpleTZ.csolution.yml` there would be 5 build types, for example:
```
  build-types:
    - type: Debug
      debug: on
      optimize: none
    - type: Release
      debug: off
      optimize: balanced
    - type: NSDebug-SRelease
      debug: on
      optimize: none
    - type: NSTest-SDebug
      define:
       - test=1
    - type: NSTest-SRelease
      define:
       - test=1
```
While the `s` part only needs to be built as `Debug` or `Release` so it can be filtered like this:
```     
  projects:
    - project: ./CM33_s/CM33_s.cproject.yml
      for-type: [.Debug, .Release]
    - project: ./CM33_ns/CM33_ns.cproject.yml
```
Finally in `CM33_ns.cproject.yml` the `cmse-lib` would be added as a dependency in this way:
```
  groups:
    - group: CMSE Library
      files:
        - file: $Output(CM33_s.Debug)$_CMSE_Lib.o
          for-type: [.Debug, .NSTest-SDebug]
        - file: $Output(CM33_s.Release)$_CMSE_Lib.o
          for-type: [.Release, .NSDebug-SRelease, .NSTest-SRelease]
```
Resulting in the following contexts:
```
CM33_s.Debug+AVH
CM33_s.Release+AVH
CM33_ns.Debug+AVH
CM33_ns.Release+AVH
CM33_ns.NSDebug-SRelease+AVH
CM33_ns.NSTest-SDebug+AVH
CM33_ns.NSTest-SRelease+AVH
```
With this approach the build artifacts do not get overwritten and the `s` part is only built once for `Debug` and once for `Release`.

**Comment by ReinhardKeil** [comment]
@brondani yes this is a working solution and shows the flexibility of the tool.  

Here is an easier way that uses the propose features in:
 - #831: build context manager removes inconsistent artifacts.
 - #821: simplified `./out` directory can be configured today already
 - #823: enables various build types at command-line

``` yml
  build-types:
    - type: Debug
      debug: on
      optimize: none
    - type: Release
      debug: off
      optimize: balanced
    - type: test
      debug: on
      optimize: none
      define:
         - test = 1

  projects:
    - project: ./CM33_s/CM33_s.cproject.yml
    - project: ./CM33_ns/CM33_ns.cproject.yml
```

Adding the `cmse-lib` to the CM33_ns project with the proposed access sequence:

``` yml
groups:
    - group: CMSE Library
      files:
        - file: $cmse-lib(CM33_s)     # note the old sequence above would work too, this is just simpler
```

When `cbuild` is extended to build any combination, the command line is like this:

```
/* Build 'ns' part with .debug, 's' part with .release */
cbuild SimpleTZ.csolution.yml -c CM33s.Release - c CM33ns.Debug

/* Build both with the same build-type */
cbuild SimpleTZ.csolution.yml -c CM33s.Release - c CM33ns.Release

/* Build 'ns' part with .test, 's' part with .debug */
cbuild SimpleTZ.csolution.yml -c CM33s.Debug - c CM33ns.test

/* Build 'ns' part with .test, 's' part with .release */
cbuild SimpleTZ.csolution.yml -c CM33s.Release - c CM33ns.test

/* Now a new combination that does not require any change in the project file */
cbuild SimpleTZ.csolution.yml -c CM33s.test - c CM33ns.Release
```

What do you think?

@tcsunhao would this be an alternative to [`context-map:`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#context-map).  NOTE: I am not proposing to remove `context-map` but I would like to get your view on that.

**Comment by ReinhardKeil** [comment]
Replaced by #894

**Comment by jkrech** [comment]
I suggest to close this issue in favor of #894 -> Access Sequence: $cmse-lib(context)$
