### ISSUE TITLE
Schema for csolution is not up-to-date.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#829]
The schema file for csolution.yml does not understand `outdir:`.  Test-file see #828

**Comment by jkrech** [comment]
https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/tools/projmgr/1.5.0/tools/projmgr/schemas/common.schema.json

```
"OutputDirectoriesType": {
      "type": "object",
      "properties": {
        "gendir":   { "type": "string" },
        "rtedir":   { "type": "string" },
        "intdir":   { "type": "string" },
        "outdir":   { "type": "string" },
        "cprjdir":  { "type": "string" }
      },
```

I am not able to reproduce this issue.
Even loading the yml file from the zip file you reference above, does not show any schema errors when loading in VSCode.

**Comment by ReinhardKeil** [comment]
you are correct. My mistake.
