### ISSUE TITLE
cbuild directory control, output-dirs:

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#830]
cbuild should have the following options:

-b, --outdir arg      base directory for build*.yml files (-O overrules this option) 
-i, --intdir arg        base directory for tmp files (-O overrules this option)  
-o, --outdir arg      base directory for out files (-O overrules this option)
-O, --output arg    redirect all generated files to common base directory

With -O the complete output files are redirected to a working directory that is different from the csolution base directory. This is used for cloud build services.

When the options -b, -i, or -o are combined with -O, cbuild generates an error "conflicting options specified"

The `output-dirs:` specification must allow only relative paths to the csolution base directory.  Absolute paths are rejected.

**Comment by ReinhardKeil** [comment]
Do we need the options `-b`, `-i`, and `-o`?  Where is this currently used?

**Comment by jkrech** [comment]
@ReinhardKeil, the options -i and -o in `cbuild` are only used for the invocation with *.cprj file and steer the command line options for cbuildgen 
```
-i, --intdir string          Set directory for intermediate files
-o, --outdir string          Set directory for output binary files
```

Any build (-job/-service) taking *.cprj as input would require it for 'backward' compatibility.
Is it a feasible option to deprecate the use of *.cprj as input to the `build` orchestration tool for 2.0.0?

Checking cbuild Version 1.6.2 (cmsis-toolbox 1.7.0) `-b` is not currently supported.
