### ISSUE TITLE
define symbols for linker script generation

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#833]
There is sometimes a need for specifying preprocessor defines for linker scripts. Having a toolchain independent way of specifying linker defines would be useful. 

This is addressed by adding `- define:` to `linker:` with this proposal: https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#linker

**Comment by jkrech** [comment]
Considering the linker script pre-processing step will be introduced, adding defines to this step makes sense to me. 
What needs to be discussed whether defines (as well as add-path) are always strictly separate from the defines/include paths specified for C/C++.

**Comment by jkrech** [comment]
Separate for linker only!

**Comment by jkrech** [comment]
To be included starting CMSIS-Toolbox 1.7.0
