### ISSUE TITLE
Review support for MVE instructions

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#834]
Is it sufficient to control the MVE instruction usage with `fpu:` under `processor:`?

See: https://github.com/open-cmsis-pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#processor 

>Note: documentation can be improved

**Comment by jkrech** [comment]
Defer. Use misc controls.

**Comment by JonatanAntoni** [comment]
Technically, mve is yet another co-processor flavor. So we could read `fpu: on` like `coprocessor enabled` and default to using full device capabilities (such as double float with mve, or just integer mve on non-fpu devices). As discussed in #806 expert options could be given via `misc:` as a last resort.

**Comment by ReinhardKeil** [comment]
Replaced by #879
