### ISSUE TITLE
[cmsis-toolbox] Windows: long pathname support

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#838]
For solving #671 the following issues are open:

- new ninja version should be included in `ctools`
- new arm linker is required to support long pathnames

**Changes to build tools:**

When  `[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]  "LongPathsEnabled"=dword:00000001`
- add to .cmake file:` set(CMAKE_OBJECT_PATH_MAX "1024")`
- list config command should display this setting (see #783)

**Comment by brondani** [comment]
I still face issues even with ninja 1.11.1 when running the reproducer described in https://github.com/Open-CMSIS-Pack/devtools/issues/671#issuecomment-1507058827:
```
CMake Error:
  Running
   'C:/ProgramData/chocolatey/bin/ninja.exe' '-C' 'C:/w/A1234567890B123456789C0123456789D0123456789E0123456789F0123456789G0123456789H01234567890IH01234567890JH01234567890/NXP_Sensor_SDK/examples/issdk/sensors/fxas21002/tmp/fxas21002_fifo/frdmk22f_agmp03/debug/CMakeFiles/CMakeScratch/TryCompile-1oopss' '-t' 'recompact'
  failed with:
ninja: error: loading 'build.ninja': The system cannot find the path specified.
```
Environment:
```
$ systeminfo
...
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045

$ csolution list environment
...
Long pathname support=enabled

$ ninja --version
1.11.1
```
Indeed the related ninja-build GH issue has been reopened on March 4th: 
https://github.com/ninja-build/ninja/issues/1900

Anyway at the present date it seems the [microsoft vcpkg registry](https://aka.ms/vcpkg-ce-default) provides only ninja 1.10.2
```
$ vcpkg version
vcpkg package management program version 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6

$ vcpkg find artifact ninja
...
microsoft:tools/ninja-build/ninja 1.10.2  Ninja is a small build system with a focus on speed.
```

On a side note the CMake variable [CMAKE_OBJECT_PATH_MAX](https://cmake.org/cmake/help/latest/variable/CMAKE_OBJECT_PATH_MAX.html) impacts only the hashing mechanism for generating object files with shorter paths. Increasing it does not help to solve the issue, at best it just evidences native tools that don't cope with long paths.

**Comment by tarek-bochkati** [comment]
@brondani could you retry with the latest ninja master HEAD
for every commit merge in ninja github an action is launched to test & compile ninja
a binary artifcat is kept and could be downloaded, for example herein: https://github.com/ninja-build/ninja/actions/runs/5111036290

**Comment by brondani** [comment]
The following PR, submitted to the `ninja-build` repository, addresses the `Filename longer than 260 characters` error:
https://github.com/ninja-build/ninja/pull/2321

**Comment by brondani** [comment]
From our side this issue is concluded.
The [PR](https://github.com/ninja-build/ninja/pull/2321) submitted to `ninja-build` was approved and merged.
External requirements, namely the Arm Compiler 6.21 and the ninja release [1.12.0 (no due date)](https://github.com/ninja-build/ninja/milestone/6) are out of scope of cmsis-toolbox 2.2.0.
