### ISSUE TITLE
Change define: `- test=1` to `- test: 1`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#843]
I recommend to change the syntax for define symbols to the standard `key: value` in YML. 

Reason: there might be tools that read/modify the YML data files, i.e. `csolution.yml` to adjust define values.  Having the non-standard syntax `text=1` does not work with a standard yml reader.

So instead of 
``` yml
      define:
         - test = 1
```

This syntax that is consistent with YML.

``` yml
      define:
         - test: 1
```

**Comment by jkrech** [comment]
It is suggested to implement this as a breaking chang.e

**Comment by mcgordonite** [comment]
Would it make sense to use a map instead of a list of maps? E.g.:
```yaml
define:
  test: 1
  THE_KEY: the_value
```

**Comment by JonatanAntoni** [comment]
>```yaml
> define:
>   - test: 1
>   - MY_KEY2: the_value
>   - MY_KEY3                  # no value
> ```

This creates an array (`define`) of maps with only a single entry, each.
I.e.; 
```
define[0][test] = 1
define[1][MY_KEY2] = 'the_value'
define[2] = 'MY_KEY3'
```

Versus
```
define:
  test: 1
  MY_KEY2: the_value
  MY_KEY3: true
```
would create a map with three key-value pairs, i.e.,
```
define[test] = 1
define[MY_KEY2] = 'the_value'
define[MY_KEY3] = true
```

**Comment by jkrech** [comment]
see: cmsis-toolbox 2.0.0-dev0
