### ISSUE TITLE
CBuild --context command should have more flexiblity

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#854]
The CBuild command should get more flexiblity (examplified on https://github.com/Open-CMSIS-Pack/csolution-examples):

I suggest to combine --configuration and --context into the same command (only --context is implemented).

The build command for `*.csolution.yml` files should allow the syntax described [here](https://github.com/open-cmsis-pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#context-name-conventions)
```
[project-name][.build-type][+target-type]
```

All elements of a context are optional, but at least one must be present.

  - When project-name is omitted, all projects in a csolution.yml are build.
  - When .build-type is omitted, it matches with any possible .build-type.
  - When +target-type is omitted, it matches with any possible +target-type.

When using `/c/w/csolution-examples/DualCore (main)` the following commands are effectively identical (as the solution only contains one project and one build type:
```
$ cbuild HelloWorld.csolution.yml --context HelloWorld_cm4.Release+FRDM-K32L3A6
$ cbuild HelloWorld.csolution.yml --context .Release+FRDM-K32L3A6
$ cbuild HelloWorld.csolution.yml --context .Release
```

I would be also create to allow multiple --context options as exemplified here with the example `/c/w/csolution-examples/dualcore`
```
cbuild HelloWorld.csolution.yml --context HelloWorld_cm0plus.Debug --context HelloWorld_cm4.Release
```

This should build the project 
  - HelloWorld_cm0plus using build-type .Debug
  - HelloWorld_cm4 using build-type .Release

**Comment by ReinhardKeil** [comment]
Relates to #823

**Comment by soumeh01** [comment]
After the discussion, the below decisions are made
- **cbuild** should provide flexibility to specify multiple` --context` options (supporting **[project-name][.build-type][+target-type]**)
`cbuild HelloWorld.csolution.yml --context HelloWorld_cm0plus.Debug --context HelloWorld_cm4.Release` 
- Order of execution should be the same as the order of projects specified in the csolution file

**Comment by jkrech** [comment]
see CMSIS-Toolbox 2.0.0-dev2
