### ISSUE TITLE
Remove build artifacts in `.out` directory when built-type or target-type changes

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#855]
With `output-dir` it is possible to use one directory for all build-type or target-types.

https://github.com/ReinhardKeil/csolution-examples shows how this could be applied.  The picture below shows a build with `*cm0*.Debug` and `*cm4.Release` build which is easy to identify by the `*.log` file names:

![image](https://user-images.githubusercontent.com/8268058/233665463-55661c07-9026-471b-8450-d2b0548e308e.png)

A problem is now when the build-types are changed, therefore I suggest to implement this additional behavior in the build process.

When a build process starts, the build tool should check if there is a log file with the current build/target-type. If this does not exist, the build output artifacts cannot be reused and to ensure a proper rebuild, the build tool could simply delete all files with the name <project-name>.*, in the example above Hello.*. This would ensure that a change of build/target-type in a build context manager would remove inconsistent artifacts.

**Comment by jkrech** [comment]
see cmsis-toolbox 2.0.0-dev0
