### ISSUE TITLE
[buildmgr] IAR compile flag issue for preinclude file

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#858]
**Describe the bug**
In IAR, for preinclude file, the compile flag is --preinclude <preinclude.h>. In the generated compile_commands.json, it uses '-include' which is for ARMCLANG, like 
![image](https://user-images.githubusercontent.com/3381677/234185593-adcc529c-6a34-4052-92f2-8ca4af534211.png).
This error generation will result in build error like
![image](https://user-images.githubusercontent.com/3381677/234185774-792e5926-7c20-48dd-bd81-3a4fc55d83aa.png)

**To Reproduce**
Use csolution to generate IAR build target with Pre_Include_Global element in related packs.

**Expected behavior**

**Environment (please complete the following information):**

- [tool or library] csolution/cbuild
- Version [e.g. v0.0.3] 1.6 for csolution; 1.6.1 for cbuild
- OS: [e.g. windows/linux/darwin] Windows

**Additional context**

**Comment by jkrech** [comment]
Hello @tcsunhao, 
you are right:
there was this PR https://github.com/Open-CMSIS-Pack/devtools/pull/734 to fix the command line
however it seems this PR https://github.com/Open-CMSIS-Pack/devtools/pull/798 did revert it again.
@JonatanAntoni and @jlonnberg could you please investigate what happened here?

**Comment by jlonnberg** [comment]
@jkrech I have an pending update for the IAR toolchain file in the near future, I'll include this for that!

**Comment by JonatanAntoni** [comment]
This slipped through the review, I guess. Unfortunately, we don't have CI for IAR Compiler integrated. @jlonnberg, any updates about running IAR Compiler within GitHub Actions? Would it be possible to provide IAR Compiler via vcpkg similar to Arm Tools?

**Comment by jlonnberg** [comment]
@JonatanAntoni Our PM for licenses are working on this atm, but I haven't heard anything concrete yet. I'll keep you notified.
Moreover, I'm running continuous integration tests each night based on the main branch but I have yet to include a test that tests this. I'll most likely add one when fixing the problem.
