### ISSUE TITLE
Support of Conan

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#865]
Many people are using Gitlab to build and deploy their code. Gitlab Ultimate will support dependency scanning of C and C++ files that use [Conan ](https://conan.io/) to analyse dependencies and to create SBOMs, an important topic in the industry nowadays. 

See https://docs.gitlab.com/ee/user/application_security/dependency_scanning/index.html#supported-languages-and-package-managers for the explanation.

Is there any plan to support Conan in the future? 

Thanks

**Comment by jkrech** [comment]
@jankap could you please confirm that you are referring to the scanning of the source code the tools are build from and not the scanning of the source code that the tools are processing?

**Comment by jankap** [comment]
I'm afraid I don't get the point, could you elaborate please?

**Comment by ReinhardKeil** [comment]
@jankap what is your use-case of Conen in context of the CMSIS-Toolbox?  

Do you want to use Conen as Artifactor or the CMSIS-Toolbox binaries so that they can be installed or is it something different?

**Comment by jankap** [comment]
We would like to use the security scanning mechanism of Gitlab. It seems like only Conan is currently supported. Conan creates lockfiles, similar to Pythons pip requirements.txt. Basically, it contains the name, link/path and version of dependent packages, required by the project to be build. CMSIS-toolbox does similar things, it creates a list of dependencies based on CMSIS-Packs. Maybe there's a way to export that list to a conan compatible format to get it scanned for vulnerabilities. I don't think that the code is scanned, but a list of known vulnerabilities is used for comparison.

**Comment by ReinhardKeil** [comment]
Would it be possible to used the information in the [Cbuild.yml](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md) files as starting point?  These describe all the files that are used in the build process.

**Comment by ReinhardKeil** [comment]
closing as no further activities.  @jankap let us know if you need additional information.
