### ISSUE TITLE
Run Doxygen while building

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#867]
Is there any option to trigger Doxygen to build documentation for the current build target? This might be especially helpful if there are multiple build targets. Can Doxygen be injected into the cmake/CMakeLists.txt process?

**Comment by jkrech** [comment]
I guess the doxygen invokation could be added as a pre-build or post-build step to today's build, however we currently plan to do that work after CMSIS-Toolbox 2.0 when we plan to generate Cmakefiles across multiple contexts.
I cannot think of any way of adding doxygen to a build today.
@brondani any comments from your side?

**Comment by brondani** [comment]
This seems to be a typical pre/post build step which is not yet supported but it's planned here:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#prepost-build-steps

**Comment by jankap** [comment]
Will the pre/post build steps know which files were included in the build and which defines were set?

My current solution looks like that:
- call csolution to create the cprj files
- call cbuild to create the CMakeLists.txt + run the binary build
- patch the generated CMakeLists.txt by adding one line `add_subdirectory(../../../doc/doxygen ../../../doc/doxygen)` to the folder where my doxygen CMakeLists.txt is located
- call cmake with a different target `cmake --build build-src/tmp/$name -j4 --target docs`
- copy the artifacts

The CMakeLists.txt in folder /doc/doxygen is like this:
```

# Doxygen
# adapted example from https://github.com/glfw/glfw/blob/df8d7bc892937a8b0f7c604c92a9f64f383cf48c/docs/CMakeLists.txt#L4

# include it via
# # Doxygen
# add_subdirectory(../../../doc/doxygen ../../../doc/doxygen)


find_package(Doxygen
        REQUIRED dot
        OPTIONAL_COMPONENTS mscgen dia)

if (DOXYGEN_FOUND)
    message("Doxygen was found")

    ## Prepare required paths to be replaced in Doxyfile.in template
    # set(extra_files DoxygenLayout.xml header.html footer.html extra.css spaces.svg)
    foreach(file IN LISTS CC_SRC_FILES)
        string(APPEND JLG_DOXYGEN_INPUT " \\\n\"${file}\"")
        # string(APPEND JLG_DOXYGEN_INPUT " \\\n\"${CMAKE_CURRENT_SOURCE_DIR}/${file}\"")
    endforeach()
    # foreach(path IN LISTS INC_PATHS)
    #     string(APPEND JLG_DOXYGEN_INPUT " \\\n\"${path}\"")
    # endforeach()
    foreach(path IN LISTS AS_ARM_SRC_FILES)
        string(APPEND JLG_DOXYGEN_INPUT " \\\n\"${path}\"")
    endforeach()

    ## Add includes - not exactly clear what that means here
    foreach(path IN LISTS INC_PATHS)
        string(APPEND JLG_DOXYGEN_INCLUDES " \\\n\"${path}\"")
    endforeach()

    ## Add defines
    foreach(path IN LISTS DEFINES)
        string(APPEND JLG_DOXYGEN_DEFINES " \\\n\"${path}\"")
    endforeach()

    ## Get current git hash
    # from https://jonathanhamberg.com/post/cmake-embedding-git-hash/
    # or https://www.mattkeeter.com/blog/2018-01-06-versioning/
    # Note: Reconfiguration is needed before building!
    execute_process(
        COMMAND git log -1 --format=%h
        WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
        OUTPUT_VARIABLE GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    execute_process(
        COMMAND git rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
        OUTPUT_VARIABLE GIT_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    ## Set version number
    set(JLG_DOXYGEN_VERSION "${GIT_BRANCH} @ ${GIT_HASH}")

    ## Set prj name
    set(JLG_DOXYGEN_PRJ_NAME "${TARGET}")

    ## Replace stuff in template
    configure_file(Doxyfile.in Doxyfile @ONLY)

    ## Build docs
    add_custom_command(OUTPUT "${OUT_DIR}/html/index.html"
                    COMMAND "${DOXYGEN_EXECUTABLE}"
                    WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
                    MAIN_DEPENDENCY Doxyfile
                    DEPENDS ${CC_SRC_FILES} ${INC_PATHS} ${AS_ARM_SRC_FILES}
                    COMMENT "Generating HTML documentation"
                    VERBATIM)

    add_custom_target(docs ALL SOURCES "${OUT_DIR}/html/index.html")

else (DOXYGEN_FOUND)
  message("Doxygen need to be installed to generate the doxygen documentation")
endif (DOXYGEN_FOUND)
```

Patchin ARM's CMakeLists.txt does not feel good, but it's a working way currently.

What do you think of that approach?

**Comment by ReinhardKeil** [comment]
Closing as I believe everything is answered. If you feel differently, reopen the issue.
Pre/post build steps will be added in CMSIS-Toolbox 2.2 that should come towards end of this year.
