### ISSUE TITLE
Question on Processor Options `fpu:` and `endian:`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#879]
Issues #806 and #359 discuss usage scenarios where explicit control of FPU features are required. 

I believe a perfect implementation for CMSIS-Toolbox 2.0 is out-of-scope and would suggest that we address such features at a later point in time.  Using `misc:` might be an option, but only if it does not conflict with the usage of the `fpu:` option.  If there is an conflict, we should perhaps not expose this option to the user as the typical use-case for devices is to use the features of a processor (also the floating point and/or MVE instruction set).  There are some reasons to disable usage of S-Registers for interrupt handlers, but it might be better to allow this at C source level.

Personally, I'm not aware of any device that requires explicit `endian:` control. I suggest for the end-user documentation we remove this option (could remain in the tools for now).

My conclusion: not to expose `fpu:` and `endian:` controls for CMSIS-Toolbox 2.0 release.

**Comment by brondani** [comment]
The `misc` options are placed in the command line after the options that come from the device selection. For most compilers when there are duplicated options the last one in the command line should win, so it should work as expected. But generally I would recommend to avoid having duplicates.

**Comment by ReinhardKeil** [comment]
Suggest to close this.  If we want to review again, open new issues.
