### ISSUE TITLE
Add option to `packchk` to fail if warning/info violations are detected

### ISSUE THREAD

**Issue by noahp** [Open-CMSIS-Pack/devtools#886]
The `packchk` tool is amazing, very helpful! I noticed that only if Errors are detected does the tool return a non-zero error code. Could an option be added to also fail if any Warnings or Infos are detected? I'm using this workaround today but it's not the greatest:

```bash
# run packchk, if it passes, check if there were INFO or WARNING entries
# in the output
packchk lwIP.lwIP.2.1.0/lwIP.lwIP.pdsc | \
  tee packcheck.log && \
  ! grep -qE '^\*\*\* INFO|^\*\*\* WARNING' packcheck.log
```

**Comment by jkrech** [comment]
@noahp, thanks a lot for your feedback and suggested enhancement.
We need to make sure that we don't break existing scripts. Therefore the suggestion of a command line flag e.g. `pedantic` could return different error codes indicating the most severe `feedback` is from level:
- info
- warning
- error

**Comment by noahp** [comment]
That sounds perfect, exactly what I had in mind!

**Comment by thorstendb-ARM** [comment]
I added option "--pedantic" to return 1 on WARNINGs and prepared for "--pedantic [warning|info]". As this extension touches (our own) widely used library ErrLog, I will postpone that extension for later.
Hope this already helps.

**Comment by jkrech** [comment]
see latest packchk version 1.4.1
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.4.1

**Comment by noahp** [comment]
Thank you so much!
