### ISSUE TITLE
Implement proposal for Access Sequences

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#894]
[Access Sequences](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#access-sequences) are somewhat inconsistent.  The new proposal in [Access Sequences](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#access-sequences) solves this and adds new, i.e. for accessing the `cmse_lib.o` file.

**Comment by jkrech** [comment]
see: cmsis-toolbox 2.0.0-dev0
