### ISSUE TITLE
What are requirements for RTE directory configuration?

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#898]
The [default RTE directory is documented here](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#rte-directory-structure)

Using [output-dirs:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#output-dirs) it is possible to change this RTE directory. However `output-dirs:` is only possible at csolution level which means that it is impossible to define this locally for a project.  I don't think that this is what is required.

Given the fact that there is already a `generator-dir:` which was IMHO the initial reason for `rtedir:` I would ask the question: what are the real requirements for RTE directory configuration?

**Comment by jankap** [comment]
I'd need to configure the RTE paths in a way that 
1. least possible code/file duplication 
2. compatibility with Keil MDK/µVision
is preserved. 

For 1:
We have some custom settings in the RTE_Device.h files, which depend on the build target (not the build config). But there's also lots of stuf that is the same for all build options, e.g. EventRecorder settings - I would love to avoid having the same contents in dozens of files under RTE/buildTarget/configTarget, it's error prone and almost every time we forget to update a file in one of these subfolders. Ideally, separation from customized/overwritten and auto generated, common RTE files would be implemented.

For 2:
We're building our code using a Docker image containing all the CMSIS-toolbox and toolchain stuff. The same image is used in CI/CD pipeline and on local machines via VSCode remote container to ensure that we're doing the same thing. From time to time the code must be debugged (and potentially re-built) using Keil MDK on the local PCs. Ideally no manual (or automated via Python script as it is the case now) patching of any files should be required. The RTE paths must be understandable by Keil MDK. And ideally the debugger settings, too.

BTW, will the cprj files be deprecated in v2? If yes, how can we use MDK then?

**Comment by jankap** [comment]
I'd need to configure the RTE paths in a way that 
1. least possible code/file duplication 
2. compatibility with Keil MDK/µVision
is preserved. 

For 1:
We have some custom settings in the RTE_Device.h files, which depend on the build target (not the build config). But there's also lots of stuf that is the same for all build options, e.g. EventRecorder settings, or even default  - I would love to avoid having the same contents in dozens of files under RTE/buildTarget/configTarget, it's error prone and almost every time we forget to update a file in one of these subfolders.

For 2:
We're building our code using a Docker image containing all the CMSIS-toolbox and toolchain stuff. The same image is used in CI/CD pipeline and on local machines via VSCode remote container to ensure that we're doing the same thing. From time to time the code must be debugged (and potentially re-built) using Keil MDK on the local PCs. Ideally no manual (or automated via Python script as it is the case now) patching of any files should be required. The RTE paths must be understandable by Keil MDK. And ideally the debugger settings, too.

BTW, will the cprj files be deprecated in v2? If yes, how can we use MDK then?
