### ISSUE TITLE
Linker Script Management - small issues

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#901]
1. Regions Filename should have no special characters such as '-' that are not allowed as C identifier.
Special characters should be replaced by '_'; Instead of `regions_SSE-300-MPS3.h`, `regions_SSE_300_MPS3.h`

2. When a `linker:` node is used, and not explicit `script:` is specified, the default scripts from the `.\etc` directory should be used.  The attached example still uses a script specified by a component.  See attached example RT1064 in Linker.zip.

3. For projects that use `clayer.yml` files and define components with Cclass=`Device`, the RTE directory relative to the layer should be used to generate the `regions*.h` file.

4. The \<h\> tag for the memory in the `regions*.h` should use the same id as the *xxx_BASE* name.  The `name` attribute of *.pdsc \<memory\> element should be appended with `=name`. Example:
```c
// <h>ROM Configuration
// =======================
// <h> IROM0=<name>
//   <o> Base address <0x0-0xFFFFFFFF:8>
//   <i> Defines base address of memory region.
//   <i> Default: 0x00000000
#define __ROM0_BASE 0x00000000
```

[Linker.zip](https://github.com/Open-CMSIS-Pack/devtools/files/11422074/Linker.zip)

**Comment by jkrech** [comment]
only item 2 above to be looked into by @brondani.

**Comment by edriouk** [comment]
Pack info is implemented here: https://github.com/Open-CMSIS-Pack/devtools/pull/937
since creator comment is common to all generated files, the information is put in the body  using `<n>` annotation:
That allows to see the info also in the config wizard UI
```
//-------- <<< Use Configuration Wizard in Context Menu >>> --------------------

// <n>Board pack:    ARM.RteTestBoard.0.1.0
// <i>Board pack used to generate this file

// <n>Device pack:   ARM.RteTest_DFP.0.2.0
// <i>Device pack used to generate this file

```
![image](https://github.com/Open-CMSIS-Pack/devtools/assets/10760440/68bd4fa4-ec8b-408b-ae04-315975592349)

**Comment by jkrech** [comment]
see cmsis-toolbox 2.0.0-dev0
