### ISSUE TITLE
Why are there some linker errors with default scripts

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#902]
With the NXP RT1064 device, there is a linker error when using default linker scripts

```
"C:/w/csolution-examples/RT1064/tmp/RT1064/Device/Debug/ac6_linker_script.sct.pp", line 14 (column 9): Error: L6236E: No section matches selector - no section to be FIRST/LAST.
```

What is causing this error?

----

With the LPC1786 project this warning is reported (which is understandable). 
```
"C:/w/csolution-examples/LPC1768/tmp/LPC1786/Device/Debug/ac6_linker_script.sct.pp", line 20 (column 7): Warning: L6314W: No section matches pattern *(.bss.noinit).
```

Should we disable this warning by default?

Both projects are in Linker.zip under #901

**Comment by brondani** [comment]
It seems in the RT1064 example the startup file names the vector table section as `.isr_vector`, while in the default linker script the first section is expected to be named `RESET`.

**Comment by JonatanAntoni** [comment]
The RT1064 example, or to be more specific the RT1064 startup component, uses custom (non-CMSIS) assembly startup code. This is not compatible with the default linker scripts shipped with CMSIS-Toolbox. The default linker scripts are written for the default CMSIS C-Startup code using the provisions from CMSIS-Core(M).

**Comment by ReinhardKeil** [comment]
Related to #1699
