### ISSUE TITLE
Create an option in csolution.yml to enable usage of cdefault.yml

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#911]
ToDo:

Create an option in csolution.yml to enable usage of cdefault.yml
Default behavior should be no cdefault.yml is used.

**Comment by jkrech** [comment]
Instead of `[<name>].cdefault.[yml|yaml]` only:
`cdefault.[yml|yaml]` located in the csolution directory or in `$CMSIS_COMPILER_ROOT` should be searched for when the node is present in the csolution.yml file.

**Comment by jkrech** [comment]
Available using `cdefault.yml` instead of `.cdefault.yml` starting CMSIS-Toolbox 2.0.0-dev1
