### ISSUE TITLE
Unsure about how to understand the ARDUINO pin meaning in provides/consumes

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#917]
We are given examples like this:

  ```
connections:
    - connect: I2C Interface 'Std'
      set:  comm.I2C-Std
      info: JP1=Off  JP2=Off
      provides:
        - Sensor_I2C:
      consumes:
        - Ardunio_Uno_I2C:

    - connect: SPI Interface 'Alt'
      set:  comm.SPI
      info: JP2=On
      provides:
        - Sensor_SPI:
      consumes:
        - Ardunio_Uno_SPI:

    - connect: Sensor Interrupt INT0
      set:  SensorIRQ.0
      info: JP3=Off
      provides:
        - Sensor_IRQ:
      consumes:
        - Ardunio_Uno_D2:

```

==> the 2 first expressions are quite clear, we need an I2C peripheral or an SPI peripheral exposed "in the Arduino Uno way" ?
What does Arduino Uno way mean here ?
Is it the pin localization on a arduino-like connector ?

==> The 3rd expression is less clear.
What does Arduino_Uno_D2 mean here ?
Digital IO pin 2 ==> so we need a digital pin, but 2 is here to impose the position ?

Or ?

**Comment by ReinhardKeil** [comment]
@fred-r I have re-qualified this as discussion as I believe it is documented.  However as you know documentation is never perfect.  Let me know if you have still questions.

**Comment by jkrech** [comment]
@fred-r any update on this issue from your side?

**Comment by fred-r** [comment]
Sorry for the delay.
So, what I understand is that basically you leverage the "Arduino standard".

Indicating Arduino_Uno_D2 specifies at the same time:
- a physical pin
- a signal (or set of signals with alternate functions)

And here we are interested in both aspects.

So, to be precise:

- Arduino_Uno_D2  ==> the Arduino pin identified as D2 "physically" and providing the signals of the Arduino D2 pin. So, for D2 it is only a GPIO, without PWM capability.

- Ardunio_Uno_I2C ==> we say we want the I2C signals on the default arduino uno pins ==> D18: SDA, D19: SCL

Is this correct ?

But I guess this means that:
- either we use a "worldwide standard" like Arduino ==> any provider can use it
- or we use our "own system": ST connectors ==> local to our project or community of users 

is this correct ?

**Comment by ReinhardKeil** [comment]
Can we close this issue or is more required?
