### ISSUE TITLE
[csolution] Add `list configs` command to list configuration files

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#922]
Currently the configuration files belonging to a given context can be retrieved only after the `convert` step, which actually runs the PLM and copies `@base` and `@update` files. 

The suggestion is to add a `list configs` command that would list the configuration files without writing or copying any file.

**Comment by jkrech** [comment]
Note: in CMSIS-Toolbox 2.0.0 the command `update-rte` combined with flag `--verbose` lists configuration files after the update operation is complete.
