### ISSUE TITLE
Create warning on potentially mis-spelled names in `for-context:`, `not-for-context:`, `for-compiler:`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#926]
This is a future improvement: when csolution compares  names in `for-context:`, `not-for-context:`, `for-compiler:` it should highlight when a name is potentially misspelled.

Example:
```yml
  target-types:
    - type: Board                          # When applying target-type: 'Board':
```

When using `for-context: +board` this will never match -> issue warning: `target-type name does not exist in solution`

When using `for-context: .Board2` this will never match -> issue warning: `build-type name does not exist in solution` (use obviously potentially mixed target with build type).

**Comment by brondani** [comment]
Addressed in https://github.com/Open-CMSIS-Pack/devtools/pull/1121 and https://github.com/Open-CMSIS-Pack/devtools/pull/1126.
