### ISSUE TITLE
[csolution] Clean-up deprecated YML nodes

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#929]
Remove YML nodes in the schema and the related handling implementation in source code.
Align [schemas](https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/projmgr/schemas) with [documentation](https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/projmgr/docs/Manual).

**Comment by jkrech** [comment]
see cmsis-toolbox 2.0.0-dev0
