### ISSUE TITLE
[csolution, cbuildgen] Add standard language options into translation controls

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#945]
The standard `language-C` and `language-CPP` options should be accepted and handled according to the specification:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#translation-control

**Comment by brondani** [comment]
@ReinhardKeil Can you please update the documentation? The `language-C` and `language-CPP` options are accepted in the same places as the other toolchain abstraction controls (namely `optimize`, `debug` and `warnings`).

**Comment by jkrech** [comment]
Documentation got updated. Hence closing.
Reflecting changes in CMSIS-Toolbox 2.0 (https://github.com/Open-CMSIS-Pack/devtools/pull/1030)
