### ISSUE TITLE
Warning does not indicate the `cproject.yml` file that is processed

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#967]
When a csolution.yml includes multiple cproject.yml files (or even clayer.yml files), the following warning does not indicate in which cproject.yml or clayer.yml a component with dependencies was identified.

```
C:\Test\Test-C0>csolution convert -s MyName.csolution.yml      
warning csolution: dependency validation for context 'MyName.Debug+MyTargetName' failed:
SELECTABLE Keil::Device:Startup@1.0.0
  require CMSIS:CORE
  require Device:STM32Cube Framework
```

My recommendation, replace the text SELECTABLE with 'component: ` and add file name that contains the component, i.e.

```
C:/Test/Test-C0/MyName.cproject.yml - warning csolution: dependency validation for context 'MyName.Debug+MyTargetName' failed:
component: Keil::Device:Startup@1.0.0
  requires component: CMSIS:CORE
  requires component: Device:STM32Cube Framework
```

A similar problem applies to the `list dependencies` command where also the `*.yml` file that defines the component would be useful. For example:

```
C:\Test\Test-C0>csolution list dependencies -s MyName.csolution.yml
C:/Test/Test-C0/MyName.cproject.yml - component: Keil::Device:Startup@1.0.0 requires component: CMSIS:CORE
C:/Test/Test-C0/MyName.cproject.yml - component: Keil::Device:Startup@1.0.0 requires component: Device:STM32Cube Framework

**Comment by brondani** [comment]
Actually the word `SELECTABLE` brings information in itself that would be lost with a simple replacement by `component:`.
I would recommend to elaborate it better according to the meaning of each condition result:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/libs/rtemodel/src/RteItem.cpp#L34-L49

**Comment by edriouk** [comment]
Project file is written to output

**Comment by ReinhardKeil** [comment]
Project file is now present - it is therefore a duplicate of #1187 1187
