### ISSUE TITLE
cproject file: warnings is missing in Setup

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#970]
Hi

In https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.0.0-dev0/tools/projmgr/schemas/common.schema.json#/definitions/ProjectDescType

it seems that
"warnings":    { "$ref": "#/definitions/WarningsType" },
is missing in "SetupType"

Regards,

**Comment by jkrech** [comment]
Well spotted. If you skip the schema check it should actually already work.

**Comment by jkrech** [comment]
Will be included in CMSIS-Toolbox 2.0.0-dev2
