### ISSUE TITLE
[csolution] Add `warnings:` option `all` in yml input

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#974]
Hi

https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#warnings

Current spec define 2 levels:
- on
- off

Proposition is to add a third one:
- all

Regards

@tarek-bochkati

**Comment by ReinhardKeil** [comment]
Good proposal. Should be a CMSIS-Toolbox 2.1 feature

**Comment by brondani** [comment]
We had the warnings `all` option in the initial proposal, but it was removed during implementation - see https://github.com/Open-CMSIS-Pack/devtools/pull/478 and https://github.com/Open-CMSIS-Pack/devtools/pull/491.
@tarek-bochkati Can you please comment about this?

I believe the meaning of `all` and the differences between `on` and `all` for each supported toolchain need to be clarified.

**Comment by ReinhardKeil** [comment]
We could implement it as follows

Value | Control diagnostic messages (warnings)
-- | --
on | Generate default compiler warning messages
off | No warning messages generated
all | Enable all compiler warning messages (option -Wall)

**Comment by tarek-bochkati** [comment]
Agree on `all`,
@mario-pi , I'm wondering IAR `--remark` is equivalent to  GCC `-Wall`

**Comment by brondani** [comment]
@jeromecoutant @tarek-bochkati @mario-pi
Can you please check whether the PR https://github.com/Open-CMSIS-Pack/devtools/pull/1160 meets your expectations?

**Comment by mario-pi** [comment]
> @jeromecoutant @tarek-bochkati @mario-pi Can you please check whether the PR #1160 meets your expectations?

Looks good to me. I have now asked the translator team and --remarks should be equivalent.

**Comment by jkrech** [comment]
@ReinhardKeil please update:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#warnings
and add Value `all` and corresponding description.

**Comment by ReinhardKeil** [comment]
now added to documentation - will be part of next pull request.
